### ISSUE TITLE
Ampersand after papaja 0.1.0.9479

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#100]
Hi Frederik,

in the new version of papaja I can use in-text citations that do not use the ampersand, but correctly "and" instead. First, thank you for implementing this very nice feature :-) However, I noted that this does does not yet seem to work in all cases. For me, this only seems to work for the first in-text citation. I am using papaja 0.1.0.9479.

The problem is as follows: when I use an in-text citation for the first time, the authors are shown correctly as bla and bla (2xxx), but the second time it is shown incorrectly as bla & bla (2xxx). Rendering [this file](https://gist.github.com/m-Py/ae03960e2274a90a1216430625731d43) demonstrates this issue (I only use your Rmd skeleton file where I inserted the citation @R-pajaja in two paragraphs). When I render this document, only the first citation is shown correctly. I just reproduced this issue on a colleague's computer who is using Windows and the most recent version of pajaja.

Cheers!

Martin

**Comment by crsh** [comment]
Thanks, Martin. @awellis reported a similar problem in #96. Thanks a lot for the example file. I'll try to take a closer look as soon as possible.

**Comment by awellis** [comment]
I can confirm this ("...the second time it is shown incorrectly as bla & bla (2xxx)...")

**Comment by crsh** [comment]
Hi @m-Py, hi @awellis,

I just pushed a commit to the master branch that fixes the bug in the ampersand filter that caused it to miss the latter citation in the file you provided, Martin. Let me know if you have any cases where it doesn't work.

Thanks again for reporting these problems.

**Comment by awellis** [comment]
hi @crsh,

thanks for fixing this; seems to be working so far.

**Comment by m-Py** [comment]
It seems to be working for me as well - thanks for the fix. If something unexpected comes up, I will report that.
