### ISSUE TITLE
unicode output in latex

### ISSUE THREAD

**Issue by alvinntnu** [crsh/papaja#103]
Hi,

In the markdown file, I tried output a data frame from R chunk. In the data frame there not non-ASCII characters. So when compiling to PDF, it throws this following error. I google a bit and it seems that maybe changing the latex engine would help? So i was wondering if there's any way to deal with this problem, and how to change the default latex_engine for papaj::apa6_pdf?

Also, if I set the output to be papaja::apa_word, everything works fine.

Million thanks in advance for the help!

Alvin

> ! Package inputenc Error: Unicode char 南 (U+5357)
> (inputenc)                not set up for use with LaTeX.
> 
> See the inputenc package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.900 001-01 & 6 & 4 & 南
> 
> Try running pandoc with --latex-engine=xelatex.
> pandoc: Error producing PDF
> Error: pandoc document conversion failed with error 43
> In addition: Warning message:
> In has_utility("convert", "ImageMagick") :
>   ImageMagick not installed or not in PATH
> Execution halted

**Comment by m-Py** [comment]
Hello alvinntnu,

to change the latex engine in Rmarkdown you can put the following in the YAML header:

```
---
output:
  papaja::apa6_pdf:
    latex_engine: xelatex
---
```

(Take care of the exact indentations and colons) I am not sure whether this works with papaja though, but for normal `pdf_output` this is the way to do it. It is possible that you need to install xelatex first, if it does not come with your Tex installation.

Also see here under advanced customizations: http://rmarkdown.rstudio.com/pdf_document_format.html

**Comment by alvinntnu** [comment]
Hi m-Py,

I did try that, following the normal way to set the latex engine  in the YAML header. But it seems not working. It would throw an error message, as shown below. I'm really new to this whole LaTex mechanics. Really appreciate your any advice.

Alvin

```
! Undefined control sequence.
\csq@main@language ->\xpg@main@language 

錯誤: Failed to compile manuscript-incremental-planning.tex. See manuscript-incremental-planning.log for more info.
此外: Warning messages:
1: In ks.test(wordnum[left == 1], wordnum[left == 0]) :
  p-value will be approximate in the presence of ties
2: 執行中命令 '"xelatex" -halt-on-error -interaction=batchmode "manuscript-incremental-planning.tex"' 已有狀態 1 
停止執行
```

**Comment by m-Py** [comment]
Hello  Alvin,

it seems to me then that xelatex maybe does not work with papaja -- I tried to render a papaja document using xelatex and it threw the same error that you describe. Alas, I do not know whether there is a workaround, sorry. 

Cheers,

Martin

**Comment by alvinntnu** [comment]
Hi,

I think right now my problems are:

(1) I need to output Chinese characters in the output pdf and I got the error:

```
! Package inputenc Error: Unicode char 南 (U+5357)
(inputenc)                not set up for use with LaTeX.

Error: Failed to compile manuscript-incremental-planning.tex. See manuscript-incremental-planning.log for more info.
```

And people suggest to change the latex engine to xelatex. But I don't how to do it with the papaja package.

(2) If I use the YAML header to set up this way:

```

output: 
  papaja::apa6_pdf:
    include: 
      in_header: header.tex
    latex_engine: xelatex
```

I got another error message:

```
! Undefined control sequence.
\csq@main@language ->\xpg@main@language 

Error: Failed to compile manuscript-incremental-planning.tex. See manuscript-incremental-planning.log for more info.
```

Thanks in advance for suggestions.
Best,

Alvin

**Comment by alvinntnu** [comment]
Ok. I figured out a way anyway. For unicode outputs in the apa6_pdf, remove the lang setting in the YAML and then everything works perfect.

Alvin

**Comment by crsh** [comment]
Hi Alvin, I'm not familiar with XeLaTeX, but `apa6_pdf` supports the `latex_engine` option, as you found out. As far as I can tell, if you use XeLaTeX and provide `lang` in the YAML header, you also have to provide `mainlang`, which is passed to the [polyglossa](http://mirror.unl.edu/ctan/macros/latex/contrib/polyglossia/polyglossia.pdf) package (see Table 1 for supported languages). But as you have found out, it also works if you remove the `lang` option.

(Thanks @m-Py for being the first repsonder here)
