### ISSUE TITLE
Turn force rounding numbers off

### ISSUE THREAD

**Issue by ReinoutVrijhoef** [crsh/papaja#104]
Hello,

First of all, thank you for all of your work designing this nice package. I use it during my studies at the moment, I hope to get some positive feedback from my teachers soon.
Is it possible to turn the standard rounding of numbers off? I would like to insert some numbers with three, or some with only one decimal. I can't seem to get it to work at the moment. Help is very appreciated.

**Comment by crsh** [comment]
Without a little more context it's difficult to give a helpful answer. Generally, though, if you are using any function that accepts additional arguments that are passed to `printnum()` via `...` you can change the number of digits by adding an argument like `digits = 5`. For example,

~~~{r}
ttest_result <- t.test(x = sleep$extra[sleep$group==1], y = sleep$extra[sleep$group==2], paired=TRUE)
apa_print(ttest_result, digits = 5)$full_result
~~~

returns

~~~
[1] "$M_d = -1.58000$, 95\\% CI $[-2.45989$, $-0.70011]$, $t(9) = -4.06$, $p = .003$"
~~~

Is this what you are looking for?

**Comment by ReinoutVrijhoef** [comment]
Thank you for your quick respons! That is not exactly what I was looking for. With another function I calculate the omega squared, instead of the eta squared. I would like to print the result of this equation in the pdf. So this will be the in-text code:
``r marktHypo.print$statistic$conditie` $omega^2 =$ `r round(marktHypo.omsq[1], 3)``
But when knitting to pdf, the numbers are rounded to two digits.

**Comment by m-Py** [comment]
You can for example use this function:

```
force_decimals <- function(x, n_digits) {
    return(format(round(x, n_digits), nsmall = n_digits))
}
```

You can specify a number of decimals that is displayed when you use rmarkdown in text code. Use it like this: 

This number has 2 decimals: `r force_decimals(marktHypo.omsq[1], 2)`; this number has 1 decimal: `r force_decimals(marktHypo.omsq[1], 1)`; this number has 3 decimals: `r force_decimals(marktHypo.omsq[1], 3)`; etc.

**Comment by ReinoutVrijhoef** [comment]
Great, thank you!

**Comment by crsh** [comment]
You could also use `printnum()`. With omega squared you would also want to eliminate the leading zero. So you could do `printnum(marktHypo.omsq[1], digits = 3, gt1 = FALSE)`.

**Comment by ReinoutVrijhoef** [comment]
That's an even better solution, thank you very much!
