### ISSUE TITLE
Citation in german

### ISSUE THREAD

**Issue by feeblee** [crsh/papaja#105]
hey Frederik,

I use papaja to write a german paper. There is no problem unless with the citation. If I have to cite an article/book from two authors it puts the english "and" between the authors names.

Is there a way to change that easily to the german "und"?

**Comment by crsh** [comment]
Hi feeblee, unfortunately there is currently no way to do this. I have started implementing the localization of the ampersand filter and in principle this is an easy fix. However, the use of the language variables has changed with recent updates of pandoc and I think I will have to revise the TeX template before I can publish the fix. It may be some time before I get around to doing this.

**Comment by ReinoutVrijhoef** [comment]
On a related note: is it possible, or will it be possible, to use another language besides 'english' as localisation? I would really like to use dutch, and I am willing to do the translation, if that's necessary.

**Comment by crsh** [comment]
Sure, `pandoc` and LaTeX in principle support a large range of languages. However, as noted above, I need to revise the template for this to work properly. I'll bump this issue up on the list of things to do. There are some terms that are inserted by `papaja` depending on the output format. If you would like to contribute to full support of Dutch you can take a look at `[localize()](https://github.com/crsh/papaja/blob/master/R/utils.R#L352)` for a list of terms and phrases that need to be translated. You are welcome to provide a pull request or post the translations into this thread.

Von meinem Handy gesendet

**Comment by ReinoutVrijhoef** [comment]
, dutch = list(
      author_note = "Over de auteur"
      , abstract = "Samenvatting"
      , keywords = "Trefwoorden"
      , word_count = "Aantal woorden"
      , table = "Tabel"
      , figure = "Figuur"
      , note = "Opmerking"
      , correspondence = "Correspondentie betreffende dit artikel wordt geadresseerd aan "
      , email = "E-mail"

Any comments or changes are welcome :-). Changing the language in LaTeX is possible, just not in R Studio.

**Comment by crsh** [comment]
Awesome, thanks. I will add this as soon as I find a little time to revise the template.

**Comment by crsh** [comment]
Note to self: [This](https://tex.stackexchange.com/questions/324985/how-can-i-translate-author-note-in-apa6-into-german) may help once I have reworked the document template.

**Comment by crsh** [comment]
Note to self: It may also be worth to explore [this `bookdown` feature](https://bookdown.org/yihui/bookdown/internationalization.html) for word documents. For example:

~~~yaml
language:
  label:
    fig: "*Figure*"
~~~

This also allows some formatting.

**Comment by crsh** [comment]
It's been a *long*  time, but I have finally made some visible progress on this. Try installing the latest development version (`devtools::install_github("crsh/papaja@devel")`) and set a language variable in the YAML front matter:

~~~yaml
lang: de-DE
~~~

or

~~~yaml
lang: nl-NL
~~~

This should a yield the corresponding translation of "and" for in-text citations. Currently, [Dutch, English, German, and Spanish are supported](https://github.com/crsh/rmdfiltr/blob/03b9715b7ccc69e5eeaf9ef39fd77484e4fb8fdd/inst/replace_ampersands.lua#L3).

**Comment by crsh** [comment]
Note, you may have to install the corresponding language definition for your TeX distribution, in case it's missing (if you are knitting a PDF).

**Comment by mariusbarth** [comment]
I just checked the new ampersand filter in German, works like a charm. :+1:

**Comment by ekothe** [comment]
@crsh perhaps worth putting a call out at SIPS2019 to see if there are people who can help with other languages?
