### ISSUE TITLE
Error Message Troubleshooting

### ISSUE THREAD

**Issue by aggieerin** [crsh/papaja#107]
Hi everyone,

When we try to knit an example document, we get the following error. Any ideas what to do to fix it?

Thanks - erin

![error message](https://cloud.githubusercontent.com/assets/12536064/24816642/2f3a8c98-1b9f-11e7-8680-34384e796f5a.PNG)

**Comment by crsh** [comment]
Hi Erin,

the error message is generated by `cite_r()`, which reads a bibliography file and generates R-related citations. It looks like the file that is read contains HTML-tags (`<td id="LC1" ...`).  Could you check and make sure the file is formatted correctly of, if in doubt, upload your bibliography file here so I can take a closer look?

Cheers,
Frederik

**Comment by aggieerin** [comment]
I think I see what's happening ... when we went to download the example, it saved as some weird version of a HTML file. I will try downloading the .bib again and get the student to test it on his computer.

**Comment by aggieerin** [comment]
That was the problem - thanks and fixed. 👍

**Comment by crsh** [comment]
You're welcome. Let me know if you experience any other issues.
