### ISSUE TITLE
Omit author note

### ISSUE THREAD

**Issue by jacob-long** [crsh/papaja#108]
As far as I can tell, even if I omit author note in the YAML frontmatter, there is still an "Author Note" heading followed by no content on the title page. I know the APA6 class won't print it if it isn't there in the LaTeX, but it apparently is included in the LaTeX by `papaja` even when it's omitted in the frontmatter.

**Comment by jacob-long** [comment]
Okay, poking around in your `apa6.tex` file, I can see what's going on on the TeX side. You do detect if there's no author note in the frontmatter, but fall back on printing information about the corresponding author in that case. I set the sole author in my frontmatter to not be the corresponding author, so this part of the conditional just generates empty content:

    $else$ % If no author_note is defined give only author information if available
      $if(author)$
      \authornote{
        \newcounter{author}
        $if(author)$
        $for(author)$
          $if(author.corresponding)$
            Correspondence concerning this article should be addressed to $author.name$$if(author.address)$, $author.address$$endif$.$if(author.email)$ E-mail: $author.email$$endif$
         $endif$
        $endfor$
        $endif$
      }
      $endif$
    $endif$

Maybe you could check for whether any listed author is corresponding first, then call `\authornote`.

**Comment by crsh** [comment]
Thanks for the pull request, I've merged your changes. Does this resolve this issue?

**Comment by jacob-long** [comment]
Yes!

**Comment by TtecSiyu** [comment]
When I set the sole author to not be the corresponding author, I got missing Missing \begin{document} error

**Comment by crsh** [comment]
This should be fixed in the current development version (`devtools::install_github("crsh/papaja@devel")`).
