### ISSUE TITLE
Final author's name is prepended with ampersand in author note if corresponding author

### ISSUE THREAD

**Issue by jacob-long** [crsh/papaja#110]
While I was poking around trying to fix #108, I noticed that choosing the final author as corresponding causes their named to be listed as "& Second Author" in the footnote.

I can see the source of the error is the pre-processing in `pdf_pre_processor` (in `apa6_formats.R`), which adds the ampersand to format the other part of the title page correctly. I'm not sure of the best way to address it.

**Comment by crsh** [comment]
Thanks for reporting this. I'll take a closer look as soon as I can.

**Comment by crsh** [comment]
I have finally found some time and pushed a fix for this bug to the development branch (`devtools::install_github("crsh/papaja", ref = "devel")`). Let me know if it works for you.
