### ISSUE TITLE
Customization is difficult / not clear, footnotes

### ISSUE THREAD

**Issue by DM-Berger** [crsh/papaja#111]
I just used your package recently. Noticed a couple things were not straightforward / obvious to change, and I had to manage them by editing the .tex source after using papaja to generate it. E.g. 

1. removing the title page (for things like, say, online supplementary appendices) seems to manually require removing the `\maketitle` line from the generated .tex source
2. if one wishes to remove the running heads, one must leave the `\shortitle` field empty, and then use, say `\thispagestyle{headings}` on the first page to not leave an empty "Running Head" field on the first page
3. if I make the above changes (or make no changes, and attempt to simply compile to pdf from the generated .tex source, my paragraph spacing is borked, because for some reason the .tex file includes the line `\setlength{\parindent}{0pt}`, which also must be changed manually back to `0.5in`. Curiously, the references section is spaced properly in the generated .tex source. 
4. References in footnotes are buggy. Attempting to place a Rmarkdown style reference `[@RefID]` inside a `\footnote{}` either prevents the pdf from compiling, or to render incorrectly. E.g. `text\footnote{[@Reference] bla bla bla.}. ` will not compile, and `text\footnote{^[@James_1910] bla bla bla.]` renders in the final pdf as **Paragraph\footnote<sup>1</sup>{bla bla bla.}** Only `text^[^[@Reference bla bla bla.]` provides the proper output. Nevertheless, using `\footnote{}` works normally in other cases. It was also not easy to figure this out (a random comment on some discussion on another website pointed out that playing with `^` might fix things. 

Anyway, these are rather minor issues, this is a really great tool, that for the most part just worked out of the box.

**Comment by crsh** [comment]
Thanks for the feedback! I'll look more closely into 1.-3. when I have a little more time. Regarding 4., you have come across a more general pandoc issue. Generally, you can use LaTeX throughout your document as you please but anything that is inside a LaTeX environment is ignored in the Markdown-to-LaTeX conversion process. The result, in your case, is that the references are not inserted correctly. If you use the [pandoc footnote syntax](http://pandoc.org/MANUAL.html#footnotes) it should work as expected.

**Comment by DM-Berger** [comment]
Ah, thanks for that link to the pandoc footnotes (and for the very prompt response!). I figured something like what you were describing was happening, but that makes it a lot clearer.

**Comment by crsh** [comment]
I have decided that 1.-3. are customizations that go beyond the scope of what I can support in `papaja` (preparing manuscripts). Thanks for the discussion.
