### ISSUE TITLE
apa_table() fails to consider the "format.args" kable's argument

### ISSUE THREAD

**Issue by lnalborczyk** [crsh/papaja#131]
Hi,

it seems that `apa_table()` fails to take into account the `format.args` kable's argument, thus preventing to specify the format of the decimal mark (for instance).

You can reproduce this problem by creating a new papaja template document and trying to knit it to PDF with this content:

```
d <- data.frame(v1 = runif(10,10,10000), v2 = runif(10,10,10000) )
apa_table(d, format.args = list(decimal.mark = ",", big.mark = "") )
```

**Comment by crsh** [comment]
Hi Ladislas, that is correct. Thanks for reminding me. It should be easy to fix this. I'll jump on it as soon as I find the time.

**Comment by lnalborczyk** [comment]
Hi Frederik, have you found some time to look at this issue ?

**Comment by crsh** [comment]
Hi Ladislas, I finally was able to take a closer look at this. I have pushed a fix to the development branch (`devtools::install_github("crsh/papaja@devel")`). Note, that `apa_table()` deviates somewhat from `knitr::kable()` in that `format.args` are passed to `formatC()` (via `printnum()`) rather than to `fromat()`.

Let me know if that works for you.

**Comment by lnalborczyk** [comment]
Hi Frederik ! Thanks for the update, it solved the "mark issue" indeed. But, it also introduced a weird interaction behaviour with the `digits` argument. It seems that the `digits` argument is now rounding in a row-wise manner (instead of column-wise)...

For instance, the following command

```
d <- data.frame(v1 = runif(10, 10, 10000), v2 = runif(10, 10, 10000) )

apa_table(d,
    format.args = list(
        digits = c(0, 2),
        decimal.mark = ".", big.mark = "") )
```

will give a table, with lines alternatively rounded to integer or to two decimals...

<img width="227" alt="screen shot 2017-10-26 at 10 45 33" src="https://user-images.githubusercontent.com/10812999/32043358-d81bd6ac-ba3a-11e7-84e4-115b0e720563.png">

but what we would like is rather column 1 be rounded to integers and column 2 be rounded to 2 decimals...

Do you know the origin of this problem ?

**Comment by crsh** [comment]
Thanks for testing and gettin back to me so quickly! `format.args` are passed to `printnum()`. `printnum()` has a `margin` argument that works just like it does in e.g. `apply()`. Hence I would expect the following to work as expected:

~~~{r}
d <- data.frame(v1 = runif(10, 10, 10000), v2 = runif(10, 10, 10000) )

apa_table(d,
    format.args = list(
        digits = c(0, 2),
        margin = 2,
        decimal.mark = ".", big.mark = "") )
~~~

**Comment by lnalborczyk** [comment]
It works perfectly indeed, many thanks ! Hopefully there will be a new papaja preprint out there very soon :)

**Comment by crsh** [comment]
Great. If you send me a link to the paper, I'll add it to the list in the papaja README.

**Comment by lnalborczyk** [comment]
Hi Frederik ! Thanks for fixing this issue. I noticed that you removed the "na_string" argument in the same commit... do you know how we can achieve the same thing (i.e., replacing NAs by a specified character) otherwise ?

**Comment by crsh** [comment]
This should still be possible by passing `na_string`. But I'll admit that this less than obvious from the documentation.

**Comment by lnalborczyk** [comment]
The current github version throws an error (when the output is a pdf)...

```
Error in kable_latex(x = c("(Intercept)", "Session", "sd\\_(Intercept).Participant",  : 
  unused argument (na_string = "")
Calls: <Anonymous> ... apa_table.latex -> do.call -> <Anonymous> -> <Anonymous> -> do.call
```

**Comment by crsh** [comment]
Okay, sorry Ladislas, this has been forever. I should have reopened this issue. The error is thrown because `na_string` is an option passed to `printnum()` and, thus, needs to be passed as part of `format.args`:

~~~r
d <- data.frame(v1 = runif(10, 10, 10000), v2 = runif(10, 10, 10000))
d[1, 1] <- NA

apa_table(
  d
  , format.args = list(
    digits = c(0, 2)
    , margin = 2
    , decimal.mark = "."
    , big.mark = ""
    , na_string = "Oh, noes!"
  )
)
~~~

**Comment by lnalborczyk** [comment]
Hi Frederik, do not apologise. Putting `na_string` inside `format.args` works perfectly ! Thanks !
