### ISSUE TITLE
Extended quotations syntax

### ISSUE THREAD

**Issue by alexholcombe** [crsh/papaja#136]
It would be nice if papaja supported extended quotations according to APA style, which apparently is:

> Start the quotation on a new line, indented 1/2 inch from the left margin, i.e., in the same place you would begin a new paragraph. Type the entire quotation on the new margin, and indent the first line of any subsequent paragraph within the quotation 1/2 inch from the new margin. Maintain double-spacing throughout.

**Comment by crsh** [comment]
Hi Alex, this is possible if you start the quote on  with `>` in a new line:

```
This is the prior paragraph.

> This is the extended quotation.

This is the subsequent paragraph.
```

**Comment by alexholcombe** [comment]
Thanks! Sorry I missed this - should have found this blockquote feature of Rmd
