### ISSUE TITLE
Error in apa_beeplot with devel version

### ISSUE THREAD

**Issue by TobiasKoeln** [crsh/papaja#137]
Hey @mariusbarth 
When running the code below using the papaja version from the devel branch, I get the following error massage:

> "Fehler in validate(x, check_class = "numeric") : The parameter 'x' is NA."

I do not get this error when running the same code with the papaja version from the master branch.

```{r}
cars$id <- rep(c(1:25), 2)
cars$factor1 <- rep(x = c(1, 2), 25)
cars$factor1 <- as.factor(cars$factor1)
cars$factor2 <- rep(x = c(1, 2), each = 25)
cars$factor2 <- as.factor(cars$factor2)


apa_beeplot(
    id = "id"
  , dv = "dist"
  , data = cars
  , factors = c("factor1", "factor2")
  , fun.aggregate = mean
  , dispersion = wsci
)
``` 
Thank you for your work

**Comment by mariusbarth** [comment]
Hi Tobi,

I just committed a fix to your problem. The root of your problem: On the development branch, we started using more rigorous input validation which caused a problem in this particular case, as the calculation of confidence intervals was only allowed for vectors *not containing any NAs*; however, the design you provided naturally contained multiple NAs, as only two out of four within-subjects conditions are realized within one participant.
