### ISSUE TITLE
ampersand_filter() fails on Windows with simplified Chinese locale

### ISSUE THREAD

**Issue by SongchaoChen** [crsh/papaja#139]
I am a new learner in writing paper using papaja.
Based on the template, I tried to use @NameYearTitle to cite reference directly, it returned the error "pandoc.exe: Error in $: Failed reading: Cannot decode byte '\x3c': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream".
However, when I used [@NameYearTitle], it did work.
The default encoding is UTF-8 for Rmarkdown.
Could you help me to fix this problem? Thanks in advance.

Here are the documents.
[r-references.txt](https://github.com/crsh/papaja/files/1224599/r-references.txt)
[test.txt](https://github.com/crsh/papaja/files/1224600/test.txt)

**Comment by crsh** [comment]
Hi Songchao, thanks for reaching out. I'll do my best to help. Unfortunately, I'm having trouble reproducing the problem. I can knit your document regardless of the citation. I'm guessing your problem is encoding-related and may have to do with a `pandoc`-filter that comes with `papaja`. With your help, I hope we can fix this rather quickly. Could you try installing a test version of `papaja` (`devtools::install_github("crsh/papaja", ref = "ampersand_filter_encoding")` and knitting again? If this doesn't work there is another approach we could try.

**Comment by SongchaoChen** [comment]
Thanks for your reply. I installed the test version and knitted again. Another error is listed as follows:
![image](https://user-images.githubusercontent.com/31031140/29461326-98f8e16c-842b-11e7-94ca-ff17a9171d8f.png)
Many thanks for your help.

**Comment by crsh** [comment]
Hmm, I assume you tried to knit a different document than the one you attached in your initial post, right? Let's try to fix that problem first and then turn to the new one, which is related to a different function. Could you knit the minimal example that you uploaded and let me know if that works?

**Comment by SongchaoChen** [comment]
Yes, you are right, I used a different document, sorry for that.
I used  the minimal example, it showed the similar error:
`pandoc.exe: Error in $: Failed reading: Cannot decode byte'\xb6':Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream.`

**Comment by crsh** [comment]
Thanks. I have implemented a different approach. Could you reinstall as per the instructions above and retry?

**Comment by SongchaoChen** [comment]
Mank many thanks for your update. The new error is as following:
`pandoc.exe: Error in $: Failed reading: not a valid json value` 
`Error: pandoc document conversion failed with error 1`

**Comment by crsh** [comment]
Sorry, that didn't work. I hate encoding bugs. ;)

Could you post the output from the following command?

~~~{r}
devtools::session_info()
~~~

**Comment by SongchaoChen** [comment]
` setting  value                                              
 version  R version 3.4.0 (2017-04-21)                       
 system   x86_64, mingw32                                    
 ui       RStudio (1.0.143)                                  
 language (EN)                                               
 collate  Chinese (Simplified)_People's Republic of China.936
 tz       Europe/Paris                                       
 date     2017-09-04                                         

Packages --------------------------------------------------------------------------------------------
 package   * version    date       source                      
 backports   1.0.5      2017-01-18 CRAN (R 3.4.0)              
 devtools    1.12.0     2016-12-05 CRAN (R 3.4.0)              
 digest      0.6.12     2017-01-27 CRAN (R 3.4.0)              
 evaluate    0.10.1     2017-06-24 CRAN (R 3.4.1)              
 htmltools   0.3.6      2017-04-28 CRAN (R 3.4.0)              
 knitr       1.17       2017-08-15 Github (yihui/knitr@ea5d88b)
 magrittr    1.5        2014-11-22 CRAN (R 3.4.0)              
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.0)              
 papaja      0.1.0.9492 2017-08-24 Github (crsh/papaja@ba803c0)
 Rcpp        0.12.11    2017-05-22 CRAN (R 3.4.1)              
 rmarkdown   1.6        2017-06-15 CRAN (R 3.4.1)              
 rprojroot   1.2        2017-01-16 CRAN (R 3.4.1)              
 stringi     1.1.5      2017-04-07 CRAN (R 3.4.0)              
 stringr     1.2.0      2017-02-18 CRAN (R 3.4.0)              
 withr       1.0.2      2016-06-20 CRAN (R 3.4.0)              
 yaml        2.1.14     2016-11-12 CRAN (R 3.4.0) `

I think it may be linked with Chinese windows system. For the same problem happened on two Chinese windows systems, but papaja package worked well on my another computer with English windows system.

Anyway, many thanks for your effects. Now I am using papaja package with the computer with English windows system in my office.

Best wishes,
Songchao

**Comment by crsh** [comment]
Thanks, I think you are right that the Chinese locale is causing this issue. I would, nonetheless like to try to fix this issue even if you have resolved it by using an English system. I have implemented another approach that also create some log files for debugging.

Would you again reinstall papaja (`devtools::install_github("crsh/papaja", ref = "ampersand_filter_encoding")`), knit the document that's giving you the trouble, post any error message you might get, and upload the files `ast_test.txt`, `ast_test2.txt`, `ast_test3.txt`, and `ast_encoding.txt` that are created in your users home directory (`~/`)?

Thanks for baring with me on this.

**Comment by SongchaoChen** [comment]
Thanks for your update. The error message is as 
`pandoc.exe: Error in $: Failed reading: not a valid json value
ERROR: pandoc document conversion failed with error 1`
[ast_encoding.txt](https://github.com/crsh/papaja/files/1282520/ast_encoding.txt)
[ast_test.txt](https://github.com/crsh/papaja/files/1282519/ast_test.txt)
[ast_test2.txt](https://github.com/crsh/papaja/files/1282521/ast_test2.txt)
[ast_test3.txt](https://github.com/crsh/papaja/files/1282522/ast_test3.txt)

Thanks for your effects.

**Comment by crsh** [comment]
I'm still scratching my head. From what I see the AST representation that is passed to the `Rscript` session is of native encoding which leads to problems when it is edited and reencoded as UTF-8 in the process. I'm not sure why it is of native encoding because `pandoc` should only output UTF-8. I think I will need a Windows computer with simplified Chinese locale to dig further into this but I don't know if/when I will get around to this. If anyone would like to help out with this, I'd appreciate it. [This](https://github.com/crsh/papaja/blob/master/R/ampersand_filter.R) is where I suspect the problem.

**Comment by SongchaoChen** [comment]
I highly appreciate your updates until now. I am sorry that I am not good at R developing otherwise I could make a contribution to this kind of problem (at least I have 2 Window computers to test).  Thanks in advance to anyone who would like to help out with this problem.

**Comment by diegotrindade** [comment]
My references are full of special characters (e.g ã, ç, à...) and I'm facing the same error using papaja and citr:

> pandoc.exe: Cannot decode byte '\x20': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 1
In addition: Warning message:
running command '"C:/Users/diego/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS mono_paper_papaja.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output mono_paper_papaja.utf8.tmp.html --csl "C:\R-3.4.2\library\papaja\rmarkdown\templates\apa6\resources\apa6.csl" --filter pandoc-citeproc --filter _papaja_ampersand_filter.bat --section-divs --mathjax --number-sections --filter pandoc-citeproc' had status 1 
Execution halted

I've tried to export my library from Zotero using western enconding, but it did not work.

The citation works perfectly when I'm using bookdown or rticles templates.

Bib:
[mono.txt](https://github.com/crsh/papaja/files/1660523/mono.txt)

**Comment by crsh** [comment]
Hi Diego, thanks for reaching out. This could indeed be a helpful test case to pinpoint the problem. I'm rather short on time at the moment. Could you create a minimal working example to reproduce the problem? Ideally this would consist of a clean `papaja` document that contains only one problematic citation. This would help me fix this problem sooner.

**Comment by diegotrindade** [comment]
Thanks for the prompt reply. I got such error using my office computer; but now, I tried in my laptop and it works perfectly. The only difference between them is that, in my computer, I'm using .libpath to load papaja from a different path. Tomorrow I'll try to figure out what can be happening and I come back here. Thanks!

**Comment by diegotrindade** [comment]
Ok. Actually, I'm getting exactly the same error reported by Songchao, it had nothing to do with special characters. I just got the error when I try to cite without brackets. Such error just occur on my computer (Estonian system), whereas on my laptop (Portuguese) the citation works fine.

**Comment by crsh** [comment]
Hi @diegotrindade, thanks for getting back to me and sorry for not responding. Could you send me the problematic R Markdown file and the BibTeX file containing only the citation you tried to add? I have a suspicion what the problem could be, but clearing this up may be a challenge. Could you also provide the output of `devtools::session_info()`?

**Comment by diegotrindade** [comment]
Hi @crsh, sorry for the delay. The problem only occurs when I remove the brackets, regardless of citation. After reinstalling the package as you suggested, I could knit the document citing without brackets, but some errors persist, specially in word documents (e.g. First Author1Â & Ernst-August Doelle1,2 Â Â Â Â Â Â Â Â Â Â Â Â Â).

> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.5.0 Patched (2018-04-25 r74647)
 system   x86_64, mingw32                            
 ui       RStudio (1.1.447)                          
 language (EN)                                       
 collate  Estonian_Estonia.1257                      
 tz       Europe/Helsinki                            
 date     2018-05-08                                 

Packages -----------------------------------------------------------------------------------------------------------
 package    * version    date       source                      
 assertthat   0.2.0      2017-04-11 CRAN (R 3.5.0)              
 backports    1.1.2      2017-12-13 CRAN (R 3.5.0)              
 base       * 3.5.0      2018-04-27 local                       
 bibtex       0.4.2      2017-06-30 CRAN (R 3.5.0)              
 citr         0.2.0      2016-09-20 CRAN (R 3.5.0)              
 compiler     3.5.0      2018-04-27 local                       
 curl         3.2        2018-03-28 CRAN (R 3.5.0)              
 datasets   * 3.5.0      2018-04-27 local                       
 devtools     1.13.5     2018-02-18 CRAN (R 3.5.0)              
 digest       0.6.15     2018-01-28 CRAN (R 3.5.0)              
 evaluate     0.10.1     2017-06-24 CRAN (R 3.5.0)              
 git2r        0.21.0     2018-01-04 CRAN (R 3.5.0)              
 graphics   * 3.5.0      2018-04-27 local                       
 grDevices  * 3.5.0      2018-04-27 local                       
 htmltools    0.3.6      2017-04-28 CRAN (R 3.5.0)              
 httpuv       1.4.2      2018-05-03 CRAN (R 3.5.0)              
 httr         1.3.1      2017-08-20 CRAN (R 3.5.0)              
 jsonlite     1.5        2017-06-01 CRAN (R 3.5.0)              
 knitr        1.20       2018-02-20 CRAN (R 3.5.0)              
 later        0.7.2      2018-05-01 CRAN (R 3.5.0)              
 lubridate    1.7.4      2018-04-11 CRAN (R 3.5.0)              
 magrittr     1.5        2014-11-22 CRAN (R 3.5.0)              
 memoise      1.1.0      2017-04-21 CRAN (R 3.5.0)              
 methods    * 3.5.0      2018-04-27 local                       
 mime         0.5        2016-07-07 CRAN (R 3.5.0)              
 miniUI       0.1.1      2016-01-15 CRAN (R 3.5.0)              
 papaja     * 0.1.0.9492 2018-05-08 Github (crsh/papaja@e2fe94a)
 plyr         1.8.4      2016-06-08 CRAN (R 3.5.0)              
 promises     1.0.1      2018-04-13 CRAN (R 3.5.0)              
 R6           2.2.2      2017-06-17 CRAN (R 3.5.0)              
 Rcpp         0.12.16    2018-03-13 CRAN (R 3.5.0)              
 RefManageR   1.2.0      2018-04-25 CRAN (R 3.5.0)              
 rmarkdown    1.9        2018-03-01 CRAN (R 3.5.0)              
 rprojroot    1.3-2      2018-01-03 CRAN (R 3.5.0)              
 rstudioapi   0.7        2017-09-07 CRAN (R 3.5.0)              
 shiny      * 1.0.5      2017-08-23 CRAN (R 3.5.0)              
 stats      * 3.5.0      2018-04-27 local                       
 stringi      1.1.7      2018-03-12 CRAN (R 3.5.0)              
 stringr      1.3.0      2018-02-19 CRAN (R 3.5.0)              
 tools        3.5.0      2018-04-27 local                       
 utils      * 3.5.0      2018-04-27 local                       
 withr        2.1.2      2018-03-15 CRAN (R 3.5.0)              
 xml2         1.2.0      2018-01-24 CRAN (R 3.5.0)              
 xtable       1.8-2      2016-02-05 CRAN (R 3.5.0)              
 yaml         2.1.19     2018-05-01 CRAN (R 3.5.0)



Best regards,

Diego

[testrmd.txt](https://github.com/crsh/papaja/files/1984079/testrmd.txt)
[testbib.txt](https://github.com/crsh/papaja/files/1984081/testbib.txt)

**Comment by crsh** [comment]
Hmm, once again, I cannot reproduce the problem. Can you confirm that adding the following to the YAML front matter prevents the error?

~~~yaml
replace_ampersands: no
~~~

**Comment by diegotrindade** [comment]
Ok! The `replace_ampersands: no` didn't help. However, I fixed the error setting the "apa6.csl"  to the YAML. Now, it is working perfectly!

**Comment by crsh** [comment]
Hmm, that's odd. If I may bother you with this again, could I ask you to install the latest development version (`devtools::install_github("crsh/papaja@devel")`) and try `replace_ampersands: no` one more time?

**Comment by diegotrindade** [comment]
After installing the latest version the error message is:

Word document:
> Error running filter _papaja_ampersand_filter.bat:
Error in $: Failed reading: Cannot decode input: Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 83
In addition: Warning message:
In kable_markdown(x, padding = padding, ...) :
  The table should have a header (column names)
Execution halted


Pdf:

> ! LaTeX Error: Missing \begin{document}.

Error: Failed to compile testrmd.tex. See testrmd.log for more info.
Execution halted

**Comment by crsh** [comment]
Sorry about that. That was an unrelated bug introduced by a previous commit. I just pushed a new commit that should resolve *that* issue.

**Comment by diegotrindade** [comment]
Error fixed to PDF documents!

However, it didn't work to word documents:

~~~
Error running filter _papaja_ampersand_filter.bat:
Error in $: Failed reading: Cannot decode input: Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 83
In addition: Warning message:
In kable_markdown(x, padding = padding, ...) :
  The table should have a header (column names)
Execution halted
~~~

**Comment by diegotrindade** [comment]
Hmm.. The new error is:

~~~

Error in namespaceExport(ns, exports) : 
  undefined exports: %s!=%, %s!==%, %s+%, %s<%, %s<=%, %s==%, %s===%, %s>%, %s>=%, %stri!=%, %stri!==%, %stri+%, %stri<%, %stri<=%, %stri==%, %stri===%, %stri>%, %stri>=%, stri_datetime_add<-, stri_sub<-, stri_subset<-, stri_subset_charclass<-, stri_subset_coll<-, stri_subset_fixed<-, stri_subset_regex<-, stri_c, stri_c_list, stri_cmp, stri_cmp_eq, stri_cmp_equiv, stri_cmp_ge, stri_cmp_gt, stri_cmp_le, stri_cmp_lt, stri_cmp_neq, stri_cmp_nequiv, stri_compare, stri_conv, stri_count, stri_count_boundaries, stri_count_charclass, stri_count_coll, stri_count_fixed, stri_count_regex, stri_count_words, stri_datetime_add, stri_datetime_create, stri_datetime_fields, stri_datetime_format, stri_datetime_fstr, stri_datetime_now, stri_datetime_parse, stri_datetime_symbols, stri_detect, stri_detect_charclass, stri_detect_coll, stri_detect_fixed, stri_detect_regex, stri_dup, stri_duplicated, stri_duplicated_any, stri_enc_detect, stri_enc_detect2, stri_enc_fromutf32, stri_enc_get, stri_enc_inf
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

~~~

**Comment by crsh** [comment]
Hmm.. indeed. If I understand correctly, all these are functions from the `stringi` package and I don't think this is directly related to `papaja`. I think this may be due to a faulty installation of that package. Could you try `remove.packages("stringi"); install.packages("stringi")`?

**Comment by crsh** [comment]
Another report regarding this (or at least a similar) issue arrive via e-mail a couple of days ago. The error only occurs for `apa6_word()`:

~~~
Fehlermeldung:
pandoc.exe: Error running filter _papaja_ampersand_filter.bat
fd:3: hClose: resource vanished (Broken pipe)
Fehler: pandoc document conversion failed with error 83
Zusätzlich: Warnmeldung:
In kable_markdown(x, padding = padding, ...) :
  The table should have a header (column names)
Ausführung angehalten

sessionInfo() Output:
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252     LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] compiler_3.5.1    backports_1.1.2   magrittr_1.5       rprojroot_1.3-2   htmltools_0.3.6   tools_3.5.1
 [7] yaml_2.1.19       Rcpp_0.12.17      stringi_1.1.7       rmarkdown_1.10    papaja_0.1.0.9709 knitr_1.20
[13] stringr_1.3.1     digest_0.6.15     evaluate_0.10.1 
~~~

**Comment by crsh** [comment]
Okay, I *finally*  found some time and set up a Windows machine with Chinese locale and I think I was able to fix your problem, @SongchaoChen. Try to install the current development version (`devtools::install_github("crsh/papaja@devel")`) and see if that fixes the the issue for you.

@diegotrindade It's possible that the fix also resolves your problem. Would you be willing to give it a try and report back whether it works?

**Comment by diegotrindade** [comment]
Sorry for the delay. It`s working for me! Many thanks!
