### ISSUE TITLE
Unnecessary table note included if `escape = TRUE`

### ISSUE THREAD

**Issue by mariusbarth** [crsh/papaja#141]
Using `apa_table`, if parameter `escape = TRUE`, an unnecessary table note is included:

```
# looks as expected:
apa_table(
  npk[1:4, ]
)

# has an empty table note:
apa_table(
  npk[1:4, ]
  , escape = TRUE
)
```

**Comment by crsh** [comment]
Hi @mariusbarth, I can't reproduce this issue with the current development version. Could you try again and close this issue if it has been resolved?

**Comment by mariusbarth** [comment]
Hi @crsh, you are completely right, I could easily reproduce this bug when I installed from either the master or the variable_labels branch, but it did not occur when I installed from the development branch.

So this bug seems to be solved.
