### ISSUE TITLE
latexmk.exe: MiKTeX encountered an internal error.

### ISSUE THREAD

**Issue by sjystu** [crsh/papaja#143]
Hello,

Before everything else, I want to Thank you for your awesome package!

I am using your package for my day-to-day writing. This is really really cool.

I rendered your example.Rmd file in R terminal and was able to successfully produce PDF file.
However, one thing I want to clearly know is why I see the following error message whenever I render .Rmd file using papaja: "latexmk.exe:

> MiKTeX encountered an internal error.

Any ideas about how to free from this bugging message?

Your help would be so much appreciated.

I am copying and pasting my R code and its corresponding output below throughout the progress:

> # System and R infomation below:
> Sys.info()
[example.pdf](https://github.com/crsh/papaja/files/1252796/example.pdf)
[example.pdf](https://github.com/crsh/papaja/files/1252797/example.pdf)

          sysname           release           version          nodename 
        "Windows"          "10 x64"     "build 14393" "DESKTOP-JCEI8IR" 
          machine             login              user    effective_user 
         "x86-64"        "JooYoung"        "JooYoung"        "JooYoung" 
> R.Version()
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "3"

$minor
[1] "4.1"

$year
[1] "2017"

$month
[1] "06"

$day
[1] "30"

$`svn rev`
[1] "72865"

$language
[1] "R"

$version.string
[1] "R version 3.4.1 (2017-06-30)"

$nickname
[1] "Single Candle"

> 
> # Rendering the example file:
> rmarkdown::render("example.Rmd")

processing file: example.Rmd

  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |...                                                              |   5%
  ordinary text without R code

  |                                                                       
  |......                                                           |  10%
label: unnamed-chunk-1 (with options) 
List of 2
 $ message: logi FALSE
 $ warning: logi FALSE

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Loading required package: lme4
Loading required package: Matrix
Loading required package: lsmeans
Loading required package: estimability
************
Welcome to afex. For support visit: http://afex.singmann.science/
- Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
- Methods for calculating p-values with mixed(): 'KR', 'S', 'LRT', and 'PB'
- 'afex_aov' and 'mixed' objects can be passed to lsmeans() for follow-up tests
- Get and set global package options with: afex_options()
- Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
- For example analyses see: browseVignettes("afex")
************

Attaching package: 'afex'

The following object is masked from 'package:lme4':

    lmer

  |                                                                       
  |.........                                                        |  14%
  ordinary text without R code

  |                                                                       
  |............                                                     |  19%
label: menu (with options) 
List of 2
 $ fig.cap  : chr "papaja's APA6 template is available through the RStudio menues."
 $ fig.align: chr "center"

  |                                                                       
  |...............                                                  |  24%
  ordinary text without R code

  |                                                                       
  |...................                                              |  29%
label: knit (with options) 
List of 2
 $ fig.cap  : chr "The Knit button in the RStudio."
 $ fig.align: chr "center"

  |                                                                       
  |......................                                           |  33%
  ordinary text without R code

  |                                                                       
  |.........................                                        |  38%
label: unnamed-chunk-2 (with options) 
List of 2
 $ echo   : logi TRUE
 $ results: chr "markup"

  |                                                                       
  |............................                                     |  43%
  ordinary text without R code

  |                                                                       
  |...............................                                  |  48%
label: unnamed-chunk-3 (with options) 
List of 2
 $ results: chr "asis"
 $ echo   : logi TRUE

  |                                                                       
  |..................................                               |  52%
  ordinary text without R code

  |                                                                       
  |.....................................                            |  57%
label: beeplot (with options) 
List of 3
 $ fig.cap : chr "Bee plot of the example data set. Small points represent individual observations, large points represent means,"| __truncated__
 $ echo    : logi TRUE
 $ dev.args: language list(bg = "white")

  |                                                                       
  |........................................                         |  62%
  ordinary text without R code

  |                                                                       
  |...........................................                      |  67%
label: unnamed-chunk-4 (with options) 
List of 1
 $ echo: logi TRUE

Contrasts set to contr.sum for the following variables: Dosage

  |                                                                       
  |..............................................                   |  71%
  ordinary text without R code

  |                                                                       
  |..................................................               |  76%
label: unnamed-chunk-5 (with options) 
List of 2
 $ eval: logi FALSE
 $ echo: logi TRUE

  |                                                                       
  |.....................................................            |  81%
   inline R code fragments

  |                                                                       
  |........................................................         |  86%
label: anova (with options) 
List of 2
 $ results: chr "asis"
 $ echo   : logi TRUE

  |                                                                       
  |...........................................................      |  90%
  ordinary text without R code

  |                                                                       
  |..............................................................   |  95%
label: unnamed-chunk-6 (with options) 
List of 1
 $ echo: logi TRUE

  |                                                                       
  |.................................................................| 100%
   inline R code fragments

output file: example.knit.md

"C:/PROGRA~1/ANACON~1/Scripts/pandoc" +RTS -K512m -RTS example.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output example.tex --template "C:\PROGRA~1\R\R-34~1.1\library\papaja\RMARKD~1\TEMPLA~1\apa6\RESOUR~1\apa6.tex" --highlight-style tango --latex-engine pdflatex --csl "C:\PROGRA~1\R\R-34~1.1\library\papaja\RMARKD~1\TEMPLA~1\apa6\RESOUR~1\apa6.csl" --filter pandoc-citeproc --filter _papaja_ampersand_filter.bat 
"C:/PROGRA~1/ANACON~1/Scripts/pandoc" +RTS -K512m -RTS example.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output example.tex --template "C:\PROGRA~1\R\R-34~1.1\library\papaja\RMARKD~1\TEMPLA~1\apa6\RESOUR~1\apa6.tex" --highlight-style tango --latex-engine pdflatex --csl "C:\PROGRA~1\R\R-34~1.1\library\papaja\RMARKD~1\TEMPLA~1\apa6\RESOUR~1\apa6.csl" --filter pandoc-citeproc --filter _papaja_ampersand_filter.bat 
latexmk.exe: MiKTeX encountered an internal error.

======================================================================
starting package maintenance...
installation directory: "C:\Program Files\MiKTeX 2.9"
package repository: http://ftp.heanet.ie/mirrors/ctan.org/tex/systems/win32/miktex/tm/packages/
lightweight database digest: afe99120467ac251661f9d2217790563
going to download 324623 bytes
going to install 24 file(s) (1 package(s))
downloading http://ftp.heanet.ie/mirrors/ctan.org/tex/systems/win32/miktex/tm/packages/latexmk.tar.lzma...
324623 bytes, 312.02 KB/Sec
extracting files from latexmk.tar.lzma...
======================================================================

Latexmk, John Collins, 5 Sep. 2016. Version 4.48
latexmk.exe: MiKTeX encountered an internal error.
This is BibTeX, Version 0.99d (MiKTeX 2.9 64-bit)
The top-level auxiliary file: example.aux
I found no \citation commands---while reading file example.aux
I found no \bibdata command---while reading file example.aux
I found no \bibstyle command---while reading file example.aux
(There were 3 error messages)

Output created: example.pdf
Warning messages:
1: running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\latexmk.exe" -v' had status 1 
2: running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\latexmk.exe" -v' had status 1 
3: The LaTeX package latexmk was not correctly installed. 
4: running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\latexmk.exe" -v' had status 1 
5: running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\latexmk.exe" -v' had status 1 
6: running command '"bibtex" "example.aux"' had status 1 
7: running command '"bibtex" "example.aux"' had status 1 
> 
> proc.time()
   user  system elapsed 
   5.68    1.28   20.98

**Comment by crsh** [comment]
Hi JooYoung, there is a discussion in GitHub issues on this [here](https://github.com/rstudio/bookdown/issues/169). It says that the warning can be safely ignored. Nonetheless, could you try running the following commands in RStudio and post the resulting output here?

~~~{r}
system("\"C:\\PROGRA~1\\MIKTEX~1.9\\miktex\\bin\x64\\latexmk.exe\" -v")
shell("latexmk.exe -v")
~~~

**Comment by sjystu** [comment]
Hello,

 

Thank you so much for your kind response as  always.

 

Please refer to the below:

> 

> # Original code:

> system("\"C:\\PROGRA~1\\MIKTEX~1.9\\miktex\\bin\x64\\latexmk.exe\" -v")

Warning message:

running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bind\latexmk.exe" -v' had status 127 

> 

> # But I have install MiTeX 2.9, not 1.9. So I have changed the version number in the path:

> system("\"C:\\PROGRA~1\\MIKTEX~2.9\\miktex\\bin\x64\\latexmk.exe\" -v")

Warning message:

running command '"C:\PROGRA~1\MIKTEX~2.9\miktex\bind\latexmk.exe" -v' had status 127 

> 

> shell("latexmk.exe -v")

 

======================================================================

starting package maintenance...

installation directory: "C:\Program Files\MiKTeX 2.9"

package repository: http://ftp.heanet.ie/mirrors/ctan.org/tex/systems/win32/miktex/tm/packages/

lightweight database digest: afe99120467ac251661f9d2217790563

going to download 324623 bytes

going to install 24 file(s) (1 package(s))

downloading http://ftp.heanet.ie/mirrors/ctan.org/tex/systems/win32/miktex/tm/packages/latexmk.tar.lzma...

324623 bytes, 251.80 KB/Sec

extracting files from latexmk.tar.lzma...

======================================================================

 

Latexmk, John Collins, 5 Sep. 2016. Version 4.48

> 

>

**Comment by crsh** [comment]
From what I see here, you seem to be experiencing that is being discussed in the linked issue above. You can safely ignore it. It is suggested that the error message is resolved in the latest development version of R Markdown (`devtools::install_github('rstudio/rmarkdown')`). Let me know if that helps.

**Comment by crsh** [comment]
I'm closing this issue because it seem to me it has been resolved. Feel free to reopen if you have any other questions.
