### ISSUE TITLE
Results not getting displayed in papaja output document

### ISSUE THREAD

**Issue by jainsnigdha** [crsh/papaja#144]

**Comment by crsh** [comment]
Hi, this description is not very informative. Could you provide a reproducible example of the issue your are experiencing together with a description of the expected behavior?

**Comment by jainsnigdha** [comment]
Hi, I'm sorry. I was in a rush when I posted the message. I figured out the
issue later.

Apologies for the confusing message and for the delayed response. Please
let me know if you want me to go ahead and delete message from the forum.

Thanks,
Snigdha

**Comment by crsh** [comment]
No problem, thanks for clearing this up. :+1:
