### ISSUE TITLE
compiling pdf from tex when generating table using texreg package

### ISSUE THREAD

**Issue by HeatherUrry** [crsh/papaja#145]
Hi there,

I'm a huge fan of papaja - it has pretty much revolutionized how I write manuscripts. Thank you!

I'm having an issue with including a table generated using the texreg package. Although the .tex file gets created, errors get thrown when producing the .pdf:

! Misplaced \noalign.
\hline ->\noalign 
                  {\ifnum 0=`}\fi \hrule \@height \arrayrulewidth \futurelet...
l.193 ...kslash{}begin\{tabular\}\{l c c \} \hline

Error: Failed to compile example.tex. See example.log for more info.

I've made a reproducible example (example .Rmd), which generates data (R code chunk:  generatedata), computes two linear mixed effects models to be included in the table (R code chunk:  mixedeffects), and then generates the texreg table in question (R code chunk:  fit). If I set the fit code chunk to eval=FALSE, the .pdf gets compiled.  I copied example.Rmd below (I also attached it as a .txt file). Below that, you'll find the output of sessInfo() on my machine.

This example also illustrates a second problem I'm having. I'm not sure what the etiquette is here. If I should submit that as a second new issues, let me know; I'm happy to do so. Otherwise, the problem is that I'm generating a figure (R code chunk:  sjplotfit) using sjp.lmer (from the sjPlot package), but the figure doesn't get numbered properly and it doesn't appear at the end of the manuscript as I was hoping/expecting. 

If you have any insight on one or both issues, I'd be very grateful. Thank you!

Best,

Heather
[example.txt](https://github.com/crsh/papaja/files/1273039/example.txt)

******************************* example.Rmd ***************************************

---
title             : "this is a title"
shorttitle        : "short title"

author: 
  - name          : "Heather L. Urry"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "490 Boston Ave, Medford, MA, 02155, USA"
    email         : "heather.urry@tufts.edu"

affiliation:
  - id            : "1"
    institution   : "Tufts University"

author_note: >
  Heather L. Urry, Department of Psychology, Tufts University.   

  This is my author note. 

abstract: >
  This is the abstract

keywords          : "keyword, keyword"
wordcount         : "X"

bibliography      : ["r_references.bib"]

figsintext        : no
figurelist        : no #defaults to no
tablelist         : no
footnotelist      : no
lineno            : no #defaults to yes

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---
```{r setup}

# Set default chunk options (can be overridden in later chunks)
knitr::opts_chunk$set(echo = FALSE, 
                      eval = TRUE,
                      message = FALSE, 
                      fig.width = 7, 
                      fig.height = 7,
                      results = "hide",
                      error = FALSE,
                      warning = FALSE,
                      include=TRUE)


```

```{r libraries, include = FALSE}

library(papaja)
library(texreg)
library(lme4)
library(ggplot2)
library(sjPlot)
library(cowplot)

```

This is a really short introduction.

# Method
## Design and data analysis
We analyzed our data using `r cite_r("r_references.bib")`. 

```{r generatedata}

## Specify number of subjects for each between-subjects group
npergroup <- c(24,29,28)  #groups 1, 2, and 3

# Specify number of items
nitems <- 6

# Compute number of subjects and groups based on Ns provided above
nsubjects <- sum(npergroup)
ngroups <- length(npergroup)

## Specify starting values to be used for generating the dependent variable
## in a linear mixed effects model ##

# intercept
b0=70       
# fixed effect beta weights; expand as needed
bcon1=10    #beta for contrast 1 
bcon2=12    #beta for contrast 2 

# random effect variance
vsubj= 91    #variance across subjects
vitem=105    #variance across items
vcon1item=6  #variance of contrast1 across items
vcon2item=10 #variance of contrast2 across items

#residual variance
verror=607   #residual error variance

# generate data

subject <- rep( 1:nsubjects, each=nitems )  # nsubjects that repeat nitems times
item <- rep( 1:nitems, nsubjects )  # nitems for each of the nsubjects above

###### specify contrasts of interest below #######
## make sure each contrast is handled properly throughout this code

# generate entries for fixed effects
# Effect codes for group 1 versus groups 2/3
con1 <- rep(c(.5,-.25,-.25), c(npergroup)) 
# Effect codes for group 2 versus group 3
con2 <- ifelse(con1==.5,0,rep(c(.5,-.5), c(npergroup[2:3])))  

# random effects per subject
s.re <- rnorm(nsubjects, 0, sqrt(vsubj))

# random effects per item
i.re <- rnorm(nitems, 0, sqrt(vitem))

# random effects for contrasts across items
con1item.re <- rnorm(nitems, 0, sqrt(vcon1item))
con2item.re <- rnorm(nitems, 0, sqrt(vcon2item))

# epsilons
eps <- rnorm(nsubjects*nitems, 0, sqrt(verror))

# construct linear model based on above to simulate data for the dependent variable (dv)
# values are integers ranging from 0 to 100
dv <- round(b0 + bcon1*con1 + bcon2*con2 + s.re[subject] + i.re[item] + con1item.re[item] + con2item.re[item]+ eps)
dv <- ifelse(dv > 100,100,ifelse(dv < 0,0,dv)) #deal with values that surpass 100 or dip below 0
  
# put all variables into a data frame
simdata <- data.frame( subject = paste('s',subject, sep=''), 
                      item = paste('v', item, sep=''), 
                      con1=con1, con2=con2,  # fixed effects
                      dv = dv)               # dv


```
# Results
```{r mixedeffects}

# run two linear mixed effects models using lme4 to enable use of texreg to create a nice table that includes both fixed and random effects

# random intercepts only
fit1 <- lmerTest::lmer(dv ~ con1 + con2 + 
                          (1|subject) + 
                          (1|item),
                        data=simdata, 
                        control=lmerControl(optCtrl=list(maxfun=50000)),
                        REML = FALSE)
# random intercepts and random slopes
fit2 <- lmerTest::lmer(dv ~ con1 + con2 + 
                          (1|subject) + 
                          ((con1+con2)|item),
                        data=simdata, 
                        control=lmerControl(optCtrl=list(maxfun=50000)),
                        REML = FALSE)

fit2addvalue <- anova(fit1,fit2)
```

```{r fit, results="asis"}

# generate a table using texreg package to show both models
# this table generates errors when compiling to tex to pdf

fit<-texreg((list(fit1,fit2)),
       single.row=TRUE, ci.force=TRUE,use.packages=FALSE,
       custom.note="\\parbox{.4\\linewidth}{\\vspace{2pt}%stars. Model 1 includes random intercepts (participants and items) only. Model 2 includes the random intercepts from Model 1 plus random slopes for the two fixed effects across items. Var = variance, Cov = covariance",
       groups=list("Fixed Effects" = 1:3),
       custom.coef.names=c("(Intercept)", 
                           "contrast 1", 
                           "contrast 2"
                           ))
cat(fit)
```
As shown in Table \@ref(tab:fit), consistent with the confirmatory analyses above, the effects of the two primary contrasts were small and unsurprising if the null hypothesis is true. 

```{r sjplotfit,results="asis",fig.cap = "\\label{fig:sjplotfit} Panel A shows random intercepts across participants. Panel B shows random intercepts and random slopes for effects of the two primary contrasts across vignettes. Panel C shows random intercepts and random slopes for those same contrasts across levels of participant knowledge about the hypothesis. Blue dots reflect positive vaues while red dots reflect negative values. Horizontal lines through each dot reflect the 95\\% confidence interval."}

# this code generates a figure but this figure doesn't get numbered properly and it shows up in text instead of at the end (figsintext is set to no)

sjplotfit<-sjp.lmer(fit2, show.values=FALSE,prnt.plot = FALSE)
p1<-sjplotfit$plot.list[[1]] + labs(y="best linear unbiased prediction",x="participant") + scale_x_discrete(breaks=seq(1,81,10))
p2<-sjplotfit$plot.list[[2]] + labs(y="best linear unbiased prediction",x="item") 

plot_grid(p1,p2, labels = "AUTO", ncol = 1, align = 'hv')

# BLUP = best linear unbiased prediction

```
Figures \@ref(fig:sjplotfit) shows the best linear unbiased predictions for the dependent variable based on a model examining random intercepts across participants and items, and random slopes for the two contrasts of interest across items.

# Discussion
Here I say some smart things to make sense of it all and wrap things up.

\newpage

# References
```{r create_r-references}

r_refs(file = "r_references.bib")

```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

**************************************************************************************

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0

**Comment by crsh** [comment]
Hi Heather,

> I'm a huge fan of papaja - it has pretty much revolutionized how I write manuscripts

what a nice compliment. Thank you!

Regarding `texreg`, the issue is an open `{` in the table note that is not closed; try `custom.note="\\parbox{.4\\linewidth}{\\vspace{2pt}%stars. Model 1 includes random intercepts (participants and items) only. Model 2 includes the random intercepts from Model 1 plus random slopes for the two fixed effects across items. Var = variance, Cov = covariance}"`. :wink:

Note that `texreg()` places the table caption under the table instead of above as would be required by APA style. There is no easy way of fixing this that I know. You could copy the table code into your document and move the caption to the top manually, though. Moreover, `texreg()` doesn't automatically add a label to the table by which it can be referenced. Hence, `\@ref(tab:fit)` will not work unless you add a label manually: `label = "tab:fit""`.

The problem with your figure is that you need an empty new line after each code chunk. If you add an empty line at line 198 everything should work as expected. As a side note, `\\label{fig:sjplotfit}` should be added automatically, so you don't need to include it in the figure caption. Also, I recommend to use text references for figure captions as explained [here](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references). If you do, there is no need to escape `%`. Finally, for this chunk you don't need to set `results="asis"`.

I hope this answers all your questions.

**Comment by HeatherUrry** [comment]
Wow, you've answered all my questions, and added so much helpful NEW information as well. Thank you so much. The figures are now all appearing as expected, and I really like using the text references for figure captions based on the bookdown link. That's a nice feature, and it even led me to determine why a figure in the appendix wasn't being properly referenced (and how to fix it). 

Re: my original question about the texreg table, how embarrassing that the problem is a missing } in the command!  :\  BUT, not the first time I've made a silly mistake, and most certainly not the last time either. 

Re: texreg, the `caption.above = TRUE` argument allows you to put the caption above rather than below the table, which is great. Ultimately, however, I decided to give up on texreg because I got tired of trying to figure out how to customize what it shows. What I did instead is use the `sjPlot::sjt.lmer` function. The tables it produces are really very nice. The only downside is that it produces html output. There's a way to get it to provide code that's knitr friendly, but I haven't so far been able to get it to play nice when outputting a pdf in papaja.  My workaround, which is definitely not ideal, has been to save the table as html, then use webshot to produce a png from the html file, and then insert that png into an R code chunk that turns the table into a figure. (It's an annoying workaround.) If you have suggestions here, I'm all ears. 

Thank you for all of your help! You've really gone above and beyond in answering questions that aren't papaja questions.

Heather

**Comment by crsh** [comment]
> `caption.above = TRUE` argument allows you to put the caption above rather than below the table

Hah, I missed that. That's handy.

> What I did instead is use the `sjPlot::sjt.lmer` function. The tables it produces are really very nice.

Those tables are indeed nice. It's unfortunate that the function only supports HTML output. I don't think there is an elegant solution to include HTML tables in PDF documents. I intend to provide support for `lmer` and `glmer` objects in `apa_print()` at some point. The function will then return tables similar to the those of `sjPlot::sjt.lmer` but they should work with LaTeX and Word. I expect it will be a little while before I get around to this, though.
