### ISSUE TITLE
LaTeX for partial eta-squared symbol and % in table not rendering correctly in pdf

### ISSUE THREAD

**Issue by HeatherUrry** [crsh/papaja#146]
Hi there,

I'm referring to both partial eta-squared and a confidence interval in the column names of a table's data frame and in the table note. In both places, the LaTeX isn't rendering properly in the pdf. 

In R Markdown, I refer to partial eta-squared as: $\\eta^{2}_{p}$
It gets rendered in the tex file as: \$\textbackslash{}eta\textasciicircum{}\{2\}\_\{p\}\$
It looks like this in the pdf: $\eta^{2}_{p}$

In R Markdown, I refer to a 90% confidence interval as: 90\\%
It gets rendered in the tex file as: 90\textbackslash{}\%
It looks like this in the pdf: 90\%

Are you able to tell me how to modify the R Markdown code to render these correctly? I recently updated papaja; one or both of these may have been introduced in that update (?).  See my sessionInfo below.

Thanks!

Heather

P.S. I can put together a reproducible example but thought perhaps this is a situation where it's not needed; let me know otherwise! 

Here's my sessionInfo():

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] papaja_0.1.0.9492

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0    knitr_1.17

**Comment by crsh** [comment]
Hi Heather, thanks for reaching out. What function are you using to render the table? If you are using `knitr::kable()` or `papaja::apa_table()` try using `escape = FALSE`. This option prevents the functions from replacing the symbols with LaTeX code.

**Comment by HeatherUrry** [comment]
Thank you! I'm using papaja::apa_table() indeed, and escape = FALSE did the trick.  (I should've been able to figure that one out myself. Also, I see now that the Markdown display above didn't show the text as typed, but you figured out the issue anyway; sorry about that.  :\ Thanks for your patience.)

**Comment by crsh** [comment]
You're welcome. :call_me_hand:
