### ISSUE TITLE
Error when trying to output to Word

### ISSUE THREAD

**Issue by lindsayhinzman** [crsh/papaja#156]
Hello,

I keep getting the following error when I set "output: papaja::apa6_word" in the YAML header"

Error in writeLines(input_file_connection, input_file) : 
  invalid 'text' argument

This is happening with older versions of the rmd that had successfully outputted to word before. This is also happening with the empty papaja template. I can't figure out what the problem is.

**Comment by lindsayhinzman** [comment]
Update: I realized this happened after I updated to the latest version of papaja (0.1.0.9492). When I reverted back to the previous version I had been using (version 0.1.0.9479) I am able to output to a Word doc.

**Comment by crsh** [comment]
Hi Lindsay, thanks for bringing this to my attention. I can reproduce the problem and will try to fix this as soon as possible.

**Comment by crsh** [comment]
Hi Lindsay, I just pushed a fix for this problem to the development branch. Try updating your papaja version (`devtools::install_github("crsh/papaja@devel")`) and let me know if it works.

**Comment by samirnemechaves** [comment]
Morning @crsh, I try the same, i actualized my papaja, but apear this error

**Comment by samirnemechaves** [comment]
Just in papaja::apa6_word; in papaja::apa6_pdf work it
