### ISSUE TITLE
Escaping of $ in apa_table

### ISSUE THREAD

**Issue by viciously0** [crsh/papaja#171]
Hey,

thanks for all your work! I have a problem with the automated escaping of special characters in apa_table:
![grafik](https://user-images.githubusercontent.com/35379548/34888996-b522b768-f7cc-11e7-864f-2becc5c02774.png)

I used `apa_print` to get the summary and `apa_table(summary$table)` to print the table. Both outputs are below. I think `apa_print` tries to make the CI in cursive, hence the $ signs, and `apa_print` tries to escape the $ by putting a \ in front of it. Obviously the $ signs should obvioulsy not be escaped here, but i am also not quite sure what they do... i removed the \ from the tex file and the table looks fine then. What also buffels me, is that the $ in the table header are translated correctly into italic font.

```
\begin{table}[tbp]
\begin{center}
\begin{threeparttable}
\caption{\label{tab:Anova Table}Table of the results of the Anova.}
\begin{tabular}{lllll}
\toprule
Predictor & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{95\% CI} & \multicolumn{1}{c}{$t(209)$} & \multicolumn{1}{c}{$p$}\\
\midrule
Intercept & 0.00 & \$[-0.03\$, \$0.03]\$ & 0.00 & > .999\\
Variable ref cS & -0.06 & \$[-0.11\$, \$-0.01]\$ & -2.58 & .010\\
Variable ref cL & -0.10 & \$[-0.14\$, \$-0.05]\$ & -4.15 & < .001\\
Variable ref cIC & -0.02 & \$[-0.07\$, \$0.03]\$ & -0.84 & .403\\
Variable ref cRC & -0.06 & \$[-0.11\$, \$-0.02]\$ & -2.66 & .008\\
Variable ref cCI0 & -0.02 & \$[-0.07\$, \$0.02]\$ & -0.96 & .337\\
Variable ref cCI100 & -0.03 & \$[-0.08\$, \$0.01]\$ & -1.37 & .172\\
Variable ref cCI400 & -0.02 & \$[-0.07\$, \$0.03]\$ & -0.82 & .414\\
Variable ref cCR0 & -0.05 & \$[-0.09\$, \$0.00]\$ & -1.98 & .049\\
Variable ref cCR100 & -0.06 & \$[-0.10\$, \$-0.01]\$ & -2.43 & .016\\
Variable ref cCR400 & 0.01 & \$[-0.03\$, \$0.06]\$ & 0.51 & .612\\
\bottomrule
\addlinespace
\end{tabular}
\begin{tablenotes}[para]
\textit{Note.} This table was created with apa\_table()
\end{tablenotes}
\end{threeparttable}
\end{center}
\end{table}
```

```
$table
A data.frame with 5 labelled columns:

             predictor estimate                 ci statistic p.value
1            Intercept     0.00  $[-0.03$, $0.03]$      0.00  > .999
2      Variable ref cS    -0.06 $[-0.11$, $-0.01]$     -2.58    .010
3      Variable ref cL    -0.10 $[-0.14$, $-0.05]$     -4.15  < .001
4     Variable ref cIC    -0.02  $[-0.07$, $0.03]$     -0.84    .403
5     Variable ref cRC    -0.06 $[-0.11$, $-0.02]$     -2.66    .008
6    Variable ref cCI0    -0.02  $[-0.07$, $0.02]$     -0.96    .337
7  Variable ref cCI100    -0.03  $[-0.08$, $0.01]$     -1.37    .172
8  Variable ref cCI400    -0.02  $[-0.07$, $0.03]$     -0.82    .414
9    Variable ref cCR0    -0.05  $[-0.09$, $0.00]$     -1.98    .049
10 Variable ref cCR100    -0.06 $[-0.10$, $-0.01]$     -2.43    .016
11 Variable ref cCR400     0.01  $[-0.03$, $0.06]$      0.51    .612

predictor: Predictor 
estimate : $b$ 
ci       : 95\% CI 
statistic: $t(209)$ 
p.value  : $p$ 
```

Thank you for your help!

**Comment by crsh** [comment]
Without access to the R code you used to produce the table I'd guess that adding `escape = FALSE` to the call of `apa_table()` should remove the `\` in the TeX code. Let me know if that helps. If it doesn't, please provide a minimal example of the code that produces this problem.

**Comment by viciously0** [comment]
unfortunately it did not help :(

this would be an example code to reproduce the phenomenon:


```
{r}
examp_lm <- lm(ChickWeight$weight ~ ChickWeight$Diet)
```

```
{r, results = "asis", escape = F}
examp_lm_apa <- apa_print.summary.lm(summary(examp_lm))
```

```
{r, results = "asis"}
apa_table(examp_lm_apa$table)
```
I tried removing the results = "asis" but this also did not help
thank you for your response

**Comment by crsh** [comment]
Thanks for the example. I was trying to suggest the following:

~~~
```{r, results = "asis"}
examp_lm <- lm(ChickWeight$weight ~ ChickWeight$Diet)
examp_lm_apa <- apa_print(examp_lm)
apa_table(examp_lm_apa$table, escape = FALSE)
```
~~~

**Comment by viciously0** [comment]
ah thank you, that worked. Apparently I did not read you answer

**Comment by viciously0** [comment]
well it worked for the example, but their is still the issue that any special character in the table will force an error in LATEX, for example:
```
```{r, results = "asis"}
examp_lm <- lm(ChickWeight$weight ~ ChickWeight$Diet)
examp_lm_apa <- apa_print(examp_lm)
apa_table(examp_lm_apa$table, escape = FALSE, note = "This table was created with apa_table()")
```
```

There is probably no way to disable the escaping only for the body of the table, or is there?

**Comment by crsh** [comment]
That is exepected behavior, although I appreciate that it may be confusing. `_` is an illegal character in LaTeX if it is used outside of equations. Hence, you deactivate the automatic escaping of special characters by using `escape = FALSE` you need to manually escape special characters in table contents, caption, and note:

~~~
```{r, results = "asis"}
examp_lm <- lm(ChickWeight$weight ~ ChickWeight$Diet)
examp_lm_apa <- apa_print(examp_lm)
apa_table(examp_lm_apa$table, escape = FALSE, note = "This table was created with apa\\_table()")
```
~~~

The double `\` is required to let R know that `\` is not an R-escape-sequence. 😶

**Comment by viciously0** [comment]
that will work for me, thank you very much!
