### ISSUE TITLE
Table above section title in Appendix (in class 'doc')

### ISSUE THREAD

**Issue by TobiasKoeln** [crsh/papaja#172]
When displaying a table in an appendix the table is automatically displayed on the top of the page and the header (e.g., Appendix A) is displayed below the table when using the class 'doc'. This problem does not exist when using the class 'man'.

The problem can be fixed when adding an '[h]' in the rendered Latex file (e.g., '\begin{table}[h]'), but maybe there is a better way.

**Comment by crsh** [comment]
Hi Tobi, thanks for opening this issue. I'm sure there is a better way. I'll take a closer look as soon as possible.

**Comment by mariusbarth** [comment]
I encountered a similar issue that was fixed by 3d87236136cad2a94241c9dce567d8698b2ce7d6. So probably this one should be fixed, too. @TobiasKoeln, can you still reproduce this problem after a fresh install of `papaja`?

**Comment by TobiasKoeln** [comment]
Weirdly I now have the problem with the appendix headers in the class "man" and it looks fine in the class "doc" (papaja 0.1.0.9709).
Can you reproduce it (see attached files)?

[Appendix_MWE.zip](https://github.com/crsh/papaja/files/1906787/Appendix_MWE.zip)

**Comment by crsh** [comment]
Hi @TobiasKoeln, thanks for the example. I think this should work now if you use placement options for figures and tables (either in the call to `apa_table()` or the `fig.pos` chunk option---note that you also need to set `out.extra = ""` for the latter to work).

Let me know if that works for you.

**Comment by TobiasKoeln** [comment]
It works well! Thank you
