### ISSUE TITLE
apa_table(): digits is applied by row rather than by column

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#173]
This was pointed out by Matti Heino on Twitter:

~~~r
library("dplyr")
x <- data.frame(rep("a", 3), rnorm(3), rnorm(3))

library("knitr")
x %>% kable(digits = c(0, 2, 0)) 

library("papaja")
x %>% apa_table(digits = c(0, 2, 0))
~~~

When passing options to `printnum()` directly it works fine:

~~~r
x %>% apa_table(format.args = list(digits = c(2, 0), margin = 2))
~~~

**Comment by pgrimald** [comment]
has this fix been merged yet? digits definitely applies to rows for me, even when using format.args.

**Comment by crsh** [comment]
Hi, thanks for asking. Yes, this should be fixed on the development branch (`devtools::install_github("crsh/papaja@devel")`). I hope to release these changes to the master branch this week.
