### ISSUE TITLE
Short title field is not properly rendered in apa6_word output

### ISSUE THREAD

**Issue by sjystu** [crsh/papaja#174]
Hello,

I have attempted to process my manuscript using papaja::apa6_word output; however, the character value inserted to short title (running head) field in YAML does not appear in an output word file.

It is just appeared as "x."

However, the pdf output using papaja::apa6_pdf renders this correctly.

The following includes my session info:

----------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RTerm                       
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2018-01-22                  

 package      * version    date       source                              
 assertthat     0.2.0      2017-04-11 CRAN (R 3.4.1)                      
 backports      1.1.2      2017-12-13 CRAN (R 3.4.3)                      
 base         * 3.4.3      2017-11-30 local                               
 bindr          0.1        2016-11-13 CRAN (R 3.4.1)                      
 bindrcpp       0.2        2017-06-17 CRAN (R 3.4.1)                      
 BrailleR     * 0.27.2     2018-01-11 Github (ajrgodfrey/BrailleR@7c3a623)
 colorspace     1.3-2      2016-12-14 CRAN (R 3.4.1)                      
 compiler       3.4.3      2017-11-30 local                               
 curl           3.1        2017-12-12 CRAN (R 3.4.3)                      
 data.table     1.10.4-3   2017-10-27 CRAN (R 3.4.2)                      
 datasets     * 3.4.3      2017-11-30 local                               
 devtools       1.13.4     2017-11-09 CRAN (R 3.4.2)                      
 digest         0.6.14     2018-01-14 CRAN (R 3.4.3)                      
 dplyr        * 0.7.4      2017-09-28 CRAN (R 3.4.2)                      
 evaluate       0.10.1     2017-06-24 CRAN (R 3.4.1)                      
 extrafont      0.17       2014-12-08 CRAN (R 3.4.0)                      
 extrafontdb    1.0        2012-06-11 CRAN (R 3.4.0)                      
 ggplot2      * 2.2.1.9000 2018-01-21 Github (hadley/ggplot2@401511e)     
 git2r          0.21.0     2018-01-04 CRAN (R 3.4.3)                      
 glue           1.2.0      2017-10-29 CRAN (R 3.4.2)                      
 graphics     * 3.4.3      2017-11-30 local                               
 grDevices    * 3.4.3      2017-11-30 local                               
 grid           3.4.3      2017-11-30 local                               
 gridGraphics   0.2        2017-06-06 CRAN (R 3.4.1)                      
 gridSVG        1.6-0      2017-10-29 CRAN (R 3.4.2)                      
 gtable         0.2.0      2016-02-26 CRAN (R 3.4.1)                      
 htmltools      0.3.6      2017-04-28 CRAN (R 3.4.1)                      
 httr           1.3.1      2017-08-20 CRAN (R 3.4.1)                      
 hunspell       2.9        2017-12-16 CRAN (R 3.4.3)                      
 installr     * 0.19.0     2017-04-21 CRAN (R 3.4.2)                      
 jsonlite       1.5        2017-06-01 CRAN (R 3.4.1)                      
 knitr          1.18.8     2018-01-22 Github (yihui/knitr@0d99e32)        
 lazyeval       0.2.1      2017-10-29 CRAN (R 3.4.2)                      
 magrittr       1.5        2014-11-22 CRAN (R 3.4.1)                      
 MASS           7.3-48     2017-12-25 CRAN (R 3.4.3)                      
 memoise        1.1.0      2017-04-21 CRAN (R 3.4.1)                      
 methods      * 3.4.3      2017-11-30 local                               
 moments        0.14       2015-01-05 CRAN (R 3.4.0)                      
 munsell        0.4.3      2016-02-13 CRAN (R 3.4.1)                      
 neuralnet    * 1.33       2016-08-16 CRAN (R 3.4.1)                      
 nortest        1.0-4      2015-07-30 CRAN (R 3.4.0)                      
 papaja       * 0.1.0.9655 2017-12-12 Github (crsh/papaja@849df30)        
 pillar         1.1.0      2018-01-14 CRAN (R 3.4.3)                      
 pkgconfig      2.0.1      2017-03-21 CRAN (R 3.4.1)                      
 plyr           1.8.4      2016-06-08 CRAN (R 3.4.1)                      
 R6             2.2.2      2017-06-17 CRAN (R 3.4.1)                      
 Rcpp           0.12.15    2018-01-20 CRAN (R 3.4.3)                      
 rlang          0.1.6.9003 2018-01-21 Github (tidyverse/rlang@fa47703)    
 rmarkdown    * 1.8.7      2018-01-19 Github (rstudio/rmarkdown@42cd97b)  
 rprojroot      1.3-2      2018-01-03 CRAN (R 3.4.3)                      
 rstudioapi     0.7        2017-09-07 CRAN (R 3.4.2)                      
 Rttf2pt1       1.3.5      2017-12-04 CRAN (R 3.4.3)                      
 scales         0.5.0.9000 2017-12-03 Github (hadley/scales@d767915)      
 signal         0.7-6      2015-07-30 CRAN (R 3.4.3)                      
 sonify       * 0.0-1      2017-02-01 CRAN (R 3.4.3)                      
 stats        * 3.4.3      2017-11-30 local                               
 stringi        1.1.6      2017-11-17 CRAN (R 3.4.2)                      
 stringr      * 1.2.0      2017-02-18 CRAN (R 3.4.1)                      
 tibble         1.4.1      2017-12-25 CRAN (R 3.4.3)                      
 tools          3.4.3      2017-11-30 local                               
 tuneR        * 1.3.2      2017-04-10 CRAN (R 3.4.2)                      
 utils        * 3.4.3      2017-11-30 local                               
 whisker        0.3-2      2013-04-28 CRAN (R 3.4.1)                      
 withr          2.1.1.9000 2017-12-23 Github (jimhester/withr@df18523)    
 XML            3.98-1.9   2017-06-19 CRAN (R 3.4.0)                      
 xtable         1.8-2      2016-02-05 CRAN (R 3.4.1)                                            
----------

Thank you.

**Comment by crsh** [comment]
Hi, and thanks for reporting this. The "x" on the title page is not even the short title but an artifact from the creation of the table that contains the author affiliations. I just pushed a fix to the development branch (`devtools::install_github("crsh/papaja@devel")`). This should fix the problem. Let me know if this works for you.

**Comment by sjystu** [comment]
Hello,

 

I have installed the development version; however, the produced word file still misses running head.

The difference that the development version made was that “x” does not appear in the running head field; it is just empty.

 

I am using the latest Pandoc in Windows 10 64bit.

Is there anything you need me to additionally report?

 

Thank you.

**Comment by crsh** [comment]
I'm not sure I understand what you mean by running head. To me the running head is the heading line on every page outside the usual page margins that contains the short title and the page number. These running heads are currently not supported in DOCX-format by `pandoc` and consequently not supportedby `rmarkdown` and `papaja` as noted in the [manual](https://crsh.github.io/papaja_man/limitations.html#microsoft-word-documents).

What I had hoped the commit to do is remove the `x` below the title and above the author affiliation. The short title is not supposed to be included here.

Maybe a more detailed description or screenshot of what you mean could clarify things.

**Comment by crsh** [comment]
Okay, great. So we are on the same page. Thanks for raising this issue.
