### ISSUE TITLE
Annotated factors confuse ggplot

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#176]
Working with an annotated `data.frame` I've noticed that some things don't work when a column is of class `annotated_factor`. I'm not sure why this is but it seems the class does not fully behave like an ordinary factor:

~~~r
library("ggplot2")
library("papaja")

mtcars$cyl <- factor(mtcars$cyl)

ggplot(mtcars, aes(cyl, mpg)) +
  geom_violin()

variable_label(mtcars$cyl) <- "Test"

ggplot(mtcars, aes(cyl, mpg)) +
  geom_violin()
~~~

~~~
Error in list_to_dataframe(res, attr(.data, "split_labels"), .id, id_as_factor) : 
  Results must be all atomic, or all data frames
~~~
Any idea how to fix this, @mariusbarth ?

You can get it to work like this:

~~~r
ggplot(mtcars, aes(factor(cyl), mpg)) +
  geom_violin()
~~~

**Comment by mariusbarth** [comment]
This seems to be an interesting case where class inheritance doesn't work nicely. I will try to dig into this this afternoon.

**Comment by mariusbarth** [comment]
I'm digging into this problem, but it's f****g hard to figure out even where problems start.

**Comment by crsh** [comment]
Turns out the problem seems to be deeply burried in `match`:

~~~r
ff <- factor(substring("statistics", 1:10, 1:10), levels = letters)
variable_label(ff) <- "Test"
match(ff, levels(ff))
~~~

~~~
 [1] NA NA NA NA NA NA NA NA NA NA
~~~

**Comment by mariusbarth** [comment]
I just pushed to the `variable_label` branch and changed the label handling to S3 methods which should be less confusing. Check it out.

This is a sad day for R.
