### ISSUE TITLE
Automatically save all plots as high resolution images

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#18]
Many journals like to have all figures as seperate high resolution files. It would be nice if it was possible to automatically save all plots.

**Comment by crsh** [comment]
@mariusbarth There is a straight forward way of accomplishing this that I have implemented on the development branch. There are several file formats that are supported by `kntir`  (for a list search for "dev" [here](http://yihui.name/knitr/options/)). I have set them to produce PNG, PDF, SVG, and TIFF by default. Pixel-based graphics are saved at 300 dpi. This yields very large TIFF files (~ 28MB), which isn't optimal. Even SVG files are ~ (8 MB).

What file formats do you reckon should be produced by default? Do you think the large file sizes will be a problem?

**Comment by mariusbarth** [comment]
I'd love to see PostScript.
