### ISSUE TITLE
apa_table default escape argument

### ISSUE THREAD

**Issue by baguadoramirez** [crsh/papaja#180]
Lately, I found that apa_table is working with non-default value for escape argument since `apa_table(cars, caption = "$\\alpha")` do not render the character alpha correctly by default as it used to.

**Comment by crsh** [comment]
Hi, I'm not quite sure what you mean by non-default value. The documentation indicates, that the default setting acts as `escape = TRUE` and that is what the function does, no? I do agree that it is a little confusing that the function definition includes `escape = NULL` and, to be honest, I'm not sure why it is that way. I think I could change it to `escape = TRUE`. Would this address your concern?

**Comment by baguadoramirez** [comment]
I think that would be more convenient.

**Comment by tormodb** [comment]
I am also struggling to escape characters properly in apa_table. I am trying to print a superscripted "1" in a note, but neither \\^1^ nor \\textsuperscript{1} seems to be working.

**Comment by crsh** [comment]
The LaTeX markup together with setting `escape = FALSE` in the call to `apa_table()` should yield the desired result. Should this not be the case, could you supply a minimal reproducible example?
