### ISSUE TITLE
Using a LaTeX citation package does not seem work

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#188]
As @doomlab [points out](http://www.aggieerin.com/post/citations-in-r-markdown-papaja/), the `citation_package` option of `apa6_pdf` does not seem to work properly. I can reproduce the problem while I can get it to work with the same options with `pdf_document2()`.

~~~yaml
output:
  bookdown::pdf_document2:
    citation_package: natbib # biblatex

bibliography: ["r-references.bib"]
biblio-style: apalike
# biblatexoptions: [backend=biber]
~~~~

It may have to do with the fact that `pandoc-citeproc` is somehow applied although `citation_package` is specified.

**Comment by doomlab** [comment]
@crsh let me know if I can help test ... I am not good at latex but can try to apply any changes to my document and see if it works.

**Comment by crsh** [comment]
Hi @doomlab, I think this is finally fixed on the development branch (`devtools::install_github("crsh/papaja@devel")`). If you find the time to try it, let me know if this fixed your problem.

**Comment by doomlab** [comment]
OhhhHHhhHhHh fancy @crsh. Let me try it. I can't say that I really understand natbib but I will test it out now.

**Comment by doomlab** [comment]
@crsh 

Ok this time I got:
```
output file: QWERTY_bibtest.knit.md

! Package babel Error: You haven't specified a language option.

Error: Failed to compile QWERTY_bibtest.tex. See QWERTY_bibtest.log for more info.
Execution halted
```
I put this in the head area:
```
lang              : "english"
class             : "man, mask"
output:
  papaja::apa6_pdf:
    citation_package: biblatex
```
You can view the whole thing in this repo folder under QWERTY_bibtest: https://github.com/doomlab/QWERTY/tree/master/6%20paper/markdown

**Comment by doomlab** [comment]
@crsh - I will also add that I got that error message just now when working on a different markdown that uses just the normal pandoc cite options. Switching back to the regular release of `papaja` fixed it.

**Comment by crsh** [comment]
Hi Erin, thanks for testing. This is a separate  issue. The `lang` variable is passed to `rmarkdown::pdf_document` and then `pandoc`. Here the use of the variable has changed and requires BCP 47 codes (see the [manual](https://pandoc.org/MANUAL.html#language-variables)). Given that this variable probably is unnecessary in this case, could you try again and simply delete that line from the YAML header?

**Comment by doomlab** [comment]
Sure! Sorry for the delay, I was with in-laws all weekend.

I had included the lang line because that was in the basic papaja template. Looks like the newer versions don't have this, so I'll keep on eye on that issue on my end. Several things have changed in the template - I like the updates! 👍 

First time I ran it I got an error, but I realized it was because the name of the .bib file had an `_` in it, which was being escaped, and therefore, it couldn't find the file. So, I changed `q_bib.bib` to `qbib.bib` and that fixed it. 

Second, then it knitted but didn't really do what was expected citation wise - it gave me chicago style and didn't fix the citations in the abstract.

So, I tried changing my clearly older template to the newer one in the header at least from:
```
figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

#lang              : "english"
class             : "man, mask"
output:
  papaja::apa6_pdf:
    citation_package: biblatex
```

```
floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes
mask              : yes
draft             : no

documentclass     : "apa6"
classoption       : "man"
output:
  papaja::apa6_pdf:
    citation_package: biblatex
```
So, they appear to be knitting, but in not in APA style, and not in the abstract. I pushed the updated .Rmd to the same folder I had linked above.

**Comment by crsh** [comment]
> First time I ran it I got an error, but I realized it was because the name of the .bib file had an _ in it, which was being escaped, and therefore, it couldn't find the file. So, I changed q_bib.bib to qbib.bib and that fixed it.

Yes, that's a good point. These sorts of things will start coming up when you start to move further into LaTeX territory...

> Second, then it knitted but didn't really do what was expected citation wise - it gave me chicago style and didn't fix the citations in the abstract.

Interesting. The default citation-style in biblatex is numeric---that's what I'm getting. If you want something that looks like APA style you'll need to specify this. There are different ways of doing this; I would recommend the following approach:

~~~yaml
biblio-style      : "apa"
lang              : "en-EN" # Optional, added for clarity
header-includes:
  - \DeclareLanguageMapping{english}{english-apa}

output:
  papaja::apa6_pdf:
    citation_package: biblatex
~~~

You don't need to specify `lang` but this is how it is used as of a recent `pandoc` version. `en-EN` is converted to `english` and inserted into the preamble of the document. Similarly, if you want, say, British english you would have to adapt the above as follows:

~~~yaml
lang              : "en-GB"
header-includes:
  - \DeclareLanguageMapping{british}{british-apa}
~~~
As I seem to remember this whole issue was motivated by the need to disable author-disambiguation. To achieve this you can additionally add

~~~yaml
biblatexoptions   : "uniquename=false"
~~~

Now, for the abstract, this is unfortunate behavior of `pandoc` but thanks to the text-references feature in `bookdown` it can be addressed. In the YAML front matter specify

~~~yaml
abstract: (ref:abstract)
~~~

`(ref:abstract)` is a placeholder for text that you can now define in the body of the R Markdown document (e.g., right after the YAML front matter):

~~~
(ref:abstract)
Typing is a ubiquitous daily action for many individuals; yet, research on how these actions have changed our perception of language is limited. One such influence, deemed the QWERTY effect, is an increase in valence ratings for words typed more with the right hand on a traditional keyboard [@Jasmin2012]. Although this finding is intuitively appealing given both right handed dominance and the smaller number of letters typed with the right hand, extension and replication of the right side advantage is warranted. The present paper reexamined the QWERTY effect within the embodied cognition framework [@Barsalou1999] and found that the right side advantage is replicable to new valence stimuli, along with findings supporting embodied cognition. Further, when examining expertise, right side advantage interacted with typing speed and typeability (i.e., alternating hand key presses or finger switches) portraying that both skill and our procedural actions play a role in judgment of valence on words.
~~~

This text will now be processed as expected by LaTeX and then inserted in the abstract field, if you will.

**Comment by doomlab** [comment]
@crsh 
I thought the numbering style was chicago, but either way, that's what I'm getting too. I figured there were other things I wasn't adding that would help. And now it works! Yes! Thank you!

I will write another blog about all the ways you can do the no initials thing / get deeper into customizing your templates once you push this to the full papaja (rather than just dev). .

**Comment by crsh** [comment]
FYI: I've added the section to the manual: https://crsh.github.io/papaja_man/tips-and-tricks.html#author-name-disambiguation

CC: @jstbcs
