### ISSUE TITLE
a4paper possible?

### ISSUE THREAD

**Issue by wuschLOR** [crsh/papaja#193]
I'm trying to use a4paper option described in the apa6 documentation like this:

~~~yaml
class : man

output: 
  papaja::apa6_pdf

classoption: 
  "a4paper"
~~~

but my result is this (default usletter):

`\documentclass[man]{apa6}`

what i would expect is 

`\documentclass[man,a4paper]{apa6}`

I think my syntax is probably wrong (first time papaja&rmarkdown) - help here would be deeply appreciated.

**Comment by crsh** [comment]
Hi Michael, you are right, currently the YAML parameter `classoption` is not handled as it is in the default LaTeX template in `rmarkdown`. I'm currently [trying](https://github.com/crsh/papaja/issues/106) to improve the consistency between these templates. Once this is done the example code you posted should produce the desired result. For now you cann do the following:

~~~yaml
class : man,a4paper
~~~

**Comment by wuschLOR** [comment]
Many thanks!
That way i can pass my options down to apa6.

Template compatibility would be nice but is not a high priority issue as long as there is a way to get the results you want - and that is the case.

Was just a little irritating that it was ignored without warning.
Implementing a warning, telling you that the option is ignored and should be used another way, should be enough - I think.

**Comment by crsh** [comment]
That's a sensible suggestion. I'll try to address this the next chance I get.

**Comment by jrennstich** [comment]
Unfortunately, this is not working in the latest development release anymore. When I use 
`classoption       : ["man", "a4paper"]`
I get the error

```
pandoc: classoption:a4paper: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1
Execution halted
```
