### ISSUE TITLE
using underscore function in equation specification

### ISSUE THREAD

**Issue by jtkulas** [crsh/papaja#198]
$$r_{\substack{p(iy)}} =\frac{(E_{m}-\sum_{j}^{m}D_{(iy)}^2)}   
{(E_{m}+\sum_{j}^{m}D_{(iy)}^2)}$$ 

creates a nice equation, but there are elements (the "m"'s) that should be underlined. This equation works without papaja, but fails with papaja:

$$r_{\substack{p(iy)}} =\frac{(E_\underline{m}-\sum_{j}^{m}D_{iy}^2)}   {(E_\underline{m}+\sum_{j}^\underline{m}D_{iy}^2)}$$          

This is my first time posting, please forgive any ettiquite violations

**Comment by crsh** [comment]
Hi @jtkulas,

no etiquette violations, your problem description was friendly and helpful. :+1:

I get the same LaTeX error you describe when I try your equations in a standard `rmarkdown` PDF-document (so it's not a `papaja`-specific problem). It appears the problem can be solved by wrapping the underlined m in sub- and superscripts in braces:

~~~
$$
r_{\substack{p(iy)}} =\frac{(E_{\underline{m}}-\sum_{j}^{m}D_{(iy)}^2)}
{(E_{\underline{m}}+\sum_{j}^{\underline{m}}D_{(iy)}^2)}
$$
~~~

Let me know if that resolves the problem.

**Comment by jtkulas** [comment]
That worked great - thanks much!!!
