### ISSUE TITLE
Empty Appendix when using "#" in Rmd

### ISSUE THREAD

**Issue by dhagmann** [crsh/papaja#204]
When the top-level header for the appendix Rmd file is created using Markdown syntax (i.e. `# Title`), the output places an empty appendix immediately prior.

Example:

```{r, include = F, eval = T}
papaja::render_appendix("appendix.Rmd")
```

And where appendix.Rmd is:

```
# Data \& R Code
Text here
```

Creates:

```
Appendix A
(blank page)

Appendix B
Data & R Code
```

The problem is fixed when you change the Rmd file to:

```
\section{Data & R Code}
Text here
```

**Comment by crsh** [comment]
Hmm, that's odd. here it just renders the Appendix as expected. Could your render these exact files one more time and upload the .tex-files for the appendix and the main document? Maybe that is informative.

**Comment by crsh** [comment]
Also, could you supply the output of `devtools::session_info()`?

**Comment by crsh** [comment]
I'm scratching my head. If I take the files you provided and render them the result looks as expected:

<img width="663" alt="bildschirmfoto 2018-05-14 um 23 44 49" src="https://user-images.githubusercontent.com/2195485/40025121-ebdbfa76-57d0-11e8-8732-a57d7ca452ea.png">

Unfortunately, the files you uploaded to not include the TeX file for the rendered appendix. Would you mind providing that as well so I can take a closer look?

**Comment by dhagmann** [comment]
Very odd indeed! I've attached the .tex file, where the relevant section at the end is:

```
\begin{appendix}
\section{}
\hypertarget{data-r-code}{%
\section{Data \& R Code}\label{data-r-code}}

The raw data from all our experiments and statistical code for all
analyses and figures reported in the paper and the supplementary
analyses will be available via Github and as an R library on CRAN
following acceptance of the paper.
\end{appendix}
```

[tex file.zip](https://github.com/crsh/papaja/files/2027146/tex.file.zip)

**Comment by crsh** [comment]
Ah, this is helpful and gives me an idea what may be causing the problem. Am I right to assume that you are using `pandoc` 2.0?

I just pushed a possible fix to the development branch (`devtools::install_github("crsh/papaja@devel")`). Let me know if that fixes the problem.

**Comment by dhagmann** [comment]
That fixed it! Works as expected now.

(Although I'm running `pandoc 1.19.2.1`, so maybe this was not specific to 2.0)

**Comment by crsh** [comment]
Great, thanks for the feedback.
