### ISSUE TITLE
ToC Level 5: name missing/blank

### ISSUE THREAD

**Issue by scottttttt** [crsh/papaja#207]
I have 5 headings that I would like to see in the table of contents (\tableofcontents). I have my depth set at {5}. When I display/print, I see the 5 levels in the toc, but on the 5th level it displays a blank name with the page number, for example:

first.............1
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;second............2
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;third.............3
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fourth............4
                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ................5

Notice how the level 5 heading displays but the title is blank.

I've tried the markdown headings (#, ##, ###, ####, #####) and Latex formatting up to \subparagraph. I get the same results either way. I also have tried  - \setcounter{tocdepth}{5} and  - \setcounter{secnumdepth}{5}.

**Comment by crsh** [comment]
Hi Scott, that's odd. From playing around with this, it seems to me that this a problem with the `apa6` LaTeX class, over which I have limited control. I have found that you can add the correct line to the table of contents by adding `\addcontentsline{toc}{subparagraph}{fifth}` after the section heading, but this does not remove the incorrect line. I think this would be a good question for [TeX-Stackexchange](https://tex.stackexchange.com/).
