### ISSUE TITLE
ERROR: dependency 'yaml' is not available for package 'papaja'

### ISSUE THREAD

**Issue by gerberleah** [crsh/papaja#211]
Could not load package

**Comment by crsh** [comment]
Hmm, that's very odd. Whenever I encountered issues of this sort, it was because a package had not been installed. Could you try and confirm that you can load the `yaml` right after you encounter this error and provide the output of `devtools::session_info()`?

**Comment by crsh** [comment]
In case anyone else finds this: I have recently found that if this error occurs (for, as of yet, unknown reasons) it may suffice to restart the R session or reinstalling `yaml` before installing `papaja`.

**Comment by oij11** [comment]
Hi, I am trying to install papaja but getting an error message. as below
 > devtools::install_github("crsh/papaja", dependencies = TRUE)
Downloading GitHub repo crsh/papaja@master
Installing 14 packages: afex, beeswarm, bookdown, broom, downloader, gsl, latex2exp, lsmeans, MBESS, OpenMx, praise, rpf, semTools, testthat
Error: (converted from warning) unable to access index for repository https://cran.stat.ucla.edu/src/contrib:
  cannot open URL 'https://cran.stat.ucla.edu/src/contrib/PACKAGES'

Would you help me resolve this?

**Comment by crsh** [comment]
Have you tried to install any other packages from CRAN? Are you sure you have access to the CRAN server? Is it maybe blocked by a firewall?

**Comment by oij11** [comment]
Yeah. I do have access to the cran server and I've also switched to a different cran and it still does not work. The issue seems to be with broom package; I cannot get it installed and it gives me the error. I've asked the broom developer but he is saying I should ask to rstudio community, which I did but have not got any reply. Would you have any idea how to resolve this issue by looking at the reprex below? Is there any other way to issue papaja despite the problem with broom? 


``` r
devtools::install_github("tidymodels/broom",force = TRUE)
#> Downloading GitHub repo tidymodels/broom@master
#> generics (0.0.2 -> d59e6b456...) [GitHub]
#> Downloading GitHub repo r-lib/generics@master
#>   
   checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/RtmpKlnj0L/remotes13a1e480964b0/r-lib-generics-d59e6b4/DESCRIPTION’ ...
  
✔  checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/RtmpKlnj0L/remotes13a1e480964b0/r-lib-generics-d59e6b4/DESCRIPTION’
#> 
  
─  preparing ‘generics’:
#> 
  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information
#> 
  
─  installing the package to process help pages
#> 
  
─  checking for LF line-endings in source and make files and shell scripts (1.2s)
#> 
  
─  checking for empty or unneeded directories
#> 
  
─  building ‘generics_0.0.2.tar.gz’
#> 
  
   
#> 
  
   checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/RtmpKlnj0L/remotes13a1e141bec83/tidymodels-broom-c5d85b4/DESCRIPTION’ ...
  
✔  checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/RtmpKlnj0L/remotes13a1e141bec83/tidymodels-broom-c5d85b4/DESCRIPTION’
#> 
  
─  preparing ‘broom’: (477ms)
#> 
  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information
#> 
  
─  checking for LF line-endings in source and make files and shell scripts (575ms)
#> 
  
─  checking for empty or unneeded directories
#> 
  
─  looking to see if a ‘data/datalist’ file should be added
#> 
  
─  building ‘broom_0.5.1.9000.tar.gz’
#> 
  
   
#> 
```

<sup>Created on 2018-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by oij11** [comment]
NM ignore the issue above.The broom package installation just worked  and no problem with papaya. Thanks!
