### ISSUE TITLE
supress minus sign in reporting result of _t_-test

### ISSUE THREAD

**Issue by LorcanKenny** [crsh/papaja#219]
When reporting a _t_-test using apa_print() a minus sign is sometimes reported. This is uninformative and is a result of which order the means were entered and so is typically not reported in manuscripts. I tend to manually remove it. Is there any way to supress this, maybe by default or by adding a parameter to apa_print().

So that instead of: _t_(63) = - 3.05, _p_ = .003, _d_ = 0.76

You get: _t_(63) = 3.05, _p_ = .003, _d_ = 0.76

**Comment by crsh** [comment]
Hi @LorcanKenny, thanks for reaching out. I'm not sure I agree that the direction of the effect is *generally* uninformative and hence I, personally, would not want to remove the sign of the *t* statistic or the mean difference. I'd prefer to use indicator variables that yield directly interpretable result. I'm, therefore, reluctant to add a parameter to `apa_print()` to accomplish this. It's, however, easy to do this by post-processing the output of `apa_print()`:

~~~r
t_test <- t.test(extra ~ group, data = sleep)
t_test_res <- apa_print(t_test)

# Just the test statistic
gsub("-", "", t_test_res$statistic)

# For all strings
lapply(t_test_res, function(x) gsub(") = -", ") = ", x))
~~~

**Comment by LorcanKenny** [comment]
Great, thank you so much for providing this code, that is exactly what I was looking for!
