### ISSUE TITLE
title for appendices

### ISSUE THREAD

**Issue by HenrikEckermann** [crsh/papaja#220]
Hi Frederik,

I see that by now, papaja puts tables and figures below the references, which is very nice.

But what I miss is: There no header like Appendix A as described [here](https://library.bryanhealthcollege.edu/c.php?g=3265&p=10832). 

Do you know if that is because I did not specify something correctly or this just not possible?

I use btw tables I created myself with kableExtra since I use models not yet supported by papaja.

Best,

Henrik

Edit: I guess I overlooked that at least figures and tables do not belong to the appendix. I have some figures for a paper that are not necessary but still helpful. I wonder if I still should put them in as figures or appendix. I will figure it out. If I need the possibility to put figures in the appendix then I would leave this open. Otherwise I would delete the issue.

**Comment by crsh** [comment]
Hi Henrik, good point, the documentation is currently lacking here. Take a look at #168 for a brief description of how to add a proper appendix. I hope to make this more convenient soon but it's a little tricky. Does that help?

**Comment by HenrikEckermann** [comment]
Thanks Frederik, I will check it out!
