### ISSUE TITLE
knit crashes in LaTeX but not in Word

### ISSUE THREAD

**Issue by brynhughes** [crsh/papaja#228]
Hi,

I have a document that will knit when the output is set to apa6_word but when I set it to apa6_pdf it produces the following error:

```
! Missing \endcsname inserted.
<to be read again> 
                   \def 
l.188 \begin{figure}
```

I suspect it has something to do with the figure captions, but I'm not completely sure. Googling the error brings me to several forums on LaTeX that suggest there is an extra character being added somewhere, but I'm not sure where. 

Thanks for your help!

**Comment by crsh** [comment]
Hi Bryn, thanks for reporting this. It's hard to know exactly what's going on without a reproducible example, but I suspect you are using a daily build of RStudio. If so, could this be the same problem as #227?

**Comment by crsh** [comment]
Hi Bryn, I pushed a fix for the possibly related problem last night (https://github.com/crsh/papaja/issues/227#issuecomment-403965514). Could you try and see whether this resolves your problem as well (`devtools::install_github("crsh/papaja@devel")`)?
