### ISSUE TITLE
Plot labels (ggplot/cowplot)

### ISSUE THREAD

**Issue by MichaelaCDeBolt** [crsh/papaja#236]
Hello--when using ggplot to create plot object, then using plot_grid to make a plot grid, it appears that papaja does not allow one to add labels = "AUTO", or any label to the plot grid object. Is this a known problem?  

# this is what I'm trying to add the labels argument to--it won't knit this way. 
plot <- plot_grid(a, b, ncol=2, align="h", label_x = "Stimulus Pairs")

Here is the error:
Error in label_x[i] * x_delta : non-numeric argument to binary operator

**Comment by MichaelaCDeBolt** [comment]
Sorry, to be clear the plot object above does not contain the label argument. But here it is for completeness: 

plot <- plot_grid(a, b, ncol=2, align="h", labels = "AUTO", label_x = "Stimulus Pairs")

**Comment by mariusbarth** [comment]
So could you solve this problem?

**Comment by MichaelaCDeBolt** [comment]
I ended up removing that argument all together. But, I think I closed the issue because it did work. Sorry, I can't remember, and now my code has changed and I can't recall. :-/
