### ISSUE TITLE
! LaTeX Error: File `APA-testing.ent' not found.

### ISSUE THREAD

**Issue by weixulu** [crsh/papaja#238]
R Studio 1.1456
R v 3.4.3
Windows 10.0.17134.165
MikTex 2.9.6753
Knitr 1.20
Pandoc 2.2.2.1

I only used a template file and changed the bib file name (and nothing else), but when I "knit", I get the following output:

```
processing file: APA-testing.Rmd
  |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%
label: load_packages (with options) 
List of 1
 $ include: logi FALSE

  |............................                                     |  43%
  ordinary text without R code

  |.....................................                            |  57%
label: analysis_preferences
  |..............................................                   |  71%
   inline R code fragments

  |........................................................         |  86%
label: create_r-references
  |.................................................................| 100%
  ordinary text without R code


output file: APA-testing.knit.md

"C:/PROGRA~2/Pandoc/pandoc" +RTS -K512m -RTS APA-testing.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output APA-testing.tex --template "C:\Users\weixu\Documents\R\win-library\3.4\papaja\rmarkdown\templates\apa6\resources\apa6.tex" --highlight-style tango --pdf-engine pdflatex --csl "C:\Users\weixu\Documents\R\win-library\3.4\papaja\rmd\apa6.csl" --filter pandoc-citeproc --filter _papaja_ampersand_filter.bat 
! LaTeX Error: File `APA-testing.ent' not found.

! Emergency stop.
<read *> 

Error: Failed to compile APA-testing.tex. See APA-testing.log for more info.
In addition: Warning message:
running command '"pdflatex" -halt-on-error -interaction=batchmode "APA-testing.tex"' had status 1 
Execution halted
```

Thank you!

**Comment by crsh** [comment]
Hmm, according to [this question on SE](https://tex.stackexchange.com/questions/303254/latex-error-file-foo-ent-not-found) it seems this is related to the `endnotes` LaTeX package. Could you check that the YAML header contains

~~~yaml
footnotelist: no
~~~

If it does, but the error persists, could you upload the `.Rmd` so I can try to replicate the problem and the `.log` file?

**Comment by weixulu** [comment]
Here is my rmd file and log file. 
To provide a clean result, I simply used the template file, without changing anything to it. 
[APA-testing2.log](https://github.com/crsh/papaja/files/2258388/APA-testing2.log)

**Comment by weixulu** [comment]
I forgot to add: footnotelist was already set to "no"

**Comment by crsh** [comment]
Hmm, I see that the LaTeX command `\theendnotes` causes the problem (although I still can't get the same error). This shouldn't be in the document, however. What version of `papaja` are you using? Have you tried with the most recent development version (`devtools::install_github("crsh/papaja@devel")`)?

**Comment by Karut** [comment]
I am not entirely sure, but I think I was having this exact problem with your version of pandoc. Updating to Pandoc-2.2.3-2 solved this for me but created a new [bug](https://github.com/crsh/papaja/issues/239) with citations unfortunately.

**Comment by weixulu** [comment]
Ok. With the most recent development version, this problem is gone. 

However, does it mean that I cannot use endnotes in my manuscript?

**Comment by crsh** [comment]
Great. The endnotes should work, e.g., when you use the [`footnotelist` option in the YAML front matter](https://crsh.github.io/papaja_man/r-markdown-components.html#rendering-options).

**Comment by Karut** [comment]
@weixulu 

But you did not update your version of pandoc as well, right?

**Comment by weixulu** [comment]
@Karut 
I would not risk it, after seeing your post...

**Comment by weixulu** [comment]
@crsh 
Thanks for the great work with papaja! Frankly, the 3rd level heading in APA is what really pushed me to Markdown from MS Word. And it's so nice to have it back in my document. (And APA should seriously consider updating their style guide. )

**Comment by crsh** [comment]
You're welcome! :) I'll close the issue, since it seems it has been resolved. Feel free to reopen if you have any other questions.
