### ISSUE TITLE
latex in table captions with apa_table

### ISSUE THREAD

**Issue by drbenvincent** [crsh/papaja#246]
I am trying to use LaTex in a table caption, using `apa_table`. You can specify captions for _figures_ using the text references features (as described here https://crsh.github.io/papaja_man/reporting.html#figure-captions). But I cannot manage to get a caption which contains some LaTeX working as a Table caption with `apa_table`

Is there a way to update `apa_table` to accept the text reference in the same way that you can with Figure captions (see link above to the manual)? Ideally, there could also be a short example in the docs of how to do this.

I have also tried to do this with `fig.cap` in the chunk options, but no luck... and it looks like text references are there to solve that problem.

**Comment by crsh** [comment]
Hi, have you tried defining a text reference and using the reference handle, e.g., `caption = "(ref:label)"`? You should be able to use text references anywhere in your R code.

You are right, we need an example in the documentation. The section on tables is somewhat in shambles right now.

**Comment by drbenvincent** [comment]
Ok, so this works :) 

First define a caption in Markdown (not in a code block).

    (ref:mytablecaption) My table caption with latex, $e=mc^2$.

Then use that as suggested in an R code block:

    {r MyTable, echo = FALSE, results = "asis"}
    apa_table(my_table_data, caption = "(ref:mytablecaption)")

**Comment by crsh** [comment]
Thanks for posting the more detailed solution. I'll reopen this is issue just to remind me to cover this in more detail in the manual.
