### ISSUE TITLE
Unable to knit

### ISSUE THREAD

**Issue by 6541687165354168486** [crsh/papaja#248]
Hello, I am unable to knit. I am providing the log below. I'm not sure what to do. I have tried installing missing packages as they pop up. I've tried completely uninstall papaja, R, and r studio. I have mactex installed, completely updated. Not sure what else to do. Please help:

Package hyperref Info: Driver (autodetected): hpdftex.
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/hyperref/hpdftex.def
File: hpdftex.def 2018/02/06 v6.86b Hyperref driver for pdfTeX
\Fld@listcount=\count125
\c@bookmark@seq@number=\count126
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty
Package: rerunfilecheck 2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
Package uniquecounter Info: New unique counter `rerunfilecheck' on input line 2
82.
)
\Hy@SectionHShift=\skip69
)
Package hyperref Info: Option `unicode' set `true' on input line 30.
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/hyperref/puenc.def
File: puenc.def 2018/02/06 v6.86b Hyperref: PDF Unicode definition (HO)
Now handling font encoding PU ...
... no UTF-8 mapping file for font encoding PU
)
Package hyperref Info: Option `breaklinks' set `true' on input line 30.
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/oberdiek/grffile.sty
Package: grffile 2017/06/30 v1.18 Extended file name support for graphics (HO)
Package grffile Info: Option `multidot' is set to `true'.
Package grffile Info: Option `extendedchars' is set to `false'.
Package grffile Info: Option `space' is set to `true'.
Package grffile Info: \Gin@ii of package `graphicx' fixed on input line 494.
) (/usr/local/texlive/2018basic/texmf-dist/tex/latex/parskip/parskip.sty
Package: parskip 2001/04/09 non-zero parskip adjustments
) (/usr/local/texlive/2018basic/texmf-dist/tex/latex/csquotes/csquotes.sty
Package: csquotes 2018/04/13 v5.2d context-sensitive quotations (JAW)
\csq@reset=\count127
\csq@gtype=\count128
\csq@glevel=\count129
\csq@qlevel=\count130
\csq@maxlvl=\count131
\csq@tshold=\count132
\csq@ltx@everypar=\toks25
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/csquotes/csquotes.def
File: csquotes.def 2018/04/13 v5.2d csquotes generic definitions (JAW)
)
Package csquotes Info: Trying to load configuration file 'csquotes.cfg'...
Package csquotes Info: ... configuration file loaded successfully.
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/csquotes/csquotes.cfg
File: csquotes.cfg 
))

! LaTeX Error: File `upgreek.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.78 \captionsetup
                  {font=singlespacing,justification=justified}^^M

**Comment by jvcasillas** [comment]
I looks like something you are using requires `upgreek.sty`. This needs to be included in the same directory as your .Rmd file. A quick google search came up with this: https://people.ok.ubc.ca/jbobowsk/LaTeX/LaTeX%20Tutorials/Introduction/upgreek.sty

**Comment by 6541687165354168486** [comment]
I found that earlier. But it doesn't really tell me whats going on. I've tried installing upgreek using tlmgr and the tex live utility. It's just not working. I've never had this problem in the past.

**Comment by 6541687165354168486** [comment]
And I'm only using the default template to knit. In other words, I'm just using the default settings for r, r studio, and papaja. I'm even using the default template that comes with papaja, I haven't changed anything in the template file. I just open the template and hit knit. I get stuck. I will try uninstalling mactex and reinstalling...

**Comment by 6541687165354168486** [comment]
I fixed it. I simply uninstalled mactex and basictex and only reinstalled mactex. Works now!
