### ISSUE TITLE
glm object is not printed by apa_print

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#250]
Hi Frederik,

I computed a logistic regression using `glm` and wanted to print it out using the generic function `apa_print`. I am using `papaja_0.1.0.9842`. Using `apa_print` yields an error message for me; using `apa_print.glm` works, but I guess this is not the envisaged workflow:

```
## use the example in ?glm
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
glm.D93 <- glm(counts ~ outcome + treatment, family = poisson())
papaja::apa_print(glm.D93)
# Fehler in UseMethod("apa_print", x) : 
#  nicht anwendbare Methode für 'apa_print' auf Objekt der Klasse "c('glm', 'lm')" angewendet

papaja::apa_print.glm(glm.D93)
# $estimate
# $estimate$Intercept
# [1] "$b = 3.04$, 95\\% CI $[2.70$, $3.37]$"
# ...
```

I also installed the developement version, but the problem persists.

As an end note: thank you so much for continuing to work on this package. I also wrote my dissertation using `papaja`. More and more I also realize how useful it is to have these default printing methods that facilitate working with all kinds of `R` functions.

Cheers, 

Martin

**Comment by crsh** [comment]
Hi Martin, I'm sorry, but I'm unable to reproduce this. Both the master and devel branch work as expected in an interactive session and R Markdown document. Could you post your session info?

**Comment by m-Py** [comment]
Hi Frederik,

sorry my reply took so long. Here is my session info:

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4    tools_3.4.4       papaja_0.1.0.9842 knitr_1.20   
```

I guess the error might be caused by me not having moved to R 3.5. If you agree, we might as well close this issue ;) 

Thanks!

Martin

**Comment by crsh** [comment]
> I guess the error might be caused by me not having moved to R 3.5. If you agree, we might as well close this issue ;)

Hmm, not sure this should make a difference, but if you update and find that this solves the issue let me know.

One other question: Does it make a difference whether you use `papaja::apa_print()` or load the package and use `apa_print()`?

**Comment by m-Py** [comment]
Oh, wow, I forgot this issue existed, sorry. The problem indeed does not occur when I first load papaja and then use `apa_print` :S
