### ISSUE TITLE
meta-analysis citations

### ISSUE THREAD

**Issue by mllewis** [crsh/papaja#251]
I'm writing up a meta-analysis and I would like to cite papers from the meta-analysis in the bibliography with an asterisks before the last name. I'm able to use the nocite function in the reference section to include references not cited in the text, but I need to also add the asterisks denoting that it's from the MA. I see that the apacite package has a function called nocitemeta, but this doesn't seem to work here. 

Is there a straightforward way to do this?

Thanks a lot!
Molly

**Comment by crsh** [comment]
Hi Molly, thanks for reaching out. Since it is a question that relates to LaTeX more than to `papaja`, would you mind moving it to StackOverflow and post it under the [`papaja`-tag](https://stackoverflow.com/questions/tagged/papaja)? I'm more than happy to answer it there.

**Comment by mllewis** [comment]
Sure!

**Comment by crsh** [comment]
For the record, the StackOverflow question including my answer can be found [here](https://stackoverflow.com/questions/53091561/citing-meta-analytic-sources-in-papaja/53164292).
