### ISSUE TITLE
Omit abstract if it is empty/NULL

### ISSUE THREAD

**Issue by jacob-long** [crsh/papaja#253]
**Is your feature request related to a problem? Please describe.**
I think so. I often want to have a roughly APA-formatted paper that has no use for an abstract (e.g., what I'm doing right now, a candidacy exam response). I just want the general trappings of APA style. But if I leave the abstract field blank, or omit it entirely, I just get an empty abstract page. 

**Describe the solution you'd like**
In my understanding, all that has to happen on the LaTeX side is not include `\abstract{}`.

**Describe alternatives you've considered**
I've poked through the source of `papaja` a bit, but I'm not familiar enough with what's going on to tell how I could implement this myself without unintended side effects.

**Comment by crsh** [comment]
Sounds reasonable. I'll take a look the next chance I get. Can you confirm that it works if you simply remove the abstract line in the TeX file? `papaja` should leave a TeX file that you can edit and compile to test this. If so this should be simple to implement.

**Comment by crsh** [comment]
I pushed a commit that should fix this. Install from the development branch (`devtools::install_github("crsh/papaja@devel")`) to try it out.

**Comment by jacob-long** [comment]
Thanks for jumping right on this! I can confirm this works. You may want to know that users will not get keywords or word count printed in this case either (they're on the abstract page), but I think that's the correct behavior.

**Comment by crsh** [comment]
Indeed, this is what the `apa6` LaTeX class does. I'm not sure I could control this if I wanted to. But I have implemented it accordingly for `apa6_docx()` for consistency. Thanks for testing!

**Comment by jupitus** [comment]
I'm very much looking forward to this feature (for Supplementary Materials). Thanks! 
When might it get included in a release?

**Comment by crsh** [comment]
I hope to release it to the `master` branch soon. In the meantime you can use the development version (`devtools::install_github("crsh/papaja@devel")`).

**Comment by tdienlin** [comment]
Thanks a bunch! Just had the exact same issue when preparing the submission of an extended abstract for a conference (and obviously, you don't want your extended abstract to include another leading abstract).
