### ISSUE TITLE
Code chunk not fully displayed in papaja document 

### ISSUE THREAD

**Issue by sirifolstad** [crsh/papaja#254]
**Describe the bug**
When I try to display my code chunk within my document (by writing {r, echo=TRUE}) parts of the code falls outside my document, rather than within the box. This has not been a problem when using the standard R Markdown function without Papaja.

**To Reproduce**
~~~
```{r, fig.align='center', echo=TRUE}
ggplot(dataset1, aes(x = Condition:Group, y = Onset, 
                     fill = Condition:Group)) + geom_violin() + geom_jitter(width = .1, alpha = .5) + stat_summary(fun.data = "mean_cl_boot", colour = "black") + 
  guides(fill = FALSE) + labs( x = "Condition", y = "Speech Onset", title = "Violin Plot of Speech Onset measured by Condition 
                               \nwith Means and 95% Confidence Intervals")
```
~~~

**Expected behavior**
I expected the code chunk to be displayed neatly within the code-box

**Screenshots**

<img width="590" alt="image" src="https://user-images.githubusercontent.com/45390075/49079264-03c2f980-f238-11e8-882c-fda2fa23bffe.png">

**Additional context**
I have used Papaja in R Markdown with Latex to create a pdf document.

**Comment by crsh** [comment]
Thanks for the more detailed description. I think what you are experiencing is not `papaja`-related. To illustrate this, try the following code chunk in a `pdf_document`.

~~~r
```{r, test, fig.align = "center", echo = TRUE}
library("plyr")
library("ggplot2")

df <- data.frame(gp = factor(rep(letters[1:3], each = 10)), y = rnorm(30))
ds <- ddply(df, "gp", summarise, mean = mean(y), sd = sd(y))

ggplot() +
  geom_point(data = df, aes(gp, y)) + geom_point(data = ds, aes(gp, mean), colour = 'red', size = 3) +
  geom_errorbar(data = ds, aes(gp, mean, ymin = mean - sd, ymax = mean + sd), colour = 'red', width = 0.4)
```
~~~

To avoid this behavior, set the chunk option `tidy = TRUE`. This will reformat the displayed code to stay within the shaded box. Note that this requires that the `formatR` package is installed.

~~~r
```{r, test, fig.align = "center", echo = TRUE, tidy = TRUE}
library("plyr")
library("ggplot2")

df <- data.frame(gp = factor(rep(letters[1:3], each = 10)), y = rnorm(30))
ds <- ddply(df, "gp", summarise, mean = mean(y), sd = sd(y))

ggplot() +
  geom_point(data = df, aes(gp, y)) + geom_point(data = ds, aes(gp, mean), colour = 'red', size = 3) +
  geom_errorbar(data = ds, aes(gp, mean, ymin = mean - sd, ymax = mean + sd), colour = 'red', width = 0.4)
```
~~~

**Comment by sirifolstad** [comment]
Thank you for your detailed explanation. I tried all of what you said, but unfortunately, it is still not working, so I am wondering whether it needs to be done differently as it is in a Latex environment?

**Comment by crsh** [comment]
Hmm, but we agree that this is not related to `papaja`? If so, I would suggest to move this question to StackOverflow.

P.S.: Are you sure `formatR` is installed? `tidy = TRUE` has no effect if the package is missing.

**Comment by sirifolstad** [comment]
I found a way of doing it by changing my settings in RStudio. However, one issue that I have not managed to figure out (which I assume is a papaja related issue) is that when I display my code chunks in-text, their designated plots do not fall straight under the code chunk in the knitted document, but rather at some other place in the text. Do you know how to fix that?

**Comment by sirifolstad** [comment]
Thank you for your help btw!

**Comment by crsh** [comment]
This is a typical LaTeX default behavior. The placement of figures in LaTeX in both `pdf_document` and `apa6_pdf()`is controlled by the chunk option `fig.pos`. See [this StackOverflow answer](https://stackoverflow.com/a/43245550/914024) for details on how to use it.

**Comment by crsh** [comment]
I'm closing this issue as it appears to me that the problems have been resolved. Feel free to reach out if this is not the case.
