### ISSUE TITLE
Combining one and two columns view in "journal" mode

### ISSUE THREAD

**Issue by jabv2015** [crsh/papaja#258]
I have seen papers written with papaja with two columns (journal mode) where everything  (including tables and graphs) follows the two column layout. However, I have seen also some papers that combine two and one column layout, especially when it is necessary to include some "big or long" tables or big images. How Do I do that? (I have downloaded some papers from the "articles written with papaja", but when I see the r markdown document always it is in "man" mode, so there is any clue about how the final paper is rendered to pdf.

**Comment by crsh** [comment]
Hi, I'm not sure I understand what you mean. Are you asking how to make figures and tables span two columns but keep text in two columns on the remainder of the page? If so, some solutions are discussed [here](https://github.com/crsh/papaja/issues/130#issuecomment-407396695) and [here](https://github.com/crsh/papaja/issues/52#issuecomment-204322473).
