### ISSUE TITLE
arrange_anova() throws error for summary.aov-object

### ISSUE THREAD

**Issue by mariusbarth** [crsh/papaja#26]
When I pass an aov object from repeated-measures ANOVA to apa_print, it fails now:

Fehler in UseMethod("arrange_anova", x) : 
  nicht anwendbare Methode für 'arrange_anova' auf Objekt der Klasse "c('summary.aov', 'listof')" angewendet 

Why did you do that?

**Comment by crsh** [comment]
I think, I need a little more context to answer the question. I have implemented unit tests for the `apa_print()`-anova family. The following repeated measures objects work as expected:

    load("data/tw_rm_data.rdata")
    tw_rm_aov <- aov(Recall~ (Task * Valence) + Error(Subject/(Task * Valence)), tw_rm_data)
    apa_print(tw_rm_aov)
    apa_print(summary(tw_rm_aov))

The data file is contained in the `tests` directory.

How did you obtain the `aov` object that you pass into the method and how does it differ from the one I use for unit testing?

**Comment by mariusbarth** [comment]
Yes, newest version.

To be more specific (and correct), I used Henrik's package to obtain an aov object from a MIXED design:

`out <- ez.glm(data=pd.data, dv="correct", id="id", between=c("material","generation","order"), within="instruction", fun.aggregate=mean, na.rm=TRUE,return="aov")

apa_print(out)`

You can obtain the data from the papaja_examples repo
