### ISSUE TITLE
How do you  include R code appendix in papaja?

### ISSUE THREAD

**Issue by jooyoungseo** [crsh/papaja#261]
I was attempting to include all reproducible R source code in my manuscript at the end as an appendix by following [Yihui Xie's Tip](https://yihui.name/en/2018/09/code-appendix/)

I have created a separate `appendix.Rmd` file and declared it in `appendix` field of YAML header.

However, `papaja::apa6_pdf` fails to render the appendix.Rmd file that contains:

~~~
```{r code = readLines(knitr::purl(knitr::current_input())), echo = T, eval = F}
```
~~~

Or, I even tried the following code in the appendix.Rmd file, but it failed:

~~~
```{r ref.label=knitr::all_labels(), echo = T, eval = F}
```
~~~

Do you have any workaround to include all R source code in the manuscript as an appendix?
Many thanks.

**Comment by crsh** [comment]
Yes, see https://github.com/crsh/papaja/issues/249#issuecomment-442001364 for two possible workarounds. 😺
