### ISSUE TITLE
Unable to install papaja on window, rstudio left error

### ISSUE THREAD

**Issue by koliii** [crsh/papaja#266]
Trying to install papaja on Rstudio, on R version 3.5.2, using Windows 10, came this error
![screenshot 4](https://user-images.githubusercontent.com/28312545/52895861-2dac0c80-31e6-11e9-90a8-4eb676c519f7.png)

**Comment by crsh** [comment]
The error says you were unable to connect to the GitHub API. I don't think there is anything I can do about this. Have you checked your internet connection and verified that you can access GitHub in a browser? Are all necessary ports on your network open?

**Comment by koliii** [comment]
Internet connection is working okay. I'm using Firefox quantum. Sadly, I do not know anything about the network ports.

**Comment by koliii** [comment]
You are right about the internet connection. It was not installed with the institution's internet. But installed using private internet. After installation, I hope it is fine.
![screenshot 5](https://user-images.githubusercontent.com/28312545/52928390-7807c780-3365-11e9-8d2d-5a1d388ba0fa.png)

**Comment by koliii** [comment]
You are right about the internet connection. I tried using private internet connection. Ended up with this
![screenshot 5](https://user-images.githubusercontent.com/28312545/52928471-db91f500-3365-11e9-873f-28aa50a2b4f7.png)

**Comment by koliii** [comment]
Thanks! I'm able to use it now.
