### ISSUE TITLE
apa_table Head Alignment 

### ISSUE THREAD

**Issue by Sheng-Bo** [crsh/papaja#268]
I found that \multicolumn{1}{c} was always generated for aligning the second and subsequent heads. Is it possible to set the alignment for these heads? Now I am using the trick (https://github.com/crsh/papaja/issues/52#issuecomment-204322473) you mentioned before to replace the code into \multicolumn{1}{l}  

Thank you so much for creating the wonderful package.

**Comment by crsh** [comment]
Hi, unfortunately there currently is no other way to adjust the alignment of the column heads.

**Comment by raphael-lorenzdelaigue** [comment]
I was trying to do the same thing just now.
I would gently vote for integrating an extra argument such as "header.align = 'l'". The workaround proposed here is working, but seems a bit overcomplicated for an operation that is quite straightforward, from the user's perspective.

[kableExtra has an option for doing this](https://github.com/haozhu233/kableExtra/issues/66#issuecomment-335547964), maybe this could be somehow integrated in the papaja package.
