### ISSUE TITLE
Remove title on introduction page

### ISSUE THREAD

**Issue by tcgriffith** [crsh/papaja#269]
**Is your feature request related to a problem? Please describe.**
The title of the paper appears again before "Introduction". 

**Describe the solution you'd like**
I would like to remove the title.

**Describe alternatives you've considered**

None

**Additional context**
This seems to be a small problem so I tried to [hack the apa6_formats.R](https://github.com/crsh/papaja/blob/6ef5e13e029624093bdae636fc2ce094c5d94c5d/R/apa6_formats.R#L132)
by deleting the `maketitle` part. Well, it removed the cover page. As I'm not familiar with latex, a little help would be greatly appreciated!

**Comment by crsh** [comment]
The `apa6` document class provides a classoption `donotrepeattitle'  that should do the trick. Try this:

~~~yaml
---
classoption       : "man, donotrepeattitle"
---
~~~

**Comment by tcgriffith** [comment]
works great, thanks!
