### ISSUE TITLE
Allow columns have same names in apa_table

### ISSUE THREAD

**Issue by jamesrrae** [crsh/papaja#271]
**Is your feature request related to a problem? Please describe.**
In cases where there are multiple outcome variables, sometimes it makes sense to have table columns with the same name.  When I give columns the same name, apa_table produces an error indicating that columns must have unique names.

**Describe the solution you'd like**
To produce tables using apa_table that have the same column names.

**Describe alternatives you've considered**
None.

**Additional context**
To illustrate the type of table I'm imagining, you could have the column spanners "Outcome 1" and "Outcome 2" and below each of them the columns "Estimate", "Lower 95% CI",  and "Upper 95% CI".

**Comment by crsh** [comment]
Hi, have you tried using the development version (`devtools::install_github("crsh/papaja@devel")`)? With it it works for me:

~~~r
my_table <- t(apply(cars, 2, function(x) # Create data
  round(c(Mean = mean(x), SD = sd(x), Mean = mean(x), SD = sd(x)), 2)
))

apa_table(
  my_table
  , align = c("l", rep("r", 3))
  , caption = "A summary table of the cars dataset."
  , col_spanners = list("Outcome 1" = c(1, 2), "Outcome 2" = c(3, 4))
)
~~~

However, in general I would recommend a to use `variable_labels()`, which grants more flexibility in column tables and also in figures created with, for example, `apa_lineplot()`:

~~~r
my_table <- data.frame(my_table)
variable_labels(my_table$Mean.1) <- "Mean"
variable_labels(my_table$SD.1) <- "SD"

apa_table(
  my_table
  , align = c("l", rep("r", 3))
  , caption = "A summary table of the cars dataset."
  , col_spanners = list("Outcome 1" = c(1, 2), "Outcome 2" = c(3, 4))
)
~~~

**Comment by jamesrrae** [comment]
I had the same problem running your code until I changed to the developmental version. Problem solved.
