### ISSUE TITLE
apa_print.aov does not compile (error in creating data.frame and sumsq_err col)

### ISSUE THREAD

**Issue by emily-ho** [crsh/papaja#275]
An ANOVA will not print in APA format using either `papaja::apa_print`, `papaja::apa_print.aov`, or `papaja::aov_print.anova`.

A MVE using the built-in dataset `ChickWeight`:

```
require(magrittr)
aov(weight ~ Time, data = ChickWeight) %>% papaja::apa_print.aov()
Error in `$<-.data.frame`(`*tmp*`, "sumsq_err", value = list(sumsq = 872212.176554657)) : 
  replacement has 1 row, data has 2
```

The error for `papaja::apa_print.anova` is different:
```
aov(weight ~ Time, data = ChickWeight) %>% papaja::apa_print.anova() 
Error in arrange_anova.default(x) : 
  Objects of class 'aov' are currently not supported (no method defined).
              Visit https://github.com/crsh/papaja/issues to request support for this class.Objects of class 'lm' are currently not supported (no method defined).
              Visit https://github.com/crsh/papaja/issues to request support for this class.
```

I am using package version `0.1.0.9842` and R version `3.5.1`.
This code worked last week so I suspect it is something that changed in the development version quite recently. Perhaps in the papaja::arrange_anova function?

**Comment by mariusbarth** [comment]
Hi @emily-ho,
I installed R 3.5.1 and papaja 0.1.0.9842 in a virtual machine, and the first of your two function calls works just as expected (i.e., I cannot reproduce the error with the information you prvided). Can you post the output from `devtools::session_info()` so I can dig a bit deeper into this?

The second of your two function calls is doomed to fail: By appending `.anova` to your function call, you bypass R's method dispatch, forcing `apa_print()` to apply its method for `anova` objects to an object of class `aov`. This is obviously inappropriate, and the function call fails.

**Comment by emily-ho** [comment]
Hi @mariusbarth - thanks for the reply. So I tried the function again and you are right, it works now. I still don't quite understand why. Session info below.

`- Session info ---------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RTerm                       
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2019-03-28                  

- Packages -------------------------------------------------------------------
 package     * version    date       lib source                      
 assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.1)              
 backports     1.1.2      2017-12-13 [1] CRAN (R 3.5.0)              
 bindr         0.1.1      2018-03-13 [1] CRAN (R 3.5.1)              
 bindrcpp    * 0.2.2      2018-03-29 [1] CRAN (R 3.5.1)              
 broom         0.5.0      2018-07-17 [1] CRAN (R 3.5.1)              
 callr         2.0.4      2018-05-15 [1] CRAN (R 3.5.1)              
 cli           1.0.0      2017-11-05 [1] CRAN (R 3.5.1)              
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)              
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.3)              
 devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.3)              
 digest        0.6.15     2018-01-28 [1] CRAN (R 3.5.1)              
 dplyr         0.7.6      2018-06-29 [1] CRAN (R 3.5.1)              
 fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.3)              
 glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.1)              
 here          0.1        2017-05-28 [1] CRAN (R 3.5.1)              
 knitr         1.20       2018-02-20 [1] CRAN (R 3.5.1)              
 lattice       0.20-35    2017-03-25 [1] CRAN (R 3.5.1)              
 magrittr    * 1.5        2014-11-22 [1] CRAN (R 3.5.1)              
 Matrix        1.2-14     2018-04-13 [2] CRAN (R 3.5.1)              
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.1)              
 metafor       2.0-0      2017-06-22 [1] CRAN (R 3.5.3)              
 nlme          3.1-137    2018-04-07 [2] CRAN (R 3.5.1)              
 papaja      * 0.1.0.9842 2019-03-27 [1] Github (crsh/papaja@b6cd70f)
 pillar        1.3.0      2018-07-14 [1] CRAN (R 3.5.1)              
 pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.3)              
 pkgconfig     2.0.1      2017-03-21 [1] CRAN (R 3.5.1)              
 pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.3)              
 plyr          1.8.4      2016-06-08 [1] CRAN (R 3.5.1)              
 prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.3)              
 processx      3.2.0      2018-08-16 [1] CRAN (R 3.5.1)              
 ps            1.1.0      2018-08-10 [1] CRAN (R 3.5.1)              
 purrr         0.2.5      2018-05-29 [1] CRAN (R 3.5.1)              
 R6            2.2.2      2017-06-17 [1] CRAN (R 3.5.1)              
 Rcpp          0.12.18    2018-07-23 [1] CRAN (R 3.5.1)              
 remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.3)              
 rlang         0.3.1      2019-01-08 [1] CRAN (R 3.5.3)              
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)              
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.3)              
 stringi       1.1.7      2018-03-12 [1] CRAN (R 3.5.0)              
 stringr       1.3.1      2018-05-10 [1] CRAN (R 3.5.1)              
 tibble        1.4.2      2018-01-22 [1] CRAN (R 3.5.1)              
 tidyr         0.8.1      2018-05-18 [1] CRAN (R 3.5.1)              
 tidyselect    0.2.4      2018-02-26 [1] CRAN (R 3.5.1)              
 usethis       1.4.0      2018-08-14 [1] CRAN (R 3.5.3)              
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)      
`

**Comment by crsh** [comment]
I have noticed in the past that sometimes, and I have no clue as to why, installing from GitHub appears to proceed without the proper registration of the S3-Methods defined in the package. Did you reinstall prior to your last post or did you restart your R session?

**Comment by emily-ho** [comment]
I just restarted my R session to fix the problem. I haven't had any issues
with this since...

Thank you for looking into it! The package is great and my co-authors and I
just wrote an article forthcoming in *Nature Climate Change *relying
heavily on papaja. We will have to send it to you so can put it on your
site when it is formally published.

All the best,
Emily

**Comment by crsh** [comment]
Thanks for the feedback, that's good to know. And big congratulations on your paper. Looking forward to seeing it in print and adding it to our list of papers!
