### ISSUE TITLE
Removing corresponding author (and address) results in LaTeX error

### ISSUE THREAD

**Issue by TobiasHeycke** [crsh/papaja#277]
When I remove 'corresponding', 'address', and 'email' from the YAML in the author list (and therefore have no corresponding author) I get a LaTeX error ('Missing \begin{document}') when knitting. The Latex error is produced by a lonely '\'  hanging around in the preamble of the tex file (just before the \abstract).
I am assuming most people will specify a corresponding author, but in case people don't (e.g., for a draft version of a manuscript), this error might confuse them (e.g., me).

Thank you for your work and let me know if I can help! 

papaja version: 0.1.0.9842 (error not present in a previous version)

**Comment by crsh** [comment]
Hi Tobi, I cannot reproduce this issue with the current development version. Could you reinstall and try again to see if that helps?

**Comment by TobiasHeycke** [comment]
After re-installing papaja (devel) and the rlang package, I no longer can reproduce the bug. Please don't ask me what happened, as the problem only occurred after I installed a new papaja version...
Thanks!
