### ISSUE TITLE
Add option to printnum() for thousands separator

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#28]
Default should probably be true.

**Comment by dgromer** [comment]
Something like:

``` r
format(1000000000.333, nsmall = 2, scientific = 60, big.mark = ",", decimal.mark = ".")
```

The `scientific` argument prevents large numbers being printed as something like 1e+06.

**Comment by crsh** [comment]
Thanks for the suggestion; this looks like it should do the trick! I'll get on it next week. It will, however, be a little while before the change is available on the master branch of the project because we are currently doing some cleaning up in the background and getting ready to release a larger set of new functions and methods (so stay tuned).

**Comment by crsh** [comment]
Okay, this should work now, we just need to fix this for the inline hook now.
