### ISSUE TITLE
Suppress title and abstract page

### ISSUE THREAD

**Issue by cjvanlissa** [crsh/papaja#281]
A lot of the times, I am the only author on a project using Rmd, and I'll use it only to generate the Results section. In this case, the Title and Abstract pages are redundant. 

Is it currently possible, or would it be possible, to add an option to suppress these pages?

Thank you sincerely,
Caspar

**Comment by crsh** [comment]
Hi Caspar, this is currently beyond the scope of `papaja`. I think you should be able to achieve this somehow using LaTeX (e.g., by [redefining `\maketitle`](https://tex.stackexchange.com/questions/405988/apa-6-class-individual-title-page-instead-of-maketitle)).
