### ISSUE TITLE
Fourth-level headings: Text starts in next line

### ISSUE THREAD

**Issue by KatharinaH01** [crsh/papaja#284]
**Describe the bug**
I have run into issues with making the headers adhere to apa when knitting to pdf. It works fine until the third-level headers, but when using a fourth-level header (Indented, boldface, italicized, lowercase with a period) with ####, the following text body is not inserted right after the heading, but into the next line. That does not happen for the third level headings, where the text is added right next to the heading. 

**Expected behavior**
According to apa, the text would need to start right away after the period.

**Comment by crsh** [comment]
Thank you for reporting this. I haven't had time to look into the issue more closely. I do know that this is indeed an issue with `papaja` rather than the underlying `apa6` class. I'll try to address this as soon as possible.

**Comment by crsh** [comment]
Closing in favor of https://github.com/crsh/papaja/issues/292
