### ISSUE TITLE
Issue after installing developmental version of papaja

### ISSUE THREAD

**Issue by jamesrrae** [crsh/papaja#285]
I've been using papaja for a while now and recently decided to install the developmental version using this code: `devtools::install_github("crsh/papaja@devel")`. After making this simple change, I'm now no longer able to compile my documents. I specifically get the error message: 

`Error in loadNamespace(name) : there is no package called 'rmdfiltr'
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted`

However, there doesn't even seem to be a rmdfiltr package.

**Comment by crsh** [comment]
Hi James, thanks for reaching out. `rmdfiltr` is another in-development package of mine and available on GitHub. It should be installed automatically, I'm not sure why it doesn't I'll look into it. For the time being do the following should fix it: `devtools::install_github("crsh/rmdfiltr")`

**Comment by jamesrrae** [comment]
This resolved my issue. Thanks!
