### ISSUE TITLE
Let's have a more general printer class

### ISSUE THREAD

**Issue by axrhart** [crsh/papaja#286]
Hi,

first of all, let me thank you maintainers and contributors for the effort you put into this package. I have used it several times for writing and almost everytime it worked flawlessly and I got extactly the result I wanted.

Now back on topic: The issue over [at the MOTE repository](https://github.com/doomlab/MOTE/issues/3) caught my attention, so I read the discussion [here](https://github.com/crsh/papaja/issues/39) and got myself a brief overview of the relevant functions. I know that this discussion is a year old and maybe you already are working on an appropriate solution for the custom CIs, but nonethless I wanted to share my latenight thoughts with you.

I liked the suggestion of breaking up the workflow a lot, but somehow the solution of writing a special function just for the CI seemed too compartmentalized to make a workflow that is not only useful for connecting the MOTE package. I know, that was the target of the issue, but why not let papaja provide a class that package maintainers could use to tell papaja how it should map their output to papajas internal functions? Lately, I have used some R6 classes for a personal project and thougth they might be good for this issue. So I came up with the following sketch:

```
library(R6)

apa_printer <- R6Class("APA_Printer",
    public = list(
        initialize = function(input, map, type) {
            
            type <- as.character(substitute(type))
            
            if(!(type %in% private$valid_types)) {
                stop(paste("A valid type would be:", unlist(private$valid_types), "\n"))
            } else if (class(map) != "APA_Printer_Map") {
                stop(paste("Argument map must be of class 'APA_Printer_Map'"))
            } else if (typeof(input) != "list") {
                stop(paste("Argument input must be a list."))
            } else if(is.null(names(input))) {
                stop(paste("Argument input must have names."))
            } else if(sum(names(input) %in% names(map)) <= 0) {
                stop(paste("At least one argument of input must correspont to a map name."))
            } else {
                private$type = type
                private$input = input
                private$build_df(input, map)
            }
        },
        print = function() {
            if (private$type == "anova") {
                cat("Pretty anova console out here")
            } else if (private$type == "glm") {
                cat("Some other fancy output")
            }
        },
        apa_print = function() {
            return(private$df)
        },
        get = function() {
            return(private$input)
        },
        get_type = function() {
            return(private$type)
        }
    ),
    private = list(
        df = NULL,
        input = NULL,
        type = NULL,
        valid_types = c("anova", "glm"),
        build_df = function(input, map) {
            
            df = list()
            
            for (field in names(map)) {
                df[[map[[field]]]] <- input[[field]]
            }
            
            private$df <- data.frame(df)
        }
    )
)

apa_printer_map <- R6Class("APA_Printer_Map", list(
    
    initialize = function(...) {
        self$map = eval(substitute(alist(...)))
        class(self$map) <- "APA_Printer_Map"
    },
    print = function() {
        return(self$map)
    },
    map = NULL
))
```

I overdid the checking part, but I think you can see that the idea is pretty basic. The Printer takes a named list as input and a map (which is also a named list, the second class is more or less for convenience) and maps them together to a data.frame format the papaja functions expect.  If you make this class a first class citizen argument in `apa_print` then it can bypass many of the evaluation steps and go directly to printing. We could also define a logic that fills possible holes in the output from several dataframes. So calling `(apa_print(aov, apa_printer$apa_print())` could, for example, get the eta^2 CIs from the second argument (which would be evaluated first) and the remaining parameters are filled from the aov function that is passed down the function cascade that is already implemented.

The printer function could be utilized by users to input any new or custom analysis (as long as papaja supports printing output for that statistic) but also by package maintainers without the need to rewrite their output functions, since we can transmute almost everything to the form of a named list.

```
aov.s = summary(aov(mpg~cyl, data = mtcars))
eta.s = MOTE::eta.F(aov.s[[1]][["Df"]][1], aov.s[[1]][["Df"]][2], aov.s[[1]][["F value"]][1], a = .05)
mote.eta <- apa_printer_map$new(eta = es, etalow = es_ll, etahigh = es_ul, F = Fvalue, dfm = dfm, dfe = dfe)
to_papaja <- apa_printer$new(eta.s, mote.eta$map, anova)
apa_print(to_apaja$apa_print())
```

From there we can just check which parameters are supplied in papajas naming convention and act accordingly.

What do you think?

**Comment by crsh** [comment]
Thanks for the thought-out discussion starter, @axrhart. I'm a little short on time at the moment but this is definitely an important issue and I'll try to come back to it as soon as I can. Feel free to brainstrom some more in the meantime.

**Comment by axrhart** [comment]
Thank you for your approval @crsh. Unfortunately, I'm also short on time atm, but I will try to elaborate on my ideas during the upcoming weekend. :-)

Best,
Alexander

**Comment by crsh** [comment]
From our discussion in the PR I got the feeling, that this issue has been resolved. Do you agree?

**Comment by axrhart** [comment]
Yes, indeed. Thank you very much. :-)
