### ISSUE TITLE
Landscape table in bookdown document

### ISSUE THREAD

**Issue by lnalborczyk** [crsh/papaja#287]
Hi,

I am trying to compile a `bookdown` document that contains tables made via the `papaja::apa_table()` function. Everything works fine works regular tables but I get the following LaTex error when I try to include landscape tables:

`! LaTeX Error: Environment lltable undefined.`

This probably comes from the environment created in the `apa_table()` function, and more specifically the `\\begin{lltable}` bit of code on line 466 of the [function](https://github.com/crsh/papaja/blob/master/R/apa_table.R).

I guess I miss a LaTex package, but I do not know which one... or maybe the error comes from something else ?

It is difficult to provide a reproducible example though, as I am working from my messy dissertation repository...

Thanks !

**Comment by crsh** [comment]
`lltable` is a custom environment I define to make the setup work with `endflaot` (there may be a more elegant solution, but this is what I came up with). The environment is designed [here](https://github.com/crsh/papaja/blob/master/inst/rmarkdown/templates/apa6/resources/apa6_header_includes.tex#L19).

**Comment by lnalborczyk** [comment]
Thanks for your prompt answer ! I have added this to my `preamble.tex` file and it works perfectly :-).
