### ISSUE TITLE
apa_table longtable with repeated header?

### ISSUE THREAD

**Issue by mischavk** [crsh/papaja#289]
Hi once more,

I'm not sure if apa_table used with the longtable=T argument is supposed to create a table with a repeated table header on each new page?
If not, is there any way to accomplish this (possibly including a caption with "....continued")?
I'd like to avoid using kableExtra because I need both pdf and word output.

Any help would be great! :)
Thanks!

**Comment by crsh** [comment]
Hi @ mischavk, thanks for the request. This has crossed my mind more than once, but I've never sat down to look at it. After a first quick look, it seems easy to implement. What do you think would be the best way to implement this with respect to caption and footnote? I'm thinking Caption on first page (all other pages "Table X conitnued") and note on last page only. Either could of course also be displayed on every page but that could potentially take up quite a bit of space.

**Comment by crsh** [comment]
How about something like this:

<img width="582" alt="Longtable top" src="https://user-images.githubusercontent.com/2195485/58380260-382d2d80-7faf-11e9-9b5e-9840d9cebc4c.png">

<img width="581" alt="Longtable bottom" src="https://user-images.githubusercontent.com/2195485/58380267-45e2b300-7faf-11e9-8c1e-792608135ac2.png">

**Comment by mischavk** [comment]
Looks great, thank you very much! That's exactly what I had in mind.

**Comment by crsh** [comment]
Reinstall from the development branch (`devtools::install_github("crsh/papaja@devel")`) et voilà. :wink:

**Comment by mischavk** [comment]
I already did! Thanks again! :)
