### ISSUE TITLE
Pronouncing papaja

### ISSUE THREAD

**Issue by jupitus** [crsh/papaja#291]
@crsh, how do **you** pronounce papaja?
PAH-pah-jah
pah-PAH-jah
PAH-pah-yah
pah-PAH-yah
Other?

**Comment by crsh** [comment]
Hehe, I pronounce it just like I would the fruit. [This](https://youtu.be/k_e8cSvexsI?t=5) is pretty much it. :sweat_smile:

**Comment by jupitus** [comment]
Yummm!  Thanks.
