### ISSUE TITLE
apa7th or updated apa6th

### ISSUE THREAD

**Issue by KarlWolters92** [crsh/papaja#293]
Hi,

I send in a document to my supervisor created with papaja. He said that this would not be the most up to date apa style. For example, that there should not be an issue number or also that there should not be https// in front of every doi.

I wonder: Is it possible to change the citation style papaja uses or will that every be updated?

Thanks,

Karl

**Comment by crsh** [comment]
Hi Karl, thanks for reaching out. It's great to hear there's a new `papaja` user.

> there should not be an issue number

That's true for most cases. The problem with this rule in the APA manual (include issue numbers only if the periodical is paginated by issue, see p. 198) is that it cannot be automated by systems that handle the references in a manuscript. If you omit the issue numbers from the bibliography file manually they will also be omitted from the reference section. Note also, that this rule is [critiqued quite a bit](https://blog.apastyle.org/apastyle/2011/10/how-to-determine-whether-a-periodical-is-paginated-by-issue.html) for being overly complicated. I have never had an (APA) journal comment on the routine inclusion of issue numbers in my reference sections.

> there should not be https// in front of every doi

As of two years ago, the [APA recommends](https://blog.apastyle.org/apastyle/digital-object-identifier-doi/) to move to the new DOI-format and include the `https://`-prefix. I expect that this new recommendation will be included in the next edition of the publication manual.

**Comment by KarlWolters92** [comment]
Thanks a lot for explaining me this! And yes, I am a happy papaja user I can tell you!
