### ISSUE TITLE
In Press Citations

### ISSUE THREAD

**Issue by AlexChristensen** [crsh/papaja#294]
**Is your feature request related to a problem? Please describe.**
Yes -- When attempting to cite something that is "in press" the output instead puts "n.d."

**Describe the solution you'd like**
I would like there to be some operation that could be input into the bibtex file with papaja so that in press articles could be cited as "in press."

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by crsh** [comment]
Hi Alex, thanks for reaching out, great question. I have added [a section to the manual](https://crsh.github.io/papaja_man/writing.html#works-in-press) that explains how to cite works that are 'in press', 'submitted', etc.

**Comment by AlexChristensen** [comment]
Great, thank you!
