### ISSUE TITLE
Revision letter reference section indents initial entry

### ISSUE THREAD

**Issue by jvcasillas** [crsh/papaja#296]
**Describe the bug**
When using a .bib file to generate a reference section in a papaja revision letter, the first line of the initial entry of the bibliography is indented. 

**To Reproduce**
I am not using any special packages, thus I believe this should be reproducible if/when using a .bib file to generate references. 

**Expected behavior**
The initial line of the first entry should not be indented (though every subsequent line of the same entry should be). 

**Screenshots**
![Screen Shot 2019-07-07 at 15 28 50](https://user-images.githubusercontent.com/1747068/60772977-f2927300-a0cb-11e9-8af5-22c2a781342c.png)

![Screen Shot 2019-07-07 at 15 28 55](https://user-images.githubusercontent.com/1747068/60772979-f625fa00-a0cb-11e9-823e-18dceb3e2e2b.png)

**Additional context**
NA

**Comment by crsh** [comment]
Thanks, I'll take a look next chance I get.

**Comment by conig** [comment]
This can be fixed by adding \noindent under # References

```
# References

\noindent
\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>

\endgroup
```
