### ISSUE TITLE
Remove Oxford commas in in-text citations when writing in German

### ISSUE THREAD

**Issue by mariusbarth** [crsh/papaja#302]
When creating a manuscript in German, the ampersand filter leaves Oxford commas in in-text citations, i.e. "Barth, Stahl, & Haider (2019)" is changed to "Barth, Stahl, und Haider (2019)".
In German, the Oxford comma should be removed.

**Comment by crsh** [comment]
Thanks for pointing this out. However, this issue related to the ampersand filter in the [`rmdfiltr`](https://github.com/crsh/rmdfiltr)-package. Could you move the issue to that repository?

**Comment by mariusbarth** [comment]
Me so stupid...
