### ISSUE TITLE
papaja::apa6_pdf causes compilation error in Sublimetext (not Rstudio)

### ISSUE THREAD

**Issue by JanaJarecki** [crsh/papaja#304]
**Describe the bug**
I am trying to compile a document in rmarkdown **not** from RStudio. As soon as I include the header `output: papaja::apa6_pdf` the document fails to compile with the error message below.

While `output: pdf_document` works, changing the option to `output: papaja::apa6_pdf` fails. I am in sublimetext, not in R studio. **Are there other settings that are defaults in R-studio that one needs to change when not in Rstudio?**

The render cmd is `rmarkdown::render("filename.Rmd")`.

The problem seems to be that the apa6.csl file is not found. The file exists

- I put the file in the directory where the .Rmd lies
- I put the file into the rmarkdown/rmd/latex directory

Both had no effect.

***Error Msg*** 
`Error in FUN(X[[i]], ...) : index outside of bounds.
`

**To Reproduce**
I am afraid, reproduction is hard to provide if you are not using Sublimetext. The file I compile contains only the header

```
---
title: "Results"
author: "JName"
date: "Aug. 2019"
output: papaja::apa6_pdf
---
```

**Additional context**
I use sublimetext3.

**Comment by JanaJarecki** [comment]
The problem was solved the problem by updating tinytex in R to the latest version

`tinytex::reinstall_tinytex()`

as per #11 here https://yihui.name/tinytex/faq/

**Comment by crsh** [comment]
Hi Jana, could you try knitting the file with a proper `papaja` YAML front matter (see the skeleton you get when you create a new R Markdown file from template) if that makes sense?
