### ISSUE TITLE
How to change only one page into landscape while keeping others as portrait?

### ISSUE THREAD

**Issue by koliii** [crsh/papaja#305]

**Comment by crsh** [comment]
Hi there, I need more context to understand the question. Are you try to create a Word or PDF-file? Why are you trying to rotate the page? Could you provide a reproducible example?

**Comment by koliii** [comment]
It is a pdf output. A big ggplot need to be fit in a portrait page. I'm helping, I hope.

**Comment by crsh** [comment]
Thanks for the clarification. I'm afraid this is a LaTeX-related rather than being related to `papaja`. But you could try using the [`landscape` environment](https://stackoverflow.com/a/27334272/914024).

**Comment by crsh** [comment]
One more idea: You could also try the [`out.extra`-chunk option](https://stackoverflow.com/a/13594070/914024).

**Comment by koliii** [comment]
Thank you for your suggestions. :)

**Comment by ericpgreen** [comment]
@crsh I've found that using `lscape` (rotate table on portrait page) or `pdflscape` (rotate page itself) works well in `header-includes` if I set `floatsintext` to "yes". If I say "no", the rotation does not happen in my setup. Does anyone know how to rotate AND float tables to the end?

```
header-includes:
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
```

**Comment by hsorlie** [comment]
Don't know if this is helpful, but I have a papaja document where some tables are rotated to landscape, and they appear at the end of the output PDF. Tables are created with `stargazer()`, with the `float.env = "sidewaystable"` argument. And then, in the YAML front matter, I include:
```{r}
documentclass     : "apa6"
classoption       : "man"
header-includes:
- \usepackage{dcolumn, rotating}
output            : papaja::apa6_pdf
```
...the point being the `rotating`-package, I suppose. Hope this helps!

**Comment by ericpgreen** [comment]
Thanks. I believe I tried rotating with the same result. Difference being
that I'm not using a package that integrates float.env directly into
the latex generation like stargazer. It's a nice feature of that package.

**Comment by ericpgreen** [comment]
I'm still struggling with this one. I can't seem to get rotated tables when floating tables to the end. I'm not using stargazer. Any ideas? cc: @crsh

**Comment by crsh** [comment]
If you are willing to provide a minimal reproducible example, I'll try to take a closer look.

**Comment by ericpgreen** [comment]
That would be great. If you turn `floatsintext` to "yes" Table 2 is rotated, but not when it's set to "no".

```
---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
header-includes:
  - \raggedbottom
  - \usepackage{booktabs}
---

```{r setup, include = FALSE}
library("papaja")
library(kableExtra)
library(tidyverse)
```

# Introduction

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Methods

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Results

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

```{r, echo=FALSE}
  set.seed(1)
  df <- data.frame(v1=runif(10),
                   v2=runif(10),
                   v3=runif(10),
                   v4=runif(10),
                   v5=runif(10),
                   v6=runif(10),
                   v7=runif(10),
                   v8=runif(10),
                   v9=runif(10),
                   v10=runif(10),
                   v11=runif(10),
                   v12=runif(10),
                   v13=runif(10))
```

Table \@ref(tab:tbl1)

```{r tbl1}
  df %>%
  select(v1:v4) %>%
  kable(format = "latex", 
        booktabs = TRUE,
        caption = "Portrait table.") %>%
    kable_styling() %>% 
    footnote(general = "This one will be portrait.") 
```

Table \@ref(tab:tbl2)

```{r tbl2}
  df %>%
  kable(format = "latex", 
        booktabs = TRUE,
        caption = "Landscape table.") %>%
    kable_styling() %>% 
    landscape() %>%
    footnote(general = "This one should be landscape.") 
```


# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
```
