### ISSUE TITLE
Add information about numbersection in the manual

### ISSUE THREAD

**Issue by bnicenboim** [crsh/papaja#306]
**Is your feature request related to a problem? Please describe.**
It took me a while to discover how to add numbers to the sections. And I found #85, but it's not relevant any more, since `numbersections: true` works just find.

**Describe the solution you'd like**
Add a reference to `numbersections:true` in the manual.

**Comment by mariusbarth** [comment]
I just added the information  to the `papaja` manual:
https://crsh.github.io/papaja_man/r-markdown-components.html#yaml-front-matter
