### ISSUE TITLE
How can I display double dates in citations?

### ISSUE THREAD

**Issue by lnalborczyk** [crsh/papaja#307]
Dear Frederik,

I am trying to cite a book originally published in the 30's, for which a novel translation has been published in 2012.

According to APA6, I think the citation format should be something like "Doe, J. (1930/2012)", both in text and in the references sections. Am I correct?

This issue is already discussed on the zotero forum: https://forums.zotero.org/discussion/74591/double-date-two-years-for-modern-classics

I have thus tried to export my library to a .bib by adding the `original-date: 1934` information to the `extra` field in zotero, as recommended in this forum thread (cf. below).

<img width="256" alt="Screenshot 2019-08-13 at 10 34 04" src="https://user-images.githubusercontent.com/10812999/62927000-f180ef80-bdb5-11e9-84ca-fd8facf5a794.png">

The generated .bib now indeed contains a field called `origdate` (cf. below).

<img width="536" alt="Screenshot 2019-08-13 at 10 35 14" src="https://user-images.githubusercontent.com/10812999/62927058-0eb5be00-bdb6-11e9-8856-1bfa2ea4b629.png">

However, when I knit my document to PDF (I am currently writing my thesis using the `bookdown` package, but I think the issue should be similarly of interest for `papaja` manuscripts), the only date displayed is 2012.

My hint is that the CSL file I am using somehow does not manage to incorporate this extra information. I am using the default `apa6.csl` file (I guess it's similar to the one you're using in papaja: https://github.com/crsh/papaja/blob/master/inst/apa_source_files.csl).

The issue might come from the fact that this CSL expects an "original-date" field whereas I am providing it an "origdate" field... I have therefore tried to replace all "original-date" by "origdate" in the CSL file but that was not successful...

Would you have any hint?

Ladislas

**Comment by crsh** [comment]
Interesting. To be honest, I'm not sure, but according to this issue, `pandoc-citeproc` should handle this: `date = {1930/2012}`.

**Comment by lnalborczyk** [comment]
Thank you for your prompt answer! You're right, `pandoc-citeproc` is indeed able to handle the double date in the `date` field. However, for some reason, the slash is converted to a dash in the PDF output... that's puzzling.

**Comment by crsh** [comment]
Ah, I didn't read closely. That's apparently what it should do. So, [apparently](https://github.com/jgm/pandoc-citeproc/issues/103#issuecomment-72275749), the approach would be to use the `origdate` field. `pandoc-citeproc` should map it to `original-date` in the CSL definition.

**Comment by lnalborczyk** [comment]
Nope, using the `origdate` field in the .bib file results in only the `date` being displayed in the output PDF document (using `pandoc-citeproc` and the `apa6.csl`). The `origdate` year does not appear... but it might also be an issue specific to `bookdown`. I'll try to provide a reproducible example as soon as possible. Thank you for your help!

**Comment by njbart** [comment]
> … use the `origdate` field. pandoc-citeproc should map it to `original-date` in the CSL definition.

Correct. (If you’re unsure about the CSL variables being used, try `pandoc-citeproc -y <file>.bib` to inspect the CSL (YAML) counterpart of your `.bib` file.)

Note: Not all `.csl` style files cater for original dates (yet). If in doubt, cross-check with one known to work, e.g., <https://github.com/citation-style-language/styles/raw/master/apa.csl>.

**Comment by HankNu** [comment]
@lnalborczyk you can just reset the range-delimiter of date-parts in your specific .csl files
![Visual CSL Editor - Chromium_004](https://user-images.githubusercontent.com/33976639/67257824-619ba800-f4c0-11e9-8315-04daf1289e66.png)
