### ISSUE TITLE
Reference Formattign

### ISSUE THREAD

**Issue by ccobserver** [crsh/papaja#31]
The references do not come out according to APA 06 (hanging indent), but rather they are indented on the first line. How would I fix this issue?

**Comment by crsh** [comment]
Thanks for the question and sorry for the late reply, @ccobserver.

This is an issue that is currently being worked on by the pandoc developers (see e.g. [this discussion](https://groups.google.com/forum/?fromgroups&hl=en#!topic/pandoc-discuss/ghOOvbHByLk)). For the time being, if your target output format is PDF, you can add the following LaTeX-lines to the end of you document:

    \setlength{\parindent}{-0.5in}
    \setlength{\leftskip}{0.5in}
    \setlength{\parskip}{8pt}

This should produce the desired results.
