### ISSUE TITLE
printnum(as.integer(0), numerals=F) to return "zero" instead of empty string

### ISSUE THREAD

**Issue by e-schott** [crsh/papaja#311]
I have printnum statement in my script that is supposed to return how many times an event occurs. If it never occured, I was expecting to return "zero", but it returns ""
`printnum(as.integer(0), numerals=F)`

It would be helpful if `printnum(as.integer(0), numerals=F)` returns "zero", which would probably mean rewriting that section. Alternatively, if printnum could throw some kind of error, that would trigger the author to rewrite that section, too. 

I am trying to write a fully reproducible manuscript that updates as data changes.

**Comment by crsh** [comment]
Hi there, thanks for starting this discussion. I agree that a return value of `""` is not very useful.

Could you be a little bit more specific about how you intend to use the output of `apa_print()` in this case? Would a return value of `"zero"` be ideal? I was thinking that `"no"` maybe easier to insert into a sentence when using `apa_print()` to create an in-text report of the result?

**Comment by crsh** [comment]
Okay, I have now implemented this with a new option `zero_string` which defaults to `"no"`. To try it out, reinstall from the development branch (`devtools::install_github("crsh/papaja@devel")`). Let me know if it works.

**Comment by e-schott** [comment]
Just tried it out, and it works! Thank you!
