### ISSUE TITLE
printnum(20, numerals =F) returns "twenty-no"

### ISSUE THREAD

**Issue by e-schott** [crsh/papaja#312]
This is most likely relates to my recent [feature request ](https://github.com/crsh/papaja/issues/311#event-2597748341). 
Evaluating 
`printnum(as.integer(20), numerals=F) `
now returns 
`"twenty-no" `
instead of `"twenty"`.

**Comment by crsh** [comment]
Ah, that embarrassing. Thanks for letting me know. This should now be fixed.

~~~r
> printnum(20L, numerals = FALSE)
[1] "twenty"
~~~

**Comment by e-schott** [comment]
great, it works! Should I close the issue or is that something you usually do?

**Comment by crsh** [comment]
I usually leave these issues open until the next merge of the development branch into the master branch, which should close them automatically. :)
