### ISSUE TITLE
Automate updating APA CSL

### ISSUE THREAD

**Issue by bwiernik** [crsh/papaja#314]
The version of apa.csl modified to remove given name disambiguation (https://tinyurl.com/apa6-no-disambiguation) is fairly out of date. I've attached an updated version of the style and a bash script that can be run to download the current version of apa.csl, apply the patch, and save it as apa_no_disambiguation.csl. You could, for example, host this csl file in a more permanent repo and run it when you release a papaja update.

If you'd rather not worry about keeping this up to date, I host a few unofficial apa.csl variants here: https://github.com/bwiernik/zotero-tools. I've added apa-no-disambiguation.csl to it (https://raw.githubusercontent.com/bwiernik/zotero-tools/master/apa-no-disambiguation.csl). You could update the destination of https://tinyurl.com/apa6-no-disambiguation to redirect there.

[update_apa_no_disambiguation.sh.txt](https://github.com/crsh/papaja/files/3588004/update_apa_no_disambiguation.sh.txt)
[apa6_no_disambiguation.csl.txt](https://github.com/crsh/papaja/files/3588005/apa6_no_disambiguation.csl.txt)

**Comment by crsh** [comment]
Great, thank you! I've been thinking about shipping this and the [meta-analysis variant](https://stackoverflow.com/questions/53091561/citing-meta-analytic-sources-in-papaja) with the package. For this purpose the bash script would be really useful! I just saw that you are also hosting a meta-analysis version. Would you be willing to briefly outline how you customized it? Maybe I could fully rely on your versions.

**Comment by bwiernik** [comment]
The meta-analysis variant adds the contents of the CSL `annote` variable as a prefix to the references list. So, the user can add an asterisk or other indicator (e.g., multiple asterisks or a, b, c to indicate different subsets of studies in the meta-analysis) to `annote` for the variables included in the meta-analysis, but not have anything show up for other cited works. 

I do keep the styles at that page updated with changes to the apa.csl, so you could use a bash script to pull the current version from my page at build time for papaja.

**Comment by bwiernik** [comment]
I've updated both of these versions hosted on my GitHub page with APA 7th edition versions.

**Comment by crsh** [comment]
Excellent, thank you. I'll implement what you have suggested for the upcoming APA7 document formats and fully rely on your approach for meta-analytic references. Thanks for sharing!

**Comment by bwiernik** [comment]
I’ll keep the no-disambiguation version up to date, too, so you can pull both from my repo.

**Comment by bwiernik** [comment]
Do you do build the package in R using `devtools` or from the command line with `R CMD CHECK`? If the latter, do you use Windows or Mac/*nix?

**Comment by crsh** [comment]
I typically build using `devtools` and work on Mac and Linux.

**Comment by bwiernik** [comment]
Cool. I’ll write an R file you can source as part of your build pipeline.

**Comment by crsh** [comment]
Sounds great, thanks. I'll gladly review a PR!

**Comment by cissard** [comment]
Hi, I am using papaja 0.1.0.9997 for a meta-analysis, and the asterisks don't appear in front of the references included in the meta-anlysis, although I added one in the respective anote fields of my .bib file, and added "annotate_references: yes" in the yaml on top. Should I add the variant csl files myself?

**Comment by bwiernik** [comment]
I don't think that pandoc imports an annote field from .bib. It's not part of the BibLaTeX or BibTeX specs. It's a CSL variable (pandoc converts other formats to CSL, and the cross-mappings aren't perfect). If you are writing with pandoc, I strongly recommend storing your bibliography as CSL YAML rather than .bib

**Comment by crsh** [comment]
> Hi, I am using papaja 0.1.0.9997 for a meta-analysis, and the asterisks don't appear in front of the references included in the meta-anlysis, although I added one in the respective anote fields of my .bib file, and added "annotate_references: yes" in the yaml on top. Should I add the variant csl files myself?

In theory, this should work as is, but there could be something wrong. It would be helpful, if you could try and let me know if it works. The approach using the annote filed [has worked in the past](https://stackoverflow.com/questions/53091561/citing-meta-analytic-sources-in-papaja/53164292#53164292).

**Comment by bwiernik** [comment]
pandoc has a new citeproc. It's possible that its treatment of invalid BibTeX variables has changed

**Comment by cissard** [comment]
Thanks for your replies! We searched for csl files but didn't get any obvious file to add. Can you please share a minimal working example? That would be very helpful.

Here is [our code](https://github.com/cissard/MA_speech_pref/blob/master/MA_speech_pref.Rmd) in case you want to have a look.

**Comment by crsh** [comment]
Hmm, if I knit your document I do get asterisks.

~~~r
> rmarkdown::pandoc_version()
[1] ‘2.11.2’
~~~

Do you have the same version?

**Comment by cissard** [comment]
Thanks for taking the time to look at my document!

I updated pandoc to 2.11.4, but I still don't get the asterisks.

**Comment by crsh** [comment]
So my first page of the reference looks like this:

![Bildschirmfoto 2021-03-04 um 08 53 29](https://user-images.githubusercontent.com/2195485/109929784-2a99f100-7cc7-11eb-9ac7-193c1fc0c10b.png)

Do you get this introductory statement about meta-analytic references?

**Comment by cissard** [comment]
Yes I do get the introductory statement. I don't know if that could be related but your first page misses several references (e.g. Cooper & Aslin, 1994 that should have an asterisk). Here is mine:
[MA_speech_pref (glissé(e)s).pdf](https://github.com/crsh/papaja/files/6084545/MA_speech_pref.glisse.e.s.pdf)

**Comment by crsh** [comment]
Strange. The reason the Cooper-Reference wasn't showing was that the reference handle in the R Markdown document was not preceeded by a `@`. After adding it, its in the references and preceeded by an asterisk. Could you share the pandoc call from the R Markdown pane in RStudio?

**Comment by cissard** [comment]
Here is the only mention of pandas I could find in the R Markdown pane in RStudio:

/usr/local/bin/pandoc +RTS -K512m -RTS MA_speech_pref.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash+raw_attribute --output MA_speech_pref.tex --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --include-in-header /Library/Frameworks/R.framework/Versions/4.0/Resources/library/papaja/rmarkdown/templates/apa6/resources/apa6_header_includes.tex --variable graphics --wrap preserve --csl /Library/Frameworks/R.framework/Versions/4.0/Resources/library/papaja/rmd/apa6.csl --citeproc --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmdfiltr/replace_ampersands.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmdfiltr/wordcount.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/papaja/lua/parse_metadata.lua --variable 'classoption:man' --variable 'lang:en-EN' --variable 'subparagraph:yes' --variable 'block-headings:no' --include-in-header /var/folders/p_/mv3bvhqd6yg54_btbr0ynxhc0000gn/T//RtmpXI99ko/includes_8cc951f8efc2.tex

**Comment by crsh** [comment]
That's the one I was looking for. The following tells me, that the asterisks are not showing because the wrong CSL file is called:

~~~
--csl /Library/Frameworks/R.framework/Versions/4.0/Resources/library/papaja/rmd/apa6.csl
~~~

It should be

~~~
--csl /Library/Frameworks/R.framework/Versions/4.0/Resources/library/papaja/rmd/apa6-annotated.csl
~~~

Are you using the latest development version? Could you try reinstalling from the `devel` branch and see if that solves the problem?

~~~r
remotes::install_github("crsh/papaja@devel")
~~~

**Comment by cissard** [comment]
Indeed! It works now, thank you very much for your help!

**Comment by crsh** [comment]
Excellent. Thanks for letting me know.
