### ISSUE TITLE
Add symbols and notes to authors

### ISSUE THREAD

**Issue by DominiqueMakowski** [crsh/papaja#315]
I was wondering if it was possible to add symbols (asterisks, daggers, ...) referring to particular notes, for instance in the case of co-authors (AA*, AB*, AC, AD) or deceased authors. Thanks!

**Comment by crsh** [comment]
Hi Dominique, just briefly as I'm on the go: Are you trying to add custom symbols to author names? If so, you should be able to use any symbol to denote "affiliations" in the YAML front matter. E.g.,

~~~
author: 
  - name          : "Peter Parker"
    affiliation   : "1*"
~~~

For mathy symbols you could try the following (admittedly, without trying, I'm not sure this works):

~~~
author: 
  - name          : "Peter Parker"
    affiliation   : "1$\dagger$"
~~~

**Comment by DominiqueMakowski** [comment]
@crsh Thanks for your answer, asterisks work, but daggers don't 😕 

```
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: while parsing a quoted scalar at line 15, column 21 found unknown escape character at line 15, column 29
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted
```

**Comment by crsh** [comment]
Ah, yes. These inputs are parsed by R so any `\` that is meant for LaTeX needs to be escaped. Try this:

~~~yaml
author: 
  - name          : "Peter Parker"
    affiliation   : "1$\\dagger$"
~~~

**Comment by DominiqueMakowski** [comment]
Thanks it works!

For other users, in the `authornote` section it should be specified as `$\dagger$` (and `$\\dagger$` in `affiliation`)
