### ISSUE TITLE
Landscape Tables + apa6 "man" does not work 

### ISSUE THREAD

**Issue by karchjd** [crsh/papaja#318]
**Describe the bug**
Using the apa6 latex document class, normal (landscape=FALSE) tables are correctly put at the end of the document but (landscape=TRUE) are not. 

**To Reproduce**
[mwe2.Rnw.zip](https://github.com/crsh/papaja/files/3623599/mwe2.Rnw.zip)

**Comment by crsh** [comment]
Hi there, as far as I can tell, you are using `apa_table()` in a non-`papaja` document template. So I think the answer to your question could be in [this issue](https://github.com/crsh/papaja/issues/287). Let me know if that doesn't address you problem.
