### ISSUE TITLE
Journal Formatting

### ISSUE THREAD

**Issue by ccobserver** [crsh/papaja#32]
When using class:journal, the paragraphs do not get indented.

**Comment by crsh** [comment]
Good catch. I'm not quite sure why this is the case, but I'll take a closer look at this issue and get back to you as soon as I know more.

**Comment by ccobserver** [comment]
The code you sent for the reference issue also indented the paragraphs 
above. Thank you for the help!

**Comment by crsh** [comment]
It works for me:

![indent](https://cloud.githubusercontent.com/assets/2195485/7236047/966234e0-e792-11e4-8a02-f9771fc733f4.png)

Have you added the
 three lines as the final lines of you Rmd-file?

**Comment by ccobserver** [comment]
I was just saying that both of my issues were resolved the those three lines of code.

**Comment by crsh** [comment]
Oh, okay. Even better. ;)

**Comment by ccobserver** [comment]
I was mistaken. The lines of code work for manuscript class, but not journal class.

**Comment by crsh** [comment]
Thanks for the update. I'll look into it.

**Comment by crsh** [comment]
I think I have fixed the issue. Try reinstalling `papaja` and knitting your document in `jou` mode. Let me know if you experience any other problems.
