### ISSUE TITLE
Feature request: integration with sjPlot (HTML-tables)

### ISSUE THREAD

**Issue by hsorlie** [crsh/papaja#321]
Hi! First: I have already posted this on the sjPlot/issues-page, but afterwards I thought it would be as well relevant here as there.

Thank you for papaja! I'm new to it, and currently writing my first paper with it. Absolutely love it so far, and I'm learning new tricks everyday. I can easily see this as my only way to write papers from now on.

However, I find it a bit difficult to create the tables I need. In this paper I use lme4 for multilevel analyses, and I have created some publication-friendly tables with sjPlot::tab_model. These are easily customizable and really good looking, perfect for publication. The downside is that sjPlot only creates HTML tables, not latex. Therefore I get error messages like this one, which I believe is because of the unicode greek letter:

! Package inputenc Error: Unicode character σ (U+03C3)
(inputenc) not set up for use with LaTeX.

Is there a way for papaja to accept input like this? My understanding now is that it isn't, but if it were, I think papaja + sjPlot would be a really powerful combo.

kind regards,
Henrik

**Comment by crsh** [comment]
Hi Henrik,

thanks for the suggestion. As I've noted in [this Twitter thread](https://twitter.com/bergelsonlab/status/1182779560850415616) I don't think there is a good solution for this unless `sjPlot` can produce either LaTeX or Markdown output (or return the table as a `data.frame`).

That said, you could try saving the table to a separate HTML file, use `pandoc_convert()` to convert the table to LaTeX/Markdown format and insert the converted table into your `papaja` R Markdown file (e.g. via `readLines()` and `knitr::asis_output()`). But I'm not sure how far this approach will get you.

For the record: This is the issue over at `sjPlot`: https://github.com/strengejacke/sjPlot/issues/555

That said, there are also [some efforts](https://github.com/crsh/papaja/pull/297) to add support for mixed models to `apa_table()`. See [this issue](https://github.com/crsh/papaja/issues/154) for the related discussion. But I suspect it will be a while before there are usable results.

**Comment by hsorlie** [comment]
Hi! Thanks for sharing that twitter thread. I saw a tip concerning the stargazer package in there, so I have been experimenting with that a bit, and it looks like that's the solution I'm going for. Getting apa_table to work with lmer-objects would be fantastic, but for now stargazer works.

Thanks again for your time in addressing this, and for all the effort you've put into papaja. Can't wait to see it on CRAN!
