### ISSUE TITLE
Could not create a copy of the original input file xxx while trying to render the appendix.

### ISSUE THREAD

**Issue by bnicenboim** [crsh/papaja#322]
I was getting the `Could not create a copy of the original input file **filename** while trying to render the appendix.` when I added an appendix.

I already know that this is because of line 717 in `https://github.com/crsh/papaja/blob/master/R/apa6_formats.R` The problem was that a temporary file was created and not deleted automatically. I fixed this by deleting the file.

I just wanted to know if I should change the code and do a pull request: I could add either a more informative message that tells the user to manually delete de temporary file, or make papaja do it by itself.

**Comment by crsh** [comment]
That's a good point. I thought I had done this already. I'll try adding this to `on_exit`.

**Comment by crsh** [comment]
Hi @karchjd, thanks for the example and sorry for the delay. I'm sorry to report that I cannot reproduce the problem with the files you attached to your last post; the original `paper.Rmd` is restored and `cGFwZXIuUm1k.Rmd`is deleted automatically. Just to be sure, could you retry after reinstalling the latest development version?

~~~r
remotes::install_github("crsh/papaja@devel")
~~~
