### ISSUE TITLE
maybe add cache = FALSE to the render_appendix chunk

### ISSUE THREAD

**Issue by bnicenboim** [crsh/papaja#323]
**Is your feature request related to a problem? Please describe.**
It took me a while to realize why my appendix wasn't changed, even if the chunks inside had cache = FALSE. 

**Describe the solution you'd like**
I would change the default cache to FALSE for the render appendix chunk

**Describe alternatives you've considered**
Or to remind the user that the entire appendix is cached, when papaja renders a document with an appendix.

(I can do any of these two changes myself and do a pull request).

**Additional context**

**Comment by bnicenboim** [comment]
yes, I guess you're right. I just got confused because even when I changed the chunks inside the appendix file, the pdf didn't change. And that was because the default state for the cache in chunk that contained `render_appendix` was TRUE when it's left implicit.

I was just suggesting to add :
`{r echo = FALSE, results = 'asis', cache = FALSE}`

because it was confusing the the default cache would affect to the entire appendix. But you can also feel free to ignore this.

**Comment by crsh** [comment]
No, I think this makes a lot of sense; thanks for the suggestion. I'd be more than happy to accept a PR!
