### ISSUE TITLE
apa_print produces no table for t-tests

### ISSUE THREAD

**Issue by Kalif-Vaughn** [crsh/papaja#324]
**PROBLEM**
When using apa_print on t-tests, it does not store any information as a table (NULL).

**REQUEST**
Store table information for t-tests. This will enable use of apa_table to combine multiple t-tests into one table.

**FINAL THOUGHT**
Thank you for all of this - you are a legend.

**Comment by crsh** [comment]
Hi Kalif, thanks for the suggestion. I think that would make a lot of sense both for practicle reasons and for consistency of the output. I'll try to implement this the next chance I get.

**Comment by Kalif-Vaughn** [comment]
Thank you, crsh! And thanks again for all your hard work on this package - it's the best!

**Comment by crsh** [comment]
Thanks for the kind words! 😊
