### ISSUE TITLE
Feature Request: Print bib files in APA style needed

### ISSUE THREAD

**Issue by jooyoungseo** [crsh/papaja#327]
Hello,

This is a feature request.

I was wondering if anyone could develop a function that prints a given bib file in APA6 style.

While writing a CV using R Markdown, I found some needs to insert my publications in accordance with APA guidelines.

Let's say you have two sections under publications like below:

```
# Publications

## Refereed Journal Papers

[journal list goes here.]

## Papers in Refereed Conference Proceedings

[proceeding list goes here.]
```

What would be the best way to automatically insert bib entries in APA style there?

I found [`RefManageR:::print.BibEntry()`](https://www.rdocumentation.org/packages/RefManageR/versions/1.2.12/topics/print.BibEntry) function; however, the printed output does not align with APA6 style.

There seems a way to tweak the printed bib.style according to [this issue](https://github.com/ropensci/RefManageR/issues/26); however, this work goes beyond my knowledge.

It would be greatly appreciated if `papaja` can implement this function so that anyone who needs to insert their bib files in APA style conveniently.

Many thanks.

**Comment by crsh** [comment]
Hmm, this is beyond the scope of `papaja`. I have only ever done this using LaTeX within R Markdown documents, e.g. (`\printbibliography[title="Proceedings\label{proceedings}",heading=subbibliography,keyword=proceedings]`). This requires setting the `keyword`-field in the bib-file and inclusion of something like the following in the preamble:

~~~latex
%% Set up bibliographies
\usepackage[backend=biber,style=apa,sortcites=true,sorting=ymdnt,uniquename=false]{biblatex}
\DeclareLanguageMapping{american}{american-apa}

\bibliography{bibliographies/paper.bib}
\addbibresource{bibliographies/proceedings.bib}
~~~
