### ISSUE TITLE
Update to APA 7?

### ISSUE THREAD

**Issue by QueenJanine** [crsh/papaja#328]
Hi Frederik, great work on the package - thank you! Are you planning on incorporating the [APA 7 guidelines](https://apastyle.apa.org/products/publication-manual-7th-edition/) anytime soon?

**Comment by crsh** [comment]
Yes, this is definitely planned. I'll look into this more closely as soon as I get my hands on a copy of the manual (anyone at APA willing to donate a copy?).

**Comment by jrennstich** [comment]
First of all thank you so much for this wonderful package. I use it now pretty much for all of my drafts. I received the new APA 7 Manual in yesterday's mail. So here are two issues I would like to raise:

# STYLE
## Levels of Headings
The style guidelines note the following five levels of heading in APA style: 

L1 = Centered, Bold, Title Case Heading [begins with new paragraph]
L2 = Flush left, Bold, Title Case Heading [begins with new paragraph]
L3 = Flush left, Bold Italic, Title Case Heading [begins with new paragraph]
L4 = Indented, Bold, Title Case Heading, Ending with a Period. [begins on same line and continues as a regular paragraph]
L5 = Indented, Bold Italic, Title Case Heading, Ending with a Period. [begins on same line and continues as a regular paragraph]

When I currently render documents using `output            : papaja::apa6_pdf` I get the following results (see attached [Test.pdf](https://github.com/crsh/papaja/files/3863180/Test.pdf)):

L1 = **Centered, Bold, Title Case Heading** [begins with new paragraph] > CORRECT
L2 = **Flush left, Bold, Title Case Heading** [begins with new paragraph] > CORRECT
L3 = **Indented, Bold, Title Case Heading, Ending with a Period.** [begins on same line and continues as a regular paragraph] > NOT CORRECT; this resembles the correct version of what should be L4; should be same as L2 only in **_bold-italic_**.
L4 = **Indented, Bold, Title Case Heading, Ending with a Period.** [begins new paragraph] > NOT CORRECT, the new paragraph is wrong, shouldn't be italic.
L5 = Indented, Title Case Heading, Ending with a Period. [begins new paragraph] > NOT CORRECT, the new paragraph is wrong, should be bold-italic, no new paragraph.

**QUESTION 1**: Would it be possible to fix this? Especially the incorrect new paragraphs make the whole document very messy.

## Author Note 
The Manual for APA 7 recommends the following for the author note (see attached [Test.pdf](https://github.com/crsh/papaja/files/3863180/Test.pdf)):

1. paragraph: ORCID iDs
2. paragraph: Change of Affiliation.
3. paragraph: Disclosures and Acknowledgments (1 - Study Registration; 2 - Open Practices and Data Sharing; 3 - Acknowledgments of Financial Support and Other Assistance)
4. paragraph: Contact Information: Correspondence concerning this article should be addressed to [author's name], [complete mailing address]. Email: author@institution.edu

APA recommends the use of the ORCID iD icon. This can be [downloaded](https://orcid.org/trademark-and-id-display-guidelines) from the ORICD website.

**QUESTION 2**: Would it be possible to make the according changes in the template? I don't think it's possible to make use of [ai Icons](https://jpswalsh.github.io/academicons/) using the [`icon` package](https://github.com/ropenscilabs/icon/), so I simply used the provided 16x16 .png file. Perhaps it would be helpful to insert the following lines in the template:

```
authornote: |
  Author ![](img/orcid.png) [https://orcid.org/XXX](https://orcid.org/XXX).
  CHANGE_OF_AFFILIATION
  DISCLOSURES_ACKNOWLEDGEMENTS_(1 - Study Registration; 2 - Open Practices and Data Sharing; 3 - Acknowledgments of Financial Support and Other Assistance)
  <add here the existing code that you currently use to create the Contact Information>
```
Something along those lines. 

The ORCID logo solution isn't pretty. If there's a way to make it work with [Academicons](https://jpswalsh.github.io/academicons/) that would be far superior. Or use a more high-resolution .png file version and scale it down?

Again, thanks for you great service to the academic community here!

**Comment by crsh** [comment]
Hi Joachim, thanks for the analysis and feedback. If you find anything else please feel free to add it here.

The problem with level 4 headings has been raised before [here](https://github.com/crsh/papaja/issues/284) and [here](https://github.com/crsh/papaja/issues/292) and it is indeed an issue with `papaja` (or rather the `pandoc` conversion of headings). I simply haven't found the time to look into it further. I'll try to look into it as soon as possible.

Similarly, I'll need to see whether the issues regarding the other headings you identified are related to `papaja`/`pandoc` or the underlying `apa6`-LaTeX document class. If the latter is the case, the issue would be most aptly addressed in the LaTeX class.

The inclusion of ORCIDs has also been suggested [before](https://github.com/crsh/papaja/issues/282) but now that the new manual requires inclusion and specifies how to do it, I'd be ready to tackle soon. I think your solution is what would be required for Word documents, in LaTeX documents the tikz approach mentioned in the other issue could be used.

**Comment by jrennstich** [comment]
Thanks for your quick reply and looking into this. The `tikz` solution looks great, especially the second one.

**Comment by benediktclaus** [comment]
Great to hear that the implementation of the 7th edition is underway! Just so you know, Daniel Weiss recently published a sort of updated apa6 LaTeX package: apa7 (https://ctan.org/pkg/apa7). This should take some work off of your shoulders.

**Comment by crsh** [comment]
Excellent. Thank you for bringing this to my attention. If you have an urgent need for APA 7th, you could try using `apa7` with the following YAML setting (assuming you installed the LaTeX package):

~~~yaml
documentclass     : "apa7"
~~~

I'd be interested to hear if that works for you or what problems you are seeing.

**Comment by jrennstich** [comment]
Would love to try it. For some reason I now get the following error for all my papaja docs:
```
Error in rmdfiltr::add_wordcount_filter(args, report = "warn") : 
  unused argument (report = "warn")
Calls: <Anonymous> -> <Anonymous> -> pdf_pre_processor
```
This is true even for brand-new created docs. Any suggestions?

**Comment by jrennstich** [comment]
> Excellent. Thank you for bringing this to my attention. If you have an urgent need for APA 7th, you could try using `apa7` with the following YAML setting (assuming you installed the LaTeX package):
> 
> ```yaml
> documentclass     : "apa7"
> ```
> 
> I'd be interested to hear if that works for you or what problems you are seeing.
So just to be clear, the following line stays the same?

```output            : papaja::apa6_pdf    # pdf or word```

or is it

```output            : papaja::apa7_pdf    # pdf or word```

**Comment by crsh** [comment]
You need to keep using `output : papaja::apa6_pdf` for now.

> For some reason I now get the following error for all my papaja docs

Could you try updating `rmdfiltr` and reintall `papaja` from the development branch (`devtools::install_github("crsh/papaja@devel")`)?

**Comment by jrennstich** [comment]
Thanks for the quick reply. Did as suggested. Now I get the new following error msg:
```
/usr/local/bin/pandoc +RTS -K512m -RTS Digitalkompetenz_PB.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash+raw_attribute --output Digitalkompetenz_PB.tex --self-contained --highlight-style tango --pdf-engine pdflatex --include-in-header /Library/Frameworks/R.framework/Versions/3.6/Resources/library/papaja/rmarkdown/templates/apa6/resources/apa6_header_includes.tex --variable graphics --lua-filter /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rmarkdown/rmd/lua/latex-div.lua --wrap preserve --csl /Library/Frameworks/R.framework/Versions/3.6/Resources/library/papaja/rmd/apa6.csl --filter /usr/local/bin/pandoc-citeproc --lua-filter /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rmdfiltr/replace_ampersands.lua --lua-filter /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rmdfiltr/wordcount.lua --variable 'classoption:man' 'classoption:a4paper' --variable 'lang:de-DE' --include-in-header /var/folders/hh/vy5948dx2jv2v9qc_m2tbrx00000gn/T//RtmpPj6dGf/includes_5ecc19a846ad.tex --filter /usr/local/bin/pandoc-citeproc 
pandoc: classoption:a4paper: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1
```
Working on MacOS 10.15.2 (19C57).

**Comment by jrennstich** [comment]
> Excellent. Thank you for bringing this to my attention. If you have an urgent need for APA 7th, you could try using `apa7` with the following YAML setting (assuming you installed the LaTeX package):
> 
> ```yaml
> documentclass     : "apa7"
> ```
> 
> I'd be interested to hear if that works for you or what problems you are seeing.

Works nicely here (except for the problems described above). Most importantly, the previous formatting/style errors I had (reported above) are fixed using `apa7`. All headlines are now formatted as they should be, as far as I can tell. Bibliography is not conforming to APA 7 style, though. Publication places are still being used, for example.

**Comment by crsh** [comment]
Thanks, I'll look into it.

For APA 7th citations, you need to manually [specify](https://crsh.github.io/papaja_man/r-markdown-components.html#rendering-options) an updated CSL file, which is available form this repository: https://www.zotero.org/styles?q=apa

**Comment by crsh** [comment]
Would you mind opening a new issue for the `apa6_word()` problem with a minimal reproducible example?

**Comment by jrennstich** [comment]
> Thanks, I'll look into it.
> 
> For APA 7th citations, you need to manually [specify](https://crsh.github.io/papaja_man/r-markdown-components.html#rendering-options) an updated CSL file, which is available form this repository: https://www.zotero.org/styles?q=apa

I did that. But the info in the YAML header gets ignored for some reason. I added:

`csl               : ["apa7.csl"]` 

and the `csl` file in the same folder to no avail. When using a wrong file name reference there was no difference. It still used apa regardless.

**Comment by jrennstich** [comment]
> Really appreciate your input and feedback! Would you mind opening a new issue for the `apa6_word()` problem with a minimal reproducible example?

When I tried, I actually could create a Word document. But then discovered a different issue: the references are listed twice. No idea why. This happens for both, PDF and Word and with `apa6`. Will try to create that error in minimal rep example. Should I open a different issue for the problem I just described?

[Example_apa7.docx](https://github.com/crsh/papaja/files/4042916/Example_apa7.docx)
[Example_apa7.pdf](https://github.com/crsh/papaja/files/4042917/Example_apa7.pdf)
[Example_apa7.Rmd.txt](https://github.com/crsh/papaja/files/4042922/Example_apa7.Rmd.txt)

**Comment by crsh** [comment]
I think what you are experiencing is the issue described in https://github.com/crsh/papaja/issues/338

**Comment by crsh** [comment]
Thanks for the MWE! I think I found the culprit that was causing the problems with specifying a custom CSL file. I just pushed the commit. Let me know if it works for you, too.

**Comment by crsh** [comment]
For further discussion on APA 7th edition, please go to https://github.com/crsh/papaja/issues/342

**Comment by crsh** [comment]
Closing in favor of #342.
