### ISSUE TITLE
Rescaling of tables to fit the page

### ISSUE THREAD

**Issue by ccobserver** [crsh/papaja#33]
I'm having trouble with getting tables to be rescaled to fit the page. Below is the table I'm using (and I've also tried using the xtable and ztable packages as well as basic markdown tables):

\begin{table}[htbp]
    \center
    \caption{Original DAST-10}
    \label{table1}
    \begin{tabular}{cl}
        \toprule
          & Item\\
        \toprule
        1 & Have you used drugs other than those required for medical reasons?\\
        2 & Do you use more than one drug at a time?\\
        3 & Are you always able to stop using drugs when you want to? (-)\\
        4 & Have you ever had blackouts or flashbacks as a result of drug use?\\
        5 & Do you ever feel bad or guilty about your drug use?\\
        6 & Does your spouse (or parents) ever complain about your involvement with drugs?\\
        7 & Have you neglected your family because of your use of drugs?\\
        8 & Have you engaged in illegal activities in order to obtain drugs?\\
        9 & Have you ever experienced withdrawal symptoms (felt sick) when you stopped taking drugs?\\
        10 & Have you had medical problems as a result of your drug use (e.g., memory loss, hepatitis, convulsions, bleeding)?\\
        \bottomrule
    \end{tabular}
\end{table}

**Comment by crsh** [comment]
This is a question concerning LaTex rather than `papaja` (although it points me towards an interesting idea to improve the `apa_table`-function).

`tabularx` shiould do what you want:

    \begin{table}[htbp]
    \center
    \caption{Original DAST-10}
    \label{table1}
    \begin{tabularx}{\textwidth}{cX}
    \toprule
    & Item \\
    \midrule
    1 & Have you used drugs other than those required for medical reasons? \\
    2 & Do you use more than one drug at a time?\\
    3 & Are you always able to stop using drugs when you want to? (-)\\
    4 & Have you ever had blackouts or flashbacks as a result of drug use?\\
    5 & Do you ever feel bad or guilty about your drug use?\\
    6 & Does your spouse (or parents) ever complain about your involvement with drugs?\\
    7 & Have you neglected your family because of your use of drugs?\\
    8 & Have you engaged in illegal activities in order to obtain drugs?\\
    9 & Have you ever experienced withdrawal symptoms (felt sick) when you stopped taking drugs?\\
    10 & Have you had medical problems as a result of your drug use (e.g., memory loss, hepatitis, convulsions, bleeding)?\\
    \bottomrule
    \end{tabularx}
    \end{table}
