### ISSUE TITLE
printp() is missing NA escape

### ISSUE THREAD

**Issue by jadenecke** [crsh/papaja#330]
**Describe the bug**
The validate part of printp() is missing check_NA = FALSE flag.

**To Reproduce**
printp(NA)

**Expected behavior**
return na_string from printnum()

**Comment by crsh** [comment]
Hi there and thanks for reaching out. Have you tried the development version (`devtools::install_github("crsh/papaja@devel")`)? I think, I have already [fixed it](https://github.com/crsh/papaja/blob/346e37b7e16c1186f8899c01b4961acf46b1914a/R/printnum.R#L379) there.

**Comment by jadenecke** [comment]
seems so, thanks!
