### ISSUE TITLE
Adding a note to markdown table (similar to caption)

### ISSUE THREAD

**Issue by jrennstich** [crsh/papaja#331]
I understand that it is possible to add notes to tables created using the `apa_table` command:
```
apa_table(
  descriptives
  , caption = "Descriptive statistics of correct recall by dosage."
  , note = "This table was created with apa_table()"
```

I would like to add notes to tables I created as part of my regular markdown script, say:
```
Table: Some header (#tab:label)
| Title1  | Title 2 |
|:--------|:-------:|
|Item1    | Task 1  |
```

Is this possible? I haven't been able to find that option in [`Bookdown`](https://github.com/rstudio/bookdown/issues/821) or in the description here. Using a footnote at the end of the table caption doesn't work either and would only be a crude workaround anyway (but still).

Thanks in advance for addressing this question!

**Comment by crsh** [comment]
Have you tried specifying the `format`?

~~~r
apa_table(
  descriptives
  , caption = "Descriptive statistics of correct recall by dosage."
  , note = "This table was created with apa_table()"
  , format = "pandoc"
)
~~~
~~~
*A summary table of the cars dataset.*
          Mean      SD    Min  Max    
------  ------  ------  -----  -------
speed    15.40    5.29   4.00  25.00  
dist     42.98   25.77   2.00  120.00 

<center>
*Note.* Test
</center>
~~~

**Comment by jrennstich** [comment]
Sorry, I was unclear. I meant, I want to draft a table using markdown instead of generating a table using apa_table and then some data.

**Comment by crsh** [comment]
I see, and I assume you would like those table to, for example, float at the end in PDF manuscripts?

**Comment by jrennstich** [comment]
Exactly!

**Comment by crsh** [comment]
Gotcha. I'm not sure this is possible, unfortunately. What you would want to look into is the [`pandoc` table syntax](https://pandoc.org/MANUAL.html#tables) and extensions thereof. I don't think this is possible out of the box, but there may be a `pandoc` extension somewhere that can do this. If you find something useful, let me know.

I'm closing the issue for now because it is not related to `papaja` in the strict sense.
