### ISSUE TITLE
number_section starts with abstract (again)

### ISSUE THREAD

**Issue by tcgriffith** [crsh/papaja#332]
**Describe the bug**

`number_section: true` started the numbering from the abstract. Related issue: #85 but judging from the option name it seems to be quite outdated.

**To Reproduce**

[example rmd](https://raw.githubusercontent.com/tcgriffith/cosx_exps/master/test115.Rmd)

**Expected behavior**

do not start numbering from the abstract?

**Screenshots**

NA

**Additional context**

NA

**Comment by crsh** [comment]
Hi TC,

thanks for bringing this to my attention. For a quick fix, use `\setcounter{secnumdepth}{5}` at the beginning of your document instead of setting the `numbersections` or the `number_sections` argument of the output format in the YAML front matter. I'll try to fix this as soon as possible.

**Comment by crsh** [comment]
This should now be fixed on the development branch (`devtools::install_github("crsh/papaja", ref = "devel")`).

**Comment by tcgriffith** [comment]
Many thanks!
