### ISSUE TITLE
Feature Request: supporting rstatix::anova_test() in papaja::apa_print()

### ISSUE THREAD

**Issue by jooyoungseo** [crsh/papaja#337]
[`rstatix::anova_test()`](https://rpkgs.datanovia.com/rstatix/reference/anova_test.html) is a very convenient function when performing any kinds of `anova` test designs.

I was wondering if there would be any way for [`papaja::apa_print()`](https://www.rdocumentation.org/packages/papaja/versions/0.1.0.9842/topics/apa_print.aov) function to support [`rstatix::anova_test()`](https://rpkgs.datanovia.com/rstatix/reference/anova_test.html) objects so that users can easily create well-formatted anova stats and table in accordance with APA guideline.

@kassambara, would you mind supporting [`papaja::apa_print()`](https://www.rdocumentation.org/packages/papaja/versions/0.1.0.9842/topics/apa_print.aov) collaboratively?

**Comment by crsh** [comment]
This looks interesting. We currently have a feature hold leading up to the (eventual) CRAN release, but this may be worth considering for a future release. A couple of thoughts:

- The internal workflow of the `apa_print()` methods heavily relies on `broom`. If `rstatix`-output is `broom`-able this would simplify things a lot.
- For ANOVA specifically, we support `afex`-output, a package that similarly provides wrappers for ANOVA. From skimming the code, it looks like `rstatix`, like `afex` uses`car::Anova`. If the corresponding objects are similarly available from the output it may be easy to add support for this particular analysis model.

**Comment by crsh** [comment]
Given that this issue has been stale for a long time, I will close it. If there is continued interest, we are happy to review a PR or reopen the discussion.
