### ISSUE TITLE
`header_includes:` for some reason doesn't work.

### ISSUE THREAD

**Issue by agricolamz** [crsh/papaja#339]
`header_includes:` for some reason doesn't work. Here is a [minimal example](https://gist.github.com/agricolamz/de8b6a69b0b8d63d74146af8ebb6a210).

I expected that `header_includes: - \setmainfont{Brill}` will add `\setmainfont{Brill}` to the `.tex` preamble.

Result:
![image](https://user-images.githubusercontent.com/15956515/71541734-a9322a80-296e-11ea-9e84-fc42b70d2d2f.png)

Expected:
![image](https://user-images.githubusercontent.com/15956515/71541751-cf57ca80-296e-11ea-9837-f93802f2bead.png)

<details>

```
> packageVersion("papaja")
[1] ‘0.1.0.9842’
> sessionInfo()$R.version$version.string
[1] "R version 3.6.2 (2019-12-12)"
> sessionInfo()$platform
[1] "x86_64-pc-linux-gnu (64-bit)"
```

</details>

**Comment by crsh** [comment]
Could you retry after installing the latest development version (`devtools::install_github("crsh/papaja@devel")`), unless you are already using it?

**Comment by agricolamz** [comment]
No change... After I install it it is the same version as in my example (Did you clicked on detail button?)

```
packageVersion("papaja")
[1] ‘0.1.0.9842’
```

**Comment by crsh** [comment]
I'll try to look into this more closely as soon as possible. In the meantime, just to clarify: I'm not too diligent about bumping the version number with every commit on the development branch. Did you try to knit again or did you just inspect the version number?

**Comment by agricolamz** [comment]
Thank you! Yes, I ran `devtools::install_github("crsh/papaja@devel")` before posting.

**Comment by crsh** [comment]
Hi George, thanks for the MWE. I think problem is a typo. I'm currently having some trouble rendering the knitted TeX document to PDF (something with my LaTeX distribution), so I wasn't able to ultimately confirm that it works, but the header includes end up in the TeX file.

Try the following:

~~~yaml
header-includes:
    - \setmainfont{Brill}
~~~ 

(dash instead of underscore)

**Comment by agricolamz** [comment]
You are right... Thank you!
