### ISSUE TITLE
Feature request: supporting flextable object in apa_table

### ISSUE THREAD

**Issue by jooyoungseo** [crsh/papaja#344]
[flextable](https://github.com/davidgohel/flextable) seems very promising especially for creating tables in word document.

It would be so nice if `papaja::apa_table()` can support `flextable` object to tackle some limited support for docx table in `knitr::kable` and `kableExtra`.

**Comment by crsh** [comment]
`flextable` looks really nice. But I'm not quite sure what you are proposing. If `flextable` can create tables for Word documents, why is there a need to use `apa_table()` with `flextable`? From what I understand, `flextable` is an alternative to `apa_table()`, no?
