### ISSUE TITLE
rmdfiltr::add_wordcount_filter throws an error in APA template

### ISSUE THREAD

**Issue by LGurtner** [crsh/papaja#345]
Hello, 
I don't know if this belongs here but when I try to knit the APA 6th edition template without changing anything in it, the execution is halted after the .knit.md file is processed with the following error message: 

> Error in rmdfiltr::add_wordcount_filter(args, report = "warn") : 
  unused argument (report = "warn")
Calls: <Anonymous> -> <Anonymous> -> pdf_pre_processor
Execution halted

I run on an older R version (3.5.2), however the exact same error also appears on a windows computer with the latest R version. If I knit pdfs from other templates (such as one of the rticles templates) everything goes as it should. Do you have any idea why this happens in papaja and how to fix it? 
Any thoughts are appreciated, thank you!

Here is my session info: 
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.2    tufte_0.5         htmltools_0.4.0   tools_3.5.2       yaml_2.2.0       
 [6] Rcpp_1.0.3        rmarkdown_2.0     papaja_0.1.0.9842 knitr_1.27        xfun_0.12        
[11] digest_0.6.23     packrat_0.5.0     thesisdown_0.0.2  rlang_0.4.2       evaluate_0.14    
>

**Comment by crsh** [comment]
Is this the same problem as https://github.com/crsh/rmdfiltr/issues/5?

**Comment by LGurtner** [comment]
Hey, it's not the exact same error message but installing the development version of papaja `devtools::install_github("crsh/papaja@devel")` fixed it anyway... Thank you for the answer and the great package, it really makes life a lot easier!
