### ISSUE TITLE
Caption/reference not rendering for kable(format = "markdown") tables

### ISSUE THREAD

**Issue by mpjashby** [crsh/papaja#347]
**Describe the bug**

Using `papaja` 0.1.0.9942 in R 3.6.1, markdown text inside tables produced with `knitr::kable()` is not processed. This can be dealt with by specifying `knitr::kable(format = "markdown")` but doing so means the table can no longer be referenced using the `\@ref(tab:chunk-name)` format and the table caption is no longer displayed.

**To Reproduce**

    ---
    title: "Test article"

    author:
      - name: "Author"
        affiliation: "1"
        corresponding: yes
        address: "Address"
        email: "email@domain"

    affiliation:
      - id: "1"
        institution: "University"

    floatsintext: yes

    documentclass: "apa6"
    classoption: "man"
    output: papaja::apa6_pdf
    ---

    ```{r setup, include=FALSE}
    library("bookdown")
    library("papaja")
    library("tibble")

    knitr::opts_chunk$set(echo=FALSE)
    ```

    ```{r create-table}
    methods_table <- tribble(
        ~"method", ~"description",
        "a method", "a description containing some *markdown* formatting",
        "another method", "another description"
    )
    ```

    With the following code we can reference Table \@ref(tab:methods) and see its
    caption, but the markdown in the table will not be parsed and the table does
    not follow the expected `booktabs` formatting:

    ```{r methods}
    knitr::kable(methods_table, caption = "A table")
    ```

    Whereas with this code, we cannot reference Table \@ref(tab:methods2) but the
    table markdown is parsed correctly and the table appears as we would expect with
    `booktabs`:

    ```{r methods2}
    knitr::kable(methods_table, format = "markdown", caption = "Another table")
    ```

Produces:

<img width="668" alt="Screenshot 2020-01-30 at 19 20 19" src="https://user-images.githubusercontent.com/3823535/73482431-a7a4b980-4395-11ea-9198-d57c63826b49.png">

**Expected behavior**

Running the same code as above but replacing the YAML header with:

    ---
    title: "Test article"
    output: pdf_document
    ---

and not loading `bookdown` and `papaja` in the first chunk gives a different behaviour: markdown formatting is now processed in both tables and both have a `booktabs`-like appearance, but the caption is still not shown in the second.

<img width="669" alt="Screenshot 2020-01-30 at 19 34 37" src="https://user-images.githubusercontent.com/3823535/73483611-9f4d7e00-4397-11ea-9d18-19cba01530db.png">

**Comment by crsh** [comment]
Hi Matt, I finally found some time to follow up on this; the second approach in your document works for me. Specifically, the following renders correctly and also lets me cross-reference the table.

~~~r
knitr::kable(methods_table, format = "markdown", caption = "Another table")
~~~

Other formats (e.g., `pipe` or `simple`) also work for me. Are you still experiencing this issue?
