### ISSUE TITLE
Change directory of _files folder?

### ISSUE THREAD

**Issue by sakritz** [crsh/papaja#348]
I was wondering if there is a way to change the directory and name of the "mydocument_files" folder.
I usually have a data structure with an output folder in which all created figures and tables are to be saved. Is there a way to tell rmarkdown/papaja to save the figures there instead of creating a new folder?

**Comment by crsh** [comment]
Hi there, this question is not directly related to `papaja` but applies to `rmarkdown` documents more generally. I currently don't have the capacity to answer questions about `rmarkdown`. Please consider asking this question on StackOverflow. Thank you.
