### ISSUE TITLE
Removing $ from confidence intervals in tables

### ISSUE THREAD

**Issue by Kalif-Vaughn** [crsh/papaja#349]
**Problem**
I cannot remove the "$" symbols from the tables generated in regression analyses following apa_print. I am creating a custom table using the rbind command to merge multiple regression tables into one, then I am using the apa_table command to display it. When I do that, the printed table always has the confidence intervals surrounded by '$' symbols. I want them to display without the '$' symbols.

**Things I have tried**
I notice that if I use the "apa.reg.table" command in apaTables, the confidence intervals are displayed correctly. But I prefer the tables generated via apa_print. I've tried using commands like "paste0" and "str_replace_all" to change the "$" to "", but it doesn't work. I've also tried using the "print(tableHere, use_math=FALSE)", but that does not work either. 

Thanks for any help!

**Comment by crsh** [comment]
Hi there, have you tried setting `escape = FALSE`?

**Comment by Kalif-Vaughn** [comment]
That was exactly what I needed - thank you!
