### ISSUE TITLE
Issue with umlaut in the author name

### ISSUE THREAD

**Issue by arcaldwell49** [crsh/papaja#350]
**Describe the bug**
The use of an umlaut in the author names now produces an error.

The error message looks like the code below

`! Misplaced alignment tab character &.
\@author ->Dani&
                euml;l`

**To Reproduce**
In the header this will produce the error
`author: `
`          - name          : "Dani&euml;l"`

**Expected behavior**
It should produce Dani&euml;l on the author line but instead throws and error. In older versions of the package it works (it works on my old laptop), but now it produces this error

**Additional context**
This is a rather minor problem, but since special characters, such as an umlaut, are in people's names I think may be worth investigating

**Comment by crsh** [comment]
Hi Aaron, thanks for reaching out. The error you get is from LaTeX. In LaTeX `&` is a syntax character and it misinterprets the HTML entity you pass. I'm on the go, but here are two things you could try:

1. Ensure that your R Markdown file is UTF-8 encoded, put in `"Daniël"` and change the LaTeX backend to [XeLaTeX](https://bookdown.org/yihui/rmarkdown/pdf-document.html#advanced-customization-1).
2. Use the correct LaTeX syntax: `Dani\"{e}l`

**Comment by ipessien** [comment]
Hi all,
After installing R, RStudio, and papaja fresh, I encountered a very similar issue. Although my RMarkdown file is UTF-8 encoded, it produces the following error:

> pandoc.exe: Cannot decode byte '\xe4': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

The YAML front matter included German umlauts ("ä" in name affiliation, id institution, and author note). Only after deleting all umlauts from the yaml front matter, it was possible to compile the document.

**Comment by arcaldwell49** [comment]
>     2\. Dani\"{e}l

Alright, I tried Dani\"{e}l

` - name          : "Dani\{"e}l"`

But, this produces Dani"el on the author line of the PDF.

Any ideas?

**Comment by crsh** [comment]
Did you also try `Dani\"{e}l`?

**Comment by arcaldwell49** [comment]
Yes, same result

**Comment by crsh** [comment]
Hmm, I need to find a Windows computer to take a closer look.

On MacOS, the following works for me to put diaeresis in author names:

~~~yaml
author: 
  - name          : "Daniël"
~~~

Have you tried this (with XeLaTeX) on Windows?

~~~yaml
output:
  papaja::apa6_pdf:
    latex_engine: xelatex
~~~

Also this worked for me (note the `' `):

~~~yaml
author: 
  - name          : 'Dani\"{e}l'
~~~

**Comment by arcaldwell49** [comment]
Okay, the single `'`  did the trick! However, I am curious as to why this worked, and what changed in the package to start causing this error?

**Comment by crsh** [comment]
I'm not sure, I need to do a some more digging, but I won't get around to it any time soon, I'm afraid.

**Comment by tdienlin** [comment]
Hi all, can only confirm that I'm having the same problem. My coauthor uses a MAC, there the code works. I'm using a PC, here, the Umlaute are causing the same problems ("pandoc.exe: Cannot decode byte '\xe4': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream"). Although I'm following this thread, I didn't realize that I'm having the exact same problem, took me some time to realize that the problem is in the YAML header ... So to me it seems this isn't a minor thing, but a more general & relevant problem?

**Comment by jadenecke** [comment]
Also the workaround does not work consistently: using {\ss} works fine the the authors name and prints ß, but in the address field 'Hamburger Stra{\ss}e' just renders as Hamburger Stra{\ss}e

With single '

**Comment by crsh** [comment]
I just pushed a first attempt to fix this this (for now this only works for PDF output). With this fix you should be able to just add special characters in plain text (e.g. `"Daniël"`), but (for now) it requires that raw LaTeX is marked up as such (e.g., <code>"Dani\`\\"{e}\`{=latex}l"</code>; I'll try to restore the previous behavior).

Try installing the latest development version (`remotes::install_github("crsh/papaja@devel")`) and let me now if it works.
