### ISSUE TITLE
Typo in description?

### ISSUE THREAD

**Issue by customcommander** [crsh/papaja#355]
At time of writing the short description for this project reads:

> papaja (Preparing APA Journal Articles) is an R package that provides document formats to produce complete APA manscripts from RMarkdown-files (PDF and Word documents) and helper functions that facilitate reporting statistics, tables, and plots. https://crsh.github.io/papaja_man/

Did you mean "manuscripts" instead of "manscripts"?

**Comment by crsh** [comment]
Good catch. Thanks, I updated the repository description.
