### ISSUE TITLE
References being duplicated in knitted pdf

### ISSUE THREAD

**Issue by swirvi** [crsh/papaja#356]
I cannot figure out what is happening in the papaja template I am using in R Markdown that is causing the references to be duplicated.  Has anyone come across this issue and know how to fix it?  Thanks.
[Annotated-Bibliography.pdf](https://github.com/crsh/papaja/files/4240504/Annotated-Bibliography.pdf)

**Comment by swirvi** [comment]
After more research, I have seen that other had the same issue and there was a fix for it, but I am a beginner and don't understand what I need to do to correct the issue.  Can someone explain me to simple terms please?  Thanks.

**Comment by mariusbarth** [comment]
Hi Shaun, I think you mean #338, right? For beginners, I think the following code should now fix the problem:
```
update.packages(ask = FALSE)
devtools::install_github("crsh/papaja@devel")
```
Please let me know if this worked for you.

**Comment by lnalborczyk** [comment]
I have the same issue... installing the development version of papaja lead to the new following error: `! LaTeX Error: There's no line here to end.`

Any idea?

**Comment by tdienlin** [comment]
I'm not sure as to whether I'm mistaken this with another similarly phrased error message, but it might be that you simply need to delete (or potentially add) the last line of your ms.

**Comment by crsh** [comment]
> installing the development version of papaja lead to the new following error: `! LaTeX Error: There's no line here to end.`
> 
> Any idea?

Not without a minimal reproducible example, I'm afraid. For what it's worth, the duplicated references should also be fixed on the master branch.

**Comment by swirvi** [comment]
Thank you!  It's working for me now.  For the other people who commented, just go back and re-install the master papaja.  After I did that, no more duplicates...

devtools::install_github("crsh/papaja")

**Comment by lnalborczyk** [comment]
> > installing the development version of papaja lead to the new following error: `! LaTeX Error: There's no line here to end.`
> > Any idea?
> 
> Not without a minimal reproducible example, I'm afraid. For what it's worth, the duplicated references should also be fixed on the master branch.

Hi Frederik, thank you for your prompt reply, and my apologies for not being able to provide a reproducible example. I was working on a paper that was being knitted well before updating to the last version of the package, but suddenly started to throw out this error after updating (for information, the error in my case came from a clash between this new version of `papaja` and some latex packages I am loading using `header-includes`)...

Anyway, the last version of `papaja` fixes the duplicate issue for me too, thank you.

**Comment by crsh** [comment]
Great, thanks for letting me know. Feel free to reopen if you continue to see problems.
