### ISSUE TITLE
Pandoc in papaja won't decode byte \xc6

### ISSUE THREAD

**Issue by dcbrh** [crsh/papaja#357]
Hello!

When I insert a character such as "ć" in the _author_  or _affiliation_ part of the yaml header, I get the following error:

`pandoc.exe: Cannot decode byte '\xc6': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 1`

No problem whatsoever when "ć" is in the abstract or in the body of the text.
I tried to get around the problem by using latex code for "ć", that is
`\\'{c}`

That solves the problem for the author's name and affiliation, but `\\'{c}` is not rendered as "ć" in the correspondence.

![image](https://user-images.githubusercontent.com/32776998/75580213-a8e60680-5a67-11ea-87c4-7cf9e7993a64.png)

It seems that different parts of the document use different text encoding....

**Comment by crsh** [comment]
Hi there, I think this is related to https://github.com/crsh/papaja/issues/350. This is top priority and I'll try to look into it as soon as possible.

**Comment by docep** [comment]
Thanks, that sounds great. I will take a look at #350

**Comment by crsh** [comment]
I just pushed a first attempt to fix this this (for now this only works for PDF output). With this fix you should be able to just add special characters in plain text (e.g. `"Daniël"`), but (for now) it requires that raw LaTeX is marked up as such (e.g., <code>"Dani\`\\"{e}\`{=latex}l"</code>; I'll try to restore the previous behavior).

Try installing the latest development version (`remotes::install_github("crsh/papaja@devel")`) and let me now if it works.
