### ISSUE TITLE
How to use single quotation as well as double quotation marks in the pdf output?

### ISSUE THREAD

**Issue by koliajay** [crsh/papaja#363]

**Comment by crsh** [comment]
Hi, could you provide a little more context for your question? What exactly do you want to achieve and what have you tried?

**Comment by koliajay** [comment]
Thanks for your reply.

Actually as per one journal author has to use 'single quote' instead of "double quote". 

And at present even if I used 'single quote' the pdf output is showing "double quote".

**Comment by crsh** [comment]
If you are creating a PDF output, you may either use <code>\`</code> and `'` or include the following in the YAML front matter to have all double quotation marks converted to single quotation marks:

~~~yaml
header-includes:
  - \setquotestyle[british]{english}
~~~

**Comment by koliajay** [comment]
Thank you so much @crsh . Both answers worked perfectly good.
