### ISSUE TITLE
How to unitize `apa_results_table`

### ISSUE THREAD

**Issue by mariusbarth** [crsh/papaja#364]
Hi @crsh, while working on LMM support, I (again) started wondering how we could best unitize the output of `apa_print()`. If I remember correctly, we both agreed that it would be desirable to have a column `statistic` irrespective of the actual type of test statistic (F, t, chi^2 value) in an `apa_results_table`; however, we also did not want to create a code-breaking change. I think I came up with a possible solution. We could create a new method for indexing objects of class `apa_results_table`:

```
#' @export

`$.apa_results_table` <- function(x, name) {
  if(name == "F") {
    message("Indexing an apa_results_table with `$F` is deprecated. Use `$statistic` instead.")
    return(x$statistic)
  } else {
    x[[name]]
  }
}
```

With a method like this, we could rename the respective column in all ANOVA outputs. What do you think about this solution?

**Comment by crsh** [comment]
Hmm, I have considered this, too, but thus far it has struck me as a "terrible hack". ;)

But I'm coming around to the idea. My initial hesitation was that this only works for element selection but might break in unexpected ways when other functions are applied to the list. But then again, I'm not sure how often this would be the case and if it's worth to keep the inconsistencies for the sake of full backward compatibility here.

So, let's give it a shot. Off the top of my head, two things we need to think about:

1. I think we would need additional methods for  `[[` and `[`.
2. To avoid more hacks of this we need to think hard about what column names we have and may need in the future and how they can be unified (I'm thinking about things like  `terms`, `predictors`, `contrasts` etc.). Also, I would suggest that we follow the naming conventions used in `broom` where they exist.

What do you think?

**Comment by mariusbarth** [comment]
Great, I totally agree! Maybe I will just start collecting my ideas.

What needs to be done:
- Rename columns `F`, `t`, etc to `statistic`
- Rename column `p` to `p.value` (for consistency with broom and most summary methods)
- Rename columns Effect, Predict, etc to `term` (because it's the most generic form)
- I think we should stick with `estimate` for original-scale estimates.

What might be hard:
- Sometimes we have multiple test statistics in one row, possibly with extra "parameter" (e.g., for MANOVA both multivariate and univariate test statistic, both with their own df). I'm leaning towards prepending the respective terms in these case (so in this case, `multivariate.statistic`, `multivariate.df`). This is inconsistent with broom, but I think I should fix my own mistake, there.
- Degrees of freedom: The stats package consistently uses "parameter", and this might be of different length, depending on the number of dfs of the distribution of the test statistic. I think the hard-core consistency point of view would be to create a list-column that contains named vectors of length 1 or 2. However, I think this will only result in more complicated code whenever one wants to access the object, and even in these rare circumstances, the (most likely experienced) user will take a closer look at the output object, anyways. So creating this extra-degree of consistency is not really necessary.
- For effect-size measures, I think these are idiosyncratic enough that we can just keep them as they are (e.g., pes, ges, etc)... This will be consistent with the respective packages, and it also allows to compute multiple effect-size measures (e.g., pes and ges). However, I'm not sure about this.
- Interval estimates might be computed for an estimate, but also for standardized effect-size measures; they might be confidence intervals, credible intervals, or highest-density intervals, therefore, I thought about using something generic like `statistic.interval`, `es.interval`. However, it then came to me that while this might be consistent across all possible outputs, it will not be what a user might expect. Therefore, I think we should prioritize the user's expectations here and stick with `conf.int` for confidence intervals of original-scale estimates and come up with something new (hopefully consistent with other packages) for CIs of effect-size measures.

**Comment by mariusbarth** [comment]
Hi @crsh, I added a draft for "aliased indexing" (i.e., you can select column `$statistic` by typing `$F`) together with some tests on branch `aliased-indexing`. When you find the time, I would be happy to hear what you think about it.
