### ISSUE TITLE
Knitting to word slow, buggy in R 4.0

### ISSUE THREAD

**Issue by jvcasillas** [crsh/papaja#365]
**Describe the bug**
After upgrading to R 4.0 kniting a papaja .Rmd document to word is extremely slow. After it does eventually knit, the document is not automatically opened in word (like previous behavior), and for some odd reason my skype application opens. 

**To Reproduce**
A [minimal complete verifiable example](https://stackoverflow.com/help/mcve) and the error message if applicable.

I am using the basic template from the papaja package. I assume this can be reproduced unless it has to do with something specific to my system. 

**Expected behavior**
I expect the .Rmd file to knit to word and open in word. 

**Screenshots**

**Additional context**

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      papaja_0.1.0.9942 rstudioapi_0.11  
 [4] knitr_1.28        magrittr_1.5      usethis_1.6.1    
 [7] devtools_2.3.0    pkgload_1.0.2     R6_2.4.1         
[10] rlang_0.4.6       fansi_0.4.1       tools_4.0.0      
[13] pkgbuild_1.0.8    packrat_0.5.0     xfun_0.13        
[16] sessioninfo_1.1.1 cli_2.0.2         withr_2.2.0      
[19] htmltools_0.4.0   ellipsis_0.3.0    remotes_2.1.1    
[22] yaml_2.2.1        assertthat_0.2.1  digest_0.6.25    
[25] rprojroot_1.3-2   crayon_1.3.4      processx_3.4.2   
[28] callr_3.4.3       fs_1.4.1          ps_1.3.3         
[31] curl_4.3          testthat_2.3.2    evaluate_0.14    
[34] memoise_1.1.0     glue_1.4.0        rmarkdown_2.1    
[37] compiler_4.0.0    desc_1.2.0        backports_1.1.6  
[40] prettyunits_1.1.1
```

**Comment by jvcasillas** [comment]
I am also getting odd behavior when I attempt to knit older projects to word. Specifically I get the following error: 

```
Error running filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/papaja/rmd/docx_fixes.lua:
[string "--[[..."]:227: Constructor for Emph failed: [string "--[[..."]:258: attempt to index a nil value (local 'x')

stack traceback:
	[C]: in function 'error'
	[string "--[[..."]:227: in field 'Emph'
	...Versions/4.0/Resources/library/papaja/rmd/docx_fixes.lua:14: in function 'Image'
Error: pandoc document conversion failed with error 83
Execution halted
```

**Comment by crsh** [comment]
Hi Joseph,

thanks for reporting this.

> After upgrading to R 4.0 kniting a papaja .Rmd document to word is extremely slow. After it does eventually knit, the document is not automatically opened in word (like previous behavior), and for some odd reason my skype application opens.

I'd be surprised if this is indeed caused by something `papaja` does (but it of course may well be). Have you tried wether you get the desired behavior when you use `rmarkdown::word_document` and `bookdown::word_document2`?

As for the Lua-filter error, I got a report of this before but was unable to reproduce the problem. Could you provide a minimal reproducible example?

**Comment by jvcasillas** [comment]
> Hi Joseph,
> 
> thanks for reporting this.
> 
> > After upgrading to R 4.0 kniting a papaja .Rmd document to word is extremely slow. After it does eventually knit, the document is not automatically opened in word (like previous behavior), and for some odd reason my skype application opens.
> 
> I'd be surprised if this is indeed caused by something `papaja` does (but it of course may well be). Have you tried wether you get the desired behavior when you use `rmarkdown::word_document` and `bookdown::word_document2`?

Excellent question. I never knit to word outside of using `papaja` so I didn't even try this. It does indeed happen with `rmarkdown::word_document` as well. I will look elsewhere for a solution and report back. 


> 
> As for the Lua-filter error, I got a report of this before but was unable to reproduce the problem. Could you provide a minimal reproducible example?

The current example I have is a rather complicated document (children for subsections and appendices). I will work on this and see if I can reproduce.

**Comment by jvcasillas** [comment]
I can reproduce the error. It seems to be related to including images via `knitr::include_graphics`. I can use `knitr::include_graphics` in the main body without problems, but when I do it within an appendix I get the lua error reported above. I've attached a .zip that you should be able to test. 

[lua_error.zip](https://github.com/crsh/papaja/files/4615799/lua_error.zip)

**Comment by jvcasillas** [comment]
Regarding my issue kniting to word outside of papaja, I downgraded to R 3.6.3 and the most to date stable version of RStudio and that is no longer happening.

**Comment by crsh** [comment]
Excellent, thank you for your feedback. I'll try to look into it as soon as possible.

**Comment by jvcasillas** [comment]
Update: If I add a figure caption to the knitr chunk where the image is added the error goes away and I can knit as expected. So in the appendix file in the example I included I can add the following: 


    ```{r, 'model-formula', echo=FALSE, eval=T, fig.cap="test"}
    knitr::include_graphics(here::here("test.png"))
    ```

... and the error goes away.

**Comment by crsh** [comment]
Thanks, that's really helped. Should now be fixed on the development branch.

**Comment by jvcasillas** [comment]
Can confirm when using the development branch I no longer get this error. Thanks!
