### ISSUE TITLE
Error report when installing broom package

### ISSUE THREAD

**Issue by MZhang14** [crsh/papaja#366]
I am trying to install Papaja, But the system gave me error as below:
Really appreciate if anybody can help me out:
> .libPaths("c:/Users/mengz/OneDrive/Documents/R/win-library/4.0")
> devtools::install_github("crsh/papaja@devel")
Downloading GitHub repo crsh/papaja@devel
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                   
2: CRAN packages only                    
3: None                                  
4: broom (0.5.6 -> 3c4409b04...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
4
broom (0.5.6 -> 3c4409b04...) [GitHub]
Downloading GitHub repo tidymodels/broom@master
√  checking for file 'C:\Users\mengz\AppData\Local\Temp\RtmpgPOUlb\remotesaf43fd88a0\tidymodels-broom-3c4409b/DESCRIPTION' (488ms)
-  preparing 'broom': (933ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (1.3s)
-  checking for empty or unneeded directories
-  building 'broom_0.7.0.9000.tar.gz'
   
Installing package into ‘C:/Users/mengz/OneDrive/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'broom' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) C:/Users/mengz/AppData/Local/Temp/RtmpUdvfja/R.INSTALL2ca46fcc4c5c/broom/man/tidy.summary_emm.Rd: Only one \value section is allowed: the first will be used
ERROR: installing Rd objects failed for package 'broom'
* removing 'C:/Users/mengz/OneDrive/Documents/R/win-library/4.0/broom'
* restoring previous 'C:/Users/mengz/OneDrive/Documents/R/win-library/4.0/broom'
Error: Failed to install 'papaja' from GitHub:
  Failed to install 'broom' from GitHub:
  (converted from warning) installation of package ‘C:/Users/mengz/AppData/Local/Temp/RtmpgPOUlb/fileaf447a45bc8/broom_0.7.0.9000.tar.gz’ had non-zero exit status

**Comment by crsh** [comment]
This error is due to a bug in the current development snapshot of `broom`. If you don't update `broom` by entering `3`, you should be able to install `papaja`.

**Comment by crsh** [comment]
As an aside, @mariusbarth has already submitted a [PR](https://github.com/tidymodels/broom/pull/846) to fix this issue on the `broom`-side.

**Comment by MZhang14** [comment]
Hi Frederik,

It really works. Now I successfully installed papaja package. Thanks for your help!


Thank you!

All the best,

Meng Zhang

________________________________

**Comment by mariusbarth** [comment]
The bug should be fixed on the broom side, so all of us can update broom, again. :)
