### ISSUE TITLE
`cslreferences` undefined error in revision letter template

### ISSUE THREAD

**Issue by jvcasillas** [crsh/papaja#368]
**Describe the bug**
When I knit the template for the revision letter I get the following error: 

```
! LaTeX Error: Environment cslreferences undefined.
```

This appears to have been an issue with an update to pandoc that was later implemented in Rmarkdown (https://github.com/rstudio/rmarkdown/issues/1649). I wonder if the same change needs to be included in the template `papaja` uses?

**To Reproduce**
A [minimal complete verifiable example](https://stackoverflow.com/help/mcve) and the error message if applicable.

Open default template and knit. 
My system is running `tinytex`, so one possibility is that the error has to do with that and not the template `papaja` uses. I am still trying to figure this out, but so far my searching in the tinytex repo hasn't provided any clues.

**Comment by jvcasillas** [comment]
Following the link I provided in the previous comment I found the following code: 

```
$if(csl-refs)$
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newenvironment{cslreferences}%
  {$if(csl-hanging-indent)$\setlength{\parindent}{0pt}%
  \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces$endif$}%
  {\par}
$endif$
```

I went into the revision letter template on my system and added this code in the `resources > revision_letter.tex` template and I can now knit the document. In an effort to be helpful I will send a pull request with this change. 

https://github.com/crsh/papaja/pull/369

**Comment by crsh** [comment]
Thanks for reporting this. I have merged your PR, I hope that resolves the issue.
