### ISSUE TITLE
Hanging indents for bibliography

### ISSUE THREAD

**Issue by jvcasill** [crsh/papaja#37]
My understanding is that current APA style requires the bibliography to use hanging indentation (i.e. the first line is normal, all the following lines are indented, for each reference). I didn't see an option to change this in the documentation.

**Comment by crsh** [comment]
You are right.This is an issue that is currently being worked on by the pandoc developers (see e.g. [this discussion](https://groups.google.com/forum/?fromgroups&hl=en#!topic/pandoc-discuss/ghOOvbHByLk)). For the time being, if your target output format is PDF, you can add the following LaTeX-lines to the end of your document:

    \setlength{\parindent}{-0.5in}
    \setlength{\leftskip}{0.5in}
    \setlength{\parskip}{8pt}

This should produce the desired results.

**Comment by ismayc** [comment]
Excellent!  That works.  Thanks!
