### ISSUE TITLE
installation fails on Windows 10

### ISSUE THREAD

**Issue by matanmazor** [crsh/papaja#377]
Hey,

I'm running R 3.6.0 on Windows 10.

I have devtools installed, and to install papaja run:
devtools::install_github("crsh/papaja")

It's all running until I get:

package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'papaja' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

Thanks!

**Comment by crsh** [comment]
Have you tried to manually remove your installation of `rlang` via `remove.packages("rlang")` prior to installing `papaja`?

**Comment by matanmazor** [comment]
just did, not I'm getting:
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rlang’

:(
