### ISSUE TITLE
Removing the abstract removes affiliations

### ISSUE THREAD

**Issue by shirdekel** [crsh/papaja#379]
**Describe the bug**
When the YAML abstract is removed, the pdf output does not show the YAML affiliations. Instead, it just says "Affiliations".

**To Reproduce**
Running the example Rmd without the YAML abstract in the development branch reproduces the error. It works fine in the master branch.

**Expected behavior**
I expect to have no abstract, but to include affiliation.

**Comment by crsh** [comment]
Thanks for bringing this to my attention. I just pushed a commit to the `devel` branch that should fix this.

**Comment by shirdekel** [comment]
Thanks, it works now!
