### ISSUE TITLE
figure label appears in caption

### ISSUE THREAD

**Issue by matanmazor** [crsh/papaja#383]
Hello,

When knitting my R Markdown document (papaja::apa6_pdf), my figure caption appears in the figure legend. This is the code to generate my figure:

````
```{r RT_pilot, echo=FALSE, fig.cap="\\label{fig:RT_pilot}Median search time."}

ggplot(data=median_search_times, 
       aes(x=set_size, y=median_RT, group=response)) +
  geom_line(aes(linetype = response))
````

My YAML is
```
title             : "my title"
shorttitle        : "short title"

author: 
  - name          : "me"
    # affiliation   : "1"
    # corresponding : yes    # Define only one corresponding author
    # address       : "Postal address"
    # email         : "my@email.com"

  - name          : "my supervisor"

authornote: |


abstract: 
  <!--  -->

keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
```
In the output file, my figure legend is:

> "Figure 2. (#fig:RT_pilot)Median search time."

How can I make the figure label disappear?

Thanks!

**Comment by crsh** [comment]
Hi Matan,

sorry, I'm pretty busy right now, but I'll try to look into this as soon as possible. A couple of questions:

1. In `bookdown` you cannot use `_` in chunk names, if you want to reference them. Does replacing `_` with `-` resolve the problem?
2. Do you get the same behavior when you use `bookdown::pdf_document2()` rather than`papaja::apa6_pdf()`?
3. Is there a particular reason you want to add the label manually? With any `bookdown::pdf_document2()`-document (and this includes `papaja::apa6_pdf()`) labels should be added automatically.

**Comment by matanmazor** [comment]
Hey Frederik,

Many thanks for your prompt reply. Replacing my `_` with `-` resolved my problem - sorry, in hindsight I should have seen this instruction in the manual.
Re point 3: I'm now using `fig:chunk_label` instead of specifying the label in the caption (cool feature!), but for some reason it only works with `\ref{fig:chunk_label}` and not `\@ref{fig:chunk_label}`as specified in the manual. I'm guessing I'm still doing something wrong?

Many thanks,
-Matan

**Comment by crsh** [comment]
> Re point 3: I'm now using `fig:chunk_label` instead of specifying the label in the caption (cool feature!), but for some reason it only works with `\ref{fig:chunk_label}` and not `\@ref{fig:chunk_label}` as specified in the manual. I'm guessing I'm still doing something wrong?

The `bookdown`-syntax requires that you use parentheses: `\@ref(fig:chunk_label)`

**Comment by matanmazor** [comment]
Thanks!
