### ISSUE TITLE
Factor Loading Table Option

### ISSUE THREAD

**Issue by bgallihu** [crsh/papaja#384]
I'm working on a factor analysis for a master's thesis. Is there a way using papaja to export a factor loading table into an APA style table?

**Comment by mariusbarth** [comment]
Hi! It's definitely possible, and I think this is a great question for [stackoverflow](https://t.co/Z3auyUrbTa)! There already is a [question](https://stackoverflow.com/questions/62018314/option-to-cut-values-below-a-threshold-in-papajaapa-table) that seems to address your problem. If it doesn't serve your purposes, feel free to ask a new question, there, and I will try to answers as quickly as possible.
