### ISSUE TITLE
Error when using apa_print for lm(). Message: Objects of class 'tbl_df' are currently not supported (no method defined).

### ISSUE THREAD

**Issue by efkccc** [crsh/papaja#386]
**Describe the bug**
Hi there, 
I'm trying to use apa_print() to get linear model subj_lm , but it's giving me the following error message:

Error in no_method(x) : 
  Objects of class 'tbl_df' are currently not supported (no method defined).
              Visit https://github.com/crsh/papaja/issues to request support for this class.Objects of class 'tbl' are currently not supported (no method defined).
              Visit https://github.com/crsh/papaja/issues to request support for this class.Objects of class 'data.frame' are currently not supported (no method defined).
              Visit https://github.com/crsh/papaja/issues to request support for this class.

**Screenshots**
how the console looks like:
<img width="962" alt="Screenshot 2020-07-10 at 20 27 17" src="https://user-images.githubusercontent.com/57488005/87154409-c2d40780-c2eb-11ea-8afe-83dddd4cd552.png">

how subj_lm is defined:
<img width="619" alt="Screenshot 2020-07-10 at 20 36 16" src="https://user-images.githubusercontent.com/57488005/87155147-04b17d80-c2ed-11ea-9bef-c4768ab84685.png">

**Expected behavior**
to print four-elements list of the linear model

(first time asking a question, please do let me know if you need other info)
Thank you very much for your help!

**Comment by mariusbarth** [comment]
Hi! You're almost there. The problem is that you `tidy()` your linear-model object before you write it into `subj_lm`. So just omit the `%>% tidy()` and it should work.

**Comment by efkccc** [comment]
> Hi! You're almost there. The problem is that you `tidy()` your linear-model object before you write it into `subj_lm`. So just omit the `%>% tidy()` and it should work.

Tried again without tidy() and worked well!  
Thanks you very much!😊

**Comment by mariusbarth** [comment]
Perfect, good to know! :relaxed:
