### ISSUE TITLE
apa_table() produces an additional blank page when big table inserted

### ISSUE THREAD

**Issue by kbeauvivre** [crsh/papaja#389]
I open this issue because my post on this closed issue didn't receive attention for more than 10 days. https://github.com/crsh/papaja/issues/256

When I insert a table in a landscape view using the apa_table() fuction, a blank numbered page is printed when I knit on pdf (I didn't try the Word output, as I don't want this kind of knittig. I have the problem twice in my document, with two different tables. Nevertheless, the two tables are long.
When I prepared the minimal complete verifiable example, I saw that the length of the table is causing the blank page. If I delete just one row, everything works fine. Also, the margins of the table remain really big on the left and on the right - there is more space on the page than on the pages filled with simple text.

My reprex :

```
library(papaja)
efa.load = read.csv("/home/kristina/Documents/thesis/output/test.csv", header = T, sep=";")
apa_table(efa.load, label = "Tableau 2", caption="Résultats", note="N = 702", landscape = T, font_size="scriptsize")
#> (#tab:reprex-body)
#>
#> Résultats
#>
#>
#>
#> A B D E F G
#> ---------- ------- --------- ---- ------------------------------------------------------- -----
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#> aaaaaaaaa BBBBBB 11111,11 FRE PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 0.98
#>
#>
Note. N = 702
```

**Comment by mariusbarth** [comment]
Hi Kristina, sorry for not replying earlier.

I cannot reproduce your problem: When I render your example (i.e., after pasting your markdown output into a fresh papaja document), everything renders as expected. Can you provide the output of `devtools::session_info()` and maybe a screenshot of the problematic pages in your document?

**Comment by kbeauvivre** [comment]
Hi Marius,

Here is what devtools::session_info() says :

> ─ Session info ────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Linux Mint 19.1             
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language fr_FR                       
 collate  fr_FR.UTF-8                 
 ctype    fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2020-07-20                  

─ Packages ────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.1)
 backports     1.1.8   2020-06-17 [1] CRAN (R 3.6.3)
 callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.3)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.1)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
 devtools      2.3.0   2020-04-10 [1] CRAN (R 3.6.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 3.6.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
 fs            1.4.2   2020-06-30 [1] CRAN (R 3.6.3)
 glue          1.4.1   2020-05-13 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.1)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 3.6.3)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 3.6.3)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.3)
 processx      3.4.3   2020-07-05 [1] CRAN (R 3.6.3)
 ps            1.3.3   2020-05-08 [1] CRAN (R 3.6.3)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
 remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.3)
 rlang         0.4.7   2020-07-09 [1] CRAN (R 3.6.3)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.1)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 usethis       1.6.1   2020-04-29 [1] CRAN (R 3.6.3)
 withr         2.2.0   2020-04-20 [1] CRAN (R 3.6.3)

[1] /home/kristina/R/x86_64-pc-linux-gnu-library/3.6
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library


I knitted the minimal example and there is a change in the output now : the note is centered and goes on two lines - I don't know why. I've updated my r libraries since I've posted my message. One of the two tables that produced a blanck page is OK now. I attch the screenship of the second which continues to be followed by a blank page.


[minimal_example-apa_table-blank_page.pdf](https://github.com/crsh/papaja/files/4946751/minimal_example-apa_table-blank_page.pdf)
![PrintscreenPapaja](https://user-images.githubusercontent.com/37898272/87922605-80918f80-ca7c-11ea-8ede-f000571c2c1d.png)

**Comment by crsh** [comment]
One more question: What version of `papaja` are you using?

**Comment by kbeauvivre** [comment]
My papaja version is 0.1.0 
I'm guessing it's outdated ?

**Comment by crsh** [comment]
Indeed. Try installing the latest version from this repository (`remotes::install_github("crsh/papaja@devel")`) to see if that helps.

**Comment by kbeauvivre** [comment]
Well, I've installed the latest version and the things are worse than before ! I cannot knit the pdf anymore.
Here is the error message that gives me :

> output file: minimal_example-apa_table-blank_page.knit.md

>[WARNING] Could not parse YAML metadata at line 47 column 1: :22:0: leading empty lines contain more spaces than the first 
>non-empty line in scalar
>0 words in text body
>0 words in reference section
>! Undefined control sequence.
><recently read> \captionsetup 

>Error : LaTeX failed to compile minimal_example-apa_table-blank_page.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See minimal_example-apa_table-blank_page.log for more info.
>Exécution arrêtée (= Execution stopped in French)

I have installed R 4.0 and all the libraries on a new proper linux mint account. Nevertheless the error remains. I guess it's a LaTeX error but I have no idea how to deal with it...

**Comment by crsh** [comment]
Okay, I'll need to dig a little deeper:

1. `! Undefined control sequence. \captionsetup` tells me you may not be knitting a `papaja` manuscript using `apa6_pdf()`. Is that right?
1. Could you share the complete R Markdown file you are trying to knit? 
2. In your reprex you access a data file (`test.csv`) that I don't have access to. As such the example is not reproducible. Could you share the file with me, so I can try to closely reproduce your environment?

**Comment by kbeauvivre** [comment]
Hi Frederik,

I attach the *.rmd file and the test.csv file.

I specified in the YAML section :  `output            : papaja::apa6_pdf` so I don't think this would be the cause.

My original file is almost 50 pages long and not really sharable. If what I send you here is not sufficient I will try to make an other reprex from it.

[kbeauvivre_reprex.zip](https://github.com/crsh/papaja/files/4953746/kbeauvivre_reprex.zip)

**Comment by mariusbarth** [comment]
@crsh, @kbeauvivre  : I can confirm that I cannot knit the document, too. Removing the empty abstract and authornote at least allows me to knit. (@crsh : This seems to be the same issue that KB had with the relational EC manuscript)

**Comment by kbeauvivre** [comment]
@mariusbarth thanks ! I removed the authornote and abstract. Tinytex installed the missing libraires. I knitted the document, and I have the blank page. 
[minimal_example-apa_table-blank_page.pdf](https://github.com/crsh/papaja/files/4953815/minimal_example-apa_table-blank_page.pdf)

**Comment by mariusbarth** [comment]
Ok, so we are least one step further. :smile: (btw, your example is super helpful, because a colleague had a similar issue a week ago, but we couldn't reproduce it) I am hopeful that Frederik will come up with an idea what might cause the empty page.

**Comment by kbeauvivre** [comment]
This is nice ! :-)
Just a last detail : I don't know why the Note text under the table is printed on several lines in my reprex. In the manuscript I am working on, the text is on the same line :

![caption_table](https://user-images.githubusercontent.com/37898272/88067348-29201c00-cb6f-11ea-89eb-87d1a8ab7b3e.png)

**Comment by crsh** [comment]
Sorry this has been such a long time. From what I understand, the table dimensions are in an awkward spot of being just slightly too small to break onto the next page (when using `longtable = TRUE`) but too large to fit the current page. This can [cause blank pages](https://tex.stackexchange.com/a/223780/11001). I don't think there is anything that I can do about this in general. I think you may have to adjust the table such that it clearly breaks onto the next page or fits the current page (e.g. by adding the note to the caption).
