### ISSUE TITLE
Confidence intervals for eta^2s

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#39]
`apa_print()` provides confidence intervals for R² (`lm`) but as of now no confidence intervals are calculated for ANOVA objects.

**Comment by crsh** [comment]
http://daniellakens.blogspot.de/2014/06/calculating-confidence-intervals-for.html

**Comment by crsh** [comment]
Also see this code by Richard Morey: https://gist.github.com/richarddmorey/ea32db6a6c2419eaff0e1a5186e986c0

**Comment by doomlab** [comment]
Our package has this functionality now, and I am adding omega and epsilon soon. 
I suppose the biggest question is if you want to just get people to use the MOTE or MBESS package to calculate them and then make sure their output is convertable using apa_print or add the calculation functionality directly to the papaja package.

**Comment by crsh** [comment]
So far, my idea was to give users the opportunity to specify a function to calculate effect sizes and confidence intervals as an argument to `apa_print()`. I'm not sure if this approach is feasible, though. Is [this](https://github.com/doomlab/MOTE/blob/2265c1bdef59a558ce33d6fb3eb049cf123def4c/R/eta.anova.R) the function in `MOTE` that does this?

**Comment by doomlab** [comment]
@crsh - sorry for the delay - yes that function will do a basic eta translation. One of my goals over the next couple of weeks is writing more functions for MOTE that will cover the gambit of eta/omega/epsilon/ges, so there will be more options than just calculating from df and F. 

Is there a good way to write those functions to pass to `apa_print()` ... this is probably where I need to read and learn the `S3` stuff a bit better yes? Trying to do double duty here on finishing some work that will help me learn/understand how to build better functions that I can apply to helping with your package.

**Comment by crsh** [comment]
Hi @doomlab,

generally, it would be helpful to define an S3 or S4 class for the output objects. It makes sense to invest some thought into whether there is some structure that works for all related functions so that the results can be returned in a standardized form. This will facilitate the processing of the results in `apa_print()`. For example, a useful default structure would be a [tidy `data.frame`](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html). I'd take a look at the objects returned by [`broom`-functions](https://github.com/tidyverse/broom/blob/master/R/anova_tidiers.R) as examples for how to name the columns.

Another question to consider is, how to implement the integration of `apa_print()` with user-supplied functions to calculate effect size estimates and confidence intervals. I haven't spent too much time thinking about this because we currently only support the functions we have implemented ourselves. But this may be a good time to invest some thought.

Internally, most (and eventually, I hope all) methods of `apa_print()` generate a table that contains estimates with corresponding confidence intervals as well as test statistics and corresponding parameters (e.g. degrees of freedom). In short, this is a `data.frame` that contains all information needed to assemble the text needed to report the results. I then apply functions to each row to paste either estimates, test statistics, or both together. Currently, there is no easy way to access and manipulate these intermediary tables.

It seems to me that the easiest way to include custom effect size estimates in the output of `apa_print()` is to enable splitting this process in two and enable users to manipulate the intermediary table. If users are happy with the default output they could simply pass the to-be-formatted output into `apa_print()` and be done with it:

~~~r
npk_aov <- aov(yield ~ block, npk)
apa_print(npk_aov)
~~~
~~~
$estimate
$estimate$block
[1] "$\\hat{\\eta}^2_G = .392$"


$statistic
$statistic$block
[1] "$F(5, 18) = 2.32$, $\\mathit{MSE} = 29.61$, $p = .086$"


$full_result
$full_result$block
[1] "$F(5, 18) = 2.32$, $\\mathit{MSE} = 29.61$, $p = .086$, $\\hat{\\eta}^2_G = .392$"


$table
A data.frame with 7 labelled columns:

  Effect    F df1 df2   MSE    p  ges
1  Block 2.32   5  18 29.61 .086 .392

Effect: Effect 
F     : $F$ 
df1   : $\mathit{df}_1$ 
df2   : $\mathit{df}_2$ 
MSE   : $\mathit{MSE}$ 
... (2 more labels)
~~~

Let's say we generally structure the workflow into two separate steps (as noted above, internally this is already the case to a large extent), (1) generate the `$table` element and  (2) paste text strings:

~~~r
npk_aov <- aov(yield ~ block, npk)
npk_table <- apa_tidy(npk_aov)
npk_table # Of class apa_aov_table
~~~
~~~
A data.frame with 7 labelled columns:

  Effect    F df1 df2   MSE    p   es
1  Block 2.32   5  18 29.61 0.09 0.39

Effect: Effect 
F     : $F$ 
df1   : $\mathit{df}_1$ 
df2   : $\mathit{df}_2$ 
MSE   : $\mathit{MSE}$ 
... (2 more labels)
~~~

If we now want to report other effect size estimates we could simply manipulate the `apa_aov_table` and subsequently paste the text together:

~~~r
npk_table$es <- omega(npk_aov)
variable_label(npk_table$es) <- "$\\hat{\\omega}^2$"
npk_table$es_ll <- omega_ll(npk_aov, level = 0.95)
npk_table$es_ul <- omega_ul(npk_aov, level = 0.95)
apa_print.apa_aov_table(npk_table, ci = 0.95)
~~~
~~~
$estimate
$estimate$block
[1] "$\\hat{\\omega}^2 = .392$ 95\\% CI $[.135$, $.539]$"


$statistic
$statistic$block
[1] "$F(5, 18) = 2.32$, $\\mathit{MSE} = 29.61$, $p = .086$"


$full_result
$full_result$block
[1] "$F(5, 18) = 2.32$, $\\mathit{MSE} = 29.61$, $p = .086$, $\\hat{\\omega}^2 = .392$ 95\\% CI $[.135$, $.539]$"


$table
A data.frame with 7 labelled columns:

  Effect    F df1 df2   MSE    p   es   es_ll   es_ul
1  Block 2.32   5  18 29.61 .086 .392     .135     .539

Effect: Effect 
F     : $F$ 
df1   : $\mathit{df}_1$ 
df2   : $\mathit{df}_2$ 
MSE   : $\mathit{MSE}$ 
... (2 more labels)
~~~

A workflow like this would grant users a lot of flexibility and, I think, it should be feasible to implement on top of our current internal workflow. The only downside is that this requires some manual labor. For functions that process the same objects as `apa_print()` and which return `data.frames` with correct variable labels we could provide a shortcut:

~~~r
omega_df <- function(x, level = 0.95) {
  out <- data.frame()
  out$es <- omega(x)
  variable_label(x$es) <- "$\\hat{\\omega}^2$"
  out$es_ll <- omega_ll(x, level = 0.95)
  out$es_ul <- omega_ul(x, level = 0.95)
  rownames(out) <- names(x$contrasts)
  out
}

npk_aov <- aov(yield ~ block, npk)
apa_print(npk_aov, es_fun = omega_df)
~~~

Does this make sense, @doomlab? Do you have any thoughts on this, @mariusbarth?

**Comment by crsh** [comment]
@doomlab If you don't want the output objects that `MOTE` generates to be in the specific format required by the `papaja` functions (whatever that may turn out to be), it would be easier to provide functions that do the restructuring if the `MOTE` output has a class for which we can write methods, e.g.:

~~~r
mote_es <- eta.anova(dfm, dfe, Fvalue, a = .05)
class(mote_es)
~~~
~~~
[1] "MOTE_eta"
~~~
~~~r
apa_es_table(mote_es)
~~~

where `apa_es_table()` could be a general function that adapts its behavior depending on the input.

**Comment by doomlab** [comment]
I've been reading about the proper formatting and such, and I am finally getting it through my thick brain.

I was wanting to write my functions with a lot of flexibility as well - so things like variance overlap effect sizes could be calculated from lm, aov, ezANOVA, etc. I could write separate functions for each of those input systems or we could just allow people to pick their favorite option.

Picking the easiest thing here, let's say I've defined my eta.anova function and I want to use aov output:
```
eta.anova <- function (dfm, dfe, Fvalue, a = .05) {
  eta <- (dfm * Fvalue) / (dfm * Fvalue + dfe)
  ncpboth <- conf.limits.ncf(Fvalue, df.1 = dfm, df.2 = dfe, conf.level = (1 - a))
  elow <- ncpboth$Lower.Limit / (ncpboth$Lower.Limit + dfm + dfe + 1)
  ehigh <- ncpboth$Upper.Limit / (ncpboth$Upper.Limit + dfm + dfe + 1)
  p <- pf(Fvalue, dfm, dfe, lower.tail = F)
  
  output <- data.frame(es = eta,
                       es_ll = elow,
                       es_ul = ehigh,
                       Fvalue = Fvalue,
                       dfm = dfm,
                       dfe = dfe)
  return(output)
  }
```
Then I could do something like this (ok this is hideous but basically I could run my analysis in whatever function I would like be it aov, lm, ez, etc. and then pull those numbers from the output)
```
##run my analysis
aov_saved = summary(aov(mpg~cyl, data = mtcars))
##process through MOTE
eta_saved = eta.anova(aov_saved[[1]][["Df"]][1], aov_saved[[1]][["Df"]][2], aov_saved[[1]][["F value"]][1], a = .05)
```
The good part of doing it this way is that when you write it, I don't have to write it 10 times to handle each versions output, which makes it a bit more work on the user end, but less functions on my end. This also controls for when people want to maybe check other numbers from a publication or something. 

Now I changed the structure in this example to be a data.frame:
```
> eta_saved
       es     es_ll     es_ul   Fvalue
1 0.72618 0.5214665 0.8148607 79.56103
  dfm dfe
1   1  30
> str(eta_saved)
'data.frame':	1 obs. of  6 variables:
 $ es    : num 0.726
 $ es_ll : num 0.521
 $ es_ul : num 0.815
 $ Fvalue: num 79.6
 $ dfm   : num 1
 $ dfe   : num 30
```
So, maybe the approach would be to do the second option, with some reformatting on my end to match up to something `apa_print` could read and write a special class of `MOTE`. 

Then I could write a `apa_print_MOTE.R` that would look for specific column names like es, es_ll, es_ul to print out in nice latex format. Then someone could use `apa_print(saved aov not summary)$statistic` and `apa_print(eta_saved)$estimate` to put them together in the markdown. 

I think another advantage to separating them a bit is also going to be that a user could pick to pair Cohen's d or ges or r with whatever statistic they are presenting and would make that choice by using the specific MOTE function that matches their choice. Then the new print function would just clean it up and print it out nicely for them. Your way also works - but keeping it separate would give you functionality for the whole family of effect sizes and their CIs. 

Another thought I just had was that there are a lot of instances that MOTE actually calculates all the appropriate statistics for you as well or at least passes them back to you - so you could be using a package you don't currently support (like ez) and get the etas from that, and have it print the whole statistic for you out of the MOTE class version.  

@crsh - thoughts on that? Let me know if I'm not also not interpreting everything you've said correctly.

**Comment by doomlab** [comment]
Yes - I get what you are saying, and I appreciate you explaining it to me! I am learning a lot here on ways to do everything. 

That being said! I will work on the `S3` ideas for `MOTE` over on my git - what can I do right now to help with CIs here for the variance family?  Want me to try to write some functions that calculate the different variance overlap families, their CIs, as the helper functions?

It would be very similar to the ideas you already have going in `apa_print_glm.R`, but modified to calculate the partial eta/omega/ges/etc. I can certainly write them like the way you've formatted them above. 

At the moment, that would only be for `aov` objects correct?

**Comment by crsh** [comment]
> I get what you are saying, and I appreciate you explaining it to me!

No problem, I just wasn't sure we had similar things in mind. Thanks to your initiative on this it got me thinking in more detail about how we can enable greater flexibility in terms of the to be reported statistics. 👍

As for starting points for supporting `papaja`: Although my goal is to [eventually](https://crsh.github.io/papaja_man/introduction.html#guiding-principles) fully outsource effect size calculations beyond what is directly available from output objects, it would be great if the currently available options (eta^2, partial eta^2, and generalized eta^2) would support confidence intervals. If you are willing to provide some code for their calculation that is light on dependencies, this would be greatly appreciated. It's fine if the code only applies to `aov`, it think it shouldn't be to hard to subsequently adapt it for other objects. If you'd like to work on this I'd be happy to review a pull request (I think a good place for these functions would be in `calculations.R`).

**Comment by doomlab** [comment]
@crsh can do! I will work on that while I write the eta ones for myself 👍

**Comment by doomlab** [comment]
@crsh - an update - we have written all the basic level code for omega, eta, ges, and epsilon. I am working on testing the values now, and I believe they are right. After we do a bit more testing and give a talk about our mote shiny app, I will work on putting those formulas in where you recommended. I have a student who's excited to help me with S3 as well. ;)

**Comment by doomlab** [comment]
@crsh - sent a pull request! Let's see what you think.
