### ISSUE TITLE
Remove author names and file location from PDF when masked

### ISSUE THREAD

**Issue by JeffreyRStevens** [crsh/papaja#392]
Thank you for the easy masking feature in `papaja`. While setting `mask` to `yes` in the YAML strips all of the author information from the title page, the author and file location are still available in the PDF properties. Is there a way to prevent this identifying information from being saved in the PDF properties, or is this an upstream problem?
By the way, I can delete the author names from the TeX document, but it would be nice if masking automatically did this.

**Comment by crsh** [comment]
Hi Jeffrey, good catch! This can be fixed by adding `author-meta: ""` to the YAML front matter. I just pushed a commit to the development branch that does this automatically when you set `mask: yes`. Let me know if that helps (`remotes::install_github("crsh/papaja@devel")`).

**Comment by jstevens5** [comment]
Thanks, Frederik. And thank you for developing and maintaining this package. It is a huge help for many of us!
