### ISSUE TITLE
Full support of base R's stats package

### ISSUE THREAD

**Issue by mariusbarth** [crsh/papaja#393]
I think we should aim at fully supporting base R's stats package. I think the most problematic bits are the functions that return objects of class `pairwise.htest`, because these contain almost none of the information that we really need. We could still add methods for these outputs returning a minimal output, but also return a message or even a warning pointing users to appropriate functions (e.g., from the emmeans package) or a section of our manual where we could collect appropriate functions. I think I would prefer the second approach, because I always found this super helpful, for instance the warning messages returned by `rstan` (e.g., about effective sample size) .

**Comment by crsh** [comment]
I'm closing this issue because at this point I don't have the time or motivation to add new methods that are neither requested by users nor useful to myself. If request for any specific methods come up, we should add them, but I don't think it's worth pushing for full support for its own sake.
