### ISSUE TITLE
https://tinyurl.com/apa6-meta-analysis

### ISSUE THREAD

**Issue by HeatherUrry** [crsh/papaja#394]
Hello! The csl link at https://tinyurl.com/apa6-meta-analysis is throwing an error. (I had trouble with an entirely different tinyurl.com link earlier today so it may be that the site is glitching.)

Best,

Heather

**Comment by crsh** [comment]
Hi Heater, thanks for reaching out. I've experienced some issues these past days too. So I'll wait a bit and see before I start worrying. ;)

I will use this issue as a reminder. Thanks again.

**Comment by HeatherUrry** [comment]
Hi Frederik,

Perhaps you already know but I discovered when knitting the document again today that the csl link worked just fine. I'll close this issue. (It might be useful to provide the real link to that csl in the documentation just in case there's big trouble in little tiny again in the future.) :)

H.

**Comment by crsh** [comment]
To be honest, these are very busy times for me and the issue had dropped off my radar. Thanks for letting me know!
