### ISSUE TITLE
Co-first/Equal Authorship

### ISSUE THREAD

**Issue by HanZhang-psych** [crsh/papaja#397]
Hello!

I wonder if there is a way in `papaja` to define co-first authorship? For example, see this paper: https://science.sciencemag.org/content/318/5855/1469/tab-pdf

Sorry in advance if this has been asked before. 

Han

**Comment by crsh** [comment]
Hi Han, this is a fairly new feature and somewhat burried in the manual, but you can set `equal_contrib: yes ` for sharing first authors: https://crsh.github.io/papaja_man/r-markdown-components.html#yaml-front-matter

Is that what you had in mind?


Sent from my phone

**Comment by HanZhang-psych** [comment]
Exactly what I wanted. Thank you!
