### ISSUE TITLE
papaja is not avaliable for R version 4.0.2

### ISSUE THREAD

**Issue by ufangYang** [crsh/papaja#404]
Will `papaja` be available for R version greater than 4 in the near future? `papaja` so far cannot be installed in R version 4.0.2 for me (OS Majave). thanks

**Comment by crsh** [comment]
Hi there, did you try installing from CRAN or this GitHub repository (`remotes::install_github("crsh/papaja")`)? Currently, `papaja` is not available on CRAN at all (regardless of the R version).

**Comment by fruchtblase** [comment]
Hey, there, I was able to install papaja in 4.0.2 on win10 and on linux without any issues.

**Comment by ufangYang** [comment]
I can install it from Cran or GitHub repository, thanks. Hope `papaja` will be available on CRAN

**Comment by eljean5** [comment]
Hello, papaja is still not running for me. Would you be able to help. Here is the error:
<img width="855" alt="Screen Shot 2020-11-16 at 23 15 51" src="https://user-images.githubusercontent.com/62871225/99349463-b34c6880-2861-11eb-84ac-af52a2892408.png">

**Comment by crsh** [comment]
The error message says that you are missing the dependencies `bookdown` and `rmdfiltr`. You could either install those manually or try `remotes::install_github("crsh/papaja", dependencies = TRUE)`.

**Comment by eljean5** [comment]
Thank you for following up: 

Even with dependencies, I am still getting an error. I am running R version 3.6.2 on MacOS 
<img width="857" alt="Screen Shot 2020-11-18 at 00 26 31" src="https://user-images.githubusercontent.com/62871225/99493471-e14ead00-2934-11eb-8ce6-c9916e756f4c.png">

**Comment by crsh** [comment]
As the error message says: "dependencies 'bookdown', 'rmdfiltr' are not available". For reasons I don't understand, `remotes::install_github()` sometimes fails to install dependencies. Please try installing those packages manually, as suggested in my previous post.

**Comment by K4tana** [comment]
I have the same problem. I have all the dependen
![image](https://user-images.githubusercontent.com/45456001/110024048-2e149300-7d2e-11eb-9a0b-f2ac3037417b.png)
cies installed (even updated), yet papaja fails to install, giving me this

**Comment by crsh** [comment]
Hi Oliver, could you post the complete error message?
