### ISSUE TITLE
When using scientific notation, printnum does not handle small numbers correctly

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#405]
@mariusbarth I think the problem may have been introduced by your recent work on `printnum()`. Could you take a look at this?

Consider the following example:

~~~r
printnum(0.00125, format = "e", digits = 2)
[1] "0.00e+00"
~~~

What I expected is the same behavior as we would get with `formatC()`:

~~~r
formatC(0.00125, format = "e", digits = 2)
[1] "1.25e-03"
~~~

If I understand correctly, it's this line that causes the problem; when I comment it out, I get the desired behavior:

https://github.com/crsh/papaja/blob/11f2f8d159d04290f422bd85d4b2151982ae21a2/R/printnum.R#L210

**Comment by mariusbarth** [comment]
Hi @crsh, I remember that I copied this line from the old code because I got some weird results with an alternate implementation. I will give this one a thorough look as quickly as possible

**Comment by crsh** [comment]
Are you sure? I tried to find the code prior to your work on `printnum()` (43229fcec06accbe115e4e83943af479c43cd7d1) but couldn't find it.

**Comment by mariusbarth** [comment]
Sure. :) Initially, I was surprised to do rounding there, but then it made sense after our discussion of whether *p* = .0005 should be rounded to `"< .001"` or `".001"`.

**Comment by mariusbarth** [comment]
This one should now be solved.

**Comment by crsh** [comment]
Thanks.
