### ISSUE TITLE
Give an example of using citation('papaja'). 

### ISSUE THREAD

**Issue by jkhartshorne** [crsh/papaja#411]
I'd be very happy to cite papaja. I have tried the following methods:

- citation('papaja')
- `r citation('papaja')`
- (citation('papaja'))

Maybe you thought this was obvious, but it's not obvious to me!

**Comment by crsh** [comment]
Hi Joshua, thanks for reaching out. I assume you are trying to cite `papaja` in the document you are rendering. Did you see the [section of the manual on citing R packages](https://crsh.github.io/papaja_man/writing.html#citing-r-and-its-packages)?

**Comment by jkhartshorne** [comment]
I did not see that. It would be helpful to link to that from where you request the citation to papaja!

**Comment by crsh** [comment]
Indeed, thanks for the suggestion!
