### ISSUE TITLE
Affiliation and author note don't appear in pdf output

### ISSUE THREAD

**Issue by efkccc** [crsh/papaja#412]
**Describe the bug**
Affiliation and author note won't appear in the PDF output (affiliation just appears as affiliation (without showing the institution, and author note just disappeared), but with the same code in the template, they work just as expected. So I'm assuming it's something to do with my YAML header? 

**To Reproduce**

~~~yaml
---
title             : "The final draft"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

documentclass     : "apa6"
class             : doc, 12pt, twoside

output:
  papaja::apa6_pdf:
    latex_engine: xelatex

bibliography      : ["references.bib"]

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

mainfont: Times 

header-includes:
  - \usepackage{setspace}\doublespacing
  - \usepackage{float}
  - \setcounter{tocdepth}{3}
  - \shorttitle{}
---
~~~

**Expected behavior**
affiliation and author note to appear on the first page 

**Screenshot**
The YAML: 
<img width="1024" alt="Screenshot 2020-09-17 at 10 25 00" src="https://user-images.githubusercontent.com/57488005/93412845-8cf56580-f8d0-11ea-922f-ab06ff1003c6.png">
<img width="868" alt="Screenshot 2020-09-17 at 10 26 07" src="https://user-images.githubusercontent.com/57488005/93412854-8f57bf80-f8d0-11ea-902f-6d33c196a512.png">

the first page of the PDF output:
<img width="406" alt="Screenshot 2020-09-17 at 10 18 14" src="https://user-images.githubusercontent.com/57488005/93412939-c201b800-f8d0-11ea-996c-c9d57a08d7cb.png">

**Additional context**

**Comment by efkccc** [comment]
Let me know if more info is needed! Any help would be appreciated!

**Comment by crsh** [comment]
That's odd. What version of `papaja` are you using?

**Comment by efkccc** [comment]
not sure which version I was using before but worked fine after updating to the latest one! Thanks a lot!
