### ISSUE TITLE
error message for landscape figure/page in papaja :  " ! Undefined control sequence. <recently read> \DeclareDelayedFloatFlavor "

### ISSUE THREAD

**Issue by efkccc** [crsh/papaja#413]
**Describe the bug**
Hi, thanks for making landscape figures possible here (https://gist.github.com/crsh/f1739bc4a6ccc634b72c11222c1c9cdc )--they are really helpful. 

I copied your .rmd file and it worked fine in my R but when I tried this with my own markdown file, it didn't work with my own figures, and also for figure set exactly same to your example (see below). Not sure if this is because of something in my YAML header or the chunk info? 

(I'm updated to the latest version of papaja)

**Expected behavior**
knitted file to have landscape figure 

**Screenshots**
YAML header
<img width="655" alt="Screenshot 2020-09-21 at 03 22 48" src="https://user-images.githubusercontent.com/57488005/93720139-bb698e00-fbb9-11ea-8f7c-70501b22deb2.png">

the chunk info for the figure demonstrated in the original post
<img width="748" alt="Screenshot 2020-09-21 at 03 23 17" src="https://user-images.githubusercontent.com/57488005/93720147-ccb29a80-fbb9-11ea-9661-c5953e85ae14.png">

chunck info for my own figure
<img width="932" alt="Screenshot 2020-09-21 at 03 25 47" src="https://user-images.githubusercontent.com/57488005/93720202-25823300-fbba-11ea-99b3-0c026a28d4f9.png">

The markdown console gives the following error message: 
<img width="449" alt="Screenshot 2020-09-21 at 03 38 09" src="https://user-images.githubusercontent.com/57488005/93720485-dfc66a00-fbbb-11ea-85b4-13147374877b.png">

**Comment by crsh** [comment]
I think the problem is that you are using the `doc` class option which does not load the LaTeX `endfloat` package, so `\DeclareDelayedFloatFlavor` is not defined. You should be able to resolve this problem by omitting this command from the header includes.
