### ISSUE TITLE
apa_table font size meaning?

### ISSUE THREAD

**Issue by jasonmoy28** [crsh/papaja#418]
What does scriptsize, normalsize, footnotesize means in terms of MS Word font size? I am new to LaTex. I tried googled it, but it seems that it depends of the default size of the document. I would really appreciate your answer.

**Comment by crsh** [comment]
Indeed. You can control the base font size via the class options (`10pt`, `11pt`, or `12pt`). The approximate corresponding font sizes in `pt` are listed [here](https://tex.stackexchange.com/a/24600/11001).
