### ISSUE TITLE
Allow rows have same names in apa_table?

### ISSUE THREAD

**Issue by jasonmoy28** [crsh/papaja#419]
I see it in #271 that apa_table allow the column name to be the same. I wonder whether apa_table also support row name to be the same. Thanks.

**Comment by crsh** [comment]
Hi Jason, as a property of the `data.frame` (`rowname(x) <- ...`), repeated rownames are not supported by `data.frame` objects and this is unrelate to `apa_table()`. But if you add a separate column for the row names than that column can easily accomodate reoccuring values. Does that make sense?

**Comment by jasonmoy28** [comment]
Thanks. Also, thank you for creating the package. It is great!

**Comment by crsh** [comment]
You're welcome. Nice to hear it's useful to you!
