### ISSUE TITLE
apa_table() doubles row names

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#42]
When I use apa_table() to insert a table into a papaja::apa6_pdf document, this table will have two rows containing the row names of the matrix that I passed to apa_table() (also happens if I pass a data.frame instead). If I replicate the example from the ?apa_table() documentation, it looks like this:

--------------------------------------

  Descriptives     speed   dist 

--------------------------------------

Mean Mean       15.4   42.98 

  SD     SD          5.29   25.77 

 Min  Min                4      2   

 Max  Max             25     120  

----------------------------------

This does not happen if I directly call kable() instead. I am using papaja_0.1.0.9000.

**Comment by crsh** [comment]
I think I fixed this bug with the last update. Try reinstalling papaja from github (`devtools::install_github("crsh/papaja")`) and let me know if the problem persists.

**Comment by m-Py** [comment]
Ah okay, after updating the header I got my document it to render again ;) 

Indeed, after updating to the most recent version, this problem is solved. Alay, the column headers now behave unexpectedly: If my colname is "Hits", the column heading is "\multicolumn{1}{c}{Hits}".

Columns in your example.pdf from this repository also look like this ("\multicolumn{1}{c}{speed}") when I "re-render" the example.Rmd, indicating this problem might not occur on your system. Maybe this could be related to my LaTex?

**Comment by m-Py** [comment]
This distortion does not appear for the regression table 2 in your example.pdf. Here my_results$table is passed to apa_table(). my_results$table is a data.frame, which does not have rownames, but instead has a column which contains the rownames.

**Comment by crsh** [comment]
Indeed, good catch. This is related to the `escape` parameter. Let me take a closer look. I may be able to provide a patch for this bug later today.

**Comment by crsh** [comment]
Okay, I fixed the multicolumn-issue you mentioned and will push it to the master branch. I'm confused about your second post, though.

> my_results$table is a data.frame, which does not have rownames, but instead has a column which contains the rownames.

The row names of `my_results$table` are 1:2 and these row names are not given in the table. Are you referring to the names of the terms, which are a column in `my_results$table` rather than row names?

**Comment by m-Py** [comment]
You are right, the R rownames are 1:2, I meant the 'semantical' rownames, which are Intercept and Speed, my fault.

Thanks for fixing the multicolumn issue!
