### ISSUE TITLE
not for R4.0.3?

### ISSUE THREAD

**Issue by vinegarlic** [crsh/papaja#421]
Hi, I try to install packages. However, there are some errors

"Warning in install.packages :
  package ‘papaja’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages"

Is it not available for the latest R version? Thank you,

**Comment by crsh** [comment]
Hi, `papaja` has not yet been released to CRAN. Please refer to the README for [instructions on how to install the package](https://github.com/crsh/papaja#installation).
