### ISSUE TITLE
double comma if I leave out 'note' in template

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#43]
If I do not specify a note in my .Rmd template, I erroneously get two commas on the first page of the manuscript:

Correspondence concerning this article should be addressed to Donald Duck**, ,**
Gansstr. 2, 12345 Entenhausen, Germany.

I can replicate this in the example file example.Rmd of this repository if I simply remove the note:

note: |  
> Currently, a development version of `papaja` is available at https://github.com/crsh/papaja.

I do not think that this is the desired behaviour, if I do not want to insert a note?

**Comment by crsh** [comment]
Again, good catch. I'll look into it.
