### ISSUE TITLE
Error: pandoc document conversion failed with error 83

### ISSUE THREAD

**Issue by DominiqueMakowski** [crsh/papaja#430]
Hi @crsh, we're struggling to knit a paper, and this error keeps popping out:

```
[WARNING] Deprecated: pandoc-citeproc filter. Use --citeproc instead.
Error running filter pandoc-citeproc:
Could not find executable pandoc-citeproc
Error: pandoc document conversion failed with error 83
In addition: Warning message:
package 'tibble' was built under R version 4.0.2 
Execution halted
```

It seems to be similar to the one reported here:

https://community.rstudio.com/t/papaja-rmd-knit-problem-with-error-pandoc-document-conversion-failed-with-error-83/86818

Any ideas of what's going on?

I have the latest pandoc / markdown. Tagging @Tam-Pham

**Comment by crsh** [comment]
I this the same issues as described in https://github.com/crsh/papaja/issues/427?

**Comment by DominiqueMakowski** [comment]
Oops, indeed 😁 closing for duplicate
