### ISSUE TITLE
apa_print.list reports wrong error-df for lm model comparison?

### ISSUE THREAD

**Issue by LukasWallrich** [crsh/papaja#433]
Thanks for this very helpful package! Just a small potential bug: As I understand it, model comparisons should report the error degrees of freedom from the test of the difference (i.e. the bottom row in the `anova()` output. Currently, apa_print.list reports the error df from the top row, which I think is incorrect? Shouldn't it be F(1,28) in the example below?

``` r
mod1 <- lm(mpg ~ wt + cyl, mtcars)
mod2 <- lm(mpg ~ wt * cyl, mtcars)
anova(mod1, mod2)
#> Analysis of Variance Table
#> 
#> Model 1: mpg ~ wt + cyl
#> Model 2: mpg ~ wt * cyl
#>   Res.Df    RSS Df Sum of Sq      F  Pr(>F)  
#> 1     29 191.17                              
#> 2     28 156.98  1    34.196 6.0995 0.01988 *
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
papaja::apa_print(list(mod1, mod2), boot = 0)$statistic
#> $model2
#> [1] "$F(1, 29) = 6.10$, $p = .020$"
```

<sup>Created on 2020-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mariusbarth** [comment]
Hi @LukasWallrich, I think you are completely right, the denominator degrees of freedom should be `n - k - 1`, where `k` is the number of predictors of the *unconstrained* (i.e., more complex) model. In this case, this would be `n - k - 1 = 32 - 3 - 1 = 28`. I will try to commit a bug fix asap. @crsh Or am I missing something? I checked Eid et al. (5th ed.), p. 652.

**Comment by crsh** [comment]
Thanks for reporting this. Not sure how that happened...
