### ISSUE TITLE
auto_invert argument does not override automatic invert in apa_print.BFBayesFactor

### ISSUE THREAD

**Issue by jstevens5** [crsh/papaja#440]
**Describe the bug**
When using `apa_print` on {BayesFactor} output, the `auto_invert` argument does not override the default value set to `TRUE`.

**To Reproduce**
``` r
suppressPackageStartupMessages(library(BayesFactor))
library(papaja)
(test_corr <- correlationBF(mtcars$wt, mtcars$qsec))
#> Bayes factor analysis
#> --------------
#> [1] Alt., r=0.333 : 0.5755118 ±0%
#> 
#> Against denominator:
#>   Null, rho = 0 
#> ---
#> Bayes factor type: BFcorrelation, Jeffreys-beta*
apa_print(test_corr)$full_result
#> [1] ", $\\mathrm{BF}_{\\textrm{01}} = 1.74$"
apa_print(test_corr, auto_invert = FALSE)$full_result
#> [1] ", $\\mathrm{BF}_{\\textrm{01}} = 1.74$"
```

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Expected behavior**
When setting `auto_invert = FALSE`, the *BF<sub>10</sub>* should be returned rather than the *BF<sub>01</sub>*.

**Additional context**
As a side note, the `auto_invert` default set to `TRUE` was unexpected behavior. My preference would be for the default to be set to `FALSE` to ensure consistency in expected output. When set to `TRUE`, the user must check the subscripts for each result to determine if their values were inverted rather than assuming that all of their values are *BF<sub>10</sub>*. Therefore, users likely expect the output of `apa_print` to match the output of the {BayesFactor} function by default.

**Comment by crsh** [comment]
Hey Steven, thanks for pointing this out! It seems this was an issue whenever the object contained only one BF. Try the latest development version. Let me know if it fixes the issue. After thinking some more about this, I also followed your suggestion to default to `auto_invert = FALSE`. Again, thanks for raising this issue.

**Comment by jstevens5** [comment]
@crsh, the development version works perfectly. Any many thanks for changing the default.
