### ISSUE TITLE
increased reproducibility using groundhog would require CRAN deposit

### ISSUE THREAD

**Issue by alecristia** [crsh/papaja#441]
**Is your feature request related to a problem? Please describe.**
Papaja is awesome to render our papers reproducible -- but the package and the world evolves, so we need ways to declare an environment that guarantees reproducibility

**Describe the solution you'd like**
The groundhog R package tries to do that, and succeeds -- provided all packages one uses are on CRAN, but papaja isn't.

**Describe alternatives you've considered**
I've written to the groundhog makers about this:
https://github.com/CredibilityLab/groundhog/issues/67#issuecomment-790752783

**Additional context**
Happy to discuss alternatives further

**Comment by crsh** [comment]
Hi Alex, thanks for reaching out. I absolutely agree. Personally, I would recommend a more comprehensive approach to ensuring computational reproducibility, such as containers or virtual machines. I have documented setups using Docker and CodeOcean in the [manual](http://frederikaust.com/papaja_man/tips-and-tricks.html#reproducible-software-environments). Another well-established alternative to `groundhog` that works with `papaja` as is, is [`renv`](https://rstudio.github.io/renv/articles/renv.html). That being said, of course publishing `papaja` on CRAN would improve things and we are working hard on making that happen. The pandemic has cut deeply into my time budget but we are slowly moving things forward nonetheless.
