### ISSUE TITLE
LaTeX Error: Command \textgreek already defined when references include \textgreek symbols

### ISSUE THREAD

**Issue by jadenecke** [crsh/papaja#444]
**Describe the bug**
When I include a reference file generated by citavi which uses \textgreek{}, latex rises the following issue:

```
! LaTeX Error: Command \textgreek already defined.  
               Or name \end... illegal, see p.192 of the manual.
```

**To Reproduce**
use this bib file: https://gist.github.com/jadenecke/ed6fde314344f28b0c156d3cbdaccfef
ref [@Laflamme.1999] in a new manuscript

**Expected behavior**
Dont include two definitions of `\textgreek` in the header automatically:

```
\usepackage[shorthands=off,greek,main=english]{babel} 
\newcommand{\textgreek}[2][]{\foreignlanguage{greek}{#2}} 
```

**Additional context**
If one removes the `\newcommand{\textgreek}[2][]{\foreignlanguage{greek}{#2}}` line, everything renders perfectly (as far as i can tell). 

I am pretty unsure about whether this is a problem generated by papaja or with markdown/knitr in general.

**Comment by crsh** [comment]
Hi there, thanks for reaching out. I don't think I add a definition of `textgreek` anywhere, so I don't think this is related to `papaja`, but you could go ahead and try to render the same document but replace the output format with `pdf_document` or `bookdown::pdf_document2`. I see that the call to babel includes a `greek` setting. Do you have any idea where that might be coming from?

**Comment by jadenecke** [comment]
Seems not to be related to papaja. `pdf_document` and `bookdown::pdf_document2` both reproduce the error. The greek setting in babel is also included only if the references contain `\textgreek`. Any idea at whom to address this issue then?

**Comment by crsh** [comment]
Thanks for checking. I think this is most probably related to `pandoc`/`citeproc`, so I would check over there. This may be related: https://github.com/jgm/pandoc/issues/2727
