### ISSUE TITLE
Adding appendix causes special characters to not be displayed correctly

### ISSUE THREAD

**Issue by mschrein** [crsh/papaja#446]
Could be related to #353 and #283 

**Describe the bug**
When adding an appendix in the YAML header, special characters such as umlaute (ö) or the euro sign (€) are no longer displayed correctly. For example, ö is instead displayed as Ã¶. This occurs on the title page, the author note, and the text body. Citations are not affected (neither in-text nor in the reference section).

**To Reproduce**
```
---
title: "title"
shorttitle        : "shorttitle"
author:
  - name          : "Nöl"
    affiliation   : " 1"
affiliation:
  - id            : "1"
    institution   : "University of x"
authornote: |
  Again name Nöl.
abstract: |
   abstract.  
keywords          : ""
wordcount         : ""
bibliography      : ["references.bib"]
floatsintext      : yes
figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
csl               : "apa.csl"
documentclass     : "apa7"
classoption       : "man"
output            : papaja::apa6_pdf
appendix          : "appendix.Rmd"
header-includes:
  - \setlength\parindent{24pt}\setlength{\parskip}{0.0pt plus 1.0pt}
  - \raggedbottom
 body-includes:
  - \usepackage{upgreek}
  - \usepackage{multirow}
  - \usepackage{threeparttable}
  - \usepackage{epstopdf}
  - \usepackage{caption}
 ---

Some text body with the € sign.
```

Removing the appendix renders the special characters correctly.

**Additional context**
I already tried several things brought up in other issues (e.g., #350) such as changing the latex enginge to xelatex or manually inserting the special characters via ```'N\"{ö}l'``` (both single and double space) or ```"N`\"{ö}`{=latex}l"``` but nothing worked. All files are UTF-8 encoded and I am using a Windows machine. The addition of appendix in the YAML header does seem to be causal for this problem.

Thanks a lot in advance for your help and your work on this great project.

**Comment by mariusbarth** [comment]
Hi @crsh, I can replicate the error on Windows, too. It seems like the error occurs within `modify_input_file()`, as the temporary .rmd file already contains the encoding-related errors. However, I was hesitant to change the code, because I dimly remember there were some-encoding-related problems with Japanese and Chinese locales.

**Comment by mariusbarth** [comment]
Hi @mschrein, sorry for not responding more quickly. I just submitted a fix for this problem to the development branch. Hope it will also solve the problem on your machine. Can you install (via `remotes::install_github("crsh/papaja@devel")`) and verify that it now works?

**Comment by mschrein** [comment]
Hi @mariusbarth , it works from my side too, thanks a lot for the fix!

**Comment by mariusbarth** [comment]
Hi @mschrein, thank you for the quick response!
