### ISSUE TITLE
Theorem environment does not render with appropriate numbering

### ISSUE THREAD

**Issue by shirdekel** [crsh/papaja#447]
**Describe the bug**
`bookdown` theorem environment isn't rendering with the appropriate numbering scheme.

**To Reproduce**
Add the below theorem environment to a `papaja` template (for instance after `# Methods`).

````r
``` {theorem, test, echo = TRUE}
Theorem test
```
````

**Expected behavior**
Expected to render as "Theorem 1."

**Screenshots**
![Screen Shot 2021-04-16 at 11 59 44](https://user-images.githubusercontent.com/49865192/114961394-41c62400-9eac-11eb-9a9b-a7eccbcebdcf.png)

**Additional context**
According to the [`bookdown` theorem environment documentation](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems):

> Theorems are numbered by chapters by default. If there are no chapters in your document, they are numbered by sections instead. If the whole document is unnumbered (the output format option number_sections = FALSE), all theorems are numbered sequentially from 1, 2, …, N.

And this indeed works when I try it on the `bookdown-demo`.

I assumed that because `papaja` removes numbering anyway, that this should work out of the box, but even knitting with the following doesn't fix it:

```yml
output            :
  papaja::apa6_pdf:
    number_sections: false
```

**Session info**
```r
xfun::session_info("papaja")
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Locale: en_AU.UTF-8 / en_AU.UTF-8 / en_AU.UTF-8 / C / en_AU.UTF-8 / en_AU.UTF-8

Package version:
  assertthat_0.2.1  backports_1.2.1   base64enc_0.1.3   bookdown_0.21.10 
  broom_0.7.6.9001  cli_2.4.0         cpp11_0.2.7       crayon_1.4.1     
  digest_0.6.27     dplyr_1.0.5.9000  ellipsis_0.3.1    evaluate_0.14    
  fansi_0.4.2       generics_0.1.0    glue_1.4.2        graphics_4.0.2   
  grDevices_4.0.2   highr_0.8         htmltools_0.5.1.1 jsonlite_1.7.2   
  knitr_1.32        lifecycle_1.0.0   magrittr_2.0.1    markdown_1.1     
  methods_4.0.2     mime_0.10         papaja_0.1.0.9997 pillar_1.6.0     
  pkgconfig_2.0.3   purrr_0.3.4       R6_2.5.0          rlang_0.4.10     
  rmarkdown_2.7.10  rmdfiltr_0.1.3    stats_4.0.2       stringi_1.5.3    
  stringr_1.4.0     tibble_3.1.0      tidyr_1.1.3       tidyselect_1.1.0 
  tinylabels_0.2.1  tinytex_0.31.3    tools_4.0.2       utf8_1.2.1       
  utils_4.0.2       vctrs_0.3.7       xfun_0.22         yaml_2.2.1       
  zip_2.1.1        
```

**Comment by mariusbarth** [comment]
Hi @shirdekel,

thank you for reporting this bug, and sorry for responding so late. I just pushed a tiny fix to the development branch that should resolve the issue.

Best,
Marius

**Comment by shirdekel** [comment]
Fixed for me, thanks!

**Comment by mariusbarth** [comment]
Great, thanks for checking!
