### ISSUE TITLE
Misplaced quotes after punctuation using "nature.csl" citation style

### ISSUE THREAD

**Issue by Kyabdro** [crsh/papaja#448]
Hi everyone,

I have some experience with papaja, but I have a problem that I can't solve on my own.

I am writing an article, initially in APA standards, but now I need to switch to a different citation style.
So, I wanted to change my citation style by using this in the YAML: `csl: "nature.csl"`
The file 'nature.csl' was downloaded from https://github.com/citation-style-language/styles

However, the result is quite surprising... All the quotes in the text appear AFTER the punctuation.

For example, I write in the .Rmd file:
`There is growing evidence that the Covid-19 pandemic situation degraded mental health in the general population [@Vindegaard2020].`

And this is what I get:
> There is growing evidence that the Covid-19 pandemic situation degraded mental health in the general population .<sup>1</sup>

But I would like to get this:
> There is growing evidence that the Covid-19 pandemic situation degraded mental health in the general population <sup>[1]</sup>.

Where can the problem come from?

I would really appreciate your help!

EDIT: I tried the citation style in overleaf to see if the problem could be in the .csl file. It seems that the citation style works fine (number in brackets and before punctuation)! So the problem is elsewhere...

**Comment by Kyabdro** [comment]
Ok, so I've found a solution for the placement before punctuation here : https://stackoverflow.com/questions/62988281/how-to-move-superscript-citation-numbers-inside-of-punctuation-in-markdown-file

Solution: simply add this n the YAML
`notes-after-punctuation: false`

I've still no solution for the brackets, yet...

**Comment by mariusbarth** [comment]
One way (but possibly not the most elegant) is to modify `nature.csl`, changing line 108 from
```
    <layout vertical-align="sup" delimiter=",">
```
to
```
    <layout vertical-align="sup" prefix="[" suffix="]" delimiter=",">
```

**Comment by Kyabdro** [comment]
Thanks !
