### ISSUE TITLE
Adding preamble.tex and/or modifying css

### ISSUE THREAD

**Issue by jsmagnuson** [crsh/papaja#449]
Hello. Thanks for making papaja. It's really terrific!

I just submitted my first journal article using it and ran into problems. The layout staff don't know what to do with the code chunks and listings that are fine in single-column, full page format, but not in their 2-column format. I'm trying use the class 'jou' option to make 2 columns, but I can't figure out how to control the size of code and listing fonts (possibly by modifying the css, [as recommended here](https://stackoverflow.com/questions/25646333/code-chunk-font-size-in-rmarkdown-with-knitr-and-latex)), or how to using the latex package 'listings' to set listings to wrap ([as recommended here](https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html)). 

I'd be grateful for any advice, and my apologies if I've missed how one might do this in the documentation.

**Comment by mariusbarth** [comment]
Hi @jsmagnuson, thanks for the kind words! It would be great if you could ask this question [on stackoverflow using the papaja tag](https://stackoverflow.com/questions/tagged/papaja), because I think stackoverflow  is better suited to your question.
