### ISSUE TITLE
Table: The elements of a table are displayed inconsistently (1 element is different)

### ISSUE THREAD

**Issue by MeikeSteinhilber** [crsh/papaja#451]
**Describe the bug**
The elements of a table are displayed inconsistently. The first element is different.

**To Reproduce**
```
---
title: "Untitled"
output: papaja::apa6_pdf
---

```{r}
library(papaja)
types_ttests <- data.frame(
  arguments = c("X", "X", "X", "X"),
  two_sample = c("x", "x", "x", "x"),
  one_sample = c("x", "x", "x", "-")
)
apa_table(
  types_ttests,
  col.names = c("Arguments", "Two-sample Test", "One-sample Test"),
  caption = "Test"
)

```

**Expected behavior**
The element in the first column are identical and should be displayed among each other.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/78479286/115994375-feb82f00-a5d6-11eb-84a8-b42199725b5c.png)

**Appreciation**
The package is great and thank you so much for the work ❤️

**Comment by mariusbarth** [comment]
Hi @MeikeSteinhilber, this behavior is related to a bug that very recently appeared in the **knitr** package. It has already been fixed by the package authors, and updating to version 1.33 (available from CRAN) should fix the problem.

**Comment by MeikeSteinhilber** [comment]
Thank you! 👍 And thanks for the quick reply! It worked! 🎉

**Comment by mariusbarth** [comment]
Great!
