### ISSUE TITLE
midrules are not added when col.names = NULL in apa_table

### ISSUE THREAD

**Issue by kalenkovich** [crsh/papaja#452]
**Describe the bug**
If you have `col.names = NULL` in `apa_table`, `midrules` does not add lines.

**To Reproduce**

```r
library(papaja)
my_table <- t(apply(cars, 2, function(x) # Create data
  round(c(Mean = mean(x), SD = sd(x), Min = min(x), Max = max(x)), 2)
))

no.midrules <- apa_table(my_table)
yes.midrules <- apa_table(my_table, midrules = c(1))
no.midrules == yes.midrules  # FALSE

no.midrules <- apa_table(my_table, col.names = NULL)
yes.midrules <- apa_table(my_table, col.names = NULL, midrules = c(1))
no.midrules == yes.midrules  # TRUE
```

**Expected behavior**
`col.names = NULL` does not interact with `midrules`.

**Additional context**
Tried fixing by changing [these](https://github.com/crsh/papaja/blob/master/R/apa_table.R#L472-L475) lines to use `midrules` instead of `table_content_start + midrules` when `table_content_start` is empty but that did not work well when there are `col_spanners` set in addition to `col.names = NULL`.

**Comment by mariusbarth** [comment]
Hi @kalenkovich,

thank you for your bug report, that was super helpful! I just submitted a fix to the development branch that should solve the problem. If you like, you can try it out after installing from the development branch via `remotes::install_github("csrh/papaja@devel")`. Your example table looks like the following now:

![Bildschirmfoto von 2021-07-12 11-54-49](https://user-images.githubusercontent.com/9460245/125268483-09e24780-e308-11eb-9e89-68a96194c0b5.png)

It also works with column spanners:

![Bildschirmfoto von 2021-07-12 11-54-56](https://user-images.githubusercontent.com/9460245/125268527-149cdc80-e308-11eb-959b-331486c6e14d.png)

**Comment by kalenkovich** [comment]
Hi, @mariusbarth! It looks like everything works as expected in the development version. Thank you for taking care of this.

**Comment by mariusbarth** [comment]
Nice, thank you for taking the time to check!
