### ISSUE TITLE
Example of how to fix LaTeX column widths using apa_table (for documentation)

### ISSUE THREAD

**Issue by conig** [crsh/papaja#454]
Hi @crsh 

Here's the reproducible example of how to fix LaTeX column widths using apa_table as [requested](https://twitter.com/jamesconigrave/status/1392369424934477825). The table content and layout is unoriginal, and I've included it in supps for a paper still in devel so no citation at this stage. But you could include a citation for the scale content itself if you're interested ([Bradley 2007](http://doi.org/10.1111/j.1530-0277.2007.00403.x)).

I've reopitimised the code for the main APA template (I had used the knitr pdf template which has smaller font).

I used an array stretch command to increase row height but this isn't necessary.

\renewcommand{\arraystretch}{1.2}

```{r results = "asis"}
audit_table <- structure(
  list(
    Questions = c(
      "How often do you have a drink containing alcohol?",
      "How many standard drinks of alcohol do you drink on a typical day when you are drinking?",
      "How often do you have 5 or more drinks on one occasion?"
    ),
    `0` = c("Never", "1–2", "Never"),
    `1` = c("Monthly or less", "3-4", "Less than monthly"),
    `2` = c("2-4 times per month", "5-6", "monthly"),
    `3` = c("2-3 times per week","7-9", "Weekly"),
    `4` = c("4+ times per week", "10+", "Daily or almost daily")
  ),
  class = "data.frame",
  row.names = c(NA, 3L)
)

papaja::apa_table(
  audit_table,
  caption = "AUDIT-C scoring table",
  align = c("m{8cm}", rep("m{2cm}", 5)),
  col_spanners = list("Score" = c(2,6)),
  note = "Item scores are summed. Women who score 3+ and men who score 4+ are at-risk",
  landscape = TRUE
)
```

![image](https://user-images.githubusercontent.com/12742211/118056565-879fda80-b3cd-11eb-97fb-4e60892b049e.png)

**Comment by crsh** [comment]
Excellent, thank you!

**Comment by crsh** [comment]
I've added the example to both the [manual](http://frederikaust.com/papaja_man/reporting.html#fixed-width-columns) and made a note of this align-option in [the documentation of `apa_table()`](https://github.com/crsh/papaja/commit/276bd5e07820b4bca8e95db23f72eef79fbdb8a7). Thanks again. Let me know when one of you papers with the table is out and I'll add the citations.

**Comment by conig** [comment]
Will do. Thanks!

**Comment by conig** [comment]
> I've added the example to both the [manual](http://frederikaust.com/papaja_man/reporting.html#fixed-width-columns) and made a note of this align-option in [the documentation of `apa_table()`](https://github.com/crsh/papaja/commit/276bd5e07820b4bca8e95db23f72eef79fbdb8a7). Thanks again. Let me know when one of you papers with the table is out and I'll add the citations.

@crsh, this paper is up now in case you're still interested in the citaiton:
https://doi.org/10.1186/s13722-022-00306-5
