### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#459]
Review the following files and check the extent to which the documentation is up-to-date

- [x] apa6_formats.R
- [x] apa_barplot.R
- [x] apa_beeplot.R
- [x] apa_factorial_plot.R
- [x] apa_lineplot.R
- [x] apa_print.R
- [x] apa_print_BFBayesFactor.R
- [x] apa_print_anova.R
- [x] apa_print_emm_lsm.R
- [x] apa_print_glht.R
- [x] apa_print_glm.R
- [x] apa_print_htest.R
- [x] apa_print_list.R
- [x] apa_print_manova.R
- [x] apa_print_merMod.R
- [x] apa_print_wsci.R
- [x] apa_results_table.R
- [x] apa_table.R
- [x] arrange_anova.R
- [x] arrange_regression.R
- [x] calculations.R
- [x] cite_r.R
- [x] fast_aggregate.R
- [x] fetch_zotero_refs.R
- [x] in_paren.R
- [x] meta.R
- [x] print_anova.R
- [x] print_model_comp.R
- [x] printnum.R
- [x] r_refs.R
- [x] remove_comments.R
- [x] render_appendix.R
- [x] revision_letter_format.R
- [x] theme_apa.R
- [x] utils.R
- [x] utils_for_plots.R
- [x] variable_label.R
- [x] word_title_page.R 
- [x] README.Rmd

**Comment by crsh** [comment]
I implemented your suggested changes and reviewed/revised the rest of the documentation and README. @mariusbarth, if you are happy with the README, I think we can close this issue.

**Comment by mariusbarth** [comment]
I'm super happy with the README, and also with "Typeset Statistical Results..."! Only one thing I was wondering: Should we use `<code>` or `<b>` in the README?

**Comment by mariusbarth** [comment]
yes

**Comment by crsh** [comment]
Do you have a preference? I see `<code>` used more frequently, but `<b>` is what the R documentation uses, right?

**Comment by mariusbarth** [comment]
Exactly. That's why I have a preference for boldface.

**Comment by crsh** [comment]
Switched to `<b>` in the last commit.

**Comment by mariusbarth** [comment]
Perfect, thanks!
