### ISSUE TITLE
supress NULL output of data.table plots

### ISSUE THREAD

**Issue by saladspices** [crsh/papaja#46]
When printing plots from a data.table in the form DT[,plot(xy)], data.table returns NULL next to the plot. This NULL is also printed in the apa manuscript.

Example:

```{r fig.cap = "Example Plot"}
dat <- data.table(x=1:10,y=11:20,subj=rep(c(1,2),5))
dat[subj==1,plot(x,y)]
dat[subj==2,lines(x,y)]
```

**Comment by mariusbarth** [comment]
Since `NULL` is the result of your code, and you don't want your result to be printed, try `results='hide'` in your chunk options.

**Comment by saladspices** [comment]
Of course! Thanks for the quick reply!
