### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by AhmedThahir** [crsh/papaja#465]
**Describe the bug**
My images keep getting appended to the end, despite using correct syntax.

**To Reproduce**
```{r knit, fig.cap = "(ref:knit-caption)", fig.align = "center", echo = FALSE}
knitr::include_graphics("gradient descent.png", dpi = 108)
```

Fames ac turpis egestas sed tempus. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Aliquet eget sit amet tellus cras. Enim neque volutpat ac tincidunt. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Cursus in hac habitasse platea dictumst quisque sagittis purus. Scelerisque mauris pellentesque pulvinar pellentesque. A iaculis at erat pellentesque adipiscing commodo elit at. Bibendum ut tristique et egestas quis.

**Expected behavior**
I expect the image to be at the position i've entered the syntax for the image, i.e., just above the dummy text

**Screenshots**
![image](https://user-images.githubusercontent.com/26618217/126861304-3193cf6a-bdc5-444c-bac1-6d7797fdfea5.png)

**Additional context**
Any help would be appreciated.

**Comment by mariusbarth** [comment]
Hi @AhmedThahir, did you also specify

```
floatsintext: yes
```

 in the YAML front matter?

**Comment by AhmedThahir** [comment]
Yes, that fixed the image location issue.

![image](https://user-images.githubusercontent.com/26618217/126877739-b1ae3258-0641-477b-9ea3-e2d41767adf6.png)


However, I've got 2 questions now:
1. How to center align the figure caption if i use `![Gradient Descent]("gradient descent.png")`
2. The list of figures doesn't appear even though `figurelist        : yes` is used in the YAML front matter

**Comment by mariusbarth** [comment]
I think questions regarding the usage of papaja are best suited for stackoverflow. I will close this issue because  it is my impression that it is not related to a bug.
