### ISSUE TITLE
Cannot turn off section numbering

### ISSUE THREAD

**Issue by Joobing** [crsh/papaja#468]
Since updating Papaja (packageVersion("papaja"): ‘0.1.0.9997’), ms-word knitted documents all have numbered sections. I would like to turn off this feature without adding {-} after each header-- there are too many across manuscripts.
In the YAML header, "numbersections    : false" next to "title:" or "number_sections   : false" after "output:" or both did not help. Niether does substituting false with no.
Knitting below example in RStudio would still produce a manuscript with numbered headers despite specifying these options. 

---
title             : "The title"
shorttitle        : "Title"
numbersections    : false

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  
  
keywords          : "keywords"
wordcount         : "X"

#bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_word
number_sections   : false
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. 

## Data analysis

# Results

# Discussion

\newpage

# References

**Comment by mariusbarth** [comment]
Hi @Joobing! Unfortunately, I cannot reproduce the problem. Can you provide the output from `sessionInfo()`?

**Comment by Joobing** [comment]
I attached the example rmd file so that you can just knit that to reproduce the issue
[test.zip](https://github.com/crsh/papaja/files/6932280/test.zip)
. Unfortunately the comment section here knitted my code in its own way, so if you copy pasted probably it did not work. 

Below is my session info:

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                       LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] papaja_0.1.0.9997

loaded via a namespace (and not attached):
 [1] compiler_4.0.2  htmltools_0.5.0 tools_4.0.2     yaml_2.2.1      rmarkdown_2.8   knitr_1.33      xfun_0.23       digest_0.6.25   rlang_0.4.11    evaluate_0.14

**Comment by mariusbarth** [comment]
Sorry, I still can't reproduce the error, even on a Windows machine with R 4.0.5 I don't get numbered sections with your example Rmd file. Can you add the output from the following calls?

```
rmarkdown::pandoc_version()
installed.packages()[, "Version", drop = FALSE]

**Comment by Joobing** [comment]
> rmarkdown::pandoc_version()
[1] ‘2.11.4’

> installed.packages()[, "Version", drop = FALSE]
              Version     
abind         "1.4-5"     
arm           "1.11-2"    
askpass       "1.1"       
assertthat    "0.2.1"     
babel         "0.3-0"     
backports     "1.2.1"     
base          "4.0.2"     
base64enc     "0.1-3"     
BH            "1.75.0-0"  
blob          "1.2.1"     
bookdown      "0.22"      
boot          "1.3-28"    
brew          "1.0-6"     
brio          "1.1.2"     
broom         "0.7.8"     
cachem        "1.0.5"     
callr         "3.7.0"     
car           "3.0-10"    
carData       "3.0-4"     
cellranger    "1.1.0"     
checkmate     "2.0.0"     
class         "7.3-19"    
cli           "2.5.0"     
clipr         "0.7.1"     
cluster       "2.1.2"     
coda          "0.19-4"    
codetools     "0.2-18"    
colorspace    "2.0-1"     
commonmark    "1.7"       
compiler      "4.0.2"     
conquer       "1.0.2"     
covr          "3.5.1"     
cpp11         "0.2.7"     
crayon        "1.4.1"     
credentials   "1.3.0"     
crosstalk     "1.1.1"     
curl          "4.3.1"     
data.table    "1.14.0"    
datasets      "4.0.2"     
DBI           "1.1.1"     
dbplyr        "2.1.1"     
desc          "1.3.0"     
devtools      "2.3.0"     
diffobj       "0.3.4"     
digest        "0.6.25"    
dplyr         "1.0.6"     
DT            "0.18"      
dtplyr        "1.1.0"     
dummies       "1.5.6"     
ellipsis      "0.3.2"     
evaluate      "0.14"      
ez            "4.4-0"     
fansi         "0.5.0"     
farver        "2.1.0"     
fastmap       "1.1.0"     
forcats       "0.5.1"     
foreign       "0.8-81"    
Formula       "1.2-4"     
fs            "1.5.0"     
gargle        "1.1.0"     
gender        "0.5.4"     
generics      "0.1.0"     
gert          "1.3.0"     
ggplot2       "3.3.3"     
gh            "1.3.0"     
git2r         "0.28.0"    
gitcreds      "0.1.1"     
glue          "1.4.2"     
googledrive   "1.0.1"     
googlesheets4 "0.3.0"     
graphics      "4.0.2"     
grDevices     "4.0.2"     
grid          "4.0.2"     
gridExtra     "2.3"       
gsl           "2.1-6"     
gsubfn        "0.7"       
gtable        "0.3.0"     
haven         "2.4.1"     
highr         "0.9"       
Hmisc         "4.5-0"     
hms           "1.1.0"     
htmlTable     "2.2.1"     
htmltools     "0.5.0"     
htmlwidgets   "1.5.3"     
httr          "1.4.2"     
ids           "1.0.1"     
igraph        "1.2.6"     
ini           "0.3.1"     
isoband       "0.2.4"     
jpeg          "0.1-8.1"   
jsonlite      "1.7.2"     
KernSmooth    "2.23-20"   
knitr         "1.33"      
labeling      "0.4.2"     
later         "1.2.0"     
lattice       "0.20-44"   
latticeExtra  "0.6-29"    
lavaan        "0.6-8"     
lazyeval      "0.2.2"     
lifecycle     "1.0.0"     
lme4          "1.1-27"    
lubridate     "1.7.10"    
magrittr      "2.0.1"     
maptools      "1.1-1"     
markdown      "1.1"       
MASS          "7.3-54"    
Matrix        "1.3-4"     
matrixcalc    "1.0-4"     
MatrixModels  "0.5-0"     
matrixStats   "0.59.0"    
MBESS         "4.8.0"     
memoise       "2.0.0"     
methods       "4.0.2"     
mgcv          "1.8-36"    
mi            "1.0"       
mime          "0.10"      
minqa         "1.2.4"     
mnormt        "2.0.2"     
modelr        "0.1.8"     
MOTE          "1.0.2"     
munsell       "0.5.0"     
mvtnorm       "1.1-2"     
nlme          "3.1-152"   
nloptr        "1.2.2.2"   
NLP           "0.2-1"     
nnet          "7.3-16"    
numDeriv      "2016.8-1.1"
OpenMx        "2.19.5"    
openssl       "1.4.4"     
openxlsx      "4.2.3"     
papaja        "0.1.0.9997"
parallel      "4.0.2"     
pbivnorm      "0.6.0"     
pbkrtest      "0.5.1"     
pillar        "1.6.1"     
pkgbuild      "1.2.0"     
pkgconfig     "2.0.3"     
pkgload       "1.2.1"     
plyr          "1.8.6"     
png           "0.1-7"     
praise        "1.0.0"     
prettyunits   "1.1.1"     
processx      "3.5.2"     
progress      "1.2.2"     
promises      "1.2.0.1"   
proto         "1.0.0"     
ps            "1.6.0"     
purrr         "0.3.4"     
quantreg      "5.86"      
R6            "2.5.0"     
rappdirs      "0.3.3"     
rcmdcheck     "1.3.3"     
RColorBrewer  "1.1-2"     
Rcpp          "1.0.6"     
RcppArmadillo "0.10.5.0.0"
RcppEigen     "0.3.3.9.1" 
RcppParallel  "5.1.4"     
readr         "1.4.0"     
readstata13   "0.10.0"    
readxl        "1.3.1"     
rematch       "1.0.1"     
rematch2      "2.1.2"     
remotes       "2.4.0"     
reprex        "2.0.0"     
reshape       "0.8.8"     
reshape2      "1.4.4"     
rex           "1.2.0"     
rio           "0.5.26"    
rlang         "0.4.11"    
rmarkdown     "2.8"       
rmdfiltr      "0.1.3"     
roxygen2      "7.1.1"     
rpart         "4.1-15"    
rpf           "1.0.7"     
rprojroot     "2.0.2"     
RSiena        "1.3.0"     
rstudioapi    "0.13"      
rversions     "2.1.1"     
rvest         "1.0.0"     
scales        "1.1.1"     
selectr       "0.4-2"     
sem           "3.1-11"    
semTools      "0.5-4"     
sessioninfo   "1.1.1"     
slam          "0.1-48"    
sp            "1.4-5"     
SparseM       "1.81"      
spatial       "7.3-14"    
splines       "4.0.2"     
StanHeaders   "2.21.0-7"  
stargazer     "5.2.2"     
statmod       "1.4.36"    
stats         "4.0.2"     
stats4        "4.0.2"     
stringi       "1.6.2"     
stringr       "1.4.0"     
survival      "3.2-11"    
sys           "3.4"       
tcltk         "4.0.2"     
testthat      "3.0.2"     
tibble        "3.1.2"     
tidyr         "1.1.3"     
tidyselect    "1.1.1"     
tidyverse     "1.3.1"     
tinytex       "0.32"      
tm            "0.7-8"     
tmvnsim       "1.0-2"     
tools         "4.0.2"     
translations  "4.0.2"     
usethis       "2.0.1"     
utf8          "1.2.1"     
utils         "4.0.2"     
uuid          "0.1-4"     
vctrs         "0.3.8"     
viridis       "0.6.1"     
viridisLite   "0.4.0"     
waldo         "0.2.5"     
whisker       "0.4"       
withr         "2.4.2"     
xfun          "0.23"      
XML           "3.99-0.6"  
xml2          "1.3.2"     
xopen         "1.0.0"     
xtable        "1.8-4"     
yaml          "2.2.1"     
zip           "2.2.0"

**Comment by mariusbarth** [comment]
Hi @Joobing, can you try installing the development version of **papaja** via `remotes::install_github("crsh/papaja@devel")` and check if the problem persists?
