### ISSUE TITLE
RMarkdown syntax whithin apa_table()

### ISSUE THREAD

**Issue by Misch007** [crsh/papaja#473]
Hey!

I am not sure if I am overseeing something, maybe there is an easy solution for this already (sorry if this is the case) but so far I haven't found one:

When I am passing a manually created `data.frame` to `apa_table()` with row names / column names / values containing RMarkdown syntax, for example `"$p$"` or `"$p > .001$"`, and try to knit it, it will not work and just print it as it is. If I use `label_variable(df, p="$p$)` it does work ofc as expected, but this is my solution only for column names, not for the other locations within a table. The same also accounts for the `note = "$p$"` beneath an `apa_table()`. 

I am curious what you think of this and if it is possible. If a solution already exists, I'd be thankful for some help on this one!
Best regards and thank you in advance
Mischa

**Comment by mariusbarth** [comment]
Hi @Misch007, can you post this question on stackoverflow? I think it would question + answer will be very helpful for other users, too.
