### ISSUE TITLE
Revision Letter Reference to Text Multiple Paragraphs

### ISSUE THREAD

**Issue by karchjd** [crsh/papaja#475]
I am currently writing a revision letter using papaja. How do I include references to text contain multiple paragraphs? Obviously, 

```
> Paragraph 1
Paragraph 2
```

fails.

**Comment by jvcasillas** [comment]
You can use

> Paragraph 1 
>
> Paragraph 2


> I am currently writing a revision letter using papaja. How do I include references to text contain multiple paragraphs? Obviously, 
> 
> 
> 
> 
> 
> ```
> 
> > Paragraph 1
> 
> Paragraph 2
> 
> ```
> 
> 
> 
> 
> 
> fails.

**Comment by crsh** [comment]
I was about to suggest the same thing. Thanks, @jvcasillas. In the future, if you have questions related to the use of `papaja` StackOverflow has a [`papaja`-tag](https://stackoverflow.com/questions/tagged/papaja) and is a great place to get answers.
