### ISSUE TITLE
Prune suggests

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#477]
I'm under the impression that we can probably shave off some suggests. First impressions from a quick skim:

- `tinytex` is, of course, recommended but not used anywhere in the package and can probably just be removed
- `carData` is only used to load data for one test; we can probably use a different dataset here or simulate one
- `downloader` is used in `fetch_zotero_refs()`, which I think should probably be removed or at least moved to a different package
- `lsmeans` can probably be safely replaced by `emmeans`
- Can we remove `MBESS` in favor of `effectsize`? That would also take care of the  `gsl` issue.
- ~~Do we need `spelling` at all?~~
- Do we need to list `covr`?

**Comment by mariusbarth** [comment]
- I think we can easily remove carData, downloader, and spelling (where do we even use this one?).
- Don't know if it is possible to remove covr and still use its CI, but worth a try.
- I would opt for removing tinytex, but we should then maybe check if TeX is available on startup of papaja (with recommendations how to install tinytex)
- Regarding MBESS, I don't have an opinion, yet.

**Comment by crsh** [comment]
> I would opt for removing tinytex, but we should then maybe check if TeX is available on startup of papaja (with recommendations how to install tinytex)

Hmm, but how does the current situation with `tinytex` in suggests help here?

**Comment by mariusbarth** [comment]
The default in `install.packages()` is to install "hard" dependencies and Suggests of the package itself, plus  "hard" dependencies for all dependencies. Hence, having tinytex in Suggests ensures that a tex distribution is available

**Comment by mariusbarth** [comment]
One more idea: base64enc is only used to create a hashed name for a temporary file. It is most likely very easy to accomplish a similar result via `base::tempfile()`.

**Comment by crsh** [comment]
According to the documentation this is the default:

> The default, NA, means c("Depends", "Imports", "LinkingTo").

From this, I would think Suggests are not installed?

**Comment by mariusbarth** [comment]
You are, right, what I remembered was the behavior for `depends = TRUE`. So yeah, doesn't really make a difference then. I also think the message you get when first trying to render to pdf is informative enough.

**Comment by crsh** [comment]
I added `spelling` to spell check documentation and vignettes on every local R CMD check. Just tried it and it was worth it. We should keep it. ;)

Unfortunately, `MBESS` cannot be replaced by `effectsize` at this point.
