### ISSUE TITLE
class: jou not working

### ISSUE THREAD

**Issue by saladspices** [crsh/papaja#48]
When using `class: jou` I get the error:

`! LaTeX Error: Something's wrong--perhaps a missing \item.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                                                                       
l.141 
pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43`

This happens with newest papaja, R 3.2.1 and newest RStudio 0.99.442 under Windows 10 with MikTeX and Ubuntu 14.04 with TeX Live. All documents I tried work fine with `class: doc` and `class: man`. This error is reproducible with the standard example document. Please correct me if I'm missing something here.

**Comment by crsh** [comment]
You're right, thanks for alerting me to this problem. Unfortunately, this is a very vague error that can result from a number of different problems in the `apa6` class. I'm away on a workshop this week, but I'll try to figure out what's going on as soon as possible and report back.

**Comment by crsh** [comment]
So I think I fixed this one. Let me know if you have any other problems.

**Comment by saladspices** [comment]
works like a charm. thanks!
