### ISSUE TITLE
Development cycle after first CRAN release

### ISSUE THREAD

**Issue by mariusbarth** [crsh/papaja#480]
Hi @crsh,

for the era coming when we have **papaja** on CRAN, I wondered whether we might want to change our development cycle. In the past, it was my impression that, in order to have a stable version on the master branch, many features accumulated on the development branch, which resulted in a heavy review burden when merging the development branch into the master branch.

I would propose the following changes:
- Rename the default branch from `master` to `main`.
- There is one continuous branch, the `main` branch, with a stable yet "development" version of **papaja** (e.g., version 0.2.0.9000)
- New features are implemented on feature branches that are merged into the `main` branch whenever a feature is ready and properly reviewed.
- Bug fixes are also implemented on feature branches, but we may skip code review if it is only a tiny fix.

**Comment by crsh** [comment]
Sure, we tried to implement this style of doing things before, but somehow we slid back into the mess we currently have. I'm all for it.
