### ISSUE TITLE
Appendix heading isn't included in the TOC

### ISSUE THREAD

**Issue by shirdekel** [crsh/papaja#484]
**Describe the bug**
When adding an appendix through the YAML option, the heading isn't included in the TOC.

**To Reproduce**
Knit `index.Rmd` from https://github.com/shirdekel/papaja-reprex-appendix.

**Expected behavior**
The appendix headings to render in the TOC as per their hierarchy.

Knitting the same body content with `bookdown::pdf_document2` and `# (APPENDIX) Appendix {-}` shows the expected behaviour. See `index.Rmd` from https://github.com/shirdekel/bookdown-reprex-appendix.

**Screenshots**
`papaja` TOC in Mac Preview:

<img width="273" alt="Screen Shot 2021-10-07 at 12 44 26 pm" src="https://user-images.githubusercontent.com/49865192/136307611-4a30e549-d715-456a-9a64-3ffc8169f24b.png">

`bookdown` TOC in Mac Preview:

<img width="273" alt="Screen Shot 2021-10-07 at 12 55 12 pm" src="https://user-images.githubusercontent.com/49865192/136308283-52371f46-93e7-4442-be21-15ded9e89e51.png">

**Session info**

```r
xfun::session_info("papaja")                                                                 
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6, RStudio 0

Locale: en_GB.UTF-8 / en_GB.UTF-8 / en_GB.UTF-8 / C / en_GB.UTF-8 / en_GB.UTF-8

Package version:
  assertthat_0.2.1  backports_1.2.1   base64enc_0.1.3   bookdown_0.24.1   broom_0.7.9.9000 
  bslib_0.3.0       cli_3.0.1         cpp11_0.4.0       crayon_1.4.1      digest_0.6.28    
  dplyr_1.0.7       ellipsis_0.3.2    evaluate_0.14     fansi_0.5.0       fastmap_1.1.0    
  fs_1.5.0          generics_0.1.0    glue_1.4.2        graphics_4.0.2    grDevices_4.0.2  
  highr_0.9         htmltools_0.5.2   jquerylib_0.1.4   jsonlite_1.7.2    knitr_1.36       
  lifecycle_1.0.1   magrittr_2.0.1    methods_4.0.2     papaja_0.1.0.9997 pillar_1.6.3     
  pkgconfig_2.0.3   purrr_0.3.4       R6_2.5.1          rappdirs_0.3.3    rlang_0.4.11     
  rmarkdown_2.11.2  rmdfiltr_0.1.3    sass_0.4.0        stats_4.0.2       stringi_1.7.4    
  stringr_1.4.0     tibble_3.1.5      tidyr_1.1.4       tidyselect_1.1.1  tinylabels_0.2.1 
  tinytex_0.34.1    tools_4.0.2       utf8_1.2.2        utils_4.0.2       vctrs_0.3.8      
  xfun_0.26         yaml_2.2.1        zip_2.2.0        
```

**Comment by crsh** [comment]
Thanks for reporting this. Just to be sure, do I understand correctly that this pertains to the document outline in the PDF viewer, not the LaTeX-generated TOC rendered in the PDF?

**Comment by shirdekel** [comment]
Yes that's my primary issue, although I'm sure those two relate.
________________________________

**Comment by crsh** [comment]
I just submitted a PR that should fix this. If would like to try it out install via `remotes::install_github("crsh/papaja@crsh/issue496")` and let me know if that resolves the issue for you.

**Comment by mariusbarth** [comment]
Even with the new version, my pdf viewer(s) do not show appendices in the document outline or a toc

**Comment by crsh** [comment]
Thanks for checking. This appears to be a problem with the `apa6` document class. It can be fixed by including the following in the YAML front matter (as suggested [here](https://tex.stackexchange.com/questions/385371/appendix-missing-in-toc)):

~~~yaml
header-includes:
  - |
    \usepackage{xpatch}
    \makeatletter
    \xapptocmd\appendix
      {\xapptocmd\section
        {\addcontentsline{toc}{section}{\appendixname\ifoneappendix\else~\theappendix\fi\ #1}}
        {}{\InnerPatchFailed}%
      }
    {}{\PatchFailed}
~~~

We could include this in the document preamble by default, but I would prefer if this could be fixed in `apa6`. However, I'm not sure how actively it's being maintained and many users will probably start moving to `apa7` at some point...

Would you prefer the ToC entry to by "Heading 3" or "Appendix Heading 3"? @shirdekel @mariusbarth

**Comment by mariusbarth** [comment]
I think "Appendix: some title" is perfect, because you also typically refer to "Appendix A", "Appendix B", ... in text

**Comment by shirdekel** [comment]
Looks good. Thanks for the fix!
