### ISSUE TITLE
"et al."ing the third-nth author after the first in text citation not working

### ISSUE THREAD

**Issue by TaymAlsalti** [crsh/papaja#488]
According to the [APA 7th](https://www.scribbr.com/apa-style/apa-seventh-edition-changes/) edition manual, works with 3 or more authors should be cited as "First author et al." in-text. Papaja implemented the 6th edition but the rule in that [edition](https://www.scribbr.com/apa-style/6th-edition/archived-in-text-citation/) saying that the second and subsequent in-text citations should look like ""First author et al." also doesn't seem to work: ![Two subsequent in-text citations](https://user-images.githubusercontent.com/57235416/141435937-1fde9c9f-b0ed-4d19-a1e5-29ca075e4fb5.png)).

**Comment by crsh** [comment]
Hi there, thanks for reaching out.

First, support for the 7th edition is forthcoming. If you are interested see https://github.com/crsh/papaja/issues/342. In the meantime, you can achieve 7th-edition citations and references by adding the following to the YAML front matter:

~~~yaml
csl: "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
~~~

Second, generally et-al-ing works (it's done by the pandoc filter citeproc, not by papaja). I'm not sure what the issue seems to be in your case, but I'd be happy to take a look at it, if you can provide a minimal reproducible example.

**Comment by TaymAlsalti** [comment]
Hi!

Thank you so much for the quick reply! Unfortunately, the references don't work at all with this csl line.  [This Onedrive folder ](https://1drv.ms/u/s!ArwTd6HIlGOaiZAG0Nz4J8Hg-v-UTQ?e=OGb9RC) contains the .rmd document with two identical in-text citations as well as the references .bib file. Is this fine? I'm new to this repro thing :D

**Comment by TaymAlsalti** [comment]
Ah, damn it. I closed it by mistake. One second.

**Comment by TaymAlsalti** [comment]
Thank you so much for the quick reply! Unfortunately the references don't work at all with this csl line. You can find an .rmd file containaing two identical in-text citations as well as the reference .bib file in [this OneDrive folder](https://1drv.ms/u/s!ArwTd6HIlGOaiZAG0Nz4J8Hg-v-UTQ?e=OGb9RC). Is this fine? I'm new to this repro thing.

**Comment by crsh** [comment]
Sorry, I was probably unclear. For 7th edition to work, you need use the development version (`remotes::install_github("crsh/papaja@devel")`).

Regarding et al: I can indeed reproduce the problem but as I have noted [elsewhere](https://stackoverflow.com/questions/66245784/why-does-my-rmarkdown-papaja-not-suppress-following-author-names-when-i-have-alr) it seems to be unrelated to `papaja`. The same problem occurs even if `papaja` is not involved at all:

~~~md
---
title             : "Title"

references:
- type: chapter
  id: veveaPublicationBias2019
  author:
  - family: Vevea
    given: Jack L.
  - family: Coburn
    given: Kathleen
  - family: Sutton
    given: Alexander
  editor:
  - family: Cooper
    given: Harris
  - family: Hedges
    given: Larry V.
  - family: Valentine
    given: Jeffrey C.
  issued:
    date-parts:
    - - 2019
  title: Publication Bias
  container-title: The Handbook of Research Synthesis and Meta-Analysis
  page: 383-430
  publisher: Russell Sage Foundation
  doi: 10.7758/9781610448864.21
  language: en-GB

csl: "https://www.zotero.org/styles/apa-6th-edition?source=1"
output: pdf_document
---

First in-text citation: [@veveaPublicationBias2019].

Second in-text citation: [@veveaPublicationBias2019].
~~~

This tells me that it's either a problem with the `apa6.csl` or, and this seems more likely to me, with `citeproc`. I will open an issue over at that repository. In the meantime you could try switching to `biblatex` like so:

~~~yaml
bibliography      : references.bib
biblio-style      : "apa"

output:
  papaja::apa6_pdf:
    citation_package: biblatex
~~~

**Comment by TaymAlsalti** [comment]
Thanks again! :)
