### ISSUE TITLE
How to remove #tab

### ISSUE THREAD

**Issue by munoztd0** [crsh/papaja#495]
hello, first thanks for this amazing project!

Second I have an issue that is a bit annoying.. Every time I use apa_table there is an "(#tab:unnamed-chunk) " header on top of it (or #tab:whatever the chunk name is").

In your demo it seems to have the same thing someting like here

![image](https://user-images.githubusercontent.com/43644805/145050465-626cccc2-e4ef-400c-934b-c803e9e2e6a3.png) (taken from https://ndphillips.github.io/IntroductionR_Course/readings/papajaguide.html)

Is there a way to circumvent this ?

**Comment by mariusbarth** [comment]
Hi @munoztd0, I don't know if there is a way to turn this off (maybe @crsh knows more about that), but it typically suffices to switch to an output format that supports cross-referencing of tables (I assume this is the root of the issue). So you can switch to `papaja::apa6_pdf`, `papaja::apa6_docx`, or to output formats prvided by the **bookdown** package, e.g. `bookdown::html_document2`.

**Comment by crsh** [comment]
Hi David, Marius si spot on here; I have nothing to add.
