### ISSUE TITLE
Bug in appendix: ampersand appearing instead of 'and'

### ISSUE THREAD

**Issue by pablobernabeu** [crsh/papaja#496]
Hello,

Thank you for such a great package.

I would like to report a bug regarding the appearance, in appendices only, of an ampersand in non-parenthetical citations for references with two authors, where 'and' should appear instead. The error appears in both the apa6 and the apa7 document classes.

It seems as though the filter that distinguishes parenthetical and non-parenthetical citations only works in the main document.

**To reproduce**

1. Create a main document that includes an appendix;
2. Write a *non-parenthetical* citation for a reference with two authors in the main document, as well as in the appendix;
3. Knit the main document (the appendix will be automatically knitted);
4. Notice in the output that the main document has 'and' linking the two authors (correct APA), whereas the appendix has '&'.

Thank you very much for your attention

**Comment by crsh** [comment]
Hi Pablo, thanks for reporting this. I just submitted a PR that should fix this. If would like to try it out install via `remotes::install_github("crsh/papaja@crsh/issue496")` and let me know if that resolves the issue for you.

**Comment by pablobernabeu** [comment]
Hi Frederik, thank you very much for your swift action. The ampersand issue is indeed resolved with this update!

I would like to note, however, that the update affects the appearance of the references of my main document, and the appendices. The references of the main document now begin with a first blank page containing only the heading, which is followed by the first appendix, and then the references of the main document intermixed with the appendices.

**Comment by crsh** [comment]
Hi Pablo, does your appendix start with a level 1 heading? It should look something like this:

~~~md
# (APPENDIX) Appendices {-}

# 
~~~

The second `#` can either be "empty" as shown above, or preferably be a descriptive heading of the appendix.

> Also, the chunks referring to the appendices in the main document (which appeared as the knitting began) weren't deleted after the knitting finished (perhaps this isn't problematic, though).

Indeed, moving forward this is desired as improves maintainability of the code and at the same time gives the user more control. In fact, the YAML front matter option `appendix` will be maintained largely for backward compatibility and the "manual" management of appendices using the `bookdown` syntax is recommended.

**Comment by pablobernabeu** [comment]
Hi Frederik,

Indeed, my appendices have the recommended heading at the top. 

I have solved the intermixing of the references with the appendices by writing `\clearpage` at the end of the last appendix. 

I'm now facing four issues with the recent update.

### 1. Appendix chunks

The chunks related to the appendices that automatically appear at the end of the main document during the knitting do create a problem if they are not manually deleted, as they are then followed by the old-style chunks.

![Screenshot 2021-12-16 at 17 08 44](https://user-images.githubusercontent.com/20436359/146417536-18c117b0-789b-4625-9c35-5e67a46e4e79.png)


## 2. Place of reference list

The reference list now appears after the appendices, whereas APA 7 recommends placing it before.


### 3. References heading 

I can't find where to place the #References heading due to the previous point. If I place the heading at the end of the main document as I used to, the heading appears right above the heading of the first appendix.

**Comment by crsh** [comment]
Hi Pablo.

1. You can simply delete the old-stlye chunks (ll. 867 ff.). They are no longer required (in fact I'm surprised the document would render like this because `render_appendix()` is defunct) and should not reappear the next time the document is knitted.
2. and 3. You can (and need to) manually place the reference section in front of the appendices like so:

~~~md
# References

::: {#refs}
:::


\newpage

# (APPENDIX) Appendix {-}

```{r, child = "appendix.Rmd"}
```
~~~

I'm sorry the new behavior is a little opaque at this point. I'm working to update the manual to reflect these changes.

**Comment by pablobernabeu** [comment]
Thank you! I'm using the latest `devel` version as the #496 patch is no longer working. I switched back to the stable version yesterday and today found that the following command isn't available: `remotes::install_github("crsh/papaja@crsh/issue496")`. Neither is: `remotes::install_github("crsh/papaja@crsh/issue497")`.

Error: 

```
Downloading GitHub repo crsh/papaja@crsh/issue497
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/crsh/papaja/tarball/crsh%2Fissue497'
```

So, I installed the `devel` version minutes ago through`devtools::install_github("crsh/papaja@devel")`. I first tried to knit the document departing from 

```
# References

::: {#refs}
:::


\newpage

# (APPENDIX) Appendix {-}

```{r, child = "Appendix-A-lexical-covariates.Rmd")
```

```{r, child = "Appendix-A-lexical-covariates.Rmd")
```
```{r, child = "Appendix-A-lexical-covariates.Rmd")
```

![Screenshot 2021-12-16 at 19 34 35](https://user-images.githubusercontent.com/20436359/146440162-0045f0ce-7fd6-4195-93b0-4b0c2a70abf3.png)

**Comment by pablobernabeu** [comment]
Thanks a lot.

I've been trying to install the current `devel` version, as the #496 patch is no longer available, and neither is `remotes::install_github("crsh/papaja@crsh/issue497")`.

I grappled with a dependency rabbit hole for long, and finally couldn't install the `devel` version by any means. One error in the console once mentioned the tinylabels package, which I then installed, but that didn't help. The other error that has appeared throughout is not very telling to me:

```
Error in library(papaja) : there is no package called ‘papaja’
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/0k/7y470h4x2m7dg48c2438jmpc0000gp/T//Rtmpb7D9W9/file5c0d1abcfe1f/papaja_0.1.0.9997.tar.gz’ had non-zero exit status
```

I have confirmed that the `devel` version can indeed be installed in a new environment. However, I don't think I can start from scratch, as I have other packages in my project that require specific versions. I think it would be safest for me to stick with the stable version of papaja for now.

In case you happened to have a clearer idea of how to tackle the dependencies, I copy links here to my library ([zipped](https://livelancsac-my.sharepoint.com/:u:/g/personal/dejuanbe_lancaster_ac_uk/EfOEnwYucslAky6evneWleUBYTlfUyAdG-JZijvdf8hwCw?e=e9A1og) /  [unzipped](https://livelancsac-my.sharepoint.com/:f:/g/personal/dejuanbe_lancaster_ac_uk/EgLhEiFRy-lPnvmGCI8zVFABISXGX46y-RRyL_SMKKxCIA?e=EQK1lV)). However, I would totally understand if you were too busy for this now.

**Comment by crsh** [comment]
> I've been trying to install the current devel version, as the #496 patch is no longer available, and neither is remotes::install_github("crsh/papaja@crsh/issue497").

Yes, sorry, work on that branch was completed and I merged it into `devel`.

> The other error that has appeared throughout is not very telling to me

The error suggests that `papaja` is currently not installed on your system. I assume that you may have missed an error message when attempting to install the `devel` version? Could you retry and post the error message here?

**Comment by pablobernabeu** [comment]
Thanks! The upper part of yesterday's error was formed of messages referring to the installation of dependencies, which were successfully installed. The screenshot below closely replicates the beginning of the messages I got yesterday. One of these messages regarded the version of the knitr package (similar to the message about {glue} shown below). 

Fortunately, I have just tried to install the devel version of papaja again, and it has worked! 

![Screenshot 2021-12-17 at 10 54 22](https://user-images.githubusercontent.com/20436359/146534791-c085d56b-95d6-4adb-b32c-e6714e5d65f9.png)

Since I have three appendices, the ending of my manuscript Rmd looked as follows:

```
    \clearpage
    
    # References
    
    ::: {#refs}
    :::
    
    
    \newpage
    
    # (APPENDIX) Appendix {-}
    
    ```{r, child = "Appendix-A-lexical-covariates.Rmd"}
    ```
    
    ```{r, child = "Appendix-B-model-diagnostics.Rmd"}
    ```
    
    ```{r, child = "Appendix-C-power-analysis.Rmd"}
    ```
```

Finally, thank you so very much!

**Comment by crsh** [comment]
Excellent, I'm glad you got it working. And again thank you for reporting this. It was the much needed push I needed to revise the previous supar implementation! 👍
