### ISSUE TITLE
LaTeX code to delete redundant fields `\author` and `\affiliation` in `tex` file

### ISSUE THREAD

**Issue by pablobernabeu** [crsh/papaja#508]
Hello,

I would like to share here a StackOverflow question I've just created to ask for help to deal with the redundant  fields `\author` and `\affiliation` in the `tex` file when using the apa7 template. 

https://stackoverflow.com/questions/70635178/deleting-redundant-author-and-affiliation-fields-in-r-papaja-document

I'll update here as soon as a solution has been posted. In case you had the possibility to look into the issue, I would be very grateful, but I would understand otherwise too.

Thanks and best regards

**Comment by crsh** [comment]
Hi Pablo, sorry the workaround isn't working for you anymore. I'm not sure why this is. Unfortunately, I'm totally swamped right now and won't have time to look into this. Proper support for `apa7` is planned but it will probably be a little while before we get around to it.

**Comment by pablobernabeu** [comment]
Hi Frederik, no problem at all. Cheers

**Comment by pablobernabeu** [comment]
:tada: Solution provided at: https://stackoverflow.com/a/70658799/7050882

**Comment by crsh** [comment]
Excellent! Thanks a lot for sharing.
