### ISSUE TITLE
Small indent to the abstract.

### ISSUE THREAD

**Issue by AdrienWitt** [crsh/papaja#510]
**Describe the bug**
There is a small indentation in the abstract of APA manuscripts using papaja.

**To Reproduce**
`abstract: |
 This is the second part of the beginner’s guide to RMarkdown. The first part was about
the basics of the Markdown syntax, embedding your results into text, and some useful
packages that give us APA-styled tables and results in Word documents. If you haven’t
checked out the first one, please do so before you read this one. If you already have, just
skip ahead to the main text!
`

**Expected behavior**
No indentation is needed for the abstract in APA style. Is it possible to remove this small indentation?

**Screenshots**
![image](https://user-images.githubusercontent.com/58138590/152141213-cc37887b-4c9c-4d47-b488-2618600f1791.png)

![image](https://user-images.githubusercontent.com/58138590/152140630-9be9606a-4724-420f-93bd-ccf7acd97e64.png)

**Additional context**

**Comment by crsh** [comment]
Thanks. I just made a change on the `devel` branch that I hope addresses this. Try reinstalling to see if that fixes it (`remotes::install_github("crsh/papaja@devel")`).

**Comment by AdrienWitt** [comment]
> Thanks. I just made a change on the `devel` branch that I hope addresses this. Try reinstalling to see if that fixes it (`remotes::install_github("crsh/papaja@devel")`).

Perfect, it works. Thanks a lot for your responsiveness!

**Comment by crsh** [comment]
Thanks for the feedback. :)
