### ISSUE TITLE
Pandoc error 83

### ISSUE THREAD

**Issue by henda52** [crsh/papaja#512]
**Describe the bug**
When I try to knit a papaja rmd to pdf I get the following error message:

Error running filter C:/Users/henda52/Documents/R/win-library/4.1/papaja/lua/parse_metadata.lua:
string expected, got List
	while retrieving function argument text
	while retrieving arguments for function Str
stack traceback:
	...ocuments/R/win-library/4.1/papaja/lua/parse_metadata.lua:220: in upvalue 'create_correspondence'
	...ocuments/R/win-library/4.1/papaja/lua/parse_metadata.lua:304: in function 'Pandoc'
Error: pandoc document conversion failed with error 83
Execution halted

It worked to knit this rmd yesterday before my University automatically updated to the new Rstudio version on my computer.

I tried to create a new papaja rmd from the template and change nothing. I got the same error when I knitted to pdf. However, if I changed to knit to word, it works and I get a word file.

I use the following versions:
RStudio 2022.02.0+443 "Prairie Trillium" Release (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
papaja_0.1.0.9997

**Comment by tarensanders** [comment]
@henda52 I had the same issue, but it seems to be fixed on the devel branch.

**Comment by henda52** [comment]
> @henda52 I had the same issue, but it seems to be fixed on the devel branch.

Thanks! It works now
