### ISSUE TITLE
Add an option for 'table*' to apa_table

### ISSUE THREAD

**Issue by saladspices** [crsh/papaja#52]
To print a two-column table in 'jou' mode, it would be nice to have an option to use `\begin{table*}` instead of `\begin{table}`.  For figures, one can simply use `fig.env='figure*'` in the chunk header, but it seems that there's no such option for tables. Maybe something like:
`apa_table(x, env='table*')`

If there's another option that I'm missing - please let me know!

If you copy the following chunk and the latex code into the default template (changed to 'jou'), you can see the difference:

``` r apa_tab, fig.env='table*'
my_table <- apply(cars, 2, function(x) # Create data
   round(c(Mean = mean(x), SD = sd(x), Min = min(x), Max = max(x)), 2)
)

apa_table(
   my_table
   , align = c("l", "r", "r")
   , caption = "A summary table of the cars dataset."
   , note = "This table was created using apa\\_table()"
   , added_colnames = "Descriptives"
)
```

``` r
\begin{table*}
\begin{center}
\begin{threeparttable}
\caption{A summary table of the cars dataset.}
\begin{tabular}{lrr}
\toprule
Descriptives & \multicolumn{1}{c}{speed} & \multicolumn{1}{c}{dist}\\
\midrule
Mean & 15.4 & 42.98\\
SD & 5.29 & 25.77\\
Min & 4 & 2\\
Max & 25 & 120\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\textit{Note.} This table was created using apa\_table()
\end{tablenotes}
\end{threeparttable}
\end{center}
\end{table*}
```

**Comment by crsh** [comment]
If I understand correctly you want to use `table*` to place the table in the center of an otherwise empty page. Is that correct? A quick fix, which I know is not quite what you want, would be to set `placement = "p"` when you call `apa_table.latex()`.

In principle, adding an option like you describe seems straight forward. I'm a little hesitant because the function uses different nested environments depending on options such as `landscape` or `longtable`. I need to explore the possible side effects of the combinations of these options.

**Comment by crsh** [comment]
Okay, this is a little tricky and will require some more experimenting on my part. `longtable` doesn't work in `jou` mode at all, so I'll need to give this some more thought and it will require some rewriting of `apa_table()`.

Another hack I just thought of that should help is the following:
~~~{r}
pretty_table <- capture.output(apa_table(
   my_table
   , align = c("l", "r", "r")
   , caption = "A summary table of the cars dataset."
   , note = "This table was created using apa\\_table()"
   , added_colnames = "Descriptives"
))

pretty_table <- gsub("\\{table}", "\\{table*}", pretty_table)
cat(paste(pretty_table, collapse = "\n"))
~~~

Not pretty, but it should do the trick in the meantime.

**Comment by crsh** [comment]
I just pushed a commit to the development branch that should enable `table*` in `jou`-mode by default unless `span_text_columns = FALSE` in the call to `apa_table()`. This may be [of interest](https://github.com/crsh/papaja/issues/130#issuecomment-436512244) to @ekothe.

**Comment by ekothe** [comment]
This worked perfectly and came at just the right time. See [here ](https://psyarxiv.com/5yv2u/)for an example of it in action :)
