### ISSUE TITLE
Reference indentation

### ISSUE THREAD

**Issue by IhnwhiHeo** [crsh/papaja#524]
Hello folks,

Thank you so much for this amazing R package. I have a quick question about reference indentation.
I am wondering how I can adjust the indentation because the current formatting does not match the APA 7th indentation size (0.5 inches).

<img width="1247" alt="스크린샷 2022-04-18 오후 6 58 01" src="https://user-images.githubusercontent.com/60255083/163905240-7a874dab-c2cf-46b2-99d7-25f2336106e9.png">

Thank you!

**Comment by crsh** [comment]
Hi there, thanks for the kind words. Could you share the relevant portions of the code you are using to generate the reference section?
