### ISSUE TITLE
Pandoc and lua-filters, pdf not knitting: parse_metadata.lua expected string, got List

### ISSUE THREAD

**Issue by LGurtner** [crsh/papaja#527]
**Describe the bug**
I just tried to knit a document that has perfectly knitted before (a year ago) to pdf. Now, I get the following error: 
```
Error running filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/papaja/lua/parse_metadata.lua:
string expected, got List
	while retrieving function argument text
	while retrieving arguments for function Str
stack traceback:
	...ions/4.0/Resources/library/papaja/lua/parse_metadata.lua:225: in upvalue 'create_correspondence'
	...ions/4.0/Resources/library/papaja/lua/parse_metadata.lua:308: in function 'Pandoc'
Error: pandoc document conversion failed with error 83
Execution halted
```

I tried:  
- knitting to Word, which works fine. 
- I read [this thread](https://github.com/crsh/papaja/issues/225), and tired to knit the apa-template from the papaja package without changing anything and also I  provided empty author note and abstract. Again, knitting to word works, but knitting to pdf does not. 

I run RStudio 2022.02.3, R version 4.0.5 (2021-03-31), on a mac. 

Any suggestions or experiences with this error? Thank you already in advance!

**Comment by crsh** [comment]
Hi there, thanks for reaching out. I'd be happy to take a closer look, but I think this may be related to something in your YAML front matter (there was a change in Lua for pandoc that broke some things on our end). Could you either share your YAML front matter or create a minimal reproducible example?

**Comment by LGurtner** [comment]
Hey there, thank you for your quick reply. The header was the one from the apa6-template. But I just checked and realized that I did not have the newest papaja-version. Now that I updated, everything runs smoothly. Sorry for bothering you, I forgot to check for updates. Thank you for the great package!!

**Comment by crsh** [comment]
Excellent. Glad you were able to resolve the issue. And thanksf or the kind words. 😊
