### ISSUE TITLE
author names in "two-column"

### ISSUE THREAD

**Issue by AdeLac74** [crsh/papaja#530]
Hi,
I use the "two-column" output, which is great (thank you so much!). The author names are written at the top of every two pages. My problem is that as there are quite a lot of authors in my current paper; it does not stand in one line and thus, the authors names are written beyond the page width (and we can't see them)... Is there a way, either top put the author names on two lines or to remove them and just let the short title of the article instead (as on the other pages)?
Thanks!

**Comment by crsh** [comment]
Hi Adelin, does the approach described [here](https://github.com/crsh/papaja/issues/130#issuecomment-493003216) work for you?
