### ISSUE TITLE
Indented figures under nested headings

### ISSUE THREAD

**Issue by sebsilas** [crsh/papaja#532]
When I have a figure under a paragraph that has a third level heading (i.e., ### Heading), the figure is indented and cut-off:

<img width="1792" alt="Screenshot 2022-08-04 at 17 31 19" src="https://user-images.githubusercontent.com/39628712/182887087-efd5cdc8-9497-4833-bf54-b2deddea360d.png">

Is it possible to turn of this behaviour so the figure can render properly?

**Describe the bug**

**To Reproduce**
A [minimal complete verifiable example](https://stackoverflow.com/help/mcve) and the error message if applicable.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by crsh** [comment]
Hi Seb, I think I just fixed this issue on a development branch. Would you mind testing it?

~~~r
remotes::install_github("crsh/papaja@word-fixes")
~~~

**Comment by sebsilas** [comment]
Hi sorry for the delay. This doesn't appear to be fixed for me after installing from that dev branch:

<img width="1218" alt="Screenshot 2022-12-23 at 13 38 30" src="https://user-images.githubusercontent.com/39628712/209337604-fedcc57a-12ee-4a25-b8c0-25d9b6ec78a5.png">

It may be relevant that this is within an included file, like this:

```

```{r child = "experiment_1.Rmd"}

```
```

**Comment by ne-vial** [comment]
I can reproduce this, not within an included file but in a paragraph with a third-level heading

**Comment by ne-vial** [comment]
> I can reproduce this, not within an included file but in a paragraph with a third-level heading

For me, a simple fig.align="center" did the job
