### ISSUE TITLE
Base papaja template won't stitch to pdf

### ISSUE THREAD

**Issue by Michaeladebolt** [crsh/papaja#533]
Hello! I've recently updated my RStudio and now my papaja apa_6 doc won't knit to pdf. I opened an entirely new papaja doc, made no edits, and attempted to knit it thinking I had done something wrong in my own file, and the template produced the exact same error (see screenshot). 

R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 12.4

![Screen Shot 2022-09-08 at 1 26 14 PM](https://user-images.githubusercontent.com/32584911/189219124-49fd2835-7b82-4c46-a6f3-6323a7ab846a.png)

**Comment by conig** [comment]
This is weird, would be useful to get more info. Updating Rstudio can result in pandoc being updated which can cause incompatabilties if you're on old package versions.

What pandoc version?
```
rmarkdown::pandoc_version()
```
Also can we see the verison of knitr, papaja and rmarkdown?

```
sapply(c("papaja","knitr", "rmarkdown"), function(x) as.character(packageVersion(x)))
```

You might find updating your packages (and tinytex for good measure) resolves any incompatibilities.

```
tinytex::install_tinytex()
```
