### ISSUE TITLE
[Suggestion] function for writing author and affiliation YAML

### ISSUE THREAD

**Issue by conig** [crsh/papaja#534]
**Problem**
On papers with many authors, managing affiliations can be taxing. If an author changes position, or if an author wants to reorder their affiliations, the affiliations section of the YAML needs to be carefully reordered which can be error-prone.

**Describe the solution you'd like**
A helper funciton could be useful for writing this section of the YAML. Affiliations and authors could be seperately recorded and then organised based on author position.

For my own work I've written a basic function to do this. Affiliations are automatically numbered based on authorship position and the order of affiliations in the researcher list. Affiliation content can be arbitratily ordered in the affiliation list. Example:

```
papaja_affiliation(
  researchers = list(
    "James H. Conigrave" = c("uExample", "CRE"),
    "John A. Smith" = c("NUni")
  ),
  affiliations = list(
    CRE = "Centre of Research Excellence: Example",
    uExample = "University of Examples, NSW, Australia",
    NUni = "Not a real university"
  ),
  corres_address = "12 Example St, Australia",
  corres_email = "james@example.com",
  corresponding = "James H. Conigrave",
  return_clipboard = FALSE
)
#> author:
#>   - name          : "James H. Conigrave"
#>     affiliation   : "1,2"
#>     corresponding : yes
#>     address       : "12 Example St, Australia"
#>     email         : "james@example.com"
#> 
#>   - name          : "John A. Smith"
#>     affiliation   : "3"
#> 
#> affiliation:
#>   - id            : "1"
#>     institution   : "University of Examples, NSW, Australia"
#>   - id            : "2"
#>     institution   : "Centre of Research Excellence: Example"
#>   - id            : "3"
#>     institution   : "Not a real university"
```

If this is something you want in papaja, I'm happy to do a pull request. Otherwise if you want to keep papaja lean, I can send it off to a helper package.

**Comment by crsh** [comment]
Hi James, thanks for sharing. I see no issue with including a helper like this in the package. @mariusbarth?

BTW, if you are dealing with many authors, another alternative is to collect authorship and contributorship information with https://tenzing.club (essentially a Google Sheet) and export it as **papaja** YAML through the web interface.

**Comment by mariusbarth** [comment]
I don't see any reason why we shouldn't include something like this.

**Comment by crsh** [comment]
Awesome. @conig would you be willing to open a PR? If you want to elaborate a bit more on this function in a vignette, you are more than welcome (but that's clearly not required).
