### ISSUE TITLE
Change note font size in apa_table

### ISSUE THREAD

**Issue by bernicecheung** [crsh/papaja#546]
Hello! I wonder if there's a way to change the font size of the table note in apa_table. The default font size is too large. 
I change the font_size, but it only controls the font size of the content, not the note. Thank you! 
<img width="421" alt="Screen Shot 2022-11-10 at 4 38 03 PM" src="https://user-images.githubusercontent.com/56136752/201235315-0406462c-b1fb-42a4-9fd8-8ef9ba9d9c53.png">
<img width="240" alt="Screen Shot 2022-11-10 at 4 38 10 PM" src="https://user-images.githubusercontent.com/56136752/201235322-36fdf742-4c58-4d02-adcc-38b116fd1bb0.png">

~~~r
apa_table(
  factor_comparison_4_tab,
  caption = "The Replicability of Four-Component Models Across Study 3-5 Baseline",
  col_spanners = list("Study3" = c(2,4), "Study4" = c(5,7), "Study5" = c(8,10)),
  #align = c("p{2cm}",rep("p{1cm}", ncol(factor_comparison_4_tab))),
  font_size = "tiny", 
  landscape = T,
  note = "'C' represents Communality; 'PC' represents Primary Component; 'PL' represents Primary Loadings; 'Congruence' represents whether the item loaded onto the same component across three studies; 'Squared Diff' represents the squared differences in loading coefficents of the primary component across three studies" 
)
~~~

**Comment by crsh** [comment]
This is currently not possible and not planned. There are, however, two things you can do:

1. You can reduce the lineheight of table, caption, and note, as described [here](http://frederikaust.com/papaja_man/customizations.html#adjusting-line-spacing).
2. You can change the font size of the note (execept for "Note.") like so

~~~r
my_table <- t(apply(cars, 2, function(x) # Create data
  round(c(Mean = mean(x), SD = sd(x), Min = min(x), Max = max(x)), 2)
))

apa_table(
  my_table
  , align = c("l", rep("r", 3))
  , caption = "A summary table of the cars dataset."
  , note = "{\\tiny test test test}"
  , font_size = "tiny"
  , escape = FALSE
)
~~~
