### ISSUE TITLE
apa_print() with contrast() from emmeans gives partially wrong output

### ISSUE THREAD

**Issue by rubenellinghaus** [crsh/papaja#551]
**Describe the bug**

My goal is to report contrasts from a two-way interaction by using apa_print with emmeans:

est_err_type_comp <-apa_print(contrast(emmeans(fit_err, ~ type*compatibility), "revpairwise", by = "type"), est_name = "M")

the output looks good:

$full_result
$full_result$AS_Incomp_comp
[1] "$M = 0.03$, 95\\% CI $[0.03, 0.04]$, $t(79) = 9.99$, $p < .001$"

$full_result$CS_Incomp_comp
[1] "$M = 0.06$, 95\\% CI $[0.05, 0.07]$, $t(79) = 9.76$, $p < .001$"

Accordingly I try to include these statistics in text:

[...} `rest_err_type_comp$full_result$CS_Incomp_comp`,  `r est_err_type_comp$full_result$AS_Incomp_comp` [...]

However, after rendering this text appears in the pdf:

M = 5.94, 95% CI [4.73, 7.15], t(79) = 9.76, p < .001, M = 3.25, 95% CI [2.61, 3.90], t(79) = 9.99, p < .001 

**--> The statistics are correct but the estimates seem wrong.**

Is this a known problem or do I miss a coding error? Couldn't find anything on it so far and I am really interested what is going on.

Thanks a lot and greetings!

**Comment by mariusbarth** [comment]
Hi @rubenellinghaus,

I tried to create a minimal example to reproduce the error you report here, but actually everything I tried worked as expected. Can you provide a minimal reproducible example, and can you also provide the versions of R, emmeans and papaja that you are using?

Thanks in advance,
Marius

**Comment by rubenellinghaus** [comment]
Hello @mariusbarth, 

thank you very much for your reply. I tried to reproduce the example - however to my surprise it worked as expected this time, both when using my own data and other example data; the estimates in the output and in the text are now consistent.

In case the problem shows up again I will try provide an example. For now, however, the problem seems solved.

Best,Ruben

**Comment by mariusbarth** [comment]
I will close this one for now. @rubenellinghaus, please feel free to re-open if the problem reoccurs, and thank you for your efforts to reproduce!

Best regards,
Marius
