### ISSUE TITLE
Problems with brewed pandoc

### ISSUE THREAD

**Issue by sebastiansauer** [crsh/papaja#56]
Hi there,

I have tried to knit the `example.rmd` file using RStudio (0.99.491), pandoc (1.16.0.2) with pandoc-citeproc (0.9). This resulted in the following error:

     pandoc-citeproc: /usr/local/Cellar/pandoc-citeproc/0.9/share/x86_64-osx-ghc-7.10.3/pandoc-citeproc-0.9/locales/locales-am.xml: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter /usr/local/bin/pandoc-citeproc

Any ideas what the problem could be?

Thanks for any advise!

Best
Sebastian

**Comment by crsh** [comment]
Thanks for reporting. I don't have time to follow up right now, but I will take a closer look on Monday. I suspect it may have something to do with a change that was made to locale identifiers in one of the recent pandoc updates.

**Comment by sebastiansauer** [comment]
Hi Frederik,

no worries, and let me add that I think your APA paper package is of potentially great help. I hope I get it running. Also, I am a markdown/pandoc fan.

First, I thought it may be due to Homebrew. But even without it, it did not work. I think your point makes sense.

You could also try to use the package „checkpoint“ to have reproducibility as to package versions.

Best
Sebastian

Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by crsh** [comment]
If you haven't set `lang`, try setting it to `de-DE` or `en-US` and see if that works. Could you also post the output of `sessionInfo()` and your YAML header?

**Comment by sebastiansauer** [comment]
Hi Frederik,
thanks for your help. I am on a business trip, and had no time ^for looking into it. Will get 	back  to your points asap!
Thanks!
Sebastian

Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by crsh** [comment]
No problem. In the mean time @mvuorre reported a similar problem and was so kind to follow up with a pull request to fix the problem. Try changing `lang` in the YAML header to `english`. I think this should take care of the problem. Let me know if the problem persists.

**Comment by mvuorre** [comment]
Also might be best to remove or comment out the `lang: ` line as it probably doesn't do much anyway.

**Comment by sebastiansauer** [comment]
Hi Matti, hi Frederik,

thanks! Removing „lang:“ out from the YAML header has solved the problem. It now compiled!

Thanks!

Great work! Please keep up!
Sebastian



> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.4.0   dplyr_0.4.3   ggplot2_2.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3       digest_0.6.9      assertthat_0.1    grid_3.2.3        plyr_1.8.3        R6_2.1.1         
 [7] gtable_0.1.2      DBI_0.3.1         magrittr_1.5      scales_0.3.0      rmarkdown_0.9.2   tools_3.2.3      
[13] munsell_0.4.2     yaml_2.1.13       parallel_3.2.3    colorspace_1.2-6  papaja_0.1.0.9054 htmltools_0.3  


Beste Grüße/ Kind Regards

Sebastian Sauer

**Comment by crsh** [comment]
Great, I'm glad it works. Let me know if you run into any other problems or have suggestions for improvements.

Just for the record: The `lang` parameter is used to set the locale for some oft the automatically generated text, such as "keywords" or "author note".

**Comment by sebastiansauer** [comment]
I think it’s of great help, and I have just started my crusade towards more reproducible science. Will present your work to colleagues and students

se


Beste Grüße/ Kind Regards

Sebastian Sauer
