### ISSUE TITLE
An outdated test for apa_table()

### ISSUE THREAD

**Issue by yihui** [crsh/papaja#563]
Hi, I just discovered that the following test would fail against the current dev version of **knitr**:
https://github.com/crsh/papaja/blob/1c488f73598ae088a4f0201e767aaa87f28387d3/tests/testthat/test_apa_table.R#L19

The reason that it fails is because of https://github.com/yihui/knitr/commit/547b7cd6b818d06eb9261c8245bb37f7654fc844. The test was working before by chance. I tracked it in Git and found it came from 2015 via @crsh's a2e5521:

https://github.com/crsh/papaja/blob/a2e55211dafea772fc6155798745dfd263842338/inst/tests/testthat/test_apa_table.R#L18

and it was actually for this error:

https://github.com/crsh/papaja/blob/a2e55211dafea772fc6155798745dfd263842338/R/apa_table.R#L100

However, `expect_error()` worked previously only because `added_colnames` was not an argument of `knitr:::kable_latex()`. Now `added_colnames` is accepted in `...`, so `kable_latex()` no longer throws an error, hence the test fails.

Perhaps this test should be removed now? Thanks a lot!

**Comment by mariusbarth** [comment]
Hi @crsh, I don't even get what this test was good for in the first place. Can't we just safely remove it?
