### ISSUE TITLE
How do I update biber and biblatex?

### ISSUE THREAD

**Issue by bjorn-persson** [crsh/papaja#573]
**Describe the bug**
INFO - This is Biber 2.17
INFO - Logfile is 'whatevs.blg'
INFO - Reading 'whatevs.bcf'
ERROR - Error: Found biblatex control file version 3.10, expected version 3.8.
This means that your biber (2.17) and biblatex (3.19) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1

I reinstalled tinytex yesterday and have tried updating the packages but it doesn't work. I guess this should be simple but google hasn't helped me.

**To Reproduce**
---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  herp derp
keywords          : "keywords"
wordcount         : "X"
bibliography      : ["bibliography.bib"]
floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
fig_caption       : yes
csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "man"
output            :
  papaja::apa6_pdf: 
    citation_package: biblatex
    latex_engine: "xelatex"
    html_document: default
header-includes:
- \usepackage{caption}
- \usepackage{fontspec}
- \usepackage{setspace}
- \usepackage{bbding}
- \AtBeginEnvironment{tabular}{\singlespacing}
- \AtBeginEnvironment{lltable}{\singlespacing}
- \AtBeginEnvironment{tablenotes}{\doublespacing}
- \captionsetup[table]{font={stretch=1.5}}
- \captionsetup[figure]{font={stretch=1.5}}
- \usepackage{pdflscape}
---

The Five Factor model [FFM; @Costa1992] has emerged as the dominant framework in personality psychology. The FFM describes five broad bipolar domains of behavior, cognition, and affect: extraversion, agreeableness, openness to experience, conscientiousness, and neuroticism [@Digman1990].

@article{Costa1992,
  doi = {10.1037/1040-3590.4.1.5},
  url = {https://doi.org/10.1037/1040-3590.4.1.5},
  year = {1992},
  publisher = {American Psychological Association ({APA})},
  volume = {4},
  number = {1},
  pages = {5--13},
  author = {Paul T. Costa and Robert R. McCrae},
  title = {Normal personality assessment in clinical practice: The {NEO} Personality Inventory.},
  journal = {Psychological Assessment}
}

@article{Digman1990,
  doi = {10.1146/annurev.ps.41.020190.002221},
  url = {https://doi.org/10.1146/annurev.ps.41.020190.002221},
  year = {1990},
  month = jan,
  publisher = {Annual Reviews},
  volume = {41},
  number = {1},
  pages = {417--440},
  author = {J M Digman},
  title = {Personality Structure: Emergence of the Five-Factor Model},
  journal = {Annual Review of Psychology}
}

Sorry don't remember of the top of my head how to put the references directly in the MWE, but in my case they are in the bibliography file that's referenced in the preable, it's just that biber and biblatex don't want to party.

**Expected behavior**
Oh I just want biber and biblatex to get along and produce my references..

**Comment by crsh** [comment]
Hi, thanks for reaching out. Seeing that this is unrelated to *papaja* I think this question would be better suited for StackOverflow (also because I don't know the solution to the problem without additional research). Also, have you looked at this issue? https://github.com/rstudio/tinytex/issues/291

Hope you can resolve the problem.
