### ISSUE TITLE
apa_print for lmer models standardized beta output bug?

### ISSUE THREAD

**Issue by sebsilas** [crsh/papaja#577]
**Describe the bug**

When I print the results of a mixed-effects model to a table using `apa_print` and `apa_table`, the table header labelling is for a standardised beta coefficient (β), but I believe this should be the unstandardised beta coefficient for a mixed-effects model (B)? 

**To Reproduce**

```
mod <- lmer(mpg ~ cyl + hp + disp + (1|gear), data = mtcars)

# Excuse the terrible model.

mod %>% 
  apa_print() |>
  apa_table()

```

**Expected behavior**
Instead of "β" in the table header, I would expect to see "Β".

**Comment by mariusbarth** [comment]
Hi @sebsilas,

The behaviour you describe is actually not a bug, but a design decision (we here follow Eid et al., 2010). However, if you don't like `$\beta$`, you can use argument `est_name` to pick whatever estimate name you want:

```
mod <- lmer(mpg ~ cyl + hp + disp + (1|gear), data = mtcars)

mod |>
  apa_print(est_name = "b*") |>
  apa_table()
  ```

**Comment by mariusbarth** [comment]
I also think there is no agreed-upon way, which is why we used this (German) stats text book as a starting point:

Eid, M., Gollwitzer, M., & Schmitt, M. (2010). _Statistik und Forschungsmethoden_ [_Statistics and research methods_] (5th ed.). Beltz, Weinheim, Germany.
