### ISSUE TITLE
Bibliography in papaja::revision_letter_pdf gives LaTeX Error: Lonely \item--perhaps a missing list environment.

### ISSUE THREAD

**Issue by cjvanlissa** [crsh/papaja#587]
I'm sorry, this won't be a reproducible example. If it's not a bug, feel free to ignore.

I'm unable to render a revision_letter_pdf with references, because the bibliography entries each give this error:

`LaTeX Error: Lonely \item--perhaps a missing list environment.`

The entries look like this:

```
\bibitem[\citeproctext]{ref-benjaminRedefineStatisticalSignificance2017}
Benjamin, D. J., Berger, J. O., Johannesson, M., Nosek, B. A., Wagenmakers, E.-J., Berk, R., \ldots{} Johnson, V. E. (2017). Redefine statistical significance. \emph{Nature Human Behaviour}, \emph{2}(1), 6--10. \url{https://doi.org/10.1038/s41562-017-0189-z}
```

Which seems to be the same as the entries from my papaja::apa6_pdf manuscript:

```
\bibitem[\citeproctext]{ref-benjaminRedefineStatisticalSignificance2017}
Benjamin, D. J., Berger, J. O., Johannesson, M., Nosek, B. A., Wagenmakers, E.-J., Berk, R., \ldots{} Johnson, V. E. (2017). Redefine statistical significance. \emph{Nature Human Behaviour}, \emph{2}(1), 6--10. \url{https://doi.org/10.1038/s41562-017-0189-z}
```

Maybe some package is missing from the revision_letter template?

**Comment by cjvanlissa** [comment]
Just changing `output         : papaja::revision_letter_pdf` to `output         : papaja::apa6_pdf` allows me to render successfully, so I do think something might be missing from the revision_letter_pdf template.

**Comment by jvcasillas** [comment]
Adding that I am also getting this error.

**Comment by crsh** [comment]
Thanks for reporting this. I'll take a look as soon as possible.

**Comment by jvcasillas** [comment]
Any update or workaround for this error?

**Comment by jvcasillas** [comment]
Following @cjvanlissa comment, I notice that if I try to render the Rmd file, get the `` error, and then inspect the .tex file, this section appears to be incomplete: 

```
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#2\baselineskip}
  \fi
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
```

If I switch to papaja::apa6_pdf and rerender, it words fine. So I can copy and paste the relevant section of the CSL code into the .tex file (after trying to render with papaja::revision_letter_pdf, it works correctly. The code I am copy/pasting is the following: 

```
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#2\baselineskip}
  \fi
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
```

I assume this needs to be added to the template to fix this issue.

**Comment by cjvanlissa** [comment]
@crsh thanks for fixing this! While you're at it: I had the same error when rendering an APA6 document recently; might have been a problem with my bib file, but if it happens again I will open an issue.

**Comment by crsh** [comment]
Thanks for letting us know! I plan to submit an update to CRAN shortly.
