### ISSUE TITLE
Problems creating table and figure lists

### ISSUE THREAD

**Issue by alfrhe** [crsh/papaja#591]
Hi, I have problems creating a table and figure list. Neither 'tablelist: yes' in the YAML header, nor '\listoftables'/'\listoffigures' works.
I tried knitting to pdf as APA6 and APA7, without any success.
However, generateing a table of contents works just fine in the YAML header and '\tableofcontents'. 

Does anyone have an idea how to fix my problem?

**Comment by crsh** [comment]
Hi there, could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), so I can explore the problem and test a possible fixes?
