### ISSUE TITLE
figsintext currently broken?

### ISSUE THREAD

**Issue by mattsigal** [crsh/papaja#61]
I am exporting to PDF, and as far as I can tell the figsintext flag doesn't seem to be working.  Here is a MWE, using the template:

<pre>
---
title: "The title"
shorttitle: "Title"
author: 
  - name: First Author
    affiliation: 1
    corresponding: yes    # Define only one corresponding author
    address: Postal address
    email: my@email.com
  - name: Ernst-August Doelle
    affiliation: "1,2"
affiliation:
  - id: 1
    institution: Wilhelm-Wundt-University
  - id: 2
    institution: Konstanz Business School

abstract: |
  Enter abstract here (note the indentation, if you start a new paragraph).
  
note: |  
  Complete departmental affiliations for each author (note the indentation, if you start a new paragraph).

  Enter author note here.
  
keywords: "keywords"

wordcount: X

class: man
lang: english
figsintext: no
lineno: yes
bibliography:
  - r-references.bib

output: papaja::apa6_pdf
---

```{r message = FALSE, warning = FALSE}
library("papaja")
apa_prepare_doc() # Prepare document for rendering
```

# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. 

## Data analysis

We used `r cite_r("r-references.bib")` for all our analyses.

# Results

See Figure 1. 

```{r}
plot(cars)
```

# Discussion

Here is some discussion.

# References

```{r create_r-references}
r_refs(file = "r-references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}

</pre>

Setting the figsintext flag to TRUE/yes/FALSE/no doesn't seem to have any impact on my output (the figure appears on line 27, which is in-text, in both cases). See [test.pdf](https://github.com/crsh/papaja/files/196081/test.pdf).

**Comment by crsh** [comment]
Interesting, indeed. What happens is that `knitr` doesn't add the LaTeX environment `figure`. If you add a proper figure caption (add `fig.cap = "May awesome caption"` to the chunk options) the environment is added and everything works as expected.

What I don't quite understand is why setting `fig.env = "figure"` doesn't seem to do anything. This would be the cleanest way to set the chunk option in order for this to work without a figure caption. I think I will add empty captions as default chunk option. Thanks for pointing this out.

**Comment by crsh** [comment]
Your example should work with the latest development version (`devtools::install_github("crsh/papaja", ref = "devel")`).
