### ISSUE TITLE
Page break in apa_table()

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#64]
Hi,

if I create a large apa_table that spans across more than one .pdf page, the lower ending is cut off, instead of continuing on the following page. I think that larger tables are desirable, because in a journal article, a page might consist of more lines than what is possible in APA double space format. It might help if the table could grow horizontally, buts its width seems to be fixed by the width of the row and column cell names, as far as I see that.

Can you think of a possible solution to this? I do not think that I can insert a manual page break into the table within the R chunk itself, right?

Best regards, Martin

**Comment by crsh** [comment]
Hi Martin,

you are right, it's not possible to manually break a table (I don't know how anyway). But there is an easy solution: Try setting `longtable = TRUE` in your call to `apa_table()`. I have rewritten the code for this functions quite a bit recently. If you experience any problems try installing the "unstable" development version `devtools::install_github("crsh/papaja", ref = "devel")`.

As for growing horizontally, I'm not sure I know what you mean. The table should grow beyond the page margins if the content of the table demands it. It's not determined by the width of column headings, if this is what you mean. You can, however, rotate a table by 90° by setting `landscape = TRUE` should it be too wide for your page. If you want to use both `longtable` and `landscape` you definitely need to use the unstable development version, though.

Let me know if this works for you.

Best regards,
Frederik

**Comment by m-Py** [comment]
Hi Frederik,

I reinstalled the 'stable' version of papaja and used `longtable = TRUE`, which it works really nice! Good to know that you are working on such issues, thank you :-)

I will look into the landscape parameter if needed, for now longtable is enough.

Best regards, 
Martin

**Comment by m-Py** [comment]
Hi Frederik,

I have faced an issue that is caused by setting `longtable = TRUE`: if I set `figsintext: no` so that tables and figures are appended to the manuscript, apa_tables that have the argument `longtable = TRUE` will remain in text, while all other tables are appended to the end. I can fix this by settiung longtable to FALSE, but then the original issue occurs (table is cut off). 

Best regards,  
Martin

**Comment by crsh** [comment]
Hi Martin,

thanks for letting me know. I'll try to take a closer look at this at the end of the week. I'm afraid I won't be able to attend to this any sooner.

Frederik

P.S.: It was nice to see you on Saturday. ;)

**Comment by m-Py** [comment]
It was nice seeing you too ;) Very nice party 

Thanks for seeing into the issue. Have a nice weekend!

Martin
