### ISSUE TITLE
r_refs and R packages with multiple sources

### ISSUE THREAD

**Issue by mattsigal** [crsh/papaja#65]
Hi, 

I'm sorry if this is already addressed, but I am currently writing a paper and using r_refs to cite all of the loaded R packages and have come across a small issue.  A few of the packages list multiple references, and seem to be returning a vector of titles when I compile.  For example:

```
library("effects")
```

Generates the following in-text citation: `effects (3.0.6, Fox, 2003)` (seems correct), but in my actual references list appears as: `Fox, J. (2003). C(“Effect displays in R for generalised linear models”, “effect displays in R for multinomial and proportional-odds logit models: Extensions to the effects package”). Journal of Statistical Software, 8 (15), 1–27. Retrieved from http://www.jstatsoft.org/v08/i15/` - the URL directs to the first article, and perhaps that should be the only one listed? Otherwise, perhaps they should both get entries in text (e.g., 2003a and 2003b), and in the references list.  The same issue occurs with library("vcd").

**Comment by crsh** [comment]
Hi Matthew, thanks for bring this to my attention. In testing `r_refs()` I don't think I ever tried a package that has more than one paper in its citation information. I think I'll be able to look into this this afternoon.

**Comment by crsh** [comment]
Hi Matthew, I just pushed a fix to the development branch (`devtools::install_github("crsh/papaja", ref = "devel")`). Let me know if this works for you.
