### ISSUE TITLE
Adding an Appendix in APA Style?

### ISSUE THREAD

**Issue by mattsigal** [crsh/papaja#70]
Sorry if there is a very basic way of accomplishing this, but how do I incorporate an appendix in my papaja document, and have appear _after_ the references?  I believe this is proper APA style.

Here is a brief example, using the template (with lang changed to English since American fails to render on my machine):

``````

---
title: "The title"
shorttitle: "Title"
author: 
  - name: First Author
    affiliation: 1
    corresponding: yes    # Define only one corresponding author
    address: Postal address
    email: my@email.com
  - name: Ernst-August Doelle
    affiliation: "1,2"
affiliation:
  - id: 1
    institution: Wilhelm-Wundt-University
  - id: 2
    institution: Konstanz Business School

abstract: |
  Enter abstract here (note the indentation, if you start a new paragraph).

note: |  
  Complete departmental affiliations for each author (note the indentation, if you start a new paragraph).

  Enter author note here.

keywords: "keywords"

wordcount: X

class: man
lang: english
figsintext: no
lineno: yes
bibliography:
  - r-references.bib

output: papaja::apa6_pdf

---

    ```{r message = FALSE, warning = FALSE}
library("papaja")
library("car")

apa_prepare_doc() # Prepare document for rendering
    ```


# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

test

# Discussion

test 

\newpage

# References

    ```{r create_r-references}
r_refs(file = "r-references.bib")
    ```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}

\newpage

\appendix
\section{Title of Appendix A} \label{App:AppendixA}

Text of Appendix A is Here

\newpage
\section{Title of Appendix B} \label{App:AppendixB}

Text of Appendix B is Here
``````

I realize that there is nothing actually putting the references in under # References.  Maybe this could be added?  Normally, you would have the Appendices, and then follow them with:

```
\newpage
\begin{thebibliography}{10}
\bibitem{FirstReference}
\end{thebibliography}
```

Or something like that.

**Comment by crsh** [comment]
Hi Matt,

as far as I know, there is currently no way in pandoc to place references anywhere but at the very end of your RMarkdown document, but there are [plans](https://github.com/jgm/pandoc/issues/771) to add this feature. That said, this is how you currently add an appendix:

1. Install the development version of papaja:

  ~~~{r}
  devtools::install_github("crsh/papaja", ref = "devel")
  ~~~

2. Add the following to your YAML header:

  ~~~{yaml}
  output:
    papaja::apa6_pdf:
      includes:
        after_body: "appendix.tex"
  ~~~

3. Create a new document `appendix.Rmd` (you can either add subsections or create more than one document depending on your needs; if you create multiple documents add them to the YAML header):

  ~~~{markdown}
  This is my appendix.
  
  ## This is an appendix subsection
  More interesting stuff here.
  ~~~

4. Add the following line of code to your main document (or run from your R console):

  ~~~{r}
  render_appendix("appendix.Rmd")
  ~~~

This last line of code will turn your `appendix.Rmd` into a TeX file that is then included after the body of your document.

Let me know if this works.

**Comment by friendly** [comment]
I tried this, after inhstalling the devel version of papaja, papaja_0.1.0.9074, and making the changes suggested to the paper.
From the command line, render_appendix just gives NULL:

    > render_appendix("Appendix.Rmd")
    NULL

Inside a ducument chunk it also seems to have no effect-- Appendix.tex is not produced.  

This may be because of the following call in `render_appendix()`:

    > knitr::opts_knit$get("rmarkdown.pandoc.to")
    NULL

**Comment by friendly** [comment]
Correction:  `render_appendix()` in a separate chunk does work.

    ```{r render_appendix, include=FALSE}
    render_appendix("Appendix.Rmd")
    ```

However, it is `after_body: Appendix.tex` that has no effect -- the appendix dows not appear.

**Comment by crsh** [comment]
Hi @friendly,

thanks for reporting this. I think I fixed both issues you report in my last commit. `render_appendix` can now be run from the console (as it should have to begin with). Also, I think the reason you report that `after_body: "Appendix.tex"` has no effect is that the include is not put on a separate page with the heading "Appendix"? I learned that the appendix section needs a section heading to work properly. `render_appendix` now adds `\section{}` if there is no level 1-heading at the beginning of `Appendix.Rmd`, so this should take care of it.

Again, thanks for bringing this to my attention. Let me know if there are any other problems.

**Comment by fdabl** [comment]
Hi Frederik,

just stumbling upon this. When I put 

```{r, echo = FALSE}
render_appendix('appendix.Rmd')
```

in my main file, it does put the appendix after the references. However, instead of including the image I plotted with R, it renders it as

``\label{fig:unnamed-chunk-13}Raw data for the excluded participants.``

I can use ``render_appendix`` from the console and paste the output into the main tex file, but I think there should be a better way. Is there?

Cheers,
Fabian

**Comment by friendly** [comment]
In my paper where I used this, I have, in the YAML header:

    output:
      papaja::apa6_pdf:
        includes:
          after_body: "Appendix.tex"

Then, at the very end of the Rmd file, to create `Appendix.tex`:


    ```{r render_appendix, include=FALSE}
    render_appendix("Appendix.Rmd")
    ```

    # References
    ```{r create_r-references, include=FALSE}
    r_refs(file = "r-references.bib")
    ```

    \setlength{\parindent}{-0.5in}
    \setlength{\leftskip}{0.5in}
    \setlength{\parskip}{8pt}

**Comment by crsh** [comment]
Yes, that is the current idea for the workflow and it seemed to work for me. Could you provide a minimal working example?

**Comment by fdabl** [comment]
Sure.

This is how example.Rmd looks like:

```
---
title             : "The title"
shorttitle        : "Title"
author: 
  - name          : "First Author"
lang              : "english"
class             : "man"
output:
  papaja::apa6_pdf:
    includes:
      after_body: "appendix.tex"
---

``{r message = FALSE, warning = FALSE}
library("papaja")
``

Main Text.

``{r render_appendix, include = FALSE}
render_appendix("appendix.Rmd")
``

# References
``{r create_r-references}
r_refs(file = "r-references.bib")
``

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
```

appendix.Rmd looks like this:

```
Appendix
``{r}
plot(1:10)
``
```

While it does render "Appendix" into the appendix, it does not show the image.

**Comment by crsh** [comment]
I see. Thanks for reporting this. I think I have pinpointed the issue. I'll try to resolve it as soon as possible.

**Comment by crsh** [comment]
I think it should work now. Reinstall `papaja` from the devel branch (`devtools::install_github("crsh/papaja", ref = "devel")`) and try again. Note that all of this is quite a bit of hackery. Unfortunately, this fix requires one to call `render_appendix()` from within an R Markdown document. You can't use the function from the console because the underlying `knitr::knit_child()` will throw an error.

**Comment by m-Py** [comment]
yes, the note is below the table again .

**Comment by fdabl** [comment]
It works now. Thank you, Frederik, for the quick fix!

**Comment by einGlasRotwein** [comment]
I'm quite late to the party; sorry if I overlooked something. I found the appendix function to work for the master version by now, but the headings now get printed below the first table. I guess it's because I have `floatsintext: yes` (which is what I want for the main document). Is there a way to change that for the appendix in order to have all my tables below the heading?

(When knitting "ordinary" documents, I think I fixed that issue with `- \makeatletter\renewcommand*{\fps@figure}{h}\makeatother` in the header, which doesn't affect papaja.)

**Comment by crsh** [comment]
Hi Julia, have you tried setting a placement option for the tables? The positioning of tables at the top or bottom of the page is a LaTeX default that you should be able to overwrite using `placement = "H"` in `apa_table()`.

**Comment by einGlasRotwein** [comment]
Awesome, that did the trick, thank you!

**Comment by pmcharrison** [comment]
Just in case someone else like me ends up coming here looking for how to include appendices, it looks like you can now achieve it just by adding the following lines to the YAML of your main Rmd file:

```
appendix:
  - "appendix-1.Rmd"
  - "appendix-2.Rmd"
```

**Comment by MarenMayer** [comment]
Hi,

I hope I didn't overlook something, but I stumbled across the problem of duplicted appendix headers in my paper. 

I added two appendices in the YAML with 

appendix          : 
  - "appendix_a.Rmd"
  - "appendix_b.Rmd"
  
  as described above.
  
  The document gets rendered without any problems but the appendix headlines look this: 

![image](https://user-images.githubusercontent.com/52958097/105372988-79536600-5c06-11eb-83da-ad0790560295.png)
![image](https://user-images.githubusercontent.com/52958097/105373038-8a03dc00-5c06-11eb-81b9-b5a0f14429d2.png)

A general headline "Appendix" is missing though.

Did I do something wrong / is there a way to avoid duplicated headers and have a single "Appendix" header before "Appendix A" and "Appendix B"?

**Comment by crsh** [comment]
What do your appendix-files look like?

**Comment by MarenMayer** [comment]
I designed them as described here: http://frederikaust.com/papaja_man/writing.html#appendices with no YAML and a level one header.
But I think, I just found the issue. The heading is not supposed to be "Appendix A", isn't it? "Appendix A" is generated by papaja and I can use any meaningful header for this appendix?

**Comment by MarenMayer** [comment]
But I just realized that the general heading "Appendix" as a start for the Appendecies is nonetheless missing

**Comment by mdkraemer** [comment]
Hi, I have a question regarding appendices and reference sections. Is it possible to have separate reference sections for the main manuscript and the appendix (i.e., refs that only appear in the appendix only appear in the appendix' ref section)? In a previous development version of papaja I was able to do this simply by including the following code twice, once at the end on the main .Rmd and once at the end of the appendix .Rmd:
```
\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
<div id="refs" custom-style="Bibliography"></div>
\endgroup
```

With the newest version, I add the appendix with `appendix: appendix.Rmd` which automatically inserts a 'child' r chunk at the end. However, the two reference sections are now identical (both contain refs from both main & appendix). Thanks so much for any help with this!

**Comment by ElineVG** [comment]
@mdkraemer, did you happen to find a solution to this problem? 

I am currently experiencing the same issue.
Thanks so much in advance!

**Comment by mdkraemer** [comment]
Unfortunately, I didn't find a solution. Still using a single reference section with all the refs after the main text (and no refs at the end of the appendix) instead

**Comment by mdkraemer** [comment]
Maybe the developers don't see this because the issue has already been closed

**Comment by crsh** [comment]
Hi Eline, hi Michael, I'm not aware of a solution to this (which does not mean there is no solution). But, as far as I know, APA 6th edition specifically asks authors  to place all references in the main reference section...

Btw, there is a new prefered approach to appendices, which does not use the YAML front matter option `appendix` (I would recommend to not use that approach any more). I really need to update the documentation, but here it is (also see [here](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers)):

~~~md
# Main text

lorem ipsum

# (APPENDIX) Appendix {-} 

# Appendix A

lorem ipsum
~~~

You can, of course, continue to use child documents:

~~~md
# Main text

lorem ipsum

# (APPENDIX) Appendix {-} 

```{r child = "appendix.Rmd"}
```
~~~

**Comment by ElineVG** [comment]
Dear Frederik, thank you so much for your response! 
sometimes journals want the Supplemental Material as a separate document (and then it is possible to create a separate Rmd for the Appendix with then a separate reflist too), but for preprints I prefer everything in one document (the reason I was interested in creating the separate reference list). Thank you as well for detailing the new appendix approach!

**Comment by crsh** [comment]
If it's important to separate the lists (and you only need PDFs), you can certainly switch to using `biblatex` for references, which supports mutliple bibliographies. To get started, see [here](http://frederikaust.com/papaja_man/customizations.html#author-name-disambiguation). You will find instructions on how to separate reference lists in various StackExchange posts. ;)

**Comment by ElineVG** [comment]
> If it's important to separate the lists (and you only need PDFs), you can certainly switch to using `biblatex` for references, which supports mutliple bibliographies. To get started, see [here](http://frederikaust.com/papaja_man/customizations.html#author-name-disambiguation). You will find instructions on how to separate reference lists in various StackExchange posts. ;)

Thank you so much!
