### ISSUE TITLE
Controlling chunk output details

### ISSUE THREAD

**Issue by friendly** [crsh/papaja#71]
Not sure if this is a knitr question or a papaja question, but I would like to be able to control features (e.g., font size, line spacing) used in the output from chunks in a .Rmd document to be processed using `papaja`. Perhaps there's a YAML option or a knitr chunk option, but I don't know what papaja does.

In my document, I get chunk code highlighted using the Highlighting environment, a variant of Verbatim, so, I am able to customize this as follows in LaTeX via `\input{my-latex}`

    % override the Highlighting environment
    \RecustomVerbatimEnvironment{Highlighting}{Verbatim}{fontsize=\small,baselinestretch=.9,commandchars=\\\{\}}

However, all code ***output*** appears within

    \begin{verbatim}
    ...
    \end{verbatim}

and I can't see how to modify this.  Any ideas?

**Comment by friendly** [comment]
Ah, I think I found a solution for font size here: http://tex.stackexchange.com/questions/171803/change-font-size-of-the-verbatim-environment

    % override verbatim environment used for chunk output
    \makeatletter
    \newcommand{\verbatimfont}[1]{\renewcommand{\verbatim@font}{\ttfamily#1}}
    \makeatother
    \verbatimfont{\small}%

**Comment by crsh** [comment]
Styling the `verbatim` environment is a LaTeX question and I'm not sure what the answer is. But depending on what you are trying to achieve it may be an option to use the `knitr` [chunk option](http://yihui.name/knitr/options/#chunk_options) `results = "asis"`:

> `asis`: output as-is, i.e., write raw results from R into the output document

This should omit the `verbatim` environment.
