### ISSUE TITLE
apa_print() breaks Pandoc/LaTex

### ISSUE THREAD

**Issue by Zuline** [crsh/papaja#77]
Using apa_print() from the console to format the results of an ANOVA leads to this code being generated:

```
[1] "$F(1, 11) = 0.61$, $\\mathit{MSE} = 207.33$, $p = .450$"


$est
$est$Gender
[1] "$\\eta^2_G = .053$"


$full
$full$Gender
[1] "$F(1, 11) = 0.61$, $\\mathit{MSE} = 207.33$, $p = .450$, $\\eta^2_G = .053$"


$table
  Effect  $F$ $\\mathit{df}_1$ $\\mathit{df}_2$ $\\mathit{MSE}$  $p$ $\\eta^2_G$
1 Gender 0.61                1               11          207.33 .450        .053

```

If you run apa_print() within an RMarkdown APA doc then Pandoc returns this:

```
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.164 \(\\mathit{MSE} = 207.33\), \(p = .450\)}

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted
```

It appears to be the `\\` that generates the problem. I think the escaping of the `\` is not needed inside a math environment from memory.

**Comment by crsh** [comment]
I assume, you used `apa_print()` in the console and copied the resulting text (e.g., `"$F(1, 11) = 0.61$, $\\mathit{MSE} = 207.33$, $p = .450$"`) into your Rmd. In this case, you are right that `\\` will cause the reported problem. There is, however, no way around `\\` because R will otherwise complain that `\m` is an unknown escape sequence (unlike `\n` or `\t`).

The intended use for `apa_print()` is not to run it once in the console and than copy and paste the text into your document. The point of dynamic documents in reproducible analyses is that the results are computed and inserted into your document anew every time you knit it. Thus, if you run your analysis in a chunk and report it in-text as intended (i.e., `` `r results$full$Gender` ``) everything should work as expected. Have a look at the [example files](https://github.com/crsh/papaja/tree/master/example).

**Comment by crsh** [comment]
This does remind me, that I should probably add a print method for `apa_print()` output..

**Comment by Zuline** [comment]
I wasn't very clear. I ran it in the console, after I had the problem to understand what the output was. Because of the issue a .tex file was never produced for the document so I could never see the whole output.

The error was thrown by this code in the document:

```{r}


papaja::apa_print(av)
```

**Comment by crsh** [comment]
I see. The default setting for the chunk option `results` in apa6_pdf currently is `asis` and the resulting `$` from lists can cause problems with the math environments. I understand that this is less than obvious. If you set the chunk option `results = "markup"` it should work as expected. I decided on this default to make the use of `apa_table()` less cumbersome but seeing that this causes confusion, I think, I may change the default back to `markup`.

**Comment by Zuline** [comment]
Thanks where is the chunk option set?

**Comment by Zuline** [comment]
OK so setting the option to `results = "markup"` delivers the following...which is not the desired output of course.

```
\begin{verbatim}
## $stat
## $stat$Gender
## [1] "$F(1, 11) = 0.61$, $\\mathit{MSE} = 207.33$, $p = .450$"
## 
## 
## $est
## $est$Gender
## [1] "$\\eta^2_G = .053$"
## 
## 
## $full
## $full$Gender
## [1] "$F(1, 11) = 0.61$, $\\mathit{MSE} = 207.33$, $p = .450$, $\\eta^2_G = .053$"
## 
## 
## $table
##   Effect  $F$ $\\mathit{df}_1$ $\\mathit{df}_2$ $\\mathit{MSE}$  $p$
## 1 Gender 0.61                1               11          207.33 .450
##   $\\eta^2_G$
## 1        .053
\end{verbatim}
```
By the way this is a test document to determine suitability for my wife who currently uses APA 6 in TeXnicle.

**Comment by crsh** [comment]
I'm afraid I don't, yet, understand what output you expect. Have you looked at the [example](https://github.com/crsh/papaja/tree/master/example)? On page 7 of the PDF there is a section explaining how to include the formatted text into the document.

**Comment by crsh** [comment]
If your wife does not use R Markdown she will have to copy-paste the formatted strings and replace `\\` by `\` manually.

**Comment by Zuline** [comment]
The intent was to identify whether R Markdown and papaja were a viable alternative so that she could cease using TeXnicle.

I have carefully read and worked through the example you point to with some progress.

**Comment by crsh** [comment]
Great, let me know if the example document leaves any questions unanswered.
