### ISSUE TITLE
`r variableName` doesn't work

### ISSUE THREAD

**Issue by hcp4715** [crsh/papaja#79]
Hi, there, 
Thank you so much for developing a very useful package for enhancing the reproducibility of psychological studies, I really appreciate that and hope to use it.

when I recently tried to use it, I found the function of `r variableName` (assuming the variableName is the variable I hope to present in the manuscript) doesn't work. It is really odd because I tried it in a default RMD file, it works! I am totally lost.
here is my system information:
R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Platform: x86_64-w64-mingw32/x64 (64-bit)
OS: window 10

I am not sure whether or not you encounter this situation before, but I know it is necessary to reproduce it situation first. So I uploaded my data and code here: https://github.com/hcp4715/AnalyzingExpData/tree/hcp4715-debug-1

Thank you very much!

**Comment by crsh** [comment]
Thanks for alerting me to this. This is a bug introduced by a hot fix I made a couple of days ago. I will shortly push a commit that will resolve the bug.
