### ISSUE TITLE
apa_table() fails when at least one column name contains _

### ISSUE THREAD

**Issue by OolonColoophid** [crsh/papaja#81]
Hi Frederik

One more for you! The title says it all.

When I have a column called (for testing) 

> How creative_do you think you are?

...the build fails in RStudio with the following:

>! Missing $ inserted.
> <inserted text> 
>                 $
> l.9 ...mn{1}{c}{How creative_do you think you are}

Removing this character leads to a successful build. I see there's another issue already open with % causing the same issue. Entering an escape character might be one solution, but is it possible to have apa_table() itself escape all special Latex characters?

Cheers

Ian

**Comment by crsh** [comment]
Hi Ian,

this one is related to #66. I have given a more elaborate explanation there. Depending on the information contained in your table passing the additional option `escape = TRUE` may do the trick.

**Comment by OolonColoophid** [comment]
Thanks, Frederik. Adding this option actually generates an error:


![error](https://cloud.githubusercontent.com/assets/18744451/17745600/58cf8fde-64a4-11e6-9939-60da5806cea8.jpg)

However, I wouldn't take this too seriously - I had some strange issues with RStudio telling me that Papaja wasn't compatible with the latest version of R, so I had to re-install 3.2.4. May have something to do with that. My Papaja version is papaja_0.1.0.9054

Cheers

Ian

**Comment by crsh** [comment]
Yes, your working with an outdated version of papaja. Try again after 
reinstalling from github and let me know if it works.

Am 17.08.2016 um 19:01 schrieb Ian Hocking:

**Comment by OolonColoophid** [comment]
Thanks, Frederick. On upgrading Papaja directly from Github, table rendering fails. I'm getting raw Latex preceded by ## in the PDF output.

> 
over the half-way point. However, they all rated the “importance of creativity in life” as
212 significantly more important (grand means of 3.44 and 4.38, respectively; t (99) = 8.68, p <
213 0.001, d = 1.019).
214 ## \begin{table}[tbp]
215 ## \begin{center}
216 ## \begin{threeparttable}

> 

>

**Comment by crsh** [comment]
You need to change the default chunk option `results = "asis"`. See #77 for a related discussion.
