### ISSUE TITLE
should deprecate old functions rather than removing them

### ISSUE THREAD

**Issue by friendly** [crsh/papaja#82]
I ran the same `Rmd` file with the latest version of papaja, and was surprised to get an error, `could not find function apa_prepare_doc`.  The only way I could solve this was to read the NEWS.md file on GitHub (`news("papaja")` does not work).

The standard way to treat a function that is no longer necessary is to use `.Deprecated` first in the function to print just a warning, then `Defunct` when the function is finally removed.

**Comment by crsh** [comment]
Point taken, thanks for the feedback. I'll try to fix this before the weekend.
