### ISSUE TITLE
apa_table() can be greater than page width

### ISSUE THREAD

**Issue by OolonColoophid** [crsh/papaja#83]
Hi Frederik

Apologies if this has come up before, but I haven't been able to find a similar issue here. I have long column names (in this case, a question given to a participant) that I'd like to sensibly wrap. Unfortunately, the table will not allow column names to wrap and my table is currently wider than the page. I've got around this before in Pandoc using Markdown-based forms of tables (which can be made to wrap), but they get unwieldy quickly, so I'd much prefer to use apa_table if possible.

With best wishes

Ian

**Comment by crsh** [comment]
Hi Ian, could you provide me with a reproducible example?

**Comment by crsh** [comment]
In the meantime, would `landscape = TRUE` be an option to tackle the problem?

**Comment by OolonColoophid** [comment]
Hmm, things are getting complicated!

Since updating Papaja to papaja_0.1.0.9440 via Github, and R to 3.3.1, my original rmarkdown paper is no longer rendering! I'm getting odd raw Latex in the PDF. The original paper is a bit complicated, but the minimal working example below produces the effect I'm talking about. I've taken the rmarkdown template from RStduio (latest version) and added a quick data frame for apa_table...

Rmarkdown is: https://www.dropbox.com/s/618h83ug26x6sr8/tempMinWorExa.Rmd?dl=0

PDF looks like this: https://www.dropbox.com/s/8cq2flpyzzvtvbw/tempMinWorExa.pdf?dl=0

With best wishes

Ian

**Comment by crsh** [comment]
This is the same problem as in #81 (see #77 for a related discussion). If you set the chunk option `results = "asis"` it will work.

**Comment by crsh** [comment]
In general, whenever a outputs the results of `apa_table()` you need to set `results = "asis"`.

**Comment by OolonColoophid** [comment]
Thanks, Frederik, that fixed the issue with the table not displaying.

I'll send some files to your institutional address so you can replicate the column behaviour mentioned above.

**Comment by crsh** [comment]
Thanks for sending me the example. Considering the compatibility with the word output format I'm hesitant to introduce a LaTeX-based solution to this problem (which would als constitute a non-trivial change to `apa_table()`). I think the best approach could currently be to use landscape mode (see above), reformat the table, or try a different function to generate the LaTeX-code for the table (maybe `xtable` or `stargazer`).

As for reformatting the table, something like this maybe?

~~~{r}
selfReportDescriptivesSD <- data.frame(rep(c("How creative do you think you are?", "How important do you think creativity is in life?"), 2), rnorm(4), rnorm(4))
colnames(selfReportDescriptivesSD) <- c("Condition","Mean", "SD")

apa_table(
  selfReportDescriptivesSD
  , caption = "Mean responses (with standard deviation) to initial self-report questions from all groups"
  , note = "Items are scaled from 1 (not at all creative/important) to 5 (very creative/extremely important)."
  , stub_indents = list(a = 1:2, b = 3:4)
)
~~~
