### ISSUE TITLE
Not showing in templates dropdown

### ISSUE THREAD

**Issue by sammcq** [crsh/papaja#86]
I have installed according to instructions, but papaja is not shown in the R templates dropdown. All versions of software are updated as of 10/7/2016.

**Comment by crsh** [comment]
Hi Sam, that's odd. Could you try loading `papaja` and restarting RStudio? Could you also post the output of `devtools::session_info()`?

**Comment by sammcq** [comment]
@crsh strange, but after restart it showed. Not sure what this issue was. Consider resolved.
