### ISSUE TITLE
Error message running the template.

### ISSUE THREAD

**Issue by keefellow** [crsh/papaja#88]
hi
What might be the problem here based on the following error message?
 
Quitting from lines 48-69 (myFirst.Rmd) 
Error in utils::packageVersion(x) : 
  package '        <td id="LC1" class="blob-code blob-code-inner js-file-line">base</td>' not found
Calls: <Anonymous> ... eval -> cite_r -> sapply -> lapply -> FUN -> <Anonymous>
Execution halted

**Comment by crsh** [comment]
Hi, it's a little hard to say without knowing what the document looks like. I haven't been able to reproduce the error. Could you provide a minimal example of a document that produces this error?

**Comment by keefellow** [comment]
Hi
the error above is gone but i have the following;
! LaTeX Error: There's no line here to end.

Error: Failed to compile myFirst.tex. See myFirst.log for more info.
In addition: Warning message:
running command '"pdflatex" -halt-on-error -interaction=batchmode "myFirst.tex"' had status 1 
Execution halted

i think the error i am facing has to do with the latex i am running on.
I am using MikTex 2.9 on Windows.  is there a need to specify where i need to save the MikTex in?   

I followed your instructions and installed MikTex. where could i have done it wrongly?
cheers!

**Comment by m-Py** [comment]
I think I had a similar error ("! LaTeX Error: There's no line here to end.") once. Try creating a new .rmd file via

```
rmarkdown::draft(
  "mymanuscript.Rmd"
  , "apa6"
  , package = "papaja"
  , create_dir = FALSE
  , edit = FALSE
)
```

Make sure that all of the options in the YAML header of the newly created file "mymanuscript.Rmd" are also in your rmd file. That helped for me - I don't know if this will help in your case, though.

**Comment by crsh** [comment]
Thanks, Martin, for the suggestion.

Again, it's very hard to diagnose the problem without a reproducible example file. I'd be happy to look into it further if you could provide one. The error message, however, does indicate that LaTeX is installed, detected, and invoked, but the document contains some incorrect LaTeX commands.

**Comment by keefellow** [comment]
Thanks, Martin.  That didn't work for me. 

Hi Frederik, i used the following files in the zip. folder  
It didn't work... until I updated the RStudio to the latest version. So maybe there is something with the RStudio version. At least now i know it can produce the pdf. I will learn more.   Thanks.

[testing.zip](https://github.com/crsh/papaja/files/567723/testing.zip)

**Comment by crsh** [comment]
Glad you were able to resolve the problem. Would you happen to remember, which RStudio version you were using before the update? Maybe I need to update the packages software requirements.

**Comment by keefellow** [comment]
A pity i didn't take down the RStudio version,
