### ISSUE TITLE
apa_table with parameter `landscape = TRUE` and YAML option `figsintext: no`

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#90]
Hi Frederik,

this one again is similar to #64; I seem to be running into the same problems. When I use an apa_table with `landscape = TRUE` and the YAML option `figsintext: no`, this table is still shown in text, whereas all other tables that do not have `landscape = TRUE` are correctly shown below the text and references. 

[Here](https://gist.github.com/m-Py/e91613aa63751ae1356c27e042ffd3a0) is a gist detailing the problem. I do not remember whether I already asked the same question in the past, but is this a bug? Or am I missing something?

Cheers,  
Martin

EDIT: this also messes with the table numbering, because the landscape table in text is always Table 1, although I create the other tables earlier than that.

**Comment by crsh** [comment]
Hey Martin, if this is the case, it's a bug. I'm at a currently at a 
conference and it will be a couple of days before I'll get a chance to 
look into this. I'll get back to you as soon as possible.

**Comment by m-Py** [comment]
Okay, then enjoy your conference =) I'm looking forward to hearing from you.

**Comment by m-Py** [comment]
I just installed the most recent version of papaja and now long tables are correctly shown after the text body when I set `figsintext = no`. 

However, there is now the opposite problem: when I set `figsintext = yes`, the long table is still shown after the text body and not in text. I guess this is not so bad because for a submission I would usually set `figsintext = no`.

**Comment by crsh** [comment]
Hi Martin, I'm always glad to read that I fixed an issue prior to it being reported. ;)

I have pushed a commit to the development branch for the figsintext-issue. Let me know if it works.

**Comment by m-Py** [comment]
Hi Frederik, that fixed the issue - thank you; but now the table Note of the long table is above the table and not below ;) Is this related to your change?

**Comment by crsh** [comment]
Sorry about that. I missed on conditional. Try again.
