### ISSUE TITLE
pdflatex.exe: GUI framework cannot be initialized.

### ISSUE THREAD

**Issue by sobradob** [crsh/papaja#92]
Hi,

Great package.

I am getting the following errors for the example found as per following the instructions. After some googling I haven't managed to find the source of the error. Any ideas?

```
pdflatex.exe: GUI framework cannot be initialized.
pdflatex.exe: GUI framework cannot be initialized.
pdflatex.exe: GUI framework cannot be initialized.

Output created: essayAPA.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'essayAPA.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning messages:
1: running command '"pdflatex" -halt-on-error -interaction=batchmode "essayAPA.tex"' had status 1 
2: running command '"pdflatex" -halt-on-error -interaction=batchmode "essayAPA.tex"' had status 1 
3: running command '"pdflatex" -halt-on-error -interaction=batchmode "essayAPA.tex"' had status 1 
Execution halted
```

**Comment by sobradob** [comment]
found this:

http://glitovsky.com/blog/?p=193

Which got rid off the error message.

However, I get this:

```
! LaTeX Error: File `apa6.cls' not found.
```

**Comment by crsh** [comment]
Hi,

both problems [seem](http://tex.stackexchange.com/questions/27138/how-can-i-fix-the-error-gui-framework-cannot-be-initialized-with-texniccenter) to be an issue related to missing LaTeX packages.

What version of MiKTex are you using? Did you install the *full* version as recommended?

> Am 02.12.2016 um 14:42 schrieb Boaz Sobrado <notifications@github.com>:
> 
> pdflatex.exe: GUI framework cannot be initialized.

**Comment by sobradob** [comment]
Hi,

I managed to resolve the problem by downloading the latest, full version of
MiKTex. It did not work immediately, so I played around with the GUI
settings until I found one that worked (see the earlier link). For me I had
to put "yes" instead of "no" but then it worked.

Thanks

**Comment by crsh** [comment]
Do you happen to know which additional LaTeX packages had to be installed?

**Comment by sobradob** [comment]
No idea, I am not entirely sure whether it is a LaTeX package issue, a GUI
issue or both.

**Comment by crsh** [comment]
Okay, thank you anyway. Glad you got it working.
