### ISSUE TITLE
Pandoc error related to ampersand_filter.R 

### ISSUE THREAD

**Issue by awellis** [crsh/papaja#96]
When attempting to compile the template Rmd file, available in the papaja package (papaja_0.1.0.9470), I get the following error:

```
output file: Untitled.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS Untitled.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Untitled.tex --template /Users/andrew/Library/R/3.3/library/papaja/rmarkdown/templates/apa6/resources/apa6.tex --highlight-style tango --latex-engine /Library/TeX/texbin/pdflatex --csl /Users/andrew/Library/R/3.3/library/papaja/rmarkdown/templates/apa6/resources/apa6.csl --filter /usr/local/bin/pandoc-citeproc --filter /Users/andrew/Library/R/3.3/library/papaja/rmarkdown/templates/apa6/resources/ampersand_filter.R 
pandoc: Error in $: endOfInput
CallStack (from HasCallStack):
  error, called at pandoc.hs:144:42 in main:Main
Error: pandoc document conversion failed with error 1
In addition: Warning message:
In cite_r("r-references.bib") :
  File r-references.bib not found. Cannot cite R-packages. If knitting again does not solve the problem, please check file path.
Execution halted
```

**Comment by crsh** [comment]
Hi Andrew,

I need a little more information to diagnose the problem. Could you post the output of `devtools::session_info()`, the `pandoc` version you are using and provide a minimal working example of the file you are trying to knit (unless it is just the bare skeleton)?

Cheers,
Frederik

**Comment by awellis** [comment]
Hi Frederik,

the file really is just the bare skeleton, obtained by opening a Rmarkdown file using the APA template. Here's the output from devtools::session_info()

```
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.35)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Zurich               
 date     2017-01-08                  

Packages -------------------------------------------------------------------------------------------------------------
 package   * version    date       source                            
 backports   1.0.4      2016-10-24 CRAN (R 3.3.1)                    
 devtools  * 1.12.0     2016-06-24 CRAN (R 3.3.0)                    
 digest      0.6.11     2017-01-03 CRAN (R 3.3.2)                    
 evaluate    0.10       2016-10-11 CRAN (R 3.3.1)                    
 htmltools   0.3.5      2016-03-21 CRAN (R 3.3.0)                    
 knitr       1.15.6     2017-01-04 Github (yihui/knitr@f936809)      
 magrittr  * 1.5        2014-11-22 CRAN (R 3.3.0)                    
 memoise     1.0.0      2016-01-29 CRAN (R 3.3.0)                    
 papaja      0.1.0.9470 2017-01-06 Github (crsh/papaja@babd334)      
 Rcpp        0.12.8.4   2017-01-07 Github (RcppCore/Rcpp@8ac38d7)    
 rmarkdown   1.3        2017-01-06 Github (rstudio/rmarkdown@d1ba313)
 rprojroot   1.1        2016-10-29 cran (@1.1)                       
 stringi     1.1.2      2016-10-01 CRAN (R 3.3.1)                    
 stringr     1.1.0      2016-08-19 CRAN (R 3.3.0)                    
 withr       1.0.2      2016-06-20 CRAN (R 3.3.0)                    
 yaml        2.1.14     2016-11-12 cran (@2.1.14)  
```

**Comment by awellis** [comment]
and here's the pandoc version:
```
[~] pandoc --version                                                                    master  ✗ ✭
pandoc 1.19.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3
Default user data directory: /Users/andrew/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by crsh** [comment]
Thanks, I'll try to take a closer look at this as soon as possible.

**Comment by crsh** [comment]
Hmm, this is weird. I have closely replicated your set up on my Ubuntu machine but I can't reproduce the error. I have also tried reproducing the error on my Mac but to no avail. Could you try adding `citeproc: no` to the YAML header and see if you still get the error?

**Comment by awellis** [comment]
hi,

the terminal output is:
```[resources] ls -l                                                                       master  ✗ ✭
total 96
-rwxr-xr-x  1 andrew  staff    600 Jan  7 21:09 ampersand_filter.R
-rwxr-xr-x  1 andrew  staff  16382 Jan  6 10:51 apa6.csl
-rwxr-xr-x  1 andrew  staff   9346 Jan  6 10:51 apa6.tex
-rw-r--r--@ 1 andrew  staff  14265 Jan  6 10:51 apa6_man.docx
```

If I set `citeproc: no` I can compile the Rmd file, and then setting `citeproc: yes` and `csl: apa.csl` with the style sheet in the working directory works, but the references are not processed by pandoc, i.e. citations remain as [@CITEKEY]. 

I can get pandoc-citeproc to work using the same bibliography.bib file and citation command in a plain Rmd file.

I have attached the examples. 
[files.zip](https://github.com/crsh/papaja/files/699154/files.zip)

**Comment by crsh** [comment]
This is really helpful, thanks. However, I'm still in the dark about the exact cause of the error. I assume that somehow the filter outputs something unexpected to `stdin`. If you don't mind, I may prepare a test-fork of papaja with a modified version of the filter to do some additional diagnosing. All this would require from you is to install a different version of `papaja` and try to knit the skeleton again.

**Comment by awellis** [comment]
certainly, I'd be glad to help.

**Comment by crsh** [comment]
Hi Andrew,

I just pushed a commit to fix a different bug related to the use of the ampersand filter on Windows. In the process I have made a minor change that may affect this issue. Could you reinstall the package and test whether your problem persists?

In case it does, I just pushed a new branch to help diagnose the problem. Install the diagnosis version with `devtools::install_github("crsh/papaja", ref = "filter_test")`. When you knit the skeleton I would hope that the filter creates two files in the directory containing the Rmd-file (`ast_test.txt` and `ast_test2.txt`). Could you upload these files? I hope they help me to get a better handle on things.

Thanks!

**Comment by awellis** [comment]
Hi, 
I installed the diagnosis version, and knitted the skeleton. I get this error:

```
/usr/local/bin/pandoc +RTS -K512m -RTS papaja-test-2.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output papaja-test-2.tex --template /Users/andrew/Library/R/3.3/library/papaja/rmarkdown/templates/apa6/resources/apa6.tex --highlight-style tango --latex-engine /Library/TeX/texbin/pdflatex --csl /Users/andrew/Library/R/3.3/library/papaja/rmarkdown/templates/apa6/resources/apa6.csl --filter /usr/local/bin/pandoc-citeproc --filter /Users/andrew/Library/R/3.3/library/papaja/rmarkdown/templates/apa6/resources/ampersand_filter.R 
output file: papaja-test-2.knit.md

pandoc: Error in $: endOfInput
CallStack (from HasCallStack):
  error, called at pandoc.hs:144:42 in main:Main
Error: pandoc document conversion failed with error 1
Execution halted
```

The text files are attached. I don't know if this is relevant, but I'm using the dev version of Rstudio (Version 1.1.44 ).



[ast_test.txt](https://github.com/crsh/papaja/files/710419/ast_test.txt)
[ast_test2.txt](https://github.com/crsh/papaja/files/710420/ast_test2.txt)

**Comment by crsh** [comment]
Hi Andrew, thanks, I'm at a conference right now, but I'll try to take a closer look as soon as I can. In the mean time, you can install an earlier version of papaja by supplying a specific commit, e.g.`devtools::install_github("crsh/papaja@cc99a16a5bc43d2468adc74e21a340f154085be1")`.

**Comment by crsh** [comment]
This is a tricky one because I can't really reproduce it. Following some more experimentation I think the filter may, for some reason, print too little or too much to `stdout` on your machine. Could you manually pipe the contents of `ast_test.txt` to the ampersand filter

    cat path/to/ast_test.txt | Rscript /Users/andrew/Library/R/3.3/library/papaja/rmarkdown/templates/apa6/resources/ampersand_filter.R > ~/ampersand_test.txt

and upload the file?

**Comment by awellis** [comment]
Hi, here is the output.
[ampersand_test.txt](https://github.com/crsh/papaja/files/754715/ampersand_test.txt)

I just discovered that the error is partly related to my .Rprofile, specifically my goodbye message:

.Last <- function() {
	# save command history here?
	cat("\nGoodbye at ", date(), "\n")
}

I think there is a problem your filter, depending on where in the text the citation occurs. I often get the error:

pandoc: Error in $: Failed reading: satisfy
CallStack (from HasCallStack):
  error, called at pandoc.hs:144:42 in main:Main
Error: pandoc document conversion failed with error 1
Execution halted
```

But I can get this to disappear by moving the citation. It also happens that the ampersand isn't removed for all entries. Haven't been able to create a reproducible example yet, sorry.

**Comment by crsh** [comment]
Ah, I suspected it might be something like this. Thank you for the continued testing. I'll see whether there is a way to ignore `.Rprofile` when I call `Rscript`.

I'll also have another look at the filter regex. If you happen to have a reproducible example of the error I'd be happy to take a look (you can e-mail it to me if you prefer not to upload it on GitHub). But I'll also try to play with it myself.

**Comment by crsh** [comment]
Hi Andrew, I just pushed a commit that I hope fixes the problems caused by the output of your `.Last()`. Let me know if it works.

**Comment by crsh** [comment]
@awellis I think my last commit also fixed the last issue you reported in here. Can you confirm this?

**Comment by awellis** [comment]
as far as I can tell, this has been fixed.
