### ISSUE TITLE
Add MANOVA support in apa_print

### ISSUE THREAD

**Issue by harmsk** [crsh/papaja#98]
MANOVA is not yet supported. If I try to print an object from the `manova` function I receive the following output:

```
 Error in apa_print.default(summary_x, ...) : 
  Objects of class 'summary.manova' are currently not supported (no method defined).
              Visit https://github.com/crsh/papaja/issues to request support for this class.
```

I looked at the code for `apa_print_anova.R` and `print_anova.R` and I not sure how to add support. I'm more than happy to help if I understand what's needed.

**Comment by crsh** [comment]
Hi Kyle,

thanks for the suggestion. I would like to add MANOVA support but I haven't found time to get started on this and, to be honest, it doesn't currently rank high on my priority list. But I'd be more than happy to consider a pull request with new S3 methods for `apa_print()`!

I'll try to illustrate the current general approach by the example of ANOVA.

As you may have seen from the S3 methods for ANOVA objects I try to make `apa_print()` work with a variety of MANOVA output objects that it could encounter. In this case, I was able to simplify the pipeline to passing raw output objects through `summary()` and working only on the summarized objects (e.g., `apa_print.aov()` -> `apa_print.summary.aov()`). I'm not sure whether the same approach would work for MANOVA.

Next, the preprocessed objects are passed through `broom::tidy()` to get everything into a tidy `data.frame` structure. This happens in `arrange_anova()`. The output of this function is a `data.frame` of class `apa_variance_table` with, currently, one attribute (`correction`). Irrespective of the initial object passed to `apa_print()` the variance tables should now have the same structure.

Now, the variance table is passed to `print_anova()` where the returned list is assembled. The list should probably contain the element `$estimate`, `$statistic`, `$full_result`, and `$table` (see the internal function `apa_print_container()`). I try tend to start with the table, which is a `data.frame` giving a summary of all results that you could report as a table in a paper. I then take elements from this table to construct the text strings for the other elements. `$estimate` is a named list containing elements for each tested factor. Each element contains a text string of the corresponding effect size estimate. `$statistic` has the same structure and contains text strings of the test statistics. `$full_result` again has the same structure and contains text strings combining estimates and test statistics. I usually simply use `paste()` to create `$full_result` from `$estimate` and `$statistic`.

I hope this overview helps to get started. If possible, please add tests for the contributed functions and use the internal `validate()` function to ensure that objects passed by the user are of the correct type.

**Comment by harmsk** [comment]
Thanks Frederik.

This is really helpful. I don't have time in the next few weeks to do this. But I'm might try to get this going sometime after that. Thanks for the detailed overview. That should help me get a good start.
