### ISSUE TITLE
Installing papaja leads to following error 

### ISSUE THREAD

**Issue by feeblee** [crsh/papaja#99]
Hey there,

I tried to instal papaja according to the instructions in the README.md and got the following out put and error:

> devtools::install_github("crsh/papaja")
Downloading GitHub repo crsh/papaja@master
from URL https://api.github.com/repos/crsh/papaja/zipball/master
Installing papaja
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 11 1563k   11  175k    0     0   614k      0  0:00:02 --:--:--  0:00:02  612k100 1563k  100 1563k    0     0  2111k      0 --:--:-- --:--:-- --:--:-- 2109k
Installing broom
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  535k  100  535k    0     0  1027k      0 --:--:-- --:--:-- --:--:-- 1029k
Installing tidyr
Downloading GitHub repo RcppCore/Rcpp@master
from URL https://api.github.com/repos/RcppCore/Rcpp/zipball/master
**Fehler: Could not find build tools necessary to build Rcpp**

Do you have any advice?

**Comment by crsh** [comment]
Hi feeblee, I assume you are working on a Windows machine. Have you installed the correct version of [`Rtools`](https://cran.r-project.org/bin/windows/Rtools/)? It is [a prerequisite](http://stackoverflow.com/questions/37776377/error-when-installing-an-r-package-from-github-could-not-find-build-tools-neces?answertab=votes#tab-top) for installing packages from source. In this case, it appears `Rcpp` depends on it.

**Comment by feeblee** [comment]
Hey Frederik,

Thanks for your reply. I am actually working on mac. I found a solution. It was a missing xcode package (command line tools).

**Comment by crsh** [comment]
Great, thank you for the letting me know.
